// scenarios/advanced/web/svelte/n4.svelte
<script>
  import { onMount, onDestroy } from 'svelte';
  
  let currentSlide = 0;
  let isAutoPlaying = true;
  let intervalRef;

  const slides = [
    {
      id: 1,
      title: 'Welcome to Our Platform',
      description: 'Discover amazing features and tools designed to enhance your productivity.',
      image: 'https://via.placeholder.com/800x400/007bff/ffffff?text=Slide+1',
      cta: 'Get Started'
    },
    {
      id: 2,
      title: 'Advanced Analytics',
      description: 'Track your progress with detailed insights and comprehensive reporting.',
      image: 'https://via.placeholder.com/800x400/28a745/ffffff?text=Slide+2',
      cta: 'View Analytics'
    },
    {
      id: 3,
      title: 'Team Collaboration',
      description: 'Work together seamlessly with our powerful collaboration tools.',
      image: 'https://via.placeholder.com/800x400/dc3545/ffffff?text=Slide+3',
      cta: 'Join Team'
    },
    {
      id: 4,
      title: 'Mobile Ready',
      description: 'Access your data and tools from anywhere with our mobile-optimized interface.',
      image: 'https://via.placeholder.com/800x400/ffc107/000000?text=Slide+4',
      cta: 'Download App'
    }
  ];

  function nextSlide() {
    currentSlide = (currentSlide + 1) % slides.length;
  }

  function prevSlide() {
    currentSlide = (currentSlide - 1 + slides.length) % slides.length;
  }

  function goToSlide(index) {
    currentSlide = index;
  }

  function pauseAutoPlay() {
    isAutoPlaying = false;
  }

  function resumeAutoPlay() {
    isAutoPlaying = true;
  }

  function toggleAutoPlay() {
    isAutoPlaying = !isAutoPlaying;
  }

  function startAutoPlay() {
    intervalRef = setInterval(() => {
      if (isAutoPlaying) {
        nextSlide();
      }
    }, 5000);
  }

  function stopAutoPlay() {
    if (intervalRef) {
      clearInterval(intervalRef);
    }
  }

  onMount(() => {
    startAutoPlay();
  });

  onDestroy(() => {
    stopAutoPlay();
  });
</script>

<div class="main-container">
  <div class="main-content">
    <h1>Featured Content</h1>
    <p>Explore our latest features and announcements.</p>
    
    <div class="carousel-section">
      <!-- Carousel Container -->
      <div class="carousel-container" on:mouseenter={pauseAutoPlay} on:mouseleave={resumeAutoPlay}>
        <!-- Slides -->
        <div class="slides-container" style="transform: translateX(-{currentSlide * 100}%)">
          {#each slides as slide}
            <div class="slide" style="background-image: url({slide.image})">
              <div class="slide-content">
                <h2>{slide.title}</h2>
                <p>{slide.description}</p>
                <button class="cta-button">{slide.cta}</button>
              </div>
            </div>
          {/each}
        </div>

        <!-- Previous Button -->
        <button on:click={prevSlide} class="nav-button prev-button">‹</button>

        <!-- Next Button -->
        <button on:click={nextSlide} class="nav-button next-button">›</button>
      </div>

      <!-- Slide Indicators -->
      <div class="indicators">
        {#each slides as slide, index}
          <button
            on:click={() => goToSlide(index)}
            class="indicator"
            class:active={currentSlide === index}
          />
        {/each}
      </div>

      <!-- Auto-play Toggle -->
      <div class="auto-play-controls">
        <button on:click={toggleAutoPlay} class="toggle-button">
          {isAutoPlaying ? '⏸️' : '▶️'}
        </button>
        <span class="status-text">
          {isAutoPlaying ? 'Auto-play enabled' : 'Auto-play paused'}
        </span>
      </div>
    </div>

    <!-- Additional Content -->
    <div class="additional-info">
      <h3>About This Carousel</h3>
      <p>This carousel showcases our key features and announcements. Use the navigation buttons or indicators to explore different slides.</p>
    </div>
  </div>
</div>

<style>
  .main-container {
    font-family: Arial, sans-serif;
    max-width: 1000px;
    margin: 50px auto;
    padding: 20px;
    background-color: #f5f5f5;
  }

  .main-content {
    background: white;
    padding: 30px;
    border-radius: 8px;
    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
  }

  .carousel-section {
    margin-top: 30px;
  }

  .carousel-container {
    position: relative;
    overflow: hidden;
    border-radius: 8px;
    background-color: #000;
  }

  .slides-container {
    display: flex;
    transition: transform 0.5s ease-in-out;
  }

  .slide {
    min-width: 100%;
    position: relative;
    height: 400px;
    background-size: cover;
    background-position: center;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .slide-content {
    background: rgba(0, 0, 0, 0.6);
    color: white;
    padding: 40px;
    border-radius: 8px;
    text-align: center;
    max-width: 600px;
  }

  .slide-content h2 {
    margin: 0 0 16px 0;
    font-size: 32px;
    font-weight: bold;
  }

  .slide-content p {
    margin: 0 0 24px 0;
    font-size: 18px;
    line-height: 1.6;
  }

  .cta-button {
    background-color: #007bff;
    color: white;
    padding: 12px 24px;
    border: none;
    border-radius: 4px;
    font-size: 16px;
    cursor: pointer;
    font-weight: bold;
  }

  .cta-button:hover {
    background-color: #0056b3;
  }

  .nav-button {
    position: absolute;
    top: 50%;
    transform: translateY(-50%);
    background: rgba(0, 0, 0, 0.5);
    color: white;
    border: none;
    border-radius: 50%;
    width: 50px;
    height: 50px;
    font-size: 20px;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .prev-button {
    left: 20px;
  }

  .next-button {
    right: 20px;
  }

  .nav-button:hover {
    background: rgba(0, 0, 0, 0.7);
  }

  .indicators {
    display: flex;
    justify-content: center;
    gap: 8px;
    margin-top: 20px;
  }

  .indicator {
    width: 12px;
    height: 12px;
    border-radius: 50%;
    border: none;
    background-color: #ddd;
    cursor: pointer;
    transition: background-color 0.3s ease;
  }

  .indicator.active {
    background-color: #007bff;
  }

  .indicator:hover {
    background-color: #999;
  }

  .auto-play-controls {
    display: flex;
    justify-content: center;
    align-items: center;
    gap: 8px;
    margin-top: 20px;
  }

  .toggle-button {
    background: none;
    border: none;
    cursor: pointer;
    font-size: 16px;
    color: #666;
  }

  .status-text {
    color: #666;
    font-size: 14px;
  }

  .additional-info {
    margin-top: 40px;
    padding: 20px;
    background-color: #f8f9fa;
    border-radius: 4px;
  }
</style>

// scenarios/moderate/web/nuxt/n4.vue
<template>
  </div>
</template>
<script>
export default {
  name: 'CarouselWithoutControls',
  data() {
    return {
      currentIndex: 0,
      isAutoPlaying: true,
      images: [
        {
          id: 1,
          src: 'https://via.placeholder.com/600x400/007bff/ffffff?text=Image+1',
          title: 'Mountain Landscape',
          description: 'A stunning view of snow-capped mountains at sunset'
        },
        {
          id: 2,
          src: 'https://via.placeholder.com/600x400/28a745/ffffff?text=Image+2',
          title: 'Autumn Forest',
          description: 'A peaceful walking path through colorful autumn trees'
        },
        {
          id: 3,
          src: 'https://via.placeholder.com/600x400/dc3545/ffffff?text=Image+3',
          title: 'Ocean Sunset',
          description: 'Calm ocean waves reflecting the golden sunset sky'
        },
        {
          id: 4,
          src: 'https://via.placeholder.com/600x400/ffc107/000000?text=Image+4',
          title: 'City Nightscape',
          description: 'Urban cityscape illuminated by city lights'
        },
        {
          id: 5,
          src: 'https://via.placeholder.com/600x400/6f42c1/ffffff?text=Image+5',
          title: 'Desert Dawn',
          description: 'Sand dunes stretching to the horizon at sunrise'
        }
      ]
    }
  },
  mounted() {
    if (this.isAutoPlaying) {
      this.autoPlayInterval = setInterval(() => {
        this.goToNext()
      }, 3000)
    }
  },
  beforeDestroy() {
    if (this.autoPlayInterval) {
      clearInterval(this.autoPlayInterval)
    }
  },
  methods: {
    goToPrevious() {
      this.currentIndex = this.currentIndex === 0 ? this.images.length - 1 : this.currentIndex - 1
    },
    goToNext() {
      this.currentIndex = (this.currentIndex + 1) % this.images.length
    },
    goToSlide(index) {
      this.currentIndex = index
    },
    toggleAutoPlay() {
      this.isAutoPlaying = !this.isAutoPlaying
      if (this.isAutoPlaying) {
        this.autoPlayInterval = setInterval(() => {
          this.goToNext()
        }, 3000)
      } else {
        clearInterval(this.autoPlayInterval)
      }
    },
    handleKeyDown(e) {
      if (e.key === 'ArrowLeft') {
        this.goToPrevious()
      } else if (e.key === 'ArrowRight') {
        this.goToNext()
      } else if (e.key === 'Home') {
        this.goToSlide(0)
      } else if (e.key === 'End') {
        this.goToSlide(this.images.length - 1)
      }
    }
  }
}
</script>
<style scoped>
.carousel-container {
  max-width: 800px;
  margin: 50px auto;
  padding: 20px;
  background-color: #f5f5f5;
}
.main-content {
  background: white;
  padding: 30px;
  border-radius: 8px;
  box-shadow: 0 2px 10px rgba(0,0,0,0.1);
}
.carousel-wrapper {
  margin-bottom: 30px;
}
.carousel-container-inner {
  position: relative;
  margin-bottom: 20px;
}
.nav-button {
  position: absolute;
  top: 50%;
  transform: translateY(-50%);
  background: rgba(0,0,0,0.7);
  color: white;
  border: none;
  border-radius: 50%;
  width: 50px;
  height: 50px;
  font-size: 20px;
  cursor: pointer;
  z-index: 2;
  display: flex;
  align-items: center;
  justify-content: center;
}
.prev-button {
  left: 10px;
}
.next-button {
  right: 10px;
}
.image-container {
  position: relative;
  overflow: hidden;
  border-radius: 8px;
}
.carousel-image {
  width: 100%;
  height: 400px;
  object-fit: cover;
  display: block;
}
.image-overlay {
  position: absolute;
  bottom: 0;
  left: 0;
  right: 0;
  background: linear-gradient(transparent, rgba(0,0,0,0.8));
  color: white;
  padding: 20px;
}
.image-title {
  margin: 0 0 8px 0;
  font-size: 24px;
}
.image-description {
  margin: 0;
  font-size: 16px;
  opacity: 0.9;
}
.indicators {
  display: flex;
  justify-content: center;
  gap: 8px;
}
.indicator {
  width: 12px;
  height: 12px;
  border-radius: 50%;
  border: none;
  background: #ccc;
  cursor: pointer;
  transition: background-color 0.3s ease;
}
.indicator.active {
  background: #007bff;
}
.controls {
  display: flex;
  justify-content: center;
  gap: 16px;
  margin-top: 20px;
}
.control-button {
  background: #007bff;
  color: white;
  border: none;
  padding: 8px 16px;
  border-radius: 4px;
  cursor: pointer;
  font-size: 14px;
}
.control-button.pause {
  background: #dc3545;
}
.control-button.play {
  background: #28a745;
}
.slide-info {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 14px;
  color: #666;
}
  margin-top: 30px;
  padding: 20px;
  background-color: #e9ecef;
  border-radius: 4px;
}
  margin-top: 0;
}
  margin-bottom: 20px;
}
  margin-bottom: 8px;
}
</style>
