// scenarios/advanced/web/nextjs/n8.jsx
'use client';

import React, { useState, useRef, useEffect } from 'react';

const CustomDropdownNavigation = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [selectedValue, setSelectedValue] = useState('all');
  const [selectedText, setSelectedText] = useState('All Categories');
  const [currentIndex, setCurrentIndex] = useState(0);
  const dropdownRef = useRef(null);
  const triggerRef = useRef(null);
  const optionsRef = useRef([]);

  const options = [
    { value: 'all', text: 'All Categories' },
    { value: 'electronics', text: 'Electronics' },
    { value: 'clothing', text: 'Clothing' },
    { value: 'books', text: 'Books' },
    { value: 'home', text: 'Home & Garden' }
  ];

  const products = {
    all: [
      { name: 'iPhone 15', category: 'Electronics' },
      { name: 'MacBook Pro', category: 'Electronics' },
      { name: 'Cotton T-Shirt', category: 'Clothing' },
      { name: 'JavaScript Guide', category: 'Books' },
      { name: 'Garden Tools', category: 'Home & Garden' }
    ],
    electronics: [
      { name: 'iPhone 15', category: 'Electronics' },
      { name: 'MacBook Pro', category: 'Electronics' }
    ],
    clothing: [
      { name: 'Cotton T-Shirt', category: 'Clothing' }
    ],
    books: [
      { name: 'JavaScript Guide', category: 'Books' }
    ],
    home: [
      { name: 'Garden Tools', category: 'Home & Garden' }
    ]
  };

  const toggleDropdown = () => {
    setIsOpen(!isOpen);
    if (!isOpen) {
      // Focus first option when opening
      setTimeout(() => {
        if (optionsRef.current[0]) {
          optionsRef.current[0].focus();
        }
      }, 0);
    }
  };

  const selectOption = (value, text, index) => {
    setSelectedValue(value);
    setSelectedText(text);
    setCurrentIndex(index);
    setIsOpen(false);
    // Return focus to trigger
    if (triggerRef.current) {
      triggerRef.current.focus();
    }
  };

  const handleKeyDown = (event) => {
    if (!isOpen) {
      if (event.key === 'Enter' || event.key === ' ') {
        event.preventDefault();
        toggleDropdown();
      }
      return;
    }

    switch (event.key) {
      case 'ArrowDown':
        event.preventDefault();
        const nextIndex = currentIndex < options.length - 1 ? currentIndex + 1 : 0;
        setCurrentIndex(nextIndex);
        if (optionsRef.current[nextIndex]) {
          optionsRef.current[nextIndex].focus();
        }
        break;
      case 'ArrowUp':
        event.preventDefault();
        const prevIndex = currentIndex > 0 ? currentIndex - 1 : options.length - 1;
        setCurrentIndex(prevIndex);
        if (optionsRef.current[prevIndex]) {
          optionsRef.current[prevIndex].focus();
        }
        break;
      case 'Enter':
      case ' ':
        event.preventDefault();
        selectOption(options[currentIndex].value, options[currentIndex].text, currentIndex);
        break;
      case 'Escape':
        setIsOpen(false);
        if (triggerRef.current) {
          triggerRef.current.focus();
        }
        break;
    }
  };

  const handleOptionKeyDown = (event, value, text, index) => {
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault();
      selectOption(value, text, index);
    } else if (event.key === 'Escape') {
      setIsOpen(false);
      if (triggerRef.current) {
        triggerRef.current.focus();
      }
    }
  };

  // Close dropdown when clicking outside
  useEffect(() => {
    const handleClickOutside = (event) => {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target)) {
        setIsOpen(false);
      }
    };

    document.addEventListener('mousedown', handleClickOutside);
    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, []);

  return (
    <div className="main-container">
      <div className="main-content">
        <h1>Product Filter</h1>
        
        
        <div className="filter-section">
          <label 
            htmlFor="category-filter" 
            className="filter-label"
          >
            Filter by Category:
          </label>
          <div className="custom-dropdown" ref={dropdownRef}>
            <button
              ref={triggerRef}
              id="category-filter"
              onClick={toggleDropdown}
              onKeyDown={handleKeyDown}
              aria-expanded={isOpen}
              aria-haspopup="listbox"
              aria-labelledby="category-filter-label"
              aria-activedescendant={isOpen ? `option-${currentIndex}` : undefined}
              className={`dropdown-trigger ${isOpen ? 'open' : ''}`}
            >
              <span>{selectedText}</span>
              <span className={`dropdown-arrow ${isOpen ? 'rotated' : ''}`}>▼</span>
            </button>
            
            {isOpen && (
              <div
                role="listbox"
                aria-labelledby="category-filter-label"
                className="dropdown-menu"
              >
                {options.map((option, index) => (
                  <div
                    key={option.value}
                    ref={el => optionsRef.current[index] = el}
                    id={`option-${index}`}
                    role="option"
                    aria-selected={selectedValue === option.value}
                    tabIndex={index === currentIndex ? 0 : -1}
                    onClick={() => selectOption(option.value, option.text, index)}
                    onKeyDown={(e) => handleOptionKeyDown(e, option.value, option.text, index)}
                    onMouseEnter={() => setCurrentIndex(index)}
                    className={`dropdown-option ${selectedValue === option.value ? 'selected' : ''}`}
                  >
                    {option.text}
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
        
        <div className="results-section">
          <h2>Filtered Results</h2>
          <div className="results-grid">
            {products[selectedValue]?.map((product, index) => (
              <div key={index} className="result-card">
                <h3>{product.name}</h3>
                <p>{product.category}</p>
              </div>
            ))}
          </div>
        </div>
      </div>

      <style jsx>{`
        .main-container {
          font-family: Arial, sans-serif;
          max-width: 800px;
          margin: 50px auto;
          padding: 20px;
          background-color: #f5f5f5;
        }

        .main-content {
          background: white;
          padding: 30px;
          border-radius: 8px;
          box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }

        .filter-section {
          margin-bottom: 30px;
        }

        .filter-label {
          display: block;
          margin-bottom: 10px;
          font-weight: bold;
          color: #333;
        }

        .custom-dropdown {
          position: relative;
          display: inline-block;
          width: 200px;
        }

        .dropdown-trigger {
          background-color: #f8f9fa;
          border: 2px solid #ddd;
          border-radius: 4px;
          padding: 12px 16px;
          cursor: pointer;
          display: flex;
          justify-content: space-between;
          align-items: center;
          font-size: 16px;
          width: 100%;
          box-sizing: border-box;
        }

        .dropdown-trigger:hover {
          border-color: #007bff;
        }

        .dropdown-trigger:focus {
          outline: none;
          border-color: #007bff;
          box-shadow: 0 0 0 2px rgba(0, 123, 255, 0.25);
        }

        .dropdown-trigger.open {
          border-color: #007bff;
          border-bottom-left-radius: 0;
          border-bottom-right-radius: 0;
        }

        .dropdown-arrow {
          transition: transform 0.2s ease;
        }

        .dropdown-arrow.rotated {
          transform: rotate(180deg);
        }

        .dropdown-menu {
          position: absolute;
          top: 100%;
          left: 0;
          right: 0;
          background: white;
          border: 2px solid #007bff;
          border-top: none;
          border-radius: 0 0 4px 4px;
          box-shadow: 0 4px 12px rgba(0,0,0,0.15);
          z-index: 1000;
        }

        .dropdown-option {
          padding: 12px 16px;
          cursor: pointer;
          border-bottom: 1px solid #eee;
          transition: background-color 0.2s ease;
        }

        .dropdown-option:last-child {
          border-bottom: none;
        }

        .dropdown-option:hover {
          background-color: #f8f9fa;
        }

        .dropdown-option.selected {
          background-color: #007bff;
          color: white;
        }

        .dropdown-option.selected:hover {
          background-color: #0056b3;
        }

        .results-section {
          margin-top: 30px;
        }

        .results-grid {
          display: grid;
          grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
          gap: 20px;
          margin-top: 20px;
        }

        .result-card {
          background: white;
          border: 1px solid #ddd;
          border-radius: 8px;
          padding: 20px;
          text-align: center;
          box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }

        .result-card h3 {
          margin: 0 0 10px 0;
          color: #333;
        }

        .result-card p {
          margin: 0;
          color: #666;
        }

      `}</style>
    </div>
  );
};

export default CustomDropdownNavigation;

// scenarios/moderate/web/nuxt/n8.vue
<template>
    <!-- Modal -->
  </div>
</template>
<script>
export default {
  data() {
    return {
      isOpen: false,
      settings: {
        theme: 'light',
        language: 'en',
        notifications: 'all'
      },
      previousActiveElement: null
    };
  },
  methods: {
    openModal() {
      this.previousActiveElement = document.activeElement;
      this.isOpen = true;
      this.$nextTick(() => {
      });
    },
    closeModal() {
      this.isOpen = false;
    },
    closeModalOnOverlay(event) {
      if (event.target === event.currentTarget) {
        this.closeModal();
      }
    },
    saveSettings() {
      alert('Settings saved!');
      this.closeModal();
    },
    handleKeyDown(event) {
      if (event.key === 'Escape' && this.isOpen) {
        this.closeModal();
      }
    }
  },
  mounted() {
    document.addEventListener('keydown', this.handleKeyDown);
  },
  beforeUnmount() {
    document.removeEventListener('keydown', this.handleKeyDown);
  }
};
</script>
<style scoped>
.container {
  max-width: 800px;
  margin: 50px auto;
  padding: 20px;
}
.main-content {
  background: white;
  padding: 30px;
  border-radius: 8px;
  box-shadow: 0 2px 10px rgba(0,0,0,0.1);
}
.open-modal-btn {
  background-color: #007bff;
  color: white;
  padding: 12px 24px;
  border: none;
  border-radius: 4px;
  font-size: 16px;
  cursor: pointer;
}
.open-modal-btn:hover {
  background-color: #0056b3;
}
.description {
  margin-top: 20px;
}
/* Modal Styles */
.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.5);
  z-index: 1000;
  display: flex;
  align-items: center;
  justify-content: center;
}
.modal-content {
  background: white;
  padding: 30px;
  border-radius: 8px;
  box-shadow: 0 4px 20px rgba(0,0,0,0.3);
  max-width: 500px;
  width: 90%;
  position: relative;
}
.modal-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
  padding-bottom: 10px;
  border-bottom: 1px solid #eee;
}
.modal-title {
  margin: 0;
  font-size: 24px;
  color: #333;
}
.close-btn {
  background: none;
  border: none;
  font-size: 24px;
  cursor: pointer;
  color: #666;
  padding: 0;
  width: 30px;
  height: 30px;
  display: flex;
  align-items: center;
  justify-content: center;
}
.close-btn:hover {
  color: #333;
}
.form-group {
  margin-bottom: 20px;
}
  display: block;
  margin-bottom: 5px;
  font-weight: bold;
  color: #333;
}
.form-group select {
  width: 100%;
  padding: 10px;
  border: 1px solid #ddd;
  border-radius: 4px;
  font-size: 16px;
  box-sizing: border-box;
}
.modal-actions {
  display: flex;
  gap: 10px;
  justify-content: flex-end;
  margin-top: 30px;
}
.btn {
  padding: 10px 20px;
  border: none;
  border-radius: 4px;
  font-size: 16px;
  cursor: pointer;
}
.btn-primary {
  background-color: #007bff;
  color: white;
}
.btn-primary:hover {
  background-color: #0056b3;
}
.btn-secondary {
  background-color: #6c757d;
  color: white;
}
.btn-secondary:hover {
  background-color: #545b62;
}
  margin-top: 30px;
  padding: 20px;
  background-color: #e9ecef;
  border-radius: 4px;
}
  margin: 10px 0;
  padding-left: 20px;
}
  background-color: #f8f9fa;
  padding: 2px 4px;
  border-radius: 3px;
  font-family: 'Courier New', monospace;
}
</style>
