// scenarios/basic/web/vue/MissingLanguageAttribute.vue
<template>
  <div class="multilingual-website">
    <!-- Language selector -->
    <div class="language-selector">
      <select
        v-model="selectedLanguage"
        class="language-dropdown"
      >
        <option value="en">English</option>
        <option value="fr">Français</option>
      </select>
    </div>

    <!-- Hero section with mixed English/French content without lang attributes -->
    <div class="hero-section">
      <h1>{{ currentContent.title }}</h1>
      <p>{{ currentContent.subtitle }}</p>
      <button class="cta-button">{{ currentContent.button }}</button>
    </div>

    <!-- Main content -->
    <div class="content-grid">
      <div class="content-card">
        <h2>About Us</h2>
        <p>{{ currentContent.description }}</p>
      </div>

      <div class="content-card">
        <h2>Our Services</h2>
        <ul>
          <li>Web Development</li>
          <li>Mobile App Development</li>
          <li>Cloud Solutions</li>
          <li>Digital Marketing</li>
        </ul>
      </div>
    </div>

    <!-- Contact section -->
    <div class="contact-section">
      <h2>Get in Touch</h2>
      <p>Ready to get started? Contact us today for more information.</p>
      <div class="contact-buttons">
        <button class="btn-primary">Contact Us</button>
        <button class="btn-secondary">View Portfolio</button>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'MissingLanguageAttribute',
  data() {
    return {
      selectedLanguage: 'en',
      content: {
        en: {
          title: "Welcome to Our Website",
          subtitle: "Discover amazing products and services",
          description: "We are a leading technology company dedicated to providing innovative solutions that help businesses grow and succeed in the digital age.",
          button: "Learn More"
        },
        fr: {
          title: "Bienvenue sur Notre Site Web",
          subtitle: "Découvrez des produits et services incroyables",
          description: "Nous sommes une entreprise technologique leader dédiée à fournir des solutions innovantes qui aident les entreprises à croître et à réussir à l'ère numérique.",
          button: "En Savoir Plus"
        }
      }
    }
  },
  computed: {
    currentContent() {
      return this.content[this.selectedLanguage] || this.content.en
    }
  }
}
</script>

<style scoped>
.multilingual-website {
  max-width: 1000px;
  margin: 50px auto;
  padding: 20px;
  font-family: Arial, sans-serif;
}

.language-selector {
  display: flex;
  justify-content: flex-end;
  margin-bottom: 30px;
}

.language-dropdown {
  padding: 8px 12px;
  border: 1px solid #ddd;
  border-radius: 4px;
  font-size: 14px;
}

.hero-section {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  padding: 60px 40px;
  border-radius: 12px;
  text-align: center;
  margin-bottom: 40px;
}

.hero-section h1 {
  font-size: 48px;
  margin: 0 0 20px 0;
  font-weight: bold;
}

.hero-section p {
  font-size: 20px;
  margin: 0 0 30px 0;
  opacity: 0.9;
}

.cta-button {
  background: white;
  color: #667eea;
  border: none;
  padding: 15px 30px;
  border-radius: 25px;
  font-size: 16px;
  font-weight: bold;
  cursor: pointer;
  box-shadow: 0 4px 15px rgba(0,0,0,0.2);
}

.content-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: 30px;
  margin-bottom: 40px;
}

.content-card {
  background: white;
  padding: 30px;
  border-radius: 8px;
  box-shadow: 0 2px 10px rgba(0,0,0,0.1);
}

.content-card h2 {
  font-size: 24px;
  margin: 0 0 15px 0;
  color: #333;
}

.content-card p {
  font-size: 16px;
  line-height: 1.6;
  color: #666;
  margin: 0;
}

.content-card ul {
  margin: 0;
  padding-left: 20px;
  font-size: 16px;
  line-height: 1.8;
  color: #666;
}

.contact-section {
  background: #f8f9fa;
  padding: 40px;
  border-radius: 8px;
  text-align: center;
}

.contact-section h2 {
  font-size: 28px;
  margin: 0 0 20px 0;
  color: #333;
}

.contact-section p {
  font-size: 16px;
  margin: 0 0 30px 0;
  color: #666;
}

.contact-buttons {
  display: flex;
  gap: 15px;
  justify-content: center;
  flex-wrap: wrap;
}

.btn-primary {
  background: #007bff;
  color: white;
  border: none;
  padding: 12px 24px;
  border-radius: 4px;
  cursor: pointer;
  font-size: 16px;
}

.btn-secondary {
  background: transparent;
  color: #007bff;
  border: 2px solid #007bff;
  padding: 10px 24px;
  border-radius: 4px;
  cursor: pointer;
  font-size: 16px;
}
</style>

// scenarios/basic/web/react/MissingLanguageAttribute.jsx
import React, { useState } from 'react';

const MissingLanguageAttribute = () => {
  const [selectedLanguage, setSelectedLanguage] = useState('en');

  const content = {
    en: {
      title: "Welcome to Our Website",
      subtitle: "Discover amazing products and services",
      description: "We offer a wide range of high-quality products and professional services to meet all your needs.",
      button: "Learn More"
    },
    fr: {
      title: "Bienvenue sur Notre Site Web",
      subtitle: "Découvrez des produits et services incroyables",
      description: "Nous offrons une large gamme de produits de haute qualité et de services professionnels pour répondre à tous vos besoins.",
      button: "En Savoir Plus"
    }
  };

  const currentContent = content[selectedLanguage];

  return (
    <div style={{ 
      maxWidth: '1000px', 
      margin: '50px auto', 
      padding: '20px',
      fontFamily: 'Arial, sans-serif'
    }}>
      {/* Language selector */}
      <div style={{
        display: 'flex',
        justifyContent: 'flex-end',
        marginBottom: '30px'
      }}>
        <select
          value={selectedLanguage}
          onChange={(e) => setSelectedLanguage(e.target.value)}
          style={{
            padding: '8px 12px',
            border: '1px solid #ddd',
            borderRadius: '4px',
            fontSize: '14px'
          }}
        >
          <option value="en">English</option>
          <option value="fr">Français</option>
        </select>
      </div>

      {/* Hero section with mixed English/French content without lang attributes */}
      <div style={{
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        color: 'white',
        padding: '60px 40px',
        borderRadius: '12px',
        textAlign: 'center',
        marginBottom: '40px'
      }}>
        <h1 style={{ 
          fontSize: '48px', 
          margin: '0 0 20px 0',
          fontWeight: 'bold'
        }}>
          {currentContent.title}
        </h1>
        <p style={{ 
          fontSize: '20px', 
          margin: '0 0 30px 0',
          opacity: 0.9
        }}>
          {currentContent.subtitle}
        </p>
        <button style={{
          background: 'white',
          color: '#667eea',
          border: 'none',
          padding: '15px 30px',
          borderRadius: '25px',
          fontSize: '16px',
          fontWeight: 'bold',
          cursor: 'pointer',
          boxShadow: '0 4px 15px rgba(0,0,0,0.2)'
        }}>
          {currentContent.button}
        </button>
      </div>

      {/* Main content */}
      <div style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
        gap: '30px',
        marginBottom: '40px'
      }}>
        <div style={{
          background: 'white',
          padding: '30px',
          borderRadius: '8px',
          boxShadow: '0 2px 10px rgba(0,0,0,0.1)'
        }}>
          <h2 style={{ 
            fontSize: '24px', 
            margin: '0 0 15px 0',
            color: '#333'
          }}>
            About Us
          </h2>
          <p style={{ 
            fontSize: '16px', 
            lineHeight: '1.6',
            color: '#666',
            margin: 0
          }}>
            {currentContent.description}
          </p>
        </div>

        <div style={{
          background: 'white',
          padding: '30px',
          borderRadius: '8px',
          boxShadow: '0 2px 10px rgba(0,0,0,0.1)'
        }}>
          <h2 style={{ 
            fontSize: '24px', 
            margin: '0 0 15px 0',
            color: '#333'
          }}>
            Our Services
          </h2>
          <ul style={{ 
            margin: 0, 
            paddingLeft: '20px',
            fontSize: '16px',
            lineHeight: '1.8',
            color: '#666'
          }}>
            <li>Web Development</li>
            <li>Mobile App Development</li>
            <li>Cloud Solutions</li>
            <li>Digital Marketing</li>
          </ul>
        </div>
      </div>

      {/* Contact section */}
      <div style={{
        background: '#f8f9fa',
        padding: '40px',
        borderRadius: '8px',
        textAlign: 'center'
      }}>
        <h2 style={{ 
          fontSize: '28px', 
          margin: '0 0 20px 0',
          color: '#333'
        }}>
          Get in Touch
        </h2>
        <p style={{ 
          fontSize: '16px', 
          margin: '0 0 30px 0',
          color: '#666'
        }}>
          Ready to get started? Contact us today for more information.
        </p>
        <div style={{ display: 'flex', gap: '15px', justifyContent: 'center', flexWrap: 'wrap' }}>
          <button style={{
            background: '#007bff',
            color: 'white',
            border: 'none',
            padding: '12px 24px',
            borderRadius: '4px',
            fontSize: '16px',
            cursor: 'pointer'
          }}>
            Contact Us
          </button>
          <button style={{
            background: 'transparent',
            color: '#007bff',
            border: '2px solid #007bff',
            padding: '10px 24px',
            borderRadius: '4px',
            fontSize: '16px',
            cursor: 'pointer'
          }}>
            View Portfolio
          </button>
        </div>
      </div>
    </div>
  );
};

export default MissingLanguageAttribute;
