// scenarios/basic/web/vue/MissingSkipLink.vue
<template>
  <div class="website">
    <!-- Page navigation without skip-to-content link -->
    <header class="main-header">
      <div class="header-content">
        <div class="logo">Company Logo</div>
        
        <nav class="main-nav">
          <button 
            v-for="section in sections" 
            :key="section.id"
            @click="setActiveSection(section.id)"
            :class="['nav-btn', { active: activeSection === section.id }]"
          >
            {{ section.title }}
          </button>
        </nav>
      </div>
    </header>

    <!-- Main content area -->
    <main class="main-content">
      <!-- Hero section -->
      <section class="hero-section">
        <h1>{{ currentSection.title }}</h1>
        <p>{{ currentSection.subtitle }}</p>
        <button class="hero-btn">{{ currentSection.button }}</button>
      </section>

      <!-- Content sections -->
      <div class="content-grid">
        <div class="content-card">
          <h2>About Our Company</h2>
          <p>{{ currentSection.description }}</p>
        </div>

        <div class="content-card">
          <h2>Our Services</h2>
          <ul>
            <li v-for="feature in currentSection.features" :key="feature">
              {{ feature }}
            </li>
          </ul>
        </div>
      </div>

      <!-- Dynamic content based on active section -->
      <section class="dynamic-content">
        <h2>{{ currentSection.title }}</h2>
        <p>{{ currentSection.content }}</p>
      </section>

      <!-- Additional content sections -->
      <div class="features-grid">
        <div class="feature-item">
          <h3>Feature 1</h3>
          <p>Description of the first feature</p>
        </div>
        <div class="feature-item">
          <h3>Feature 2</h3>
          <p>Description of the second feature</p>
        </div>
        <div class="feature-item">
          <h3>Feature 3</h3>
          <p>Description of the third feature</p>
        </div>
      </div>
    </main>

    <!-- Footer -->
    <footer class="main-footer">
      <div class="footer-content">
        <p>© 2024 Company Name. All rights reserved.</p>
        <div class="footer-links">
          <a href="#">Privacy Policy</a>
          <a href="#">Terms of Service</a>
          <a href="#">Contact Us</a>
        </div>
      </div>
    </footer>
  </div>
</template>

<script>
export default {
  name: 'MissingSkipLink',
  data() {
    return {
      activeSection: 'home',
      sections: [
        { id: 'home', title: 'Home', content: 'Welcome to our website' },
        { id: 'about', title: 'About', content: 'Learn more about our company' },
        { id: 'services', title: 'Services', content: 'Our professional services' },
        { id: 'products', title: 'Products', content: 'Browse our product catalog' },
        { id: 'contact', title: 'Contact', content: 'Get in touch with us' }
      ],
      content: {
        home: {
          title: "Welcome to Our Platform",
          subtitle: "Discover innovative solutions for your business needs",
          button: "Get Started Today",
          description: "We are a leading technology company dedicated to providing innovative solutions that help businesses grow and succeed in the digital age.",
          features: ["Web Development", "Mobile App Development", "Cloud Solutions", "Digital Marketing"],
          content: "Welcome to our website"
        },
        about: {
          title: "About Our Company",
          subtitle: "Learn more about our mission and values",
          button: "Learn More",
          description: "We are a leading technology company dedicated to providing innovative solutions that help businesses grow and succeed in the digital age.",
          features: ["Expert Team", "Proven Track Record", "Customer Focus", "Innovation"],
          content: "Learn more about our company"
        },
        services: {
          title: "Our Services",
          subtitle: "Comprehensive solutions for your business",
          button: "View Services",
          description: "We offer a wide range of professional services to help your business succeed in the digital world.",
          features: ["Web Development", "Mobile App Development", "Cloud Solutions", "Digital Marketing"],
          content: "Our professional services"
        },
        products: {
          title: "Our Products",
          subtitle: "Discover our innovative product solutions",
          button: "Browse Products",
          description: "Explore our comprehensive range of products designed to meet your business needs.",
          features: ["Software Solutions", "Hardware Products", "Cloud Services", "Support"],
          content: "Browse our product catalog"
        },
        contact: {
          title: "Contact Us",
          subtitle: "Get in touch with our team",
          button: "Contact Now",
          description: "Ready to get started? Contact us today for more information about our services.",
          features: ["Email Support", "Phone Support", "Live Chat", "Documentation"],
          content: "Get in touch with us"
        }
      }
    }
  },
  computed: {
    currentSection() {
      return this.content[this.activeSection] || this.content.home
    }
  },
  methods: {
    setActiveSection(sectionId) {
      this.activeSection = sectionId
    }
  }
}
</script>

<style scoped>
.website {
  font-family: Arial, sans-serif;
  min-height: 100vh;
}

.main-header {
  background: #2c3e50;
  color: white;
  padding: 0;
  position: sticky;
  top: 0;
  z-index: 100;
  box-shadow: 0 2px 4px rgba(0,0,0,0.1);
}

.header-content {
  max-width: 1200px;
  margin: 0 auto;
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 20px;
}

.logo {
  font-size: 24px;
  font-weight: bold;
  padding: 15px 0;
}

.main-nav {
  display: flex;
  gap: 0;
}

.nav-btn {
  background: transparent;
  color: white;
  border: none;
  padding: 15px 20px;
  cursor: pointer;
  font-size: 16px;
  font-weight: 500;
  transition: background-color 0.3s ease;
}

.nav-btn.active {
  background: #34495e;
}

.main-content {
  max-width: 1200px;
  margin: 0 auto;
  padding: 40px 20px;
}

.hero-section {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  padding: 80px 40px;
  border-radius: 12px;
  text-align: center;
  margin-bottom: 60px;
}

.hero-section h1 {
  font-size: 48px;
  margin: 0 0 20px 0;
  font-weight: bold;
}

.hero-section p {
  font-size: 20px;
  margin: 0 0 40px 0;
  opacity: 0.9;
}

.hero-btn {
  background: white;
  color: #667eea;
  border: none;
  padding: 15px 30px;
  border-radius: 25px;
  font-size: 18px;
  font-weight: bold;
  cursor: pointer;
  box-shadow: 0 4px 15px rgba(0,0,0,0.2);
}

.content-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: 30px;
  margin-bottom: 60px;
}

.content-card {
  background: white;
  padding: 30px;
  border-radius: 8px;
  box-shadow: 0 2px 10px rgba(0,0,0,0.1);
  border: 1px solid #e0e0e0;
}

.content-card h2 {
  font-size: 24px;
  margin: 0 0 15px 0;
  color: #333;
}

.content-card p {
  font-size: 16px;
  line-height: 1.6;
  color: #666;
  margin: 0;
}

.content-card ul {
  margin: 0;
  padding-left: 20px;
  font-size: 16px;
  line-height: 1.8;
  color: #666;
}

.dynamic-content {
  background: #f8f9fa;
  padding: 40px;
  border-radius: 8px;
  margin-bottom: 40px;
}

.dynamic-content h2 {
  font-size: 28px;
  margin: 0 0 20px 0;
  color: #333;
}

.dynamic-content p {
  font-size: 18px;
  line-height: 1.6;
  color: #666;
  margin: 0;
}

.features-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
  gap: 20px;
  margin-bottom: 40px;
}

.feature-item {
  background: white;
  padding: 20px;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0,0,0,0.1);
  border: 1px solid #e0e0e0;
}

.feature-item h3 {
  font-size: 18px;
  margin: 0 0 10px 0;
  color: #333;
}

.feature-item p {
  font-size: 14px;
  color: #666;
  margin: 0;
}

.main-footer {
  background: #34495e;
  color: white;
  padding: 40px 20px;
  text-align: center;
}

.footer-content {
  max-width: 1200px;
  margin: 0 auto;
}

.footer-content p {
  margin: 0 0 20px 0;
  font-size: 16px;
}

.footer-links {
  display: flex;
  justify-content: center;
  gap: 30px;
  flex-wrap: wrap;
}

.footer-links a {
  color: white;
  text-decoration: none;
}
</style>

// scenarios/basic/web/react/MissingSkipLink.jsx
import React, { useState } from 'react';

const MissingSkipLink = () => {
  const [activeSection, setActiveSection] = useState('home');

  const sections = [
    { id: 'home', title: 'Home', content: 'Welcome to our website' },
    { id: 'about', title: 'About', content: 'Learn more about our company' },
    { id: 'services', title: 'Services', content: 'Our professional services' },
    { id: 'products', title: 'Products', content: 'Browse our product catalog' },
    { id: 'contact', title: 'Contact', content: 'Get in touch with us' }
  ];

  return (
    <div style={{ 
      fontFamily: 'Arial, sans-serif',
      minHeight: '100vh'
    }}>
      {/* Page navigation without skip-to-content link */}
      <header style={{
        background: '#2c3e50',
        color: 'white',
        padding: '0',
        position: 'sticky',
        top: 0,
        zIndex: 100,
        boxShadow: '0 2px 4px rgba(0,0,0,0.1)'
      }}>
        <div style={{
          maxWidth: '1200px',
          margin: '0 auto',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          padding: '0 20px'
        }}>
          <div style={{
            fontSize: '24px',
            fontWeight: 'bold',
            padding: '15px 0'
          }}>
            Company Logo
          </div>
          
          <nav style={{ display: 'flex', gap: '0' }}>
            {sections.map(section => (
              <button
                key={section.id}
                onClick={() => setActiveSection(section.id)}
                style={{
                  background: activeSection === section.id ? '#34495e' : 'transparent',
                  color: 'white',
                  border: 'none',
                  padding: '15px 20px',
                  cursor: 'pointer',
                  fontSize: '16px',
                  fontWeight: '500',
                  transition: 'background-color 0.3s ease'
                }}
              >
                {section.title}
              </button>
            ))}
          </nav>
        </div>
      </header>

      {/* Main content area */}
      <main style={{
        maxWidth: '1200px',
        margin: '0 auto',
        padding: '40px 20px'
      }}>
        {/* Hero section */}
        <section style={{
          background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
          color: 'white',
          padding: '80px 40px',
          borderRadius: '12px',
          textAlign: 'center',
          marginBottom: '60px'
        }}>
          <h1 style={{ 
            fontSize: '48px', 
            margin: '0 0 20px 0',
            fontWeight: 'bold'
          }}>
            Welcome to Our Platform
          </h1>
          <p style={{ 
            fontSize: '20px', 
            margin: '0 0 40px 0',
            opacity: 0.9
          }}>
            Discover innovative solutions for your business needs
          </p>
          <button style={{
            background: 'white',
            color: '#667eea',
            border: 'none',
            padding: '15px 30px',
            borderRadius: '25px',
            fontSize: '18px',
            fontWeight: 'bold',
            cursor: 'pointer',
            boxShadow: '0 4px 15px rgba(0,0,0,0.2)'
          }}>
            Get Started Today
          </button>
        </section>

        {/* Content sections */}
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
          gap: '30px',
          marginBottom: '60px'
        }}>
          <div style={{
            background: 'white',
            padding: '30px',
            borderRadius: '8px',
            boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
            border: '1px solid #e0e0e0'
          }}>
            <h2 style={{ 
              fontSize: '24px', 
              margin: '0 0 15px 0',
              color: '#333'
            }}>
              About Our Company
            </h2>
            <p style={{ 
              fontSize: '16px', 
              lineHeight: '1.6',
              color: '#666',
              margin: 0
            }}>
              We are a leading technology company dedicated to providing innovative 
              solutions that help businesses grow and succeed in the digital age.
            </p>
          </div>

          <div style={{
            background: 'white',
            padding: '30px',
            borderRadius: '8px',
            boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
            border: '1px solid #e0e0e0'
          }}>
            <h2 style={{ 
              fontSize: '24px', 
              margin: '0 0 15px 0',
              color: '#333'
            }}>
              Our Services
            </h2>
            <ul style={{ 
              margin: 0, 
              paddingLeft: '20px',
              fontSize: '16px',
              lineHeight: '1.8',
              color: '#666'
            }}>
              <li>Web Development</li>
              <li>Mobile App Development</li>
              <li>Cloud Solutions</li>
              <li>Digital Marketing</li>
            </ul>
          </div>
        </div>

        {/* Dynamic content based on active section */}
        <section style={{
          background: '#f8f9fa',
          padding: '40px',
          borderRadius: '8px',
          marginBottom: '40px'
        }}>
          <h2 style={{ 
            fontSize: '28px', 
            margin: '0 0 20px 0',
            color: '#333'
          }}>
            {sections.find(s => s.id === activeSection)?.title}
          </h2>
          <p style={{ 
            fontSize: '18px', 
            lineHeight: '1.6',
            color: '#666',
            margin: 0
          }}>
            {sections.find(s => s.id === activeSection)?.content}
          </p>
        </section>

        {/* Additional content sections */}
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
          gap: '20px',
          marginBottom: '40px'
        }}>
          <div style={{
            background: 'white',
            padding: '20px',
            borderRadius: '8px',
            boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
            border: '1px solid #e0e0e0'
          }}>
            <h3 style={{ 
              fontSize: '18px', 
              margin: '0 0 10px 0',
              color: '#333'
            }}>
              Feature 1
            </h3>
            <p style={{ 
              fontSize: '14px', 
              color: '#666',
              margin: 0
            }}>
              Description of the first feature
            </p>
          </div>
          <div style={{
            background: 'white',
            padding: '20px',
            borderRadius: '8px',
            boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
            border: '1px solid #e0e0e0'
          }}>
            <h3 style={{ 
              fontSize: '18px', 
              margin: '0 0 10px 0',
              color: '#333'
            }}>
              Feature 2
            </h3>
            <p style={{ 
              fontSize: '14px', 
              color: '#666',
              margin: 0
            }}>
              Description of the second feature
            </p>
          </div>
          <div style={{
            background: 'white',
            padding: '20px',
            borderRadius: '8px',
            boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
            border: '1px solid #e0e0e0'
          }}>
            <h3 style={{ 
              fontSize: '18px', 
              margin: '0 0 10px 0',
              color: '#333'
            }}>
              Feature 3
            </h3>
            <p style={{ 
              fontSize: '14px', 
              color: '#666',
              margin: 0
            }}>
              Description of the third feature
            </p>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer style={{
        background: '#34495e',
        color: 'white',
        padding: '40px 20px',
        textAlign: 'center'
      }}>
        <div style={{
          maxWidth: '1200px',
          margin: '0 auto'
        }}>
          <p style={{ 
            margin: '0 0 20px 0',
            fontSize: '16px'
          }}>
            © 2024 Company Name. All rights reserved.
          </p>
          <div style={{
            display: 'flex',
            justifyContent: 'center',
            gap: '30px',
            flexWrap: 'wrap'
          }}>
            <a href="#" style={{ color: 'white', textDecoration: 'none' }}>Privacy Policy</a>
            <a href="#" style={{ color: 'white', textDecoration: 'none' }}>Terms of Service</a>
            <a href="#" style={{ color: 'white', textDecoration: 'none' }}>Contact Us</a>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default MissingSkipLink;
