// scenarios/basic/web/vue/n14.vue
<template>
  <div class="employee-directory">
    <h1>Employee Directory</h1>
    <p>View and manage employee information across all departments.</p>
    
    <div class="stats-section">
      <h2>Department Statistics</h2>
      <div class="stats-grid">
        <div class="stat-card">
          <div class="stat-number">5</div>
          <div class="stat-label">Total Employees</div>
        </div>
        <div class="stat-card">
          <div class="stat-number">4</div>
          <div class="stat-label">Departments</div>
        </div>
        <div class="stat-card">
          <div class="stat-number">$73,600</div>
          <div class="stat-label">Average Salary</div>
        </div>
      </div>
    </div>

    <div class="table-container">
      <div class="table-header">
        <h2>Employee List</h2>
        <p>Click on column headers to sort the data</p>
      </div>
      
      <div class="table-wrapper">
        <table class="employee-table">
          <tbody>
            <!-- Using td elements instead of th for column headers -->
            <tr class="header-row">
              <td 
                v-for="header in headers" 
                :key="header.key"
                @click="handleSort(header.key)"
                class="sortable-header"
              >
                {{ header.label }} {{ sortField === header.key && (sortDirection === 'asc' ? '↑' : '↓') }}
              </td>
            </tr>
            <tr 
              v-for="(employee, index) in sortedEmployees" 
              :key="employee.id"
              :class="['data-row', { 'even': index % 2 === 0 }]"
            >
              <td>{{ employee.name }}</td>
              <td>
                <span class="department-badge">{{ employee.department }}</span>
              </td>
              <td>{{ employee.position }}</td>
              <td>${{ employee.salary.toLocaleString() }}</td>
              <td>
                <span class="status-badge">{{ employee.status }}</span>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'MissingTableHeader',
  data() {
    return {
      employees: [
        { id: 1, name: 'John Smith', department: 'Engineering', position: 'Senior Developer', salary: 95000, status: 'Active' },
        { id: 2, name: 'Sarah Johnson', department: 'Marketing', position: 'Marketing Manager', salary: 78000, status: 'Active' },
        { id: 3, name: 'Mike Wilson', department: 'Sales', position: 'Sales Representative', salary: 65000, status: 'Active' },
        { id: 4, name: 'Emily Davis', department: 'HR', position: 'HR Specialist', salary: 60000, status: 'Active' },
        { id: 5, name: 'David Brown', department: 'Finance', position: 'Financial Analyst', salary: 70000, status: 'Active' }
      ],
      sortField: null,
      sortDirection: 'asc',
      headers: [
        { key: 'name', label: 'Name' },
        { key: 'department', label: 'Department' },
        { key: 'position', label: 'Position' },
        { key: 'salary', label: 'Salary' },
        { key: 'status', label: 'Status' }
      ]
    }
  },
  computed: {
    sortedEmployees() {
      if (!this.sortField) return this.employees
      
      return [...this.employees].sort((a, b) => {
        const aValue = a[this.sortField]
        const bValue = b[this.sortField]
        
        if (typeof aValue === 'string') {
          return this.sortDirection === 'asc' 
            ? aValue.localeCompare(bValue)
            : bValue.localeCompare(aValue)
        }
        
        return this.sortDirection === 'asc' ? aValue - bValue : bValue - aValue
      })
    }
  },
  methods: {
    handleSort(field) {
      if (this.sortField === field) {
        this.sortDirection = this.sortDirection === 'asc' ? 'desc' : 'asc'
      } else {
        this.sortField = field
        this.sortDirection = 'asc'
      }
    }
  }
}
</script>

<style scoped>
.employee-directory {
  max-width: 1000px;
  margin: 50px auto;
  padding: 20px;
  font-family: Arial, sans-serif;
}

.stats-section {
  background: #f8f9fa;
  padding: 20px;
  border-radius: 8px;
  margin-bottom: 30px;
}

.stats-section h2 {
  margin: 0 0 15px 0;
}

.stats-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 20px;
  margin-top: 15px;
}

.stat-card {
  background: white;
  padding: 15px;
  border-radius: 4px;
  text-align: center;
  border: 1px solid #e0e0e0;
}

.stat-number {
  font-size: 24px;
  font-weight: bold;
  color: #007bff;
  margin-bottom: 5px;
}

.stat-label {
  font-size: 14px;
  color: #666;
}

.table-container {
  background: white;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0,0,0,0.1);
  overflow: hidden;
  border: 1px solid #e0e0e0;
}

.table-header {
  background: #f8f9fa;
  padding: 20px;
  border-bottom: 1px solid #e0e0e0;
}

.table-header h2 {
  margin: 0;
  font-size: 20px;
}

.table-header p {
  margin: 5px 0 0 0;
  color: #666;
  font-size: 14px;
}

.table-wrapper {
  overflow-x: auto;
}

.employee-table {
  width: 100%;
  border-collapse: collapse;
  font-size: 14px;
}

.header-row {
  background: #e9ecef;
  border-bottom: 2px solid #dee2e6;
}

.sortable-header {
  padding: 12px 16px;
  font-weight: bold;
  cursor: pointer;
  user-select: none;
  border-right: 1px solid #dee2e6;
}

.data-row {
  border-bottom: 1px solid #e0e0e0;
}

.data-row.even {
  background: #f8f9fa;
}

.data-row td {
  padding: 12px 16px;
  border-right: 1px solid #e0e0e0;
}

.department-badge {
  background: #e3f2fd;
  color: #1976d2;
  padding: 4px 8px;
  border-radius: 12px;
  font-size: 12px;
  font-weight: bold;
}

.status-badge {
  background: #e8f5e8;
  color: #2e7d32;
  padding: 4px 8px;
  border-radius: 12px;
  font-size: 12px;
  font-weight: bold;
}
</style>

// scenarios/basic/web/react/n14.jsx
import React, { useState } from 'react';

const MissingTableHeader = () => {
  const [employees] = useState([
    { id: 1, name: 'John Smith', department: 'Engineering', position: 'Senior Developer', salary: 95000, status: 'Active' },
    { id: 2, name: 'Sarah Johnson', department: 'Marketing', position: 'Marketing Manager', salary: 78000, status: 'Active' },
    { id: 3, name: 'Mike Wilson', department: 'Sales', position: 'Sales Representative', salary: 65000, status: 'Active' },
    { id: 4, name: 'Emily Davis', department: 'HR', position: 'HR Specialist', salary: 60000, status: 'Active' },
    { id: 5, name: 'David Brown', department: 'Finance', position: 'Financial Analyst', salary: 70000, status: 'Active' }
  ]);

  const [sortField, setSortField] = useState(null);
  const [sortDirection, setSortDirection] = useState('asc');

  const handleSort = (field) => {
    if (sortField === field) {
      setSortDirection(sortDirection === 'asc' ? 'desc' : 'asc');
    } else {
      setSortField(field);
      setSortDirection('asc');
    }
  };

  const sortedEmployees = [...employees].sort((a, b) => {
    if (!sortField) return 0;
    
    const aValue = a[sortField];
    const bValue = b[sortField];
    
    if (typeof aValue === 'string') {
      return sortDirection === 'asc' 
        ? aValue.localeCompare(bValue)
        : bValue.localeCompare(aValue);
    }
    
    return sortDirection === 'asc' ? aValue - bValue : bValue - aValue;
  });

  return (
    <div style={{ 
      maxWidth: '1000px', 
      margin: '50px auto', 
      padding: '20px',
      fontFamily: 'Arial, sans-serif'
    }}>
      <h1>Employee Directory</h1>
      <p>View and manage employee information across all departments.</p>
      
      <div style={{
        background: '#f8f9fa',
        padding: '20px',
        borderRadius: '8px',
        marginBottom: '30px'
      }}>
        <h2>Department Statistics</h2>
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
          gap: '20px',
          marginTop: '15px'
        }}>
          <div style={{
            background: 'white',
            padding: '15px',
            borderRadius: '4px',
            textAlign: 'center',
            border: '1px solid #e0e0e0'
          }}>
            <div style={{ fontSize: '24px', fontWeight: 'bold', color: '#007bff' }}>5</div>
            <div style={{ fontSize: '14px', color: '#666' }}>Total Employees</div>
          </div>
          <div style={{
            background: 'white',
            padding: '15px',
            borderRadius: '4px',
            textAlign: 'center',
            border: '1px solid #e0e0e0'
          }}>
            <div style={{ fontSize: '24px', fontWeight: 'bold', color: '#28a745' }}>4</div>
            <div style={{ fontSize: '14px', color: '#666' }}>Departments</div>
          </div>
          <div style={{
            background: 'white',
            padding: '15px',
            borderRadius: '4px',
            textAlign: 'center',
            border: '1px solid #e0e0e0'
          }}>
            <div style={{ fontSize: '24px', fontWeight: 'bold', color: '#ffc107' }}>$73,600</div>
            <div style={{ fontSize: '14px', color: '#666' }}>Average Salary</div>
          </div>
        </div>
      </div>

      <div style={{
        background: 'white',
        borderRadius: '8px',
        boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
        overflow: 'hidden',
        border: '1px solid #e0e0e0'
      }}>
        <div style={{
          background: '#f8f9fa',
          padding: '20px',
          borderBottom: '1px solid #e0e0e0'
        }}>
          <h2 style={{ margin: 0, fontSize: '20px' }}>Employee List</h2>
          <p style={{ margin: '5px 0 0 0', color: '#666', fontSize: '14px' }}>
            Click on column headers to sort the data
          </p>
        </div>
        
        <div style={{ overflowX: 'auto' }}>
          <table style={{
            width: '100%',
            borderCollapse: 'collapse',
            fontSize: '14px'
          }}>
            <tbody>
              {/* Using td elements instead of th for column headers */}
              <tr style={{
                background: '#e9ecef',
                borderBottom: '2px solid #dee2e6'
              }}>
                <td 
                  style={{
                    padding: '12px 16px',
                    fontWeight: 'bold',
                    cursor: 'pointer',
                    userSelect: 'none',
                    borderRight: '1px solid #dee2e6'
                  }}
                  onClick={() => handleSort('name')}
                >
                  Name {sortField === 'name' && (sortDirection === 'asc' ? '↑' : '↓')}
                </td>
                <td 
                  style={{
                    padding: '12px 16px',
                    fontWeight: 'bold',
                    cursor: 'pointer',
                    userSelect: 'none',
                    borderRight: '1px solid #dee2e6'
                  }}
                  onClick={() => handleSort('department')}
                >
                  Department {sortField === 'department' && (sortDirection === 'asc' ? '↑' : '↓')}
                </td>
                <td 
                  style={{
                    padding: '12px 16px',
                    fontWeight: 'bold',
                    cursor: 'pointer',
                    userSelect: 'none',
                    borderRight: '1px solid #dee2e6'
                  }}
                  onClick={() => handleSort('position')}
                >
                  Position {sortField === 'position' && (sortDirection === 'asc' ? '↑' : '↓')}
                </td>
                <td 
                  style={{
                    padding: '12px 16px',
                    fontWeight: 'bold',
                    cursor: 'pointer',
                    userSelect: 'none',
                    borderRight: '1px solid #dee2e6'
                  }}
                  onClick={() => handleSort('salary')}
                >
                  Salary {sortField === 'salary' && (sortDirection === 'asc' ? '↑' : '↓')}
                </td>
                <td 
                  style={{
                    padding: '12px 16px',
                    fontWeight: 'bold',
                    cursor: 'pointer',
                    userSelect: 'none'
                  }}
                  onClick={() => handleSort('status')}
                >
                  Status {sortField === 'status' && (sortDirection === 'asc' ? '↑' : '↓')}
                </td>
              </tr>
              {sortedEmployees.map((employee, index) => (
                <tr 
                  key={employee.id}
                  style={{
                    borderBottom: '1px solid #e0e0e0',
                    background: index % 2 === 0 ? 'white' : '#f8f9fa'
                  }}
                >
                  <td style={{ padding: '12px 16px', borderRight: '1px solid #e0e0e0' }}>
                    {employee.name}
                  </td>
                  <td style={{ padding: '12px 16px', borderRight: '1px solid #e0e0e0' }}>
                    <span style={{
                      background: '#e3f2fd',
                      color: '#1976d2',
                      padding: '4px 8px',
                      borderRadius: '12px',
                      fontSize: '12px',
                      fontWeight: 'bold'
                    }}>
                      {employee.department}
                    </span>
                  </td>
                  <td style={{ padding: '12px 16px', borderRight: '1px solid #e0e0e0' }}>
                    {employee.position}
                  </td>
                  <td style={{ padding: '12px 16px', borderRight: '1px solid #e0e0e0' }}>
                    ${employee.salary.toLocaleString()}
                  </td>
                  <td style={{ padding: '12px 16px' }}>
                    <span style={{
                      background: '#e8f5e8',
                      color: '#2e7d32',
                      padding: '4px 8px',
                      borderRadius: '12px',
                      fontSize: '12px',
                      fontWeight: 'bold'
                    }}>
                      {employee.status}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default MissingTableHeader;
