// scenarios/basic/web/vue/UngroupedRadioButtons.vue
<template>
  <div class="contact-form">
    <h1>Contact Information Form</h1>
    <p>Please provide your contact details and preferences.</p>
    
    <form @submit.prevent="handleSubmit" class="form-container">
      <div class="form-group">
        <label class="form-label">Full Name *</label>
        <input
          type="text"
          v-model="formData.name"
          required
          class="form-input"
        />
      </div>

      <div class="form-group">
        <label class="form-label">Email Address *</label>
        <input
          type="email"
          v-model="formData.email"
          required
          class="form-input"
        />
      </div>

      <div class="form-group">
        <label class="form-label">Phone Number</label>
        <input
          type="tel"
          v-model="formData.phone"
          class="form-input"
        />
      </div>

      <div class="form-group">
        <label class="form-label">Preferred Contact Method</label>
        
        <!-- Contact preference radio buttons without fieldset grouping -->
        <div class="radio-group">
          <div class="radio-item">
            <input
              type="radio"
              id="email-contact"
              v-model="formData.contactPreference"
              value="email"
              class="radio-input"
            />
            <label for="email-contact" class="radio-label">Email</label>
          </div>
          
          <div class="radio-item">
            <input
              type="radio"
              id="phone-contact"
              v-model="formData.contactPreference"
              value="phone"
              class="radio-input"
            />
            <label for="phone-contact" class="radio-label">Phone</label>
          </div>
          
          <div class="radio-item">
            <input
              type="radio"
              id="text-contact"
              v-model="formData.contactPreference"
              value="text"
              class="radio-input"
            />
            <label for="text-contact" class="radio-label">Text Message</label>
          </div>
          
          <div class="radio-item">
            <input
              type="radio"
              id="mail-contact"
              v-model="formData.contactPreference"
              value="mail"
              class="radio-input"
            />
            <label for="mail-contact" class="radio-label">Postal Mail</label>
          </div>
        </div>
      </div>

      <div class="form-group">
        <label class="form-label">Communication Preferences</label>
        
        <div class="checkbox-group">
          <div class="checkbox-item">
            <input
              type="checkbox"
              id="newsletter"
              v-model="formData.newsletter"
              class="checkbox-input"
            />
            <label for="newsletter" class="checkbox-label">Subscribe to our newsletter</label>
          </div>
          
          <div class="checkbox-item">
            <input
              type="checkbox"
              id="notifications"
              v-model="formData.notifications"
              class="checkbox-input"
            />
            <label for="notifications" class="checkbox-label">Receive promotional notifications</label>
          </div>
        </div>
      </div>

      <div class="form-actions">
        <button type="button" class="btn-secondary">Cancel</button>
        <button type="submit" class="btn-primary">Submit</button>
      </div>
    </form>
  </div>
</template>

<script>
export default {
  name: 'UngroupedRadioButtons',
  data() {
    return {
      formData: {
        name: '',
        email: '',
        phone: '',
        contactPreference: '',
        newsletter: false,
        notifications: false
      }
    }
  },
  methods: {
    handleSubmit() {
      alert('Form submitted successfully!')
    }
  }
}
</script>

<style scoped>
.contact-form {
  max-width: 600px;
  margin: 50px auto;
  padding: 20px;
  font-family: Arial, sans-serif;
}

.form-container {
  background: white;
  padding: 30px;
  border-radius: 8px;
  box-shadow: 0 2px 10px rgba(0,0,0,0.1);
  border: 1px solid #e0e0e0;
}

.form-group {
  margin-bottom: 25px;
}

.form-label {
  display: block;
  margin-bottom: 5px;
  font-weight: bold;
  color: #333;
}

.form-input {
  width: 100%;
  padding: 12px;
  border: 1px solid #ddd;
  border-radius: 4px;
  font-size: 16px;
  box-sizing: border-box;
}

.radio-group {
  margin-top: 10px;
}

.radio-item {
  margin-bottom: 10px;
}

.radio-input {
  margin-right: 8px;
}

.radio-label {
  cursor: pointer;
}

.checkbox-group {
  margin-top: 10px;
}

.checkbox-item {
  margin-bottom: 15px;
}

.checkbox-input {
  margin-right: 10px;
}

.checkbox-label {
  display: flex;
  align-items: center;
  cursor: pointer;
  font-weight: bold;
  color: #333;
}

.form-actions {
  display: flex;
  gap: 15px;
  justify-content: flex-end;
}

.btn-primary {
  background: #007bff;
  color: white;
  border: none;
  padding: 12px 24px;
  border-radius: 4px;
  cursor: pointer;
  font-size: 16px;
}

.btn-secondary {
  background: #6c757d;
  color: white;
  border: none;
  padding: 12px 24px;
  border-radius: 4px;
  cursor: pointer;
  font-size: 16px;
}
</style>

// scenarios/basic/web/react/UngroupedRadioButtons.jsx
import React, { useState } from 'react';

const UngroupedRadioButtons = () => {
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    phone: '',
    contactPreference: '',
    newsletter: false,
    notifications: false
  });

  const handleInputChange = (e) => {
    const { name, value, type, checked } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value
    }));
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    alert('Form submitted successfully!');
  };

  return (
    <div style={{ 
      maxWidth: '600px', 
      margin: '50px auto', 
      padding: '20px',
      fontFamily: 'Arial, sans-serif'
    }}>
      <h1>Contact Information Form</h1>
      <p>Please provide your contact details and preferences.</p>
      
      <form onSubmit={handleSubmit} style={{
        background: 'white',
        padding: '30px',
        borderRadius: '8px',
        boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
        border: '1px solid #e0e0e0'
      }}>
        <div style={{ marginBottom: '25px' }}>
          <label style={{
            display: 'block',
            marginBottom: '5px',
            fontWeight: 'bold',
            color: '#333'
          }}>
            Full Name *
          </label>
          <input
            type="text"
            name="name"
            value={formData.name}
            onChange={handleInputChange}
            required
            style={{
              width: '100%',
              padding: '12px',
              border: '1px solid #ddd',
              borderRadius: '4px',
              fontSize: '16px',
              boxSizing: 'border-box'
            }}
          />
        </div>

        <div style={{ marginBottom: '25px' }}>
          <label style={{
            display: 'block',
            marginBottom: '5px',
            fontWeight: 'bold',
            color: '#333'
          }}>
            Email Address *
          </label>
          <input
            type="email"
            name="email"
            value={formData.email}
            onChange={handleInputChange}
            required
            style={{
              width: '100%',
              padding: '12px',
              border: '1px solid #ddd',
              borderRadius: '4px',
              fontSize: '16px',
              boxSizing: 'border-box'
            }}
          />
        </div>

        <div style={{ marginBottom: '25px' }}>
          <label style={{
            display: 'block',
            marginBottom: '5px',
            fontWeight: 'bold',
            color: '#333'
          }}>
            Phone Number
          </label>
          <input
            type="tel"
            name="phone"
            value={formData.phone}
            onChange={handleInputChange}
            style={{
              width: '100%',
              padding: '12px',
              border: '1px solid #ddd',
              borderRadius: '4px',
              fontSize: '16px',
              boxSizing: 'border-box'
            }}
          />
        </div>

        <div style={{ marginBottom: '25px' }}>
          <label style={{
            display: 'block',
            marginBottom: '10px',
            fontWeight: 'bold',
            color: '#333'
          }}>
            Preferred Contact Method
          </label>
          
          {/* Contact preference radio buttons without fieldset grouping */}
          <div style={{ marginBottom: '10px' }}>
            <input
              type="radio"
              id="email-contact"
              name="contactPreference"
              value="email"
              checked={formData.contactPreference === 'email'}
              onChange={handleInputChange}
              style={{ marginRight: '8px' }}
            />
            <label htmlFor="email-contact" style={{ cursor: 'pointer' }}>
              Email
            </label>
          </div>
          
          <div style={{ marginBottom: '10px' }}>
            <input
              type="radio"
              id="phone-contact"
              name="contactPreference"
              value="phone"
              checked={formData.contactPreference === 'phone'}
              onChange={handleInputChange}
              style={{ marginRight: '8px' }}
            />
            <label htmlFor="phone-contact" style={{ cursor: 'pointer' }}>
              Phone
            </label>
          </div>
          
          <div style={{ marginBottom: '10px' }}>
            <input
              type="radio"
              id="text-contact"
              name="contactPreference"
              value="text"
              checked={formData.contactPreference === 'text'}
              onChange={handleInputChange}
              style={{ marginRight: '8px' }}
            />
            <label htmlFor="text-contact" style={{ cursor: 'pointer' }}>
              Text Message
            </label>
          </div>
          
          <div style={{ marginBottom: '10px' }}>
            <input
              type="radio"
              id="mail-contact"
              name="contactPreference"
              value="mail"
              checked={formData.contactPreference === 'mail'}
              onChange={handleInputChange}
              style={{ marginRight: '8px' }}
            />
            <label htmlFor="mail-contact" style={{ cursor: 'pointer' }}>
              Postal Mail
            </label>
          </div>
        </div>

        <div style={{ marginBottom: '25px' }}>
          <label style={{
            display: 'block',
            marginBottom: '10px',
            fontWeight: 'bold',
            color: '#333'
          }}>
            Communication Preferences
          </label>
          
          <div style={{ marginBottom: '10px' }}>
            <input
              type="checkbox"
              id="newsletter"
              name="newsletter"
              checked={formData.newsletter}
              onChange={handleInputChange}
              style={{ marginRight: '8px' }}
            />
            <label htmlFor="newsletter" style={{ cursor: 'pointer' }}>
              Subscribe to our newsletter
            </label>
          </div>
          
          <div style={{ marginBottom: '10px' }}>
            <input
              type="checkbox"
              id="notifications"
              name="notifications"
              checked={formData.notifications}
              onChange={handleInputChange}
              style={{ marginRight: '8px' }}
            />
            <label htmlFor="notifications" style={{ cursor: 'pointer' }}>
              Receive promotional notifications
            </label>
          </div>
        </div>

        <div style={{
          display: 'flex',
          gap: '15px',
          justifyContent: 'flex-end'
        }}>
          <button
            type="button"
            style={{
              background: '#6c757d',
              color: 'white',
              border: 'none',
              padding: '12px 24px',
              borderRadius: '4px',
              cursor: 'pointer',
              fontSize: '16px'
            }}
          >
            Cancel
          </button>
          <button
            type="submit"
            style={{
              background: '#007bff',
              color: 'white',
              border: 'none',
              padding: '12px 24px',
              borderRadius: '4px',
              cursor: 'pointer',
              fontSize: '16px'
            }}
          >
            Submit
          </button>
        </div>
      </form>
    </div>
  );
};

export default UngroupedRadioButtons;
