// scenarios/advanced/web/react/n9.jsx
import React, { useState } from 'react';

const FormValidationWithoutAssociation = () => {
  const [formData, setFormData] = useState({
    username: '',
    password: '',
    email: '',
    confirmPassword: ''
  });
  const [errors, setErrors] = useState({});
  const [isSubmitting, setIsSubmitting] = useState(false);

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
    
    // Clear error when user starts typing
    if (errors[name]) {
      setErrors(prev => ({
        ...prev,
        [name]: ''
      }));
    }
  };

  const validateForm = () => {
    const newErrors = {};

    if (!formData.username.trim()) {
      newErrors.username = 'Username is required';
    } else if (formData.username.length < 3) {
      newErrors.username = 'Username must be at least 3 characters';
    }

    if (!formData.email.trim()) {
      newErrors.email = 'Email is required';
    } else if (!/\S+@\S+\.\S+/.test(formData.email)) {
      newErrors.email = 'Please enter a valid email address';
    }

    if (!formData.password) {
      newErrors.password = 'Password is required';
    } else if (formData.password.length < 8) {
      newErrors.password = 'Password must be at least 8 characters';
    }

    if (!formData.confirmPassword) {
      newErrors.confirmPassword = 'Please confirm your password';
    } else if (formData.password !== formData.confirmPassword) {
      newErrors.confirmPassword = 'Passwords do not match';
    }

    return newErrors;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setIsSubmitting(true);

    const validationErrors = validateForm();
    
    if (Object.keys(validationErrors).length > 0) {
      setErrors(validationErrors);
      setIsSubmitting(false);
      return;
    }

    // Simulate API call
    try {
      await new Promise(resolve => setTimeout(resolve, 1000));
      alert('Registration successful!');
      setFormData({ username: '', password: '', email: '', confirmPassword: '' });
      setErrors({});
    } catch (error) {
      alert('Registration failed. Please try again.');
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div style={{ fontFamily: 'Arial, sans-serif', maxWidth: '600px', margin: '50px auto', padding: '20px', backgroundColor: '#f5f5f5' }}>
      <div style={{ background: 'white', padding: '30px', borderRadius: '8px', boxShadow: '0 2px 10px rgba(0,0,0,0.1)' }}>
        <h1>User Registration</h1>
        <p>Create your account by filling out the form below.</p>
        
        <form onSubmit={handleSubmit} style={{ marginTop: '20px' }}>
          <div style={{ marginBottom: '20px' }}>
            <label htmlFor="username" style={{ display: 'block', marginBottom: '5px', fontWeight: 'bold', color: '#333' }}>
              Username:
            </label>
            <input
              type="text"
              id="username"
              name="username"
              value={formData.username}
              onChange={handleInputChange}
              style={{
                width: '100%',
                padding: '12px',
                border: '2px solid #ddd',
                borderRadius: '4px',
                fontSize: '16px',
                boxSizing: 'border-box',
                borderColor: errors.username ? '#dc3545' : '#ddd'
              }}
            />
          </div>
          
          <div style={{ marginBottom: '20px' }}>
            <label htmlFor="email" style={{ display: 'block', marginBottom: '5px', fontWeight: 'bold', color: '#333' }}>
              Email:
            </label>
            <input
              type="email"
              id="email"
              name="email"
              value={formData.email}
              onChange={handleInputChange}
              style={{
                width: '100%',
                padding: '12px',
                border: '2px solid #ddd',
                borderRadius: '4px',
                fontSize: '16px',
                boxSizing: 'border-box',
                borderColor: errors.email ? '#dc3545' : '#ddd'
              }}
            />
          </div>
          
          <div style={{ marginBottom: '20px' }}>
            <label htmlFor="password" style={{ display: 'block', marginBottom: '5px', fontWeight: 'bold', color: '#333' }}>
              Password:
            </label>
            <input
              type="password"
              id="password"
              name="password"
              value={formData.password}
              onChange={handleInputChange}
              style={{
                width: '100%',
                padding: '12px',
                border: '2px solid #ddd',
                borderRadius: '4px',
                fontSize: '16px',
                boxSizing: 'border-box',
                borderColor: errors.password ? '#dc3545' : '#ddd'
              }}
            />
          </div>
          
          <div style={{ marginBottom: '20px' }}>
            <label htmlFor="confirmPassword" style={{ display: 'block', marginBottom: '5px', fontWeight: 'bold', color: '#333' }}>
              Confirm Password:
            </label>
            <input
              type="password"
              id="confirmPassword"
              name="confirmPassword"
              value={formData.confirmPassword}
              onChange={handleInputChange}
              style={{
                width: '100%',
                padding: '12px',
                border: '2px solid #ddd',
                borderRadius: '4px',
                fontSize: '16px',
                boxSizing: 'border-box',
                borderColor: errors.confirmPassword ? '#dc3545' : '#ddd'
              }}
            />
          </div>
          
          {/* Error Messages - Not properly associated with fields */}
          {Object.keys(errors).length > 0 && (
            <div style={{ 
              color: '#dc3545', 
              fontSize: '14px', 
              marginBottom: '20px',
              padding: '10px',
              backgroundColor: '#f8d7da',
              border: '1px solid #f5c6cb',
              borderRadius: '4px'
            }}>
              <strong>Please fix the following errors:</strong>
              <ul style={{ margin: '5px 0 0 20px' }}>
                {Object.entries(errors).map(([field, error]) => (
                  <li key={field}>{error}</li>
                ))}
              </ul>
            </div>
          )}
          
          <button
            type="submit"
            disabled={isSubmitting}
            style={{
              backgroundColor: isSubmitting ? '#6c757d' : '#007bff',
              color: 'white',
              padding: '12px 30px',
              border: 'none',
              borderRadius: '4px',
              fontSize: '16px',
              cursor: isSubmitting ? 'not-allowed' : 'pointer',
              width: '100%'
            }}
          >
            {isSubmitting ? 'Creating Account...' : 'Create Account'}
          </button>
        </form>
      </div>
    </div>
  );
};

export default FormValidationWithoutAssociation;

// scenarios/advanced/web/angular/n9.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-form-validation-without-association',
  template: `
    <div class="main-container">
      <div class="main-content">
        <h1>User Registration</h1>
        <p>Create your account by filling out the form below.</p>
        
        <form (ngSubmit)="handleSubmit($event)" class="registration-form">
          <div class="form-group">
            <label for="username">Username:</label>
            <input
              type="text"
              id="username"
              [(ngModel)]="formData.username"
              (input)="clearError('username')"
              [class.error]="errors['username']"
              name="username"
            />
          </div>
          
          <div class="form-group">
            <label for="email">Email:</label>
            <input
              type="email"
              id="email"
              [(ngModel)]="formData.email"
              (input)="clearError('email')"
              [class.error]="errors['email']"
              name="email"
            />
          </div>
          
          <div class="form-group">
            <label for="password">Password:</label>
            <input
              type="password"
              id="password"
              [(ngModel)]="formData.password"
              (input)="clearError('password')"
              [class.error]="errors['password']"
              name="password"
            />
          </div>
          
          <div class="form-group">
            <label for="confirmPassword">Confirm Password:</label>
            <input
              type="password"
              id="confirmPassword"
              [(ngModel)]="formData.confirmPassword"
              (input)="clearError('confirmPassword')"
              [class.error]="errors['confirmPassword']"
              name="confirmPassword"
            />
          </div>
          
          <!-- Error Messages - Not properly associated with fields -->
          <div *ngIf="Object.keys(errors).length > 0" class="error-summary">
            <strong>Please fix the following errors:</strong>
            <ul>
              <li *ngFor="let error of getErrorEntries()">{{ error.value }}</li>
            </ul>
          </div>
          
          <button type="submit" [disabled]="isSubmitting" class="submit-button">
            {{ isSubmitting ? 'Creating Account...' : 'Create Account' }}
          </button>
        </form>
      </div>
    </div>
  `,
  styles: [`
    .main-container {
      font-family: Arial, sans-serif;
      max-width: 600px;
      margin: 50px auto;
      padding: 20px;
      background-color: #f5f5f5;
    }

    .main-content {
      background: white;
      padding: 30px;
      border-radius: 8px;
      box-shadow: 0 2px 10px rgba(0,0,0,0.1);
    }

    .registration-form {
      margin-top: 20px;
    }

    .form-group {
      margin-bottom: 20px;
    }

    .form-group label {
      display: block;
      margin-bottom: 5px;
      font-weight: bold;
      color: #333;
    }

    .form-group input {
      width: 100%;
      padding: 12px;
      border: 2px solid #ddd;
      border-radius: 4px;
      font-size: 16px;
      box-sizing: border-box;
    }

    .form-group input:focus {
      border-color: #007bff;
      outline: none;
    }

    .form-group input.error {
      border-color: #dc3545;
    }

    .error-summary {
      color: #dc3545;
      font-size: 14px;
      margin-bottom: 20px;
      padding: 10px;
      background-color: #f8d7da;
      border: 1px solid #f5c6cb;
      border-radius: 4px;
    }

    .error-summary ul {
      margin: 5px 0 0 20px;
    }

    .submit-button {
      background-color: #007bff;
      color: white;
      padding: 12px 30px;
      border: none;
      border-radius: 4px;
      font-size: 16px;
      cursor: pointer;
      width: 100%;
    }

    .submit-button:hover:not(:disabled) {
      background-color: #0056b3;
    }

    .submit-button:disabled {
      background-color: #6c757d;
      cursor: not-allowed;
    }
  `]
})
export class FormValidationWithoutAssociationComponent {
  formData = {
    username: '',
    password: '',
    email: '',
    confirmPassword: ''
  };
  
  errors: { [key: string]: string } = {};
  isSubmitting = false;

  clearError(field: string) {
    if (this.errors[field]) {
      delete this.errors[field];
    }
  }

  getErrorEntries() {
    return Object.entries(this.errors).map(([key, value]) => ({ key, value }));
  }

  validateForm() {
    const newErrors: { [key: string]: string } = {};

    if (!this.formData.username.trim()) {
      newErrors['username'] = 'Username is required';
    } else if (this.formData.username.length < 3) {
      newErrors['username'] = 'Username must be at least 3 characters';
    }

    if (!this.formData.email.trim()) {
      newErrors['email'] = 'Email is required';
    } else if (!/\S+@\S+\.\S+/.test(this.formData.email)) {
      newErrors['email'] = 'Please enter a valid email address';
    }

    if (!this.formData.password) {
      newErrors['password'] = 'Password is required';
    } else if (this.formData.password.length < 8) {
      newErrors['password'] = 'Password must be at least 8 characters';
    }

    if (!this.formData.confirmPassword) {
      newErrors['confirmPassword'] = 'Please confirm your password';
    } else if (this.formData.password !== this.formData.confirmPassword) {
      newErrors['confirmPassword'] = 'Passwords do not match';
    }

    return newErrors;
  }

  async handleSubmit(event: Event) {
    event.preventDefault();
    this.isSubmitting = true;

    const validationErrors = this.validateForm();
    
    if (Object.keys(validationErrors).length > 0) {
      this.errors = validationErrors;
      this.isSubmitting = false;
      return;
    }

    // Simulate API call
    try {
      await new Promise(resolve => setTimeout(resolve, 1000));
      alert('Registration successful!');
      this.formData = { username: '', password: '', email: '', confirmPassword: '' };
      this.errors = {};
    } catch (error) {
      alert('Registration failed. Please try again.');
    } finally {
      this.isSubmitting = false;
    }
  }
}
