// scenarios/advanced/web/svelte/MediaPlayerFullInterface.svelte
<script>
  import { onMount, onDestroy } from 'svelte';
  
  let isPlaying = false;
  let currentTime = 0;
  let duration = 0;
  let volume = 0.7;
  let isMuted = false;
  let playbackRate = 1.0;
  let isFullscreen = false;
  let showCaptions = false;
  let showQualityMenu = false;
  let showPlaybackSpeedMenu = false;
  let showVolumeSlider = false;
  let showSettings = false;
  let isLoading = false;
  let buffering = false;

  let videoElement;
  let progressBar;
  let volumeSlider;

  const qualityOptions = [
    { label: 'Auto', value: 'auto' },
    { label: '1080p', value: '1080p' },
    { label: '720p', value: '720p' },
    { label: '480p', value: '480p' },
    { label: '360p', value: '360p' }
  ];

  const speedOptions = [
    { label: '0.5x', value: 0.5 },
    { label: '0.75x', value: 0.75 },
    { label: '1x', value: 1.0 },
    { label: '1.25x', value: 1.25 },
    { label: '1.5x', value: 1.5 },
    { label: '2x', value: 2.0 }
  ];

  const captionOptions = [
    { label: 'Off', value: 'off' },
    { label: 'English', value: 'en' },
    { label: 'Spanish', value: 'es' },
    { label: 'French', value: 'fr' },
    { label: 'German', value: 'de' }
  ];

  onMount(() => {
    if (videoElement) {
      videoElement.addEventListener('loadedmetadata', handleLoadedMetadata);
      videoElement.addEventListener('timeupdate', handleTimeUpdate);
      videoElement.addEventListener('ended', handleEnded);
      videoElement.addEventListener('waiting', handleWaiting);
      videoElement.addEventListener('canplay', handleCanPlay);
    }
  });

  onDestroy(() => {
    if (videoElement) {
      videoElement.removeEventListener('loadedmetadata', handleLoadedMetadata);
      videoElement.removeEventListener('timeupdate', handleTimeUpdate);
      videoElement.removeEventListener('ended', handleEnded);
      videoElement.removeEventListener('waiting', handleWaiting);
      videoElement.removeEventListener('canplay', handleCanPlay);
    }
  });

  function handleLoadedMetadata() {
    duration = videoElement.duration;
  }

  function handleTimeUpdate() {
    currentTime = videoElement.currentTime;
  }

  function handleEnded() {
    isPlaying = false;
  }

  function handleWaiting() {
    buffering = true;
  }

  function handleCanPlay() {
    buffering = false;
    isLoading = false;
  }

  function togglePlay() {
    if (videoElement) {
      if (isPlaying) {
        videoElement.pause();
      } else {
        videoElement.play();
      }
      isPlaying = !isPlaying;
    }
  }

  function handleSeek(event) {
    if (videoElement && progressBar) {
      const rect = progressBar.getBoundingClientRect();
      const clickX = event.clientX - rect.left;
      const newTime = (clickX / rect.width) * duration;
      videoElement.currentTime = newTime;
      currentTime = newTime;
    }
  }

  function handleVolumeChange(event) {
    if (videoElement && volumeSlider) {
      const newVolume = parseFloat(event.target.value);
      volume = newVolume;
      videoElement.volume = newVolume;
      isMuted = newVolume === 0;
    }
  }

  function toggleMute() {
    if (videoElement) {
      if (isMuted) {
        videoElement.volume = volume;
        isMuted = false;
      } else {
        videoElement.volume = 0;
        isMuted = true;
      }
    }
  }

  function handlePlaybackRateChange(rate) {
    if (videoElement) {
      playbackRate = rate;
      videoElement.playbackRate = rate;
    }
    showPlaybackSpeedMenu = false;
  }

  function handleQualityChange(quality) {
    console.log('Quality changed to:', quality);
    showQualityMenu = false;
  }

  function handleCaptionChange(caption) {
    console.log('Captions changed to:', caption);
    showCaptions = caption !== 'off';
    showSettings = false;
  }

  function toggleFullscreen() {
    if (!document.fullscreenElement) {
      document.documentElement.requestFullscreen();
      isFullscreen = true;
    } else {
      document.exitFullscreen();
      isFullscreen = false;
    }
  }

  function formatTime(seconds) {
    const mins = Math.floor(seconds / 60);
    const secs = Math.floor(seconds % 60);
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  }

  function getProgressPercentage() {
    return duration > 0 ? (currentTime / duration) * 100 : 0;
  }

  function getVolumePercentage() {
    return volume * 100;
  }

  function handleKeydown(event) {
    if (event.code === 'Space') {
      event.preventDefault();
      togglePlay();
    } else if (event.code === 'KeyM') {
      toggleMute();
    } else if (event.code === 'KeyF') {
      toggleFullscreen();
    } else if (event.code === 'ArrowLeft') {
      if (videoElement) {
        videoElement.currentTime = Math.max(0, currentTime - 10);
      }
    } else if (event.code === 'ArrowRight') {
      if (videoElement) {
        videoElement.currentTime = Math.min(duration, currentTime + 10);
      }
    }
  }
</script>

<svelte:window on:keydown={handleKeydown} />

<div class="media-player" class:fullscreen={isFullscreen}>
  <div class="video-container">
    <video
      bind:this={videoElement}
      class="video-element"
      poster="https://via.placeholder.com/800x450/333/fff?text=Video+Thumbnail"
      preload="metadata"
    >
      <source src="https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_1mb.mp4" type="video/mp4">
      Your browser does not support the video tag.
    </video>

    {#if isLoading || buffering}
      <div class="loading-overlay">
        <div class="loading-spinner"></div>
        <span class="loading-text">
          {isLoading ? 'Loading...' : 'Buffering...'}
        </span>
      </div>
    {/if}

    <div class="video-overlay">
      <div class="video-controls">
        <div class="progress-container">
          <div 
            class="progress-bar"
            bind:this={progressBar}
            on:click={handleSeek}
          >
            <div 
              class="progress-fill"
              style="width: {getProgressPercentage()}%"
            />
            <div 
              class="progress-handle"
              style="left: {getProgressPercentage()}%"
            />
          </div>
        </div>

        <div class="controls-row">
          <div class="left-controls">
            <button 
              on:click={togglePlay}
              class="control-btn play-btn"
            >
              {isPlaying ? '⏸️' : '▶️'}
            </button>
            
            <div class="time-display">
              <span class="current-time">{formatTime(currentTime)}</span>
              <span class="time-separator">/</span>
              <span class="duration">{formatTime(duration)}</span>
            </div>

            <div class="volume-control">
              <button 
                on:click={toggleMute}
                class="control-btn volume-btn"
              >
                {isMuted ? '🔇' : volume > 0.5 ? '🔊' : '🔉'}
              </button>
              
              <div 
                class="volume-slider-container"
                class:show={showVolumeSlider}
              >
                <input
                  type="range"
                  bind:this={volumeSlider}
                  min="0"
                  max="1"
                  step="0.01"
                  value={volume}
                  on:input={handleVolumeChange}
                  class="volume-slider"
                />
              </div>
            </div>
          </div>

          <div class="right-controls">
            <div class="playback-speed">
              <button 
                on:click={() => showPlaybackSpeedMenu = !showPlaybackSpeedMenu}
                class="control-btn speed-btn"
              >
                {playbackRate}x
              </button>
              
              {#if showPlaybackSpeedMenu}
                <div class="speed-menu">
                  {#each speedOptions as option}
                    <button
                      on:click={() => handlePlaybackRateChange(option.value)}
                      class="speed-option"
                      class:active={playbackRate === option.value}
                    >
                      {option.label}
                    </button>
                  {/each}
                </div>
              {/if}
            </div>

            <div class="quality-selector">
              <button 
                on:click={() => showQualityMenu = !showQualityMenu}
                class="control-btn quality-btn"
              >
                Quality
              </button>
              
              {#if showQualityMenu}
                <div class="quality-menu">
                  {#each qualityOptions as option}
                    <button
                      on:click={() => handleQualityChange(option.value)}
                      class="quality-option"
                    >
                      {option.label}
                    </button>
                  {/each}
                </div>
              {/if}
            </div>

            <button 
              on:click={() => showSettings = !showSettings}
              class="control-btn settings-btn"
            >
              ⚙️
            </button>

            <button 
              on:click={toggleFullscreen}
              class="control-btn fullscreen-btn"
            >
              {isFullscreen ? '⤢' : '⤡'}
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>

  {#if showSettings}
    <div class="settings-panel">
      <div class="settings-header">
        <h3>Player Settings</h3>
        <button 
          on:click={() => showSettings = false}
          class="close-btn"
        >
          ✕
        </button>
      </div>
      
      <div class="settings-content">
        <div class="setting-group">
          <label class="setting-label">Captions</label>
          <select 
            on:change={(e) => handleCaptionChange(e.target.value)}
            class="setting-select"
          >
            {#each captionOptions as option}
              <option value={option.value}>{option.label}</option>
            {/each}
          </select>
        </div>

        <div class="setting-group">
          <label class="setting-label">Quality</label>
          <select class="setting-select">
            {#each qualityOptions as option}
              <option value={option.value}>{option.label}</option>
            {/each}
          </select>
        </div>

        <div class="setting-group">
          <label class="setting-label">Playback Speed</label>
          <select 
            on:change={(e) => handlePlaybackRateChange(parseFloat(e.target.value))}
            class="setting-select"
          >
            {#each speedOptions as option}
              <option value={option.value}>{option.label}</option>
            {/each}
          </select>
        </div>

        <div class="setting-group">
          <label class="setting-label">Volume</label>
          <input
            type="range"
            min="0"
            max="1"
            step="0.01"
            bind:value={volume}
            on:input={handleVolumeChange}
            class="setting-slider"
          />
        </div>
      </div>
    </div>
  {/if}
</div>

<style>
  .media-player {
    max-width: 1000px;
    margin: 0 auto;
    background: #000;
    border-radius: 8px;
    overflow: hidden;
    position: relative;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  }

  .media-player.fullscreen {
    position: fixed;
    top: 0;
    left: 0;
    width: 100vw;
    height: 100vh;
    z-index: 9999;
    border-radius: 0;
  }

  .video-container {
    position: relative;
    width: 100%;
    height: 0;
    padding-bottom: 56.25%;
    background: #000;
  }

  .video-element {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    object-fit: contain;
  }

  .loading-overlay {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: rgba(0, 0, 0, 0.8);
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    z-index: 10;
  }

  .loading-spinner {
    width: 40px;
    height: 40px;
    border: 4px solid rgba(255, 255, 255, 0.3);
    border-top: 4px solid #4caf50;
    border-radius: 50%;
    animation: spin 1s linear infinite;
    margin-bottom: 15px;
  }

  @keyframes spin {
    0% { transform: rotate(0deg); }
    100% { transform: rotate(360deg); }
  }

  .loading-text {
    color: white;
    font-size: 14px;
    font-weight: 500;
  }

  .video-overlay {
    position: absolute;
    bottom: 0;
    left: 0;
    right: 0;
    background: linear-gradient(transparent, rgba(0, 0, 0, 0.8));
    padding: 20px;
    z-index: 5;
  }

  .video-controls {
    color: white;
  }

  .progress-container {
    margin-bottom: 15px;
  }

  .progress-bar {
    width: 100%;
    height: 6px;
    background: rgba(255, 255, 255, 0.3);
    border-radius: 3px;
    cursor: pointer;
    position: relative;
  }

  .progress-fill {
    height: 100%;
    background: #4caf50;
    border-radius: 3px;
    transition: width 0.1s ease;
  }

  .progress-handle {
    position: absolute;
    top: 50%;
    width: 12px;
    height: 12px;
    background: #4caf50;
    border-radius: 50%;
    transform: translate(-50%, -50%);
    opacity: 0;
    transition: opacity 0.3s ease;
  }

  .progress-bar:hover .progress-handle {
    opacity: 1;
  }

  .controls-row {
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  .left-controls,
  .right-controls {
    display: flex;
    align-items: center;
    gap: 15px;
  }

  .control-btn {
    background: none;
    border: none;
    color: white;
    cursor: pointer;
    font-size: 16px;
    padding: 8px;
    border-radius: 4px;
    transition: background-color 0.3s ease;
  }

  .control-btn:hover {
    background: rgba(255, 255, 255, 0.2);
  }

  .play-btn {
    font-size: 20px;
  }

  .time-display {
    display: flex;
    align-items: center;
    gap: 5px;
    font-size: 14px;
    font-weight: 500;
    min-width: 100px;
  }

  .time-separator {
    opacity: 0.7;
  }

  .volume-control {
    position: relative;
    display: flex;
    align-items: center;
    gap: 8px;
  }

  .volume-slider-container {
    position: absolute;
    left: 50%;
    bottom: 100%;
    transform: translateX(-50%);
    background: rgba(0, 0, 0, 0.8);
    padding: 10px;
    border-radius: 4px;
    opacity: 0;
    visibility: hidden;
    transition: all 0.3s ease;
  }

  .volume-slider-container.show {
    opacity: 1;
    visibility: visible;
  }

  .volume-slider {
    width: 80px;
    height: 4px;
    background: rgba(255, 255, 255, 0.3);
    border-radius: 2px;
    outline: none;
    cursor: pointer;
  }

  .volume-slider::-webkit-slider-thumb {
    appearance: none;
    width: 12px;
    height: 12px;
    background: #4caf50;
    border-radius: 50%;
    cursor: pointer;
  }

  .playback-speed,
  .quality-selector {
    position: relative;
  }

  .speed-btn,
  .quality-btn {
    font-size: 12px;
    padding: 6px 10px;
    background: rgba(255, 255, 255, 0.2);
    border-radius: 4px;
  }

  .speed-menu,
  .quality-menu {
    position: absolute;
    bottom: 100%;
    right: 0;
    background: rgba(0, 0, 0, 0.9);
    border-radius: 4px;
    padding: 5px 0;
    min-width: 80px;
    z-index: 10;
  }

  .speed-option,
  .quality-option {
    display: block;
    width: 100%;
    padding: 8px 12px;
    background: none;
    border: none;
    color: white;
    text-align: left;
    cursor: pointer;
    font-size: 12px;
    transition: background-color 0.3s ease;
  }

  .speed-option:hover,
  .quality-option:hover {
    background: rgba(255, 255, 255, 0.2);
  }

  .speed-option.active {
    background: #4caf50;
  }

  .settings-panel {
    position: absolute;
    top: 20px;
    right: 20px;
    background: rgba(0, 0, 0, 0.9);
    border-radius: 8px;
    padding: 20px;
    min-width: 250px;
    z-index: 20;
  }

  .settings-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 20px;
    padding-bottom: 10px;
    border-bottom: 1px solid rgba(255, 255, 255, 0.2);
  }

  .settings-header h3 {
    margin: 0;
    color: white;
    font-size: 16px;
  }

  .close-btn {
    background: none;
    border: none;
    color: white;
    cursor: pointer;
    font-size: 16px;
    padding: 4px;
  }

  .settings-content {
    display: flex;
    flex-direction: column;
    gap: 15px;
  }

  .setting-group {
    display: flex;
    flex-direction: column;
    gap: 5px;
  }

  .setting-label {
    color: white;
    font-size: 12px;
    font-weight: 500;
  }

  .setting-select {
    padding: 6px 8px;
    background: rgba(255, 255, 255, 0.1);
    border: 1px solid rgba(255, 255, 255, 0.3);
    border-radius: 4px;
    color: white;
    font-size: 12px;
  }

  .setting-select:focus {
    outline: none;
    border-color: #4caf50;
  }

  .setting-slider {
    width: 100%;
    height: 4px;
    background: rgba(255, 255, 255, 0.3);
    border-radius: 2px;
    outline: none;
    cursor: pointer;
  }

  .setting-slider::-webkit-slider-thumb {
    appearance: none;
    width: 12px;
    height: 12px;
    background: #4caf50;
    border-radius: 50%;
    cursor: pointer;
  }

  @media (max-width: 768px) {
    .media-player {
      margin: 10px;
    }
    
    .video-overlay {
      padding: 15px;
    }
    
    .controls-row {
      flex-direction: column;
      gap: 10px;
    }
    
    .left-controls,
    .right-controls {
      justify-content: center;
      flex-wrap: wrap;
    }
    
    .time-display {
      min-width: auto;
    }
    
    .settings-panel {
      position: fixed;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      width: 90%;
      max-width: 300px;
    }
  }

  @media (max-width: 480px) {
    .video-overlay {
      padding: 10px;
    }
    
    .control-btn {
      font-size: 14px;
      padding: 6px;
    }
    
    .time-display {
      font-size: 12px;
    }
    
    .speed-btn,
    .quality-btn {
      font-size: 10px;
      padding: 4px 6px;
    }
  }
</style>

// scenarios/advanced/web/vue/MediaPlayerFullInterface.vue
<template>
  <div :class="`media-player ${isFullscreen ? 'fullscreen' : ''}`">
    <div class="video-container">
      <video
        ref="videoRef"
        class="video-element"
        poster="https://via.placeholder.com/800x450/333/fff?text=Sample+Video"
        @mousemove="showControls = true"
        @mouseleave="showControls = false"
      >
        <source src="https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4" type="video/mp4" />
        <track kind="captions" srcLang="en" label="English" default />
        <track kind="captions" srcLang="es" label="Spanish" />
        <track kind="captions" srcLang="fr" label="French" />
        <track kind="captions" srcLang="de" label="German" />
      </video>

      <div v-if="isLoading" class="loading-overlay">
        <div class="loading-spinner"></div>
        <span>Loading...</span>
      </div>

      <div v-if="showControls" class="video-controls">
        <!-- Progress Bar -->
        <div class="progress-container" @click="handleSeek">
          <div class="progress-bar">
            <div 
              class="progress-fill" 
              :style="{ width: `${(currentTime / duration) * 100}%` }"
            ></div>
            <div 
              class="progress-handle" 
              :style="{ left: `${(currentTime / duration) * 100}%` }"
            ></div>
          </div>
        </div>

        <!-- Control Buttons -->
        <div class="controls-row">
          <div class="left-controls">
            <button 
              class="control-btn play-btn"
              @click="togglePlay"
            >
              {{ isPlaying ? '⏸️' : '▶️' }}
            </button>

            <div class="time-display">
              {{ formatTime(currentTime) }} / {{ formatTime(duration) }}
            </div>

            <button 
              class="control-btn volume-btn"
              @click="toggleMute"
            >
              {{ isMuted ? '🔇' : volume > 0.5 ? '🔊' : '🔉' }}
            </button>

            <div class="volume-slider">
              <input
                type="range"
                min="0"
                max="1"
                step="0.1"
                :value="isMuted ? 0 : volume"
                @input="handleVolumeChange"
                class="volume-range"
              />
            </div>
          </div>

          <div class="right-controls">
            <div class="playback-rate-menu">
              <button 
                class="control-btn"
                @click="showSettingsMenu = !showSettingsMenu"
              >
                {{ playbackRate }}x
              </button>
              <div v-if="showSettingsMenu" class="settings-dropdown">
                <div class="settings-section">
                  <div class="settings-label">Playback Speed</div>
                  <button
                    v-for="rate in playbackRates"
                    :key="rate"
                    :class="`settings-option ${playbackRate === rate ? 'active' : ''}`"
                    @click="changePlaybackRate(rate); showSettingsMenu = false"
                  >
                    {{ rate }}x
                  </button>
                </div>
              </div>
            </div>

            <div class="quality-menu">
              <button 
                class="control-btn"
                @click="showQualityMenu = !showQualityMenu"
              >
                {{ selectedQuality }}
              </button>
              <div v-if="showQualityMenu" class="quality-dropdown">
                <button
                  v-for="quality in qualityOptions"
                  :key="quality"
                  :class="`quality-option ${selectedQuality === quality ? 'active' : ''}`"
                  @click="handleQualityChange(quality)"
                >
                  {{ quality }}
                </button>
              </div>
            </div>

            <button 
              class="control-btn captions-btn"
              @click="showCaptions = !showCaptions"
            >
              📺
            </button>

            <button 
              class="control-btn fullscreen-btn"
              @click="toggleFullscreen"
            >
              {{ isFullscreen ? '⤢' : '⤡' }}
            </button>
          </div>
        </div>
      </div>

      <!-- Captions Menu -->
      <div v-if="showCaptions" class="captions-menu">
        <div class="captions-header">Captions</div>
        <button
          v-for="caption in captionOptions"
          :key="caption"
          :class="`caption-option ${selectedCaption === caption ? 'active' : ''}`"
          @click="handleCaptionChange(caption)"
        >
          {{ caption }}
        </button>
      </div>
    </div>

    <!-- Video Info -->
    <div class="video-info">
      <h3>Big Buck Bunny</h3>
      <p>A short animated film by the Blender Institute</p>
      <div class="video-meta">
        <span>Duration: {{ formatTime(duration) }}</span>
        <span>Quality: {{ selectedQuality }}</span>
        <span>Captions: {{ selectedCaption }}</span>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'MediaPlayerFullInterface',
  data() {
    return {
      isPlaying: false,
      currentTime: 0,
      duration: 0,
      volume: 1,
      isMuted: false,
      playbackRate: 1,
      isFullscreen: false,
      showCaptions: false,
      showQualityMenu: false,
      showSettingsMenu: false,
      selectedQuality: '1080p',
      selectedCaption: 'English',
      showControls: true,
      isLoading: false,
      qualityOptions: ['360p', '480p', '720p', '1080p', '4K'],
      captionOptions: ['English', 'Spanish', 'French', 'German', 'Off'],
      playbackRates: [0.5, 0.75, 1, 1.25, 1.5, 2]
    }
  },
  mounted() {
    this.setupVideoListeners();
  },
  beforeUnmount() {
    this.removeVideoListeners();
  },
  methods: {
    setupVideoListeners() {
      const video = this.$refs.videoRef;
      if (!video) return;

      video.addEventListener('timeupdate', this.handleTimeUpdate);
      video.addEventListener('durationchange', this.handleDurationChange);
      video.addEventListener('loadstart', this.handleLoadStart);
      video.addEventListener('canplay', this.handleCanPlay);
      video.addEventListener('play', this.handlePlay);
      video.addEventListener('pause', this.handlePause);
    },
    removeVideoListeners() {
      const video = this.$refs.videoRef;
      if (!video) return;

      video.removeEventListener('timeupdate', this.handleTimeUpdate);
      video.removeEventListener('durationchange', this.handleDurationChange);
      video.removeEventListener('loadstart', this.handleLoadStart);
      video.removeEventListener('canplay', this.handleCanPlay);
      video.removeEventListener('play', this.handlePlay);
      video.removeEventListener('pause', this.handlePause);
    },
    handleTimeUpdate() {
      this.currentTime = this.$refs.videoRef.currentTime;
    },
    handleDurationChange() {
      this.duration = this.$refs.videoRef.duration;
    },
    handleLoadStart() {
      this.isLoading = true;
    },
    handleCanPlay() {
      this.isLoading = false;
    },
    handlePlay() {
      this.isPlaying = true;
    },
    handlePause() {
      this.isPlaying = false;
    },
    togglePlay() {
      const video = this.$refs.videoRef;
      if (!video) return;

      if (this.isPlaying) {
        video.pause();
      } else {
        video.play();
      }
    },
    handleSeek(event) {
      const video = this.$refs.videoRef;
      if (!video) return;

      const rect = event.currentTarget.getBoundingClientRect();
      const clickX = event.clientX - rect.left;
      const newTime = (clickX / rect.width) * this.duration;
      video.currentTime = newTime;
      this.currentTime = newTime;
    },
    handleVolumeChange(event) {
      const video = this.$refs.videoRef;
      if (!video) return;

      const newVolume = parseFloat(event.target.value);
      video.volume = newVolume;
      this.volume = newVolume;
      this.isMuted = newVolume === 0;
    },
    toggleMute() {
      const video = this.$refs.videoRef;
      if (!video) return;

      if (this.isMuted) {
        video.volume = this.volume;
        this.isMuted = false;
      } else {
        video.volume = 0;
        this.isMuted = true;
      }
    },
    changePlaybackRate(rate) {
      const video = this.$refs.videoRef;
      if (!video) return;

      video.playbackRate = rate;
      this.playbackRate = rate;
    },
    toggleFullscreen() {
      if (!document.fullscreenElement) {
        this.$refs.videoRef?.requestFullscreen();
        this.isFullscreen = true;
      } else {
        document.exitFullscreen();
        this.isFullscreen = false;
      }
    },
    formatTime(time) {
      const minutes = Math.floor(time / 60);
      const seconds = Math.floor(time % 60);
      return `${minutes}:${seconds.toString().padStart(2, '0')}`;
    },
    handleQualityChange(quality) {
      this.selectedQuality = quality;
      this.showQualityMenu = false;
      console.log(`Quality changed to ${quality}`);
    },
    handleCaptionChange(caption) {
      this.selectedCaption = caption;
      this.showCaptions = caption !== 'Off';
      console.log(`Captions changed to ${caption}`);
    }
  }
}
</script>

<style scoped>
.media-player {
  max-width: 800px;
  margin: 0 auto;
  padding: 20px;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}

.media-player.fullscreen {
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  z-index: 1000;
  background: black;
  padding: 0;
}

.video-container {
  position: relative;
  background: black;
  border-radius: 8px;
  overflow: hidden;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.3);
}

.video-element {
  width: 100%;
  height: auto;
  display: block;
  background: #000;
}

.loading-overlay {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.7);
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  color: white;
  z-index: 10;
}

.loading-spinner {
  width: 40px;
  height: 40px;
  border: 4px solid rgba(255, 255, 255, 0.3);
  border-top: 4px solid white;
  border-radius: 50%;
  animation: spin 1s linear infinite;
  margin-bottom: 10px;
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

.video-controls {
  position: absolute;
  bottom: 0;
  left: 0;
  right: 0;
  background: linear-gradient(transparent, rgba(0, 0, 0, 0.8));
  padding: 20px 15px 15px;
  color: white;
  z-index: 5;
}

.progress-container {
  margin-bottom: 15px;
  cursor: pointer;
}

.progress-bar {
  position: relative;
  height: 6px;
  background: rgba(255, 255, 255, 0.3);
  border-radius: 3px;
  overflow: hidden;
}

.progress-fill {
  height: 100%;
  background: #4caf50;
  border-radius: 3px;
  transition: width 0.1s ease;
}

.progress-handle {
  position: absolute;
  top: 50%;
  width: 12px;
  height: 12px;
  background: #4caf50;
  border-radius: 50%;
  transform: translate(-50%, -50%);
  opacity: 0;
  transition: opacity 0.3s ease;
}

.progress-container:hover .progress-handle {
  opacity: 1;
}

.controls-row {
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 15px;
}

.left-controls,
.right-controls {
  display: flex;
  align-items: center;
  gap: 10px;
}

.control-btn {
  background: none;
  border: none;
  color: white;
  cursor: pointer;
  padding: 8px;
  border-radius: 4px;
  font-size: 16px;
  transition: background-color 0.3s ease;
  min-width: 40px;
  height: 40px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.control-btn:hover {
  background: rgba(255, 255, 255, 0.2);
}

.play-btn {
  font-size: 20px;
  background: rgba(255, 255, 255, 0.1);
}

.time-display {
  font-size: 14px;
  font-weight: 500;
  min-width: 100px;
  text-align: center;
}

.volume-slider {
  width: 80px;
}

.volume-range {
  width: 100%;
  height: 4px;
  background: rgba(255, 255, 255, 0.3);
  border-radius: 2px;
  outline: none;
  cursor: pointer;
}

.volume-range::-webkit-slider-thumb {
  appearance: none;
  width: 12px;
  height: 12px;
  background: #4caf50;
  border-radius: 50%;
  cursor: pointer;
}

.volume-range::-moz-range-thumb {
  width: 12px;
  height: 12px;
  background: #4caf50;
  border-radius: 50%;
  cursor: pointer;
  border: none;
}

.playback-rate-menu,
.quality-menu {
  position: relative;
}

.settings-dropdown,
.quality-dropdown {
  position: absolute;
  bottom: 100%;
  right: 0;
  background: rgba(0, 0, 0, 0.9);
  border-radius: 6px;
  padding: 8px 0;
  min-width: 120px;
  z-index: 20;
  margin-bottom: 5px;
}

.settings-section {
  padding: 0;
}

.settings-label {
  padding: 8px 15px;
  font-size: 12px;
  color: #ccc;
  text-transform: uppercase;
  letter-spacing: 0.5px;
  border-bottom: 1px solid rgba(255, 255, 255, 0.1);
  margin-bottom: 5px;
}

.settings-option,
.quality-option {
  display: block;
  width: 100%;
  padding: 8px 15px;
  background: none;
  border: none;
  color: white;
  text-align: left;
  cursor: pointer;
  font-size: 14px;
  transition: background-color 0.3s ease;
}

.settings-option:hover,
.quality-option:hover {
  background: rgba(255, 255, 255, 0.1);
}

.settings-option.active,
.quality-option.active {
  background: #4caf50;
  color: white;
}

.captions-menu {
  position: absolute;
  bottom: 100%;
  right: 60px;
  background: rgba(0, 0, 0, 0.9);
  border-radius: 6px;
  padding: 8px 0;
  min-width: 120px;
  z-index: 20;
  margin-bottom: 5px;
}

.captions-header {
  padding: 8px 15px;
  font-size: 12px;
  color: #ccc;
  text-transform: uppercase;
  letter-spacing: 0.5px;
  border-bottom: 1px solid rgba(255, 255, 255, 0.1);
  margin-bottom: 5px;
}

.caption-option {
  display: block;
  width: 100%;
  padding: 8px 15px;
  background: none;
  border: none;
  color: white;
  text-align: left;
  cursor: pointer;
  font-size: 14px;
  transition: background-color 0.3s ease;
}

.caption-option:hover {
  background: rgba(255, 255, 255, 0.1);
}

.caption-option.active {
  background: #4caf50;
  color: white;
}

.video-info {
  margin-top: 20px;
  padding: 20px;
  background: #f8f9fa;
  border-radius: 8px;
}

.video-info h3 {
  margin: 0 0 10px 0;
  color: #333;
  font-size: 20px;
}

.video-info p {
  margin: 0 0 15px 0;
  color: #666;
  font-size: 14px;
  line-height: 1.5;
}

.video-meta {
  display: flex;
  gap: 20px;
  font-size: 12px;
  color: #888;
}

.video-meta span {
  padding: 4px 8px;
  background: #e9ecef;
  border-radius: 4px;
}

@media (max-width: 768px) {
  .media-player {
    padding: 15px;
  }
  
  .controls-row {
    flex-wrap: wrap;
    gap: 10px;
  }
  
  .left-controls,
  .right-controls {
    flex-wrap: wrap;
    gap: 8px;
  }
  
  .time-display {
    min-width: 80px;
    font-size: 12px;
  }
  
  .volume-slider {
    width: 60px;
  }
  
  .control-btn {
    min-width: 36px;
    height: 36px;
    font-size: 14px;
  }
  
  .play-btn {
    font-size: 18px;
  }
  
  .video-meta {
    flex-direction: column;
    gap: 8px;
  }
}

@media (max-width: 480px) {
  .video-controls {
    padding: 15px 10px 10px;
  }
  
  .controls-row {
    flex-direction: column;
    align-items: stretch;
    gap: 10px;
  }
  
  .left-controls,
  .right-controls {
    justify-content: center;
  }
  
  .settings-dropdown,
  .quality-dropdown,
  .captions-menu {
    right: auto;
    left: 50%;
    transform: translateX(-50%);
  }
}
</style>
