// scenarios/advanced/web/react/n10.jsx
import React, { useState, useRef, useEffect } from 'react';
import './InteractiveMap.css';

const InteractiveMap = () => {
  const mapRef = useRef(null);
  const [mapCenter, setMapCenter] = useState({ lat: 40.7128, lng: -74.0060 }); // New York City
  const [zoom, setZoom] = useState(10);
  const [markers, setMarkers] = useState([
    {
      id: 1,
      lat: 40.7589,
      lng: -73.9851,
      title: 'Times Square',
      type: 'attraction',
      description: 'Famous commercial intersection and tourist destination'
    },
    {
      id: 2,
      lat: 40.7829,
      lng: -73.9654,
      title: 'Central Park',
      type: 'park',
      description: 'Large public park in Manhattan'
    },
    {
      id: 3,
      lat: 40.6892,
      lng: -74.0445,
      title: 'Statue of Liberty',
      type: 'monument',
      description: 'Iconic symbol of freedom and democracy'
    },
    {
      id: 4,
      lat: 40.7505,
      lng: -73.9934,
      title: 'Empire State Building',
      type: 'building',
      description: 'Famous Art Deco skyscraper'
    },
    {
      id: 5,
      lat: 40.7614,
      lng: -73.9776,
      title: 'Broadway Theater',
      type: 'entertainment',
      description: 'Historic theater district'
    }
  ]);

  const [selectedMarker, setSelectedMarker] = useState(null);
  const [showInfoWindow, setShowInfoWindow] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [filteredMarkers, setFilteredMarkers] = useState(markers);
  const [showLayers, setShowLayers] = useState(false);
  const [activeLayers, setActiveLayers] = useState({
    attractions: true,
    parks: true,
    monuments: true,
    buildings: true,
    entertainment: true,
    traffic: false,
    weather: false
  });
  const [showSearchOverlay, setShowSearchOverlay] = useState(false);
  const [searchResults, setSearchResults] = useState([]);
  const [isSearching, setIsSearching] = useState(false);
  const [mapStyle, setMapStyle] = useState('default'); // default, satellite, terrain

  const markerTypes = {
    attraction: { color: '#4caf50', icon: '🎯' },
    park: { color: '#8bc34a', icon: '🌳' },
    monument: { color: '#ff9800', icon: '🏛️' },
    building: { color: '#2196f3', icon: '🏢' },
    entertainment: { color: '#9c27b0', icon: '🎭' }
  };

  const mapStyles = [
    { id: 'default', name: 'Default', preview: '🗺️' },
    { id: 'satellite', name: 'Satellite', preview: '🛰️' },
    { id: 'terrain', name: 'Terrain', preview: '🏔️' }
  ];

  useEffect(() => {
    filterMarkers();
  }, [activeLayers, markers]);

  const filterMarkers = () => {
    const filtered = markers.filter(marker => {
      const layerKey = marker.type === 'attraction' ? 'attractions' : 
                      marker.type === 'park' ? 'parks' :
                      marker.type === 'monument' ? 'monuments' :
                      marker.type === 'building' ? 'buildings' :
                      marker.type === 'entertainment' ? 'entertainment' : marker.type;
      return activeLayers[layerKey];
    });
    setFilteredMarkers(filtered);
  };

  const handleMarkerClick = (marker) => {
    setSelectedMarker(marker);
    setShowInfoWindow(true);
    setMapCenter({ lat: marker.lat, lng: marker.lng });
    setZoom(15);
  };

  const handleMapClick = (event) => {
    if (event.target === mapRef.current) {
      setShowInfoWindow(false);
      setSelectedMarker(null);
    }
  };

  const handleZoomIn = () => {
    setZoom(prev => Math.min(prev + 1, 20));
  };

  const handleZoomOut = () => {
    setZoom(prev => Math.max(prev - 1, 1));
  };

  const handleLayerToggle = (layer) => {
    setActiveLayers(prev => ({
      ...prev,
      [layer]: !prev[layer]
    }));
  };

  const handleSearch = async () => {
    if (!searchQuery.trim()) return;

    setIsSearching(true);
    setShowSearchOverlay(true);

    // Simulate API search
    setTimeout(() => {
      const results = markers.filter(marker =>
        marker.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
        marker.description.toLowerCase().includes(searchQuery.toLowerCase())
      );
      setSearchResults(results);
      setIsSearching(false);
    }, 1000);
  };

  const handleSearchResultClick = (result) => {
    setMapCenter({ lat: result.lat, lng: result.lng });
    setZoom(15);
    setShowSearchOverlay(false);
    setSearchQuery('');
    setSearchResults([]);
  };

  const addCustomMarker = (event) => {
    const rect = mapRef.current.getBoundingClientRect();
    const x = event.clientX - rect.left;
    const y = event.clientY - rect.top;
    
    // Convert screen coordinates to lat/lng (simplified)
    const lat = mapCenter.lat + (rect.height / 2 - y) * (0.01 / zoom);
    const lng = mapCenter.lng + (x - rect.width / 2) * (0.01 / zoom);
    
    const newMarker = {
      id: Date.now(),
      lat,
      lng,
      title: 'Custom Location',
      type: 'attraction',
      description: 'User-added marker'
    };
    
    setMarkers(prev => [...prev, newMarker]);
  };

  const removeMarker = (markerId) => {
    setMarkers(prev => prev.filter(marker => marker.id !== markerId));
    if (selectedMarker && selectedMarker.id === markerId) {
      setShowInfoWindow(false);
      setSelectedMarker(null);
    }
  };

  const getMarkerPosition = (marker) => {
    // Convert lat/lng to screen coordinates (simplified)
    const rect = mapRef.current?.getBoundingClientRect();
    if (!rect) return { x: 0, y: 0 };
    
    const x = rect.width / 2 + (marker.lng - mapCenter.lng) * (zoom * 10);
    const y = rect.height / 2 - (marker.lat - mapCenter.lat) * (zoom * 10);
    
    return { x, y };
  };

  return (
    <div className="interactive-map">
      <div className="map-header">
        <h1>Interactive Map</h1>
        <div className="map-controls">
          <div className="search-container">
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search locations..."
              className="search-input"
            />
            <button onClick={handleSearch} className="search-btn">
              🔍
            </button>
          </div>
          
          <div className="map-style-selector">
            <select
              value={mapStyle}
              onChange={(e) => setMapStyle(e.target.value)}
            >
              {mapStyles.map(style => (
                <option key={style.id} value={style.id}>
                  {style.preview} {style.name}
                </option>
              ))}
            </select>
          </div>
        </div>
      </div>

      <div className="map-container">
        <div className="map-sidebar">
          <div className="sidebar-section">
            <h3>Map Layers</h3>
            <button 
              onClick={() => setShowLayers(!showLayers)}
              className="layers-toggle"
            >
              {showLayers ? 'Hide' : 'Show'} Layers
            </button>
            
            {showLayers && (
              <div className="layers-panel">
                {Object.entries(activeLayers).map(([layer, active]) => (
                  <label key={layer} className="layer-item">
                    <input
                      type="checkbox"
                      checked={active}
                      onChange={() => handleLayerToggle(layer)}
                    />
                    <span className="layer-name">
                      {layer.charAt(0).toUpperCase() + layer.slice(1)}
                    </span>
                  </label>
                ))}
              </div>
            )}
          </div>

          <div className="sidebar-section">
            <h3>Quick Actions</h3>
            <div className="quick-actions">
              <button onClick={() => setMapCenter({ lat: 40.7128, lng: -74.0060 })}>
                Reset View
              </button>
              <button onClick={() => setZoom(10)}>
                Default Zoom
              </button>
              <button onClick={() => setShowInfoWindow(false)}>
                Clear Selection
              </button>
            </div>
          </div>

          <div className="sidebar-section">
            <h3>Map Info</h3>
            <div className="map-info">
              <div className="info-item">
                <span>Center:</span>
                <span>{mapCenter.lat.toFixed(4)}, {mapCenter.lng.toFixed(4)}</span>
              </div>
              <div className="info-item">
                <span>Zoom:</span>
                <span>{zoom}</span>
              </div>
              <div className="info-item">
                <span>Markers:</span>
                <span>{filteredMarkers.length}</span>
              </div>
            </div>
          </div>
        </div>

        <div className="map-main">
          <div 
            ref={mapRef}
            className="map-display"
            onClick={handleMapClick}
            onDoubleClick={addCustomMarker}
          >
            {/* Map background simulation */}
            <div className="map-background" style={{ 
              backgroundImage: `url('https://via.placeholder.com/800x600/4caf50/fff?text=Map+View')`,
              transform: `scale(${zoom / 10})`
            }}>
              {/* Render markers */}
              {filteredMarkers.map(marker => {
                const position = getMarkerPosition(marker);
                const markerType = markerTypes[marker.type];
                
                return (
                  <div
                    key={marker.id}
                    className="map-marker"
                    style={{
                      left: `${position.x}px`,
                      top: `${position.y}px`,
                      backgroundColor: markerType.color
                    }}
                    onClick={(e) => {
                      e.stopPropagation();
                      handleMarkerClick(marker);
                    }}
                    title={marker.title}
                  >
                    <span className="marker-icon">{markerType.icon}</span>
                  </div>
                );
              })}
            </div>

            {/* Zoom controls */}
            <div className="zoom-controls">
              <button onClick={handleZoomIn} className="zoom-btn">
                +
              </button>
              <button onClick={handleZoomOut} className="zoom-btn">
                −
              </button>
            </div>

            {/* Info window */}
            {showInfoWindow && selectedMarker && (
              <div className="info-window">
                <div className="info-header">
                  <h4>{selectedMarker.title}</h4>
                  <button 
                    onClick={() => setShowInfoWindow(false)}
                    className="close-btn"
                  >
                    ✕
                  </button>
                </div>
                <div className="info-content">
                  <div className="info-type">
                    Type: {selectedMarker.type}
                  </div>
                  <div className="info-description">
                    {selectedMarker.description}
                  </div>
                  <div className="info-coordinates">
                    {selectedMarker.lat.toFixed(4)}, {selectedMarker.lng.toFixed(4)}
                  </div>
                </div>
                <div className="info-actions">
                  <button onClick={() => removeMarker(selectedMarker.id)}>
                    Remove
                  </button>
                  <button onClick={() => setMapCenter({ lat: selectedMarker.lat, lng: selectedMarker.lng })}>
                    Center
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Search overlay */}
      {showSearchOverlay && (
        <div className="search-overlay">
          <div className="search-results">
            <div className="search-header">
              <h3>Search Results</h3>
              <button 
                onClick={() => setShowSearchOverlay(false)}
                className="close-btn"
              >
                ✕
              </button>
            </div>
            
            {isSearching ? (
              <div className="search-loading">
                <div className="loading-spinner"></div>
                <span>Searching...</span>
              </div>
            ) : (
              <div className="search-results-list">
                {searchResults.length > 0 ? (
                  searchResults.map(result => (
                    <div
                      key={result.id}
                      className="search-result-item"
                      onClick={() => handleSearchResultClick(result)}
                    >
                      <div className="result-title">{result.title}</div>
                      <div className="result-description">{result.description}</div>
                      <div className="result-type">{result.type}</div>
                    </div>
                  ))
                ) : (
                  <div className="no-results">
                    No results found for "{searchQuery}"
                  </div>
                )}
              </div>
            )}
          </div>
        </div>
      )}

      <div className="map-footer">
        <div className="map-instructions">
          <span>Click markers to view details • Double-click map to add marker • Use zoom controls to navigate</span>
        </div>
        <div className="map-legend">
          {Object.entries(markerTypes).map(([type, config]) => (
            <div key={type} className="legend-item">
              <div 
                className="legend-color" 
                style={{ backgroundColor: config.color }}
              >
                {config.icon}
              </div>
              <span>{type}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default InteractiveMap;

// scenarios/advanced/web/vue/n10.vue
<template>
  <div class="interactive-map">
    <div class="map-header">
      <h1>Interactive Map</h1>
      <div class="map-controls">
        <div class="search-container">
          <input
            type="text"
            v-model="searchQuery"
            placeholder="Search locations..."
            class="search-input"
          />
          <button @click="handleSearch" class="search-btn">🔍</button>
        </div>
        
        <div class="map-style-selector">
          <select v-model="mapStyle">
            <option v-for="style in mapStyles" :key="style.id" :value="style.id">
              {{ style.preview }} {{ style.name }}
            </option>
          </select>
        </div>
      </div>
    </div>

    <div class="map-container">
      <div class="map-sidebar">
        <div class="sidebar-section">
          <h3>Map Layers</h3>
          <button @click="showLayers = !showLayers" class="layers-toggle">
            {{ showLayers ? 'Hide' : 'Show' }} Layers
          </button>
          
          <div v-if="showLayers" class="layers-panel">
            <label v-for="(active, layer) in activeLayers" :key="layer" class="layer-item">
              <input
                type="checkbox"
                :checked="active"
                @change="handleLayerToggle(layer)"
              />
              <span class="layer-name">
                {{ layer.charAt(0).toUpperCase() + layer.slice(1) }}
              </span>
            </label>
          </div>
        </div>

        <div class="sidebar-section">
          <h3>Quick Actions</h3>
          <div class="quick-actions">
            <button @click="resetView">Reset View</button>
            <button @click="setDefaultZoom">Default Zoom</button>
            <button @click="clearSelection">Clear Selection</button>
          </div>
        </div>

        <div class="sidebar-section">
          <h3>Map Info</h3>
          <div class="map-info">
            <div class="info-item">
              <span>Center:</span>
              <span>{{ mapCenter.lat.toFixed(4) }}, {{ mapCenter.lng.toFixed(4) }}</span>
            </div>
            <div class="info-item">
              <span>Zoom:</span>
              <span>{{ zoom }}</span>
            </div>
            <div class="info-item">
              <span>Markers:</span>
              <span>{{ filteredMarkers.length }}</span>
            </div>
          </div>
        </div>
      </div>

      <div class="map-main">
        <div 
          ref="mapRef"
          class="map-display"
          @click="handleMapClick"
          @dblclick="addCustomMarker"
        >
          <!-- Map background simulation -->
          <div 
            class="map-background" 
            :style="{ 
              backgroundImage: `url('https://via.placeholder.com/800x600/4caf50/fff?text=Map+View')`,
              transform: `scale(${zoom / 10})`
            }"
          >
            <!-- Render markers -->
            <div
              v-for="marker in filteredMarkers"
              :key="marker.id"
              class="map-marker"
              :style="{
                left: getMarkerPosition(marker).x + 'px',
                top: getMarkerPosition(marker).y + 'px',
                backgroundColor: markerTypes[marker.type].color
              }"
              @click.stop="handleMarkerClick(marker)"
              :title="marker.title"
            >
              <span class="marker-icon">{{ markerTypes[marker.type].icon }}</span>
            </div>
          </div>

          <!-- Zoom controls -->
          <div class="zoom-controls">
            <button @click="handleZoomIn" class="zoom-btn">+</button>
            <button @click="handleZoomOut" class="zoom-btn">−</button>
          </div>

          <!-- Info window -->
          <div v-if="showInfoWindow && selectedMarker" class="info-window">
            <div class="info-header">
              <h4>{{ selectedMarker.title }}</h4>
              <button @click="showInfoWindow = false" class="close-btn">✕</button>
            </div>
            <div class="info-content">
              <div class="info-type">Type: {{ selectedMarker.type }}</div>
              <div class="info-description">{{ selectedMarker.description }}</div>
              <div class="info-coordinates">
                {{ selectedMarker.lat.toFixed(4) }}, {{ selectedMarker.lng.toFixed(4) }}
              </div>
            </div>
            <div class="info-actions">
              <button @click="removeMarker(selectedMarker.id)">Remove</button>
              <button @click="centerOnMarker(selectedMarker)">Center</button>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Search overlay -->
    <div v-if="showSearchOverlay" class="search-overlay">
      <div class="search-results">
        <div class="search-header">
          <h3>Search Results</h3>
          <button @click="showSearchOverlay = false" class="close-btn">✕</button>
        </div>
        
        <div v-if="isSearching" class="search-loading">
          <div class="loading-spinner"></div>
          <span>Searching...</span>
        </div>
        
        <div v-else class="search-results-list">
          <div v-if="searchResults.length > 0">
            <div
              v-for="result in searchResults"
              :key="result.id"
              class="search-result-item"
              @click="handleSearchResultClick(result)"
            >
              <div class="result-title">{{ result.title }}</div>
              <div class="result-description">{{ result.description }}</div>
              <div class="result-type">{{ result.type }}</div>
            </div>
          </div>
          <div v-else class="no-results">
            No results found for "{{ searchQuery }}"
          </div>
        </div>
      </div>
    </div>

    <div class="map-footer">
      <div class="map-instructions">
        <span>Click markers to view details • Double-click map to add marker • Use zoom controls to navigate</span>
      </div>
      <div class="map-legend">
        <div v-for="(config, type) in markerTypes" :key="type" class="legend-item">
          <div 
            class="legend-color" 
            :style="{ backgroundColor: config.color }"
          >
            {{ config.icon }}
          </div>
          <span>{{ type }}</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'InteractiveMap',
  data() {
    return {
      mapCenter: { lat: 40.7128, lng: -74.0060 },
      zoom: 10,
      markers: [
        {
          id: 1,
          lat: 40.7589,
          lng: -73.9851,
          title: 'Times Square',
          type: 'attraction',
          description: 'Famous commercial intersection and tourist destination'
        },
        {
          id: 2,
          lat: 40.7829,
          lng: -73.9654,
          title: 'Central Park',
          type: 'park',
          description: 'Large public park in Manhattan'
        },
        {
          id: 3,
          lat: 40.6892,
          lng: -74.0445,
          title: 'Statue of Liberty',
          type: 'monument',
          description: 'Iconic symbol of freedom and democracy'
        },
        {
          id: 4,
          lat: 40.7505,
          lng: -73.9934,
          title: 'Empire State Building',
          type: 'building',
          description: 'Famous Art Deco skyscraper'
        },
        {
          id: 5,
          lat: 40.7614,
          lng: -73.9776,
          title: 'Broadway Theater',
          type: 'entertainment',
          description: 'Historic theater district'
        }
      ],
      selectedMarker: null,
      showInfoWindow: false,
      searchQuery: '',
      filteredMarkers: [],
      showLayers: false,
      activeLayers: {
        attractions: true,
        parks: true,
        monuments: true,
        buildings: true,
        entertainment: true,
        traffic: false,
        weather: false
      },
      showSearchOverlay: false,
      searchResults: [],
      isSearching: false,
      mapStyle: 'default',
      mapStyles: [
        { id: 'default', name: 'Default', preview: '🗺️' },
        { id: 'satellite', name: 'Satellite', preview: '🛰️' },
        { id: 'terrain', name: 'Terrain', preview: '🏔️' }
      ],
      markerTypes: {
        attraction: { color: '#4caf50', icon: '🎯' },
        park: { color: '#8bc34a', icon: '🌳' },
        monument: { color: '#ff9800', icon: '🏛️' },
        building: { color: '#2196f3', icon: '🏢' },
        entertainment: { color: '#9c27b0', icon: '🎭' }
      }
    }
  },
  watch: {
    activeLayers: {
      handler() {
        this.filterMarkers();
      },
      deep: true
    },
    searchQuery() {
      if (this.searchQuery.length > 2) {
        const filteredSuggestions = this.markers.filter(marker =>
          marker.title.toLowerCase().includes(this.searchQuery.toLowerCase()) ||
          marker.description.toLowerCase().includes(this.searchQuery.toLowerCase())
        );
        this.searchResults = filteredSuggestions.slice(0, 5);
        this.showSearchOverlay = true;
      } else {
        this.showSearchOverlay = false;
      }
    }
  },
  mounted() {
    this.filterMarkers();
  },
  methods: {
    filterMarkers() {
      this.filteredMarkers = this.markers.filter(marker => {
        const layerKey = marker.type === 'attraction' ? 'attractions' : 
                        marker.type === 'park' ? 'parks' :
                        marker.type === 'monument' ? 'monuments' :
                        marker.type === 'building' ? 'buildings' :
                        marker.type === 'entertainment' ? 'entertainment' : marker.type;
        return this.activeLayers[layerKey];
      });
    },
    handleMarkerClick(marker) {
      this.selectedMarker = marker;
      this.showInfoWindow = true;
      this.mapCenter = { lat: marker.lat, lng: marker.lng };
      this.zoom = 15;
    },
    handleMapClick(event) {
      if (event.target === this.$refs.mapRef) {
        this.showInfoWindow = false;
        this.selectedMarker = null;
      }
    },
    handleZoomIn() {
      this.zoom = Math.min(this.zoom + 1, 20);
    },
    handleZoomOut() {
      this.zoom = Math.max(this.zoom - 1, 1);
    },
    handleLayerToggle(layer) {
      this.activeLayers[layer] = !this.activeLayers[layer];
    },
    async handleSearch() {
      if (!this.searchQuery.trim()) return;

      this.isSearching = true;
      this.showSearchOverlay = true;

      setTimeout(() => {
        const results = this.markers.filter(marker =>
          marker.title.toLowerCase().includes(this.searchQuery.toLowerCase()) ||
          marker.description.toLowerCase().includes(this.searchQuery.toLowerCase())
        );
        this.searchResults = results;
        this.isSearching = false;
      }, 1000);
    },
    handleSearchResultClick(result) {
      this.mapCenter = { lat: result.lat, lng: result.lng };
      this.zoom = 15;
      this.showSearchOverlay = false;
      this.searchQuery = '';
      this.searchResults = [];
    },
    addCustomMarker(event) {
      const rect = this.$refs.mapRef.getBoundingClientRect();
      const x = event.clientX - rect.left;
      const y = event.clientY - rect.top;
      
      const lat = this.mapCenter.lat + (rect.height / 2 - y) * (0.01 / this.zoom);
      const lng = this.mapCenter.lng + (x - rect.width / 2) * (0.01 / this.zoom);
      
      const newMarker = {
        id: Date.now(),
        lat,
        lng,
        title: 'Custom Location',
        type: 'attraction',
        description: 'User-added marker'
      };
      
      this.markers.push(newMarker);
    },
    removeMarker(markerId) {
      this.markers = this.markers.filter(marker => marker.id !== markerId);
      if (this.selectedMarker && this.selectedMarker.id === markerId) {
        this.showInfoWindow = false;
        this.selectedMarker = null;
      }
    },
    getMarkerPosition(marker) {
      const rect = this.$refs.mapRef?.getBoundingClientRect();
      if (!rect) return { x: 0, y: 0 };
      
      const x = rect.width / 2 + (marker.lng - this.mapCenter.lng) * (this.zoom * 10);
      const y = rect.height / 2 - (marker.lat - this.mapCenter.lat) * (this.zoom * 10);
      
      return { x, y };
    },
    resetView() {
      this.mapCenter = { lat: 40.7128, lng: -74.0060 };
    },
    setDefaultZoom() {
      this.zoom = 10;
    },
    clearSelection() {
      this.showInfoWindow = false;
    },
    centerOnMarker(marker) {
      this.mapCenter = { lat: marker.lat, lng: marker.lng };
    }
  }
}
</script>

<style scoped>
.interactive-map {
  max-width: 1200px;
  margin: 0 auto;
  padding: 20px;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}

.map-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 25px;
  padding-bottom: 15px;
  border-bottom: 2px solid #e0e0e0;
}

.map-header h1 {
  margin: 0;
  color: #333;
  font-size: 28px;
}

.map-controls {
  display: flex;
  align-items: center;
  gap: 15px;
}

.search-container {
  display: flex;
  align-items: center;
  background: white;
  border: 1px solid #ddd;
  border-radius: 6px;
  overflow: hidden;
}

.search-input {
  padding: 8px 12px;
  border: none;
  outline: none;
  font-size: 14px;
  min-width: 200px;
}

.search-input:focus {
  background: #f8f9fa;
}

.search-btn {
  padding: 8px 12px;
  background: #4caf50;
  color: white;
  border: none;
  cursor: pointer;
  font-size: 14px;
  transition: background-color 0.3s ease;
}

.search-btn:hover {
  background: #45a049;
}

.map-style-selector select {
  padding: 8px 12px;
  border: 1px solid #ddd;
  border-radius: 6px;
  font-size: 14px;
  background: white;
  cursor: pointer;
}

.map-container {
  display: grid;
  grid-template-columns: 300px 1fr;
  gap: 20px;
  height: 600px;
}

.map-sidebar {
  background: #f8f9fa;
  border-radius: 8px;
  padding: 20px;
  overflow-y: auto;
}

.sidebar-section {
  margin-bottom: 25px;
}

.sidebar-section h3 {
  margin: 0 0 15px 0;
  color: #333;
  font-size: 16px;
  font-weight: 600;
}

.layers-toggle {
  width: 100%;
  padding: 8px 12px;
  background: white;
  border: 1px solid #ddd;
  border-radius: 6px;
  cursor: pointer;
  font-size: 14px;
  color: #333;
  transition: all 0.3s ease;
}

.layers-toggle:hover {
  background: #f5f5f5;
  border-color: #4caf50;
}

.layers-panel {
  margin-top: 10px;
  background: white;
  border: 1px solid #e0e0e0;
  border-radius: 6px;
  padding: 10px;
}

.layer-item {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 6px 0;
  cursor: pointer;
  font-size: 14px;
}

.layer-item input[type="checkbox"] {
  margin: 0;
}

.layer-name {
  color: #333;
  text-transform: capitalize;
}

.quick-actions {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.quick-actions button {
  padding: 8px 12px;
  background: white;
  border: 1px solid #ddd;
  border-radius: 6px;
  cursor: pointer;
  font-size: 14px;
  color: #333;
  transition: all 0.3s ease;
}

.quick-actions button:hover {
  background: #4caf50;
  color: white;
  border-color: #4caf50;
}

.map-info {
  background: white;
  border: 1px solid #e0e0e0;
  border-radius: 6px;
  padding: 10px;
}

.info-item {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 4px 0;
  font-size: 12px;
  color: #666;
}

.info-item span:first-child {
  font-weight: 600;
}

.map-main {
  background: white;
  border-radius: 8px;
  overflow: hidden;
  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
}

.map-display {
  position: relative;
  width: 100%;
  height: 100%;
  overflow: hidden;
  cursor: crosshair;
}

.map-background {
  width: 100%;
  height: 100%;
  background-size: cover;
  background-position: center;
  background-repeat: no-repeat;
  position: relative;
  transition: transform 0.3s ease;
}

.map-marker {
  position: absolute;
  width: 30px;
  height: 30px;
  border-radius: 50%;
  border: 3px solid white;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 14px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.3);
  transition: all 0.3s ease;
  transform: translate(-50%, -50%);
}

.map-marker:hover {
  transform: translate(-50%, -50%) scale(1.2);
  z-index: 10;
}

.marker-icon {
  color: white;
  text-shadow: 0 1px 2px rgba(0, 0, 0, 0.5);
}

.zoom-controls {
  position: absolute;
  top: 20px;
  right: 20px;
  display: flex;
  flex-direction: column;
  gap: 5px;
  z-index: 20;
}

.zoom-btn {
  width: 40px;
  height: 40px;
  background: white;
  border: 1px solid #ddd;
  border-radius: 6px;
  cursor: pointer;
  font-size: 18px;
  font-weight: bold;
  color: #333;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all 0.3s ease;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
}

.zoom-btn:hover {
  background: #4caf50;
  color: white;
  border-color: #4caf50;
}

.info-window {
  position: absolute;
  top: 20px;
  left: 20px;
  background: white;
  border: 1px solid #ddd;
  border-radius: 8px;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.2);
  z-index: 30;
  min-width: 250px;
  max-width: 300px;
}

.info-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 15px;
  background: #f8f9fa;
  border-bottom: 1px solid #e0e0e0;
  border-radius: 8px 8px 0 0;
}

.info-header h4 {
  margin: 0;
  color: #333;
  font-size: 16px;
  font-weight: 600;
}

.close-btn {
  background: none;
  border: none;
  font-size: 16px;
  cursor: pointer;
  color: #666;
  padding: 4px;
  border-radius: 3px;
  transition: background-color 0.3s ease;
}

.close-btn:hover {
  background: #e9ecef;
}

.info-content {
  padding: 15px;
}

.info-type {
  font-size: 12px;
  color: #666;
  text-transform: uppercase;
  letter-spacing: 0.5px;
  margin-bottom: 8px;
}

.info-description {
  font-size: 14px;
  color: #333;
  line-height: 1.4;
  margin-bottom: 10px;
}

.info-coordinates {
  font-size: 11px;
  color: #999;
  font-family: monospace;
}

.info-actions {
  display: flex;
  gap: 8px;
  padding: 15px;
  border-top: 1px solid #e0e0e0;
}

.info-actions button {
  flex: 1;
  padding: 8px 12px;
  border: 1px solid #ddd;
  background: white;
  cursor: pointer;
  border-radius: 4px;
  font-size: 12px;
  color: #333;
  transition: all 0.3s ease;
}

.info-actions button:hover {
  background: #4caf50;
  color: white;
  border-color: #4caf50;
}

.search-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.5);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1000;
}

.search-results {
  background: white;
  border-radius: 8px;
  width: 90%;
  max-width: 500px;
  max-height: 80vh;
  overflow: hidden;
}

.search-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 20px;
  background: #f8f9fa;
  border-bottom: 1px solid #e0e0e0;
}

.search-header h3 {
  margin: 0;
  color: #333;
  font-size: 18px;
}

.search-loading {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 40px;
  color: #666;
}

.loading-spinner {
  width: 30px;
  height: 30px;
  border: 3px solid rgba(76, 175, 80, 0.3);
  border-top: 3px solid #4caf50;
  border-radius: 50%;
  animation: spin 1s linear infinite;
  margin-bottom: 15px;
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

.search-results-list {
  max-height: 400px;
  overflow-y: auto;
}

.search-result-item {
  padding: 15px 20px;
  border-bottom: 1px solid #f0f0f0;
  cursor: pointer;
  transition: background-color 0.3s ease;
}

.search-result-item:hover {
  background: #f8f9fa;
}

.search-result-item:last-child {
  border-bottom: none;
}

.result-title {
  font-size: 16px;
  font-weight: 600;
  color: #333;
  margin-bottom: 5px;
}

.result-description {
  font-size: 14px;
  color: #666;
  margin-bottom: 5px;
}

.result-type {
  font-size: 12px;
  color: #999;
  text-transform: uppercase;
  letter-spacing: 0.5px;
}

.no-results {
  padding: 40px 20px;
  text-align: center;
  color: #666;
  font-style: italic;
}

.map-footer {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-top: 20px;
  padding-top: 15px;
  border-top: 1px solid #e0e0e0;
  font-size: 12px;
  color: #666;
}

.map-instructions {
  flex: 1;
}

.map-legend {
  display: flex;
  gap: 15px;
}

.legend-item {
  display: flex;
  align-items: center;
  gap: 5px;
}

.legend-color {
  width: 16px;
  height: 16px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 10px;
  color: white;
  text-shadow: 0 1px 2px rgba(0, 0, 0, 0.5);
}

@media (max-width: 968px) {
  .map-container {
    grid-template-columns: 1fr;
    height: auto;
  }
  
  .map-sidebar {
    order: 2;
    height: auto;
  }
  
  .map-main {
    order: 1;
    height: 400px;
  }
}

@media (max-width: 768px) {
  .interactive-map {
    padding: 15px;
  }
  
  .map-header {
    flex-direction: column;
    gap: 15px;
    align-items: stretch;
  }
  
  .map-controls {
    flex-direction: column;
    gap: 10px;
  }
  
  .search-input {
    min-width: auto;
  }
  
  .map-main {
    height: 300px;
  }
  
  .info-window {
    position: relative;
    top: auto;
    left: auto;
    margin: 10px;
  }
  
  .zoom-controls {
    top: 10px;
    right: 10px;
  }
  
  .zoom-btn {
    width: 35px;
    height: 35px;
    font-size: 16px;
  }
  
  .map-footer {
    flex-direction: column;
    gap: 15px;
    align-items: stretch;
  }
  
  .map-legend {
    justify-content: center;
  }
}

@media (max-width: 480px) {
  .map-sidebar {
    padding: 15px;
  }
  
  .sidebar-section {
    margin-bottom: 20px;
  }
  
  .layers-panel {
    padding: 8px;
  }
  
  .quick-actions {
    gap: 6px;
  }
  
  .quick-actions button {
    padding: 6px 10px;
    font-size: 13px;
  }
  
  .map-info {
    padding: 8px;
  }
  
  .info-item {
    font-size: 11px;
  }
  
  .map-marker {
    width: 25px;
    height: 25px;
    font-size: 12px;
  }
  
  .info-window {
    min-width: 200px;
    max-width: 250px;
  }
  
  .info-header,
  .info-content,
  .info-actions {
    padding: 12px;
  }
  
  .info-header h4 {
    font-size: 14px;
  }
  
  .info-description {
    font-size: 13px;
  }
  
  .info-actions button {
    padding: 6px 10px;
    font-size: 11px;
  }
  
  .search-results {
    width: 95%;
  }
  
  .search-header {
    padding: 15px;
  }
  
  .search-header h3 {
    font-size: 16px;
  }
  
  .search-result-item {
    padding: 12px 15px;
  }
  
  .result-title {
    font-size: 14px;
  }
  
  .result-description {
    font-size: 13px;
  }
  
  .map-legend {
    flex-wrap: wrap;
    gap: 10px;
  }
  
  .legend-color {
    width: 14px;
    height: 14px;
    font-size: 9px;
  }
}
</style>
