// scenarios/advanced/web/svelte/n8.svelte
<script>
  import { onMount } from 'svelte';
  
  let data = [];
  let filteredData = [];
  let sortConfig = { key: null, direction: 'asc' };
  let filters = {
    name: '',
    category: '',
    status: '',
    dateRange: ''
  };
  let selectedRows = [];
  let currentPage = 1;
  let itemsPerPage = 10;
  let showFilters = false;
  let isLoading = false;

  const sampleData = [
    { id: 1, name: 'Project Alpha', category: 'Development', status: 'Active', priority: 'High', assignee: 'John Doe', startDate: '2024-01-15', endDate: '2024-03-15', progress: 75 },
    { id: 2, name: 'Project Beta', category: 'Design', status: 'Planning', priority: 'Medium', assignee: 'Jane Smith', startDate: '2024-02-01', endDate: '2024-04-01', progress: 25 },
    { id: 3, name: 'Project Gamma', category: 'Testing', status: 'Completed', priority: 'Low', assignee: 'Mike Johnson', startDate: '2024-01-01', endDate: '2024-01-31', progress: 100 },
    { id: 4, name: 'Project Delta', category: 'Development', status: 'Active', priority: 'High', assignee: 'Sarah Wilson', startDate: '2024-02-15', endDate: '2024-05-15', progress: 50 },
    { id: 5, name: 'Project Epsilon', category: 'Research', status: 'Planning', priority: 'Medium', assignee: 'David Brown', startDate: '2024-03-01', endDate: '2024-06-01', progress: 10 },
    { id: 6, name: 'Project Zeta', category: 'Development', status: 'On Hold', priority: 'Low', assignee: 'Lisa Davis', startDate: '2024-01-20', endDate: '2024-04-20', progress: 30 },
    { id: 7, name: 'Project Eta', category: 'Design', status: 'Active', priority: 'High', assignee: 'Tom Wilson', startDate: '2024-02-10', endDate: '2024-04-10', progress: 60 },
    { id: 8, name: 'Project Theta', category: 'Testing', status: 'Completed', priority: 'Medium', assignee: 'Anna Taylor', startDate: '2024-01-05', endDate: '2024-02-05', progress: 100 },
    { id: 9, name: 'Project Iota', category: 'Research', status: 'Planning', priority: 'High', assignee: 'Chris Lee', startDate: '2024-03-15', endDate: '2024-07-15', progress: 5 },
    { id: 10, name: 'Project Kappa', category: 'Development', status: 'Active', priority: 'Medium', assignee: 'Emma Garcia', startDate: '2024-02-20', endDate: '2024-05-20', progress: 40 }
  ];

  $: totalPages = Math.ceil(filteredData.length / itemsPerPage);
  $: startIndex = (currentPage - 1) * itemsPerPage;
  $: paginatedData = filteredData.slice(startIndex, startIndex + itemsPerPage);

  onMount(() => {
    data = sampleData;
    filteredData = sampleData;
  });

  $: applyFilters();

  function applyFilters() {
    let filtered = [...data];

    if (filters.name) {
      filtered = filtered.filter(item => 
        item.name.toLowerCase().includes(filters.name.toLowerCase())
      );
    }

    if (filters.category) {
      filtered = filtered.filter(item => item.category === filters.category);
    }

    if (filters.status) {
      filtered = filtered.filter(item => item.status === filters.status);
    }

    if (filters.dateRange) {
      const today = new Date();
      const days = parseInt(filters.dateRange);
      const cutoffDate = new Date(today.getTime() - (days * 24 * 60 * 60 * 1000));
      
      filtered = filtered.filter(item => {
        const startDate = new Date(item.startDate);
        return startDate >= cutoffDate;
      });
    }

    filteredData = filtered;
    currentPage = 1;
  }

  function handleSort(key) {
    let direction = 'asc';
    if (sortConfig.key === key && sortConfig.direction === 'asc') {
      direction = 'desc';
    }
    sortConfig = { key, direction };

    const sorted = [...filteredData].sort((a, b) => {
      if (a[key] < b[key]) {
        return direction === 'asc' ? -1 : 1;
      }
      if (a[key] > b[key]) {
        return direction === 'asc' ? 1 : -1;
      }
      return 0;
    });

    filteredData = sorted;
  }

  function handleSelectRow(id) {
    selectedRows = selectedRows.includes(id) 
      ? selectedRows.filter(rowId => rowId !== id)
      : [...selectedRows, id];
  }

  function handleSelectAll() {
    if (selectedRows.length === paginatedData.length) {
      selectedRows = [];
    } else {
      selectedRows = paginatedData.map(item => item.id);
    }
  }

  function handleBulkAction(action) {
    if (selectedRows.length === 0) return;

    isLoading = true;
    setTimeout(() => {
      console.log(`Bulk action: ${action} on rows:`, selectedRows);
      selectedRows = [];
      isLoading = false;
      alert(`Bulk action "${action}" completed for ${selectedRows.length} items`);
    }, 1000);
  }

  function handleExport(format) {
    isLoading = true;
    setTimeout(() => {
      console.log(`Exporting data as ${format}:`, filteredData);
      isLoading = false;
      alert(`Data exported as ${format.toUpperCase()} successfully!`);
    }, 1500);
  }

  function getStatusColor(status) {
    switch (status) {
      case 'Active': return '#4caf50';
      case 'Planning': return '#ff9800';
      case 'Completed': return '#2196f3';
      case 'On Hold': return '#f44336';
      default: return '#666';
    }
  }

  function getPriorityColor(priority) {
    switch (priority) {
      case 'High': return '#f44336';
      case 'Medium': return '#ff9800';
      case 'Low': return '#4caf50';
      default: return '#666';
    }
  }

  const categories = [...new Set(data.map(item => item.category))];
  const statuses = [...new Set(data.map(item => item.status))];
</script>

<div class="data-table-container">
  <div class="table-header">
    <h2>Project Management Dashboard</h2>
    <div class="header-actions">
      <button 
        on:click={() => showFilters = !showFilters}
        class="filter-toggle"
      >
        {showFilters ? 'Hide' : 'Show'} Filters
      </button>
      <button 
        on:click={() => handleExport('csv')}
        disabled={isLoading}
        class="export-btn"
      >
        {isLoading ? 'Exporting...' : 'Export CSV'}
      </button>
      <button 
        on:click={() => handleExport('pdf')}
        disabled={isLoading}
        class="export-btn"
      >
        {isLoading ? 'Exporting...' : 'Export PDF'}
      </button>
    </div>
  </div>

  {#if showFilters}
    <div class="filters-panel">
      <div class="filter-row">
        <div class="filter-group">
          <input
            type="text"
            placeholder="Search by name..."
            bind:value={filters.name}
            class="filter-input"
          />
        </div>
        <div class="filter-group">
          <select
            bind:value={filters.category}
            class="filter-select"
          >
            <option value="">All Categories</option>
            {#each categories as category}
              <option value={category}>{category}</option>
            {/each}
          </select>
        </div>
        <div class="filter-group">
          <select
            bind:value={filters.status}
            class="filter-select"
          >
            <option value="">All Statuses</option>
            {#each statuses as status}
              <option value={status}>{status}</option>
            {/each}
          </select>
        </div>
        <div class="filter-group">
          <select
            bind:value={filters.dateRange}
            class="filter-select"
          >
            <option value="">All Time</option>
            <option value="7">Last 7 days</option>
            <option value="30">Last 30 days</option>
            <option value="90">Last 90 days</option>
          </select>
        </div>
      </div>
    </div>
  {/if}

  {#if selectedRows.length > 0}
    <div class="bulk-actions">
      <span class="selected-count">
        {selectedRows.length} item{selectedRows.length !== 1 ? 's' : ''} selected
      </span>
      <div class="bulk-buttons">
        <button 
          on:click={() => handleBulkAction('Delete')}
          class="bulk-btn"
        >
          Delete
        </button>
        <button 
          on:click={() => handleBulkAction('Archive')}
          class="bulk-btn"
        >
          Archive
        </button>
        <button 
          on:click={() => handleBulkAction('Export')}
          class="bulk-btn"
        >
          Export Selected
        </button>
      </div>
    </div>
  {/if}

  <div class="table-wrapper">
    <table class="data-table">
      <thead>
        <tr>
          <th class="checkbox-column">
            <input
              type="checkbox"
              checked={selectedRows.length === paginatedData.length && paginatedData.length > 0}
              on:change={handleSelectAll}
            />
          </th>
          <th 
            class="sortable-header"
            on:click={() => handleSort('name')}
          >
            Project Name
            {#if sortConfig.key === 'name'}
              <span class="sort-indicator">
                {sortConfig.direction === 'asc' ? '↑' : '↓'}
              </span>
            {/if}
          </th>
          <th 
            class="sortable-header"
            on:click={() => handleSort('category')}
          >
            Category
            {#if sortConfig.key === 'category'}
              <span class="sort-indicator">
                {sortConfig.direction === 'asc' ? '↑' : '↓'}
              </span>
            {/if}
          </th>
          <th 
            class="sortable-header"
            on:click={() => handleSort('status')}
          >
            Status
            {#if sortConfig.key === 'status'}
              <span class="sort-indicator">
                {sortConfig.direction === 'asc' ? '↑' : '↓'}
              </span>
            {/if}
          </th>
          <th 
            class="sortable-header"
            on:click={() => handleSort('priority')}
          >
            Priority
            {#if sortConfig.key === 'priority'}
              <span class="sort-indicator">
                {sortConfig.direction === 'asc' ? '↑' : '↓'}
              </span>
            {/if}
          </th>
          <th 
            class="sortable-header"
            on:click={() => handleSort('assignee')}
          >
            Assignee
            {#if sortConfig.key === 'assignee'}
              <span class="sort-indicator">
                {sortConfig.direction === 'asc' ? '↑' : '↓'}
              </span>
            {/if}
          </th>
          <th 
            class="sortable-header"
            on:click={() => handleSort('startDate')}
          >
            Start Date
            {#if sortConfig.key === 'startDate'}
              <span class="sort-indicator">
                {sortConfig.direction === 'asc' ? '↑' : '↓'}
              </span>
            {/if}
          </th>
          <th 
            class="sortable-header"
            on:click={() => handleSort('progress')}
          >
            Progress
            {#if sortConfig.key === 'progress'}
              <span class="sort-indicator">
                {sortConfig.direction === 'asc' ? '↑' : '↓'}
              </span>
            {/if}
          </th>
          <th class="actions-column">Actions</th>
        </tr>
      </thead>
      <tbody>
        {#each paginatedData as item}
          <tr 
            class="table-row"
            class:selected-row={selectedRows.includes(item.id)}
          >
            <td class="checkbox-column">
              <input
                type="checkbox"
                checked={selectedRows.includes(item.id)}
                on:change={() => handleSelectRow(item.id)}
              />
            </td>
            <td class="name-cell">
              <div class="project-name">{item.name}</div>
              <div class="project-id">ID: {item.id}</div>
            </td>
            <td class="category-cell">
              <span class="category-tag">{item.category}</span>
            </td>
            <td class="status-cell">
              <span 
                class="status-badge"
                style="background-color: {getStatusColor(item.status)}"
              >
                {item.status}
              </span>
            </td>
            <td class="priority-cell">
              <span 
                class="priority-badge"
                style="background-color: {getPriorityColor(item.priority)}"
              >
                {item.priority}
              </span>
            </td>
            <td class="assignee-cell">
              <div class="assignee-info">
                <div class="assignee-name">{item.assignee}</div>
              </div>
            </td>
            <td class="date-cell">
              <div class="date-info">
                <div class="start-date">{item.startDate}</div>
                <div class="end-date">End: {item.endDate}</div>
              </div>
            </td>
            <td class="progress-cell">
              <div class="progress-container">
                <div class="progress-bar">
                  <div 
                    class="progress-fill"
                    style="width: {item.progress}%"
                  />
                </div>
                <span class="progress-text">{item.progress}%</span>
              </div>
            </td>
            <td class="actions-cell">
              <div class="action-buttons">
                <button class="action-btn">Edit</button>
                <button class="action-btn">View</button>
                <button class="action-btn">Delete</button>
              </div>
            </td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>

  <div class="table-footer">
    <div class="pagination-info">
      Showing {startIndex + 1} to {Math.min(startIndex + itemsPerPage, filteredData.length)} of {filteredData.length} entries
    </div>
    <div class="pagination">
      <button 
        on:click={() => currentPage = Math.max(1, currentPage - 1)}
        disabled={currentPage === 1}
        class="pagination-btn"
      >
        Previous
      </button>
      {#each Array(totalPages) as _, i}
        <button
          on:click={() => currentPage = i + 1}
          class="pagination-btn"
          class:active-page={currentPage === i + 1}
        >
          {i + 1}
        </button>
      {/each}
      <button 
        on:click={() => currentPage = Math.min(totalPages, currentPage + 1)}
        disabled={currentPage === totalPages}
        class="pagination-btn"
      >
        Next
      </button>
    </div>
  </div>
</div>

<style>
  .data-table-container {
    max-width: 1400px;
    margin: 0 auto;
    padding: 20px;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    background: white;
    border-radius: 8px;
    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
  }

  .table-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 25px;
    padding-bottom: 15px;
    border-bottom: 2px solid #e0e0e0;
  }

  .table-header h2 {
    margin: 0;
    color: #333;
    font-size: 24px;
  }

  .header-actions {
    display: flex;
    gap: 10px;
    align-items: center;
  }

  .filter-toggle {
    padding: 8px 16px;
    background: #f5f5f5;
    border: 1px solid #ddd;
    border-radius: 6px;
    cursor: pointer;
    font-size: 14px;
    color: #333;
    transition: all 0.3s ease;
  }

  .filter-toggle:hover {
    background: #e0e0e0;
    border-color: #4caf50;
  }

  .export-btn {
    padding: 8px 16px;
    background: #4caf50;
    color: white;
    border: none;
    border-radius: 6px;
    cursor: pointer;
    font-size: 14px;
    font-weight: 600;
    transition: background-color 0.3s ease;
  }

  .export-btn:hover:not(:disabled) {
    background: #45a049;
  }

  .export-btn:disabled {
    background: #ccc;
    cursor: not-allowed;
  }

  .filters-panel {
    background: #f8f9fa;
    border: 1px solid #e0e0e0;
    border-radius: 8px;
    padding: 20px;
    margin-bottom: 20px;
  }

  .filter-row {
    display: grid;
    grid-template-columns: 2fr 1fr 1fr 1fr;
    gap: 15px;
    align-items: end;
  }

  .filter-group {
    display: flex;
    flex-direction: column;
    gap: 5px;
  }

  .filter-input,
  .filter-select {
    padding: 10px 12px;
    border: 1px solid #ddd;
    border-radius: 6px;
    font-size: 14px;
    transition: border-color 0.3s ease;
  }

  .filter-input:focus,
  .filter-select:focus {
    outline: none;
    border-color: #4caf50;
  }

  .bulk-actions {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 15px 20px;
    background: #e3f2fd;
    border: 1px solid #2196f3;
    border-radius: 6px;
    margin-bottom: 20px;
  }

  .selected-count {
    font-weight: 600;
    color: #1976d2;
  }

  .bulk-buttons {
    display: flex;
    gap: 10px;
  }

  .bulk-btn {
    padding: 6px 12px;
    background: white;
    border: 1px solid #2196f3;
    border-radius: 4px;
    cursor: pointer;
    font-size: 12px;
    color: #1976d2;
    transition: all 0.3s ease;
  }

  .bulk-btn:hover {
    background: #2196f3;
    color: white;
  }

  .table-wrapper {
    overflow-x: auto;
    border: 1px solid #e0e0e0;
    border-radius: 8px;
    margin-bottom: 20px;
  }

  .data-table {
    width: 100%;
    border-collapse: collapse;
    background: white;
  }

  .data-table th {
    background: #f8f9fa;
    padding: 15px 12px;
    text-align: left;
    font-weight: 600;
    color: #333;
    border-bottom: 2px solid #e0e0e0;
    font-size: 14px;
  }

  .sortable-header {
    cursor: pointer;
    user-select: none;
    transition: background-color 0.3s ease;
    position: relative;
  }

  .sortable-header:hover {
    background: #e9ecef;
  }

  .sort-indicator {
    margin-left: 8px;
    color: #4caf50;
    font-weight: bold;
  }

  .checkbox-column {
    width: 50px;
    text-align: center;
  }

  .actions-column {
    width: 150px;
    text-align: center;
  }

  .table-row {
    transition: background-color 0.3s ease;
  }

  .table-row:hover {
    background: #f8f9fa;
  }

  .selected-row {
    background: #e3f2fd;
  }

  .table-row td {
    padding: 12px;
    border-bottom: 1px solid #f0f0f0;
    font-size: 14px;
    vertical-align: middle;
  }

  .name-cell {
    min-width: 200px;
  }

  .project-name {
    font-weight: 600;
    color: #333;
    margin-bottom: 2px;
  }

  .project-id {
    font-size: 11px;
    color: #666;
  }

  .category-cell {
    min-width: 120px;
  }

  .category-tag {
    display: inline-block;
    padding: 4px 8px;
    background: #e9ecef;
    color: #495057;
    border-radius: 4px;
    font-size: 12px;
    font-weight: 500;
  }

  .status-cell {
    min-width: 100px;
  }

  .status-badge {
    display: inline-block;
    padding: 4px 8px;
    color: white;
    border-radius: 4px;
    font-size: 11px;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.5px;
  }

  .priority-cell {
    min-width: 80px;
  }

  .priority-badge {
    display: inline-block;
    padding: 4px 8px;
    color: white;
    border-radius: 4px;
    font-size: 11px;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.5px;
  }

  .assignee-cell {
    min-width: 150px;
  }

  .assignee-name {
    font-weight: 500;
    color: #333;
  }

  .date-cell {
    min-width: 120px;
  }

  .start-date {
    font-weight: 500;
    color: #333;
    margin-bottom: 2px;
  }

  .end-date {
    font-size: 11px;
    color: #666;
  }

  .progress-cell {
    min-width: 120px;
  }

  .progress-container {
    display: flex;
    align-items: center;
    gap: 8px;
  }

  .progress-bar {
    flex: 1;
    height: 8px;
    background: #e0e0e0;
    border-radius: 4px;
    overflow: hidden;
  }

  .progress-fill {
    height: 100%;
    background: linear-gradient(90deg, #4caf50, #8bc34a);
    transition: width 0.3s ease;
  }

  .progress-text {
    font-size: 11px;
    color: #666;
    font-weight: 600;
    min-width: 35px;
  }

  .actions-cell {
    text-align: center;
  }

  .action-buttons {
    display: flex;
    gap: 4px;
    justify-content: center;
  }

  .action-btn {
    padding: 4px 8px;
    background: #f5f5f5;
    border: 1px solid #ddd;
    border-radius: 3px;
    cursor: pointer;
    font-size: 11px;
    color: #666;
    transition: all 0.3s ease;
  }

  .action-btn:hover {
    background: #4caf50;
    color: white;
    border-color: #4caf50;
  }

  .table-footer {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 15px 0;
    border-top: 1px solid #e0e0e0;
  }

  .pagination-info {
    font-size: 14px;
    color: #666;
  }

  .pagination {
    display: flex;
    gap: 5px;
    align-items: center;
  }

  .pagination-btn {
    padding: 8px 12px;
    border: 1px solid #ddd;
    background: white;
    cursor: pointer;
    border-radius: 4px;
    font-size: 14px;
    color: #333;
    transition: all 0.3s ease;
  }

  .pagination-btn:hover:not(:disabled) {
    background: #f5f5f5;
    border-color: #4caf50;
  }

  .pagination-btn:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  .active-page {
    background: #4caf50;
    color: white;
    border-color: #4caf50;
  }

  @media (max-width: 1200px) {
    .filter-row {
      grid-template-columns: 1fr 1fr;
      gap: 10px;
    }
  }

  @media (max-width: 768px) {
    .data-table-container {
      padding: 15px;
    }
    
    .table-header {
      flex-direction: column;
      gap: 15px;
      align-items: stretch;
    }
    
    .header-actions {
      justify-content: center;
      flex-wrap: wrap;
    }
    
    .filter-row {
      grid-template-columns: 1fr;
      gap: 10px;
    }
    
    .bulk-actions {
      flex-direction: column;
      gap: 10px;
      align-items: stretch;
    }
    
    .bulk-buttons {
      justify-content: center;
    }
    
    .table-footer {
      flex-direction: column;
      gap: 15px;
      align-items: stretch;
    }
    
    .pagination {
      justify-content: center;
    }
    
    .action-buttons {
      flex-direction: column;
      gap: 2px;
    }
  }

  @media (max-width: 480px) {
    .data-table-container {
      padding: 10px;
    }
    
    .table-wrapper {
      font-size: 12px;
    }
    
    .data-table th,
    .table-row td {
      padding: 8px 6px;
    }
    
    .pagination-btn {
      padding: 6px 8px;
      font-size: 12px;
    }
  }
</style>

// scenarios/advanced/web/vue/n8.vue
<template>
  <div class="data-table-container">
    <div class="table-header">
      <h2>Employee Management System</h2>
      <div class="bulk-actions">
        <button 
          @click="handleBulkAction('export')"
          :disabled="selectedRows.length === 0"
        >
          Export Selected
        </button>
        <button 
          @click="handleBulkAction('delete')"
          :disabled="selectedRows.length === 0"
          class="delete-btn"
        >
          Delete Selected
        </button>
      </div>
    </div>

    <div class="filters">
      <input
        type="text"
        placeholder="Search employees..."
        v-model="filters.search"
      />
      
      <select v-model="filters.department">
        <option value="">All Departments</option>
        <option v-for="dept in departments" :key="dept" :value="dept">{{ dept }}</option>
      </select>

      <select v-model="filters.status">
        <option value="">All Status</option>
        <option value="active">Active</option>
        <option value="inactive">Inactive</option>
      </select>
    </div>

    <div class="table-wrapper">
      <table>
        <thead>
          <tr>
            <th>
              <input
                type="checkbox"
                :checked="selectedRows.length === paginatedEmployees.length && paginatedEmployees.length > 0"
                @change="handleSelectAll"
              />
            </th>
            <th @click="handleSort('name')">
              Name
              <span v-if="sortConfig.key === 'name'">
                {{ sortConfig.direction === 'asc' ? '↑' : '↓' }}
              </span>
            </th>
            <th @click="handleSort('department')">
              Department
              <span v-if="sortConfig.key === 'department'">
                {{ sortConfig.direction === 'asc' ? '↑' : '↓' }}
              </span>
            </th>
            <th @click="handleSort('position')">
              Position
              <span v-if="sortConfig.key === 'position'">
                {{ sortConfig.direction === 'asc' ? '↑' : '↓' }}
              </span>
            </th>
            <th @click="handleSort('salary')">
              Salary
              <span v-if="sortConfig.key === 'salary'">
                {{ sortConfig.direction === 'asc' ? '↑' : '↓' }}
              </span>
            </th>
            <th @click="handleSort('status')">
              Status
              <span v-if="sortConfig.key === 'status'">
                {{ sortConfig.direction === 'asc' ? '↑' : '↓' }}
              </span>
            </th>
            <th @click="handleSort('startDate')">
              Start Date
              <span v-if="sortConfig.key === 'startDate'">
                {{ sortConfig.direction === 'asc' ? '↑' : '↓' }}
              </span>
            </th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <tr 
            v-for="employee in paginatedEmployees" 
            :key="employee.id" 
            :class="{ selected: selectedRows.includes(employee.id) }"
          >
            <td>
              <input
                type="checkbox"
                :checked="selectedRows.includes(employee.id)"
                @change="handleSelectRow(employee.id)"
              />
            </td>
            <td>{{ employee.name }}</td>
            <td>{{ employee.department }}</td>
            <td>{{ employee.position }}</td>
            <td>${{ employee.salary.toLocaleString() }}</td>
            <td>
              <span :class="`status ${employee.status}`">
                {{ employee.status === 'active' ? '●' : '○' }}
              </span>
            </td>
            <td>{{ formatDate(employee.startDate) }}</td>
            <td>
              <button @click="editEmployee(employee.id)">Edit</button>
              <button @click="deleteEmployee(employee.id)">Delete</button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <div class="pagination">
      <button 
        @click="currentPage = Math.max(1, currentPage - 1)"
        :disabled="currentPage === 1"
      >
        Previous
      </button>
      
      <span>
        Page {{ currentPage }} of {{ totalPages }} 
        ({{ filteredAndSortedEmployees.length }} total employees)
      </span>
      
      <button 
        @click="currentPage = Math.min(totalPages, currentPage + 1)"
        :disabled="currentPage === totalPages"
      >
        Next
      </button>
    </div>

    <div v-if="selectedRows.length > 0" class="selection-info">
      {{ selectedRows.length }} employee(s) selected
    </div>
  </div>
</template>

<script>
export default {
  name: 'DataTableComplex',
  data() {
    return {
      employees: [
        { id: 1, name: 'John Doe', department: 'Engineering', position: 'Senior Developer', salary: 95000, status: 'active', startDate: '2022-01-15' },
        { id: 2, name: 'Jane Smith', department: 'Marketing', position: 'Marketing Manager', salary: 78000, status: 'active', startDate: '2021-08-20' },
        { id: 3, name: 'Mike Johnson', department: 'Sales', position: 'Sales Representative', salary: 65000, status: 'inactive', startDate: '2023-03-10' },
        { id: 4, name: 'Sarah Wilson', department: 'HR', position: 'HR Specialist', salary: 72000, status: 'active', startDate: '2022-11-05' },
        { id: 5, name: 'David Brown', department: 'Engineering', position: 'Junior Developer', salary: 68000, status: 'active', startDate: '2023-06-01' },
        { id: 6, name: 'Lisa Davis', department: 'Finance', position: 'Financial Analyst', salary: 82000, status: 'active', startDate: '2021-12-15' },
        { id: 7, name: 'Tom Anderson', department: 'Sales', position: 'Sales Manager', salary: 88000, status: 'active', startDate: '2020-09-30' },
        { id: 8, name: 'Emma Taylor', department: 'Engineering', position: 'DevOps Engineer', salary: 92000, status: 'active', startDate: '2022-04-12' }
      ],
      sortConfig: { key: null, direction: 'asc' },
      filters: {
        department: '',
        status: '',
        search: ''
      },
      selectedRows: [],
      currentPage: 1,
      itemsPerPage: 5
    }
  },
  computed: {
    departments() {
      return [...new Set(this.employees.map(emp => emp.department))];
    },
    filteredAndSortedEmployees() {
      let filtered = this.employees.filter(emp => {
        const matchesDepartment = !this.filters.department || emp.department === this.filters.department;
        const matchesStatus = !this.filters.status || emp.status === this.filters.status;
        const matchesSearch = !this.filters.search || 
          emp.name.toLowerCase().includes(this.filters.search.toLowerCase()) ||
          emp.position.toLowerCase().includes(this.filters.search.toLowerCase());
        
        return matchesDepartment && matchesStatus && matchesSearch;
      });

      if (this.sortConfig.key) {
        filtered.sort((a, b) => {
          if (a[this.sortConfig.key] < b[this.sortConfig.key]) {
            return this.sortConfig.direction === 'asc' ? -1 : 1;
          }
          if (a[this.sortConfig.key] > b[this.sortConfig.key]) {
            return this.sortConfig.direction === 'asc' ? 1 : -1;
          }
          return 0;
        });
      }

      return filtered;
    },
    totalPages() {
      return Math.ceil(this.filteredAndSortedEmployees.length / this.itemsPerPage);
    },
    paginatedEmployees() {
      const startIndex = (this.currentPage - 1) * this.itemsPerPage;
      return this.filteredAndSortedEmployees.slice(startIndex, startIndex + this.itemsPerPage);
    }
  },
  methods: {
    handleSort(key) {
      this.sortConfig = {
        key,
        direction: this.sortConfig.key === key && this.sortConfig.direction === 'asc' ? 'desc' : 'asc'
      };
    },
    handleSelectRow(id) {
      if (this.selectedRows.includes(id)) {
        this.selectedRows = this.selectedRows.filter(rowId => rowId !== id);
      } else {
        this.selectedRows.push(id);
      }
    },
    handleSelectAll() {
      if (this.selectedRows.length === this.paginatedEmployees.length) {
        this.selectedRows = [];
      } else {
        this.selectedRows = this.paginatedEmployees.map(emp => emp.id);
      }
    },
    handleBulkAction(action) {
      if (this.selectedRows.length === 0) return;
      
      switch (action) {
        case 'delete':
          this.employees = this.employees.filter(emp => !this.selectedRows.includes(emp.id));
          this.selectedRows = [];
          break;
        case 'export':
          const selectedEmployees = this.employees.filter(emp => this.selectedRows.includes(emp.id));
          console.log('Exporting:', selectedEmployees);
          break;
      }
    },
    editEmployee(id) {
      console.log('Edit', id);
    },
    deleteEmployee(id) {
      console.log('Delete', id);
    },
    formatDate(dateString) {
      return new Date(dateString).toLocaleDateString();
    }
  }
}
</script>

<style scoped>
.data-table-container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 20px;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}

.table-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
  padding-bottom: 15px;
  border-bottom: 2px solid #e0e0e0;
}

.table-header h2 {
  margin: 0;
  color: #333;
  font-size: 24px;
}

.bulk-actions {
  display: flex;
  gap: 10px;
}

.bulk-actions button {
  padding: 8px 16px;
  border: 1px solid #ddd;
  background: white;
  cursor: pointer;
  border-radius: 4px;
  font-size: 14px;
}

.bulk-actions button:hover:not(:disabled) {
  background: #f5f5f5;
}

.bulk-actions button:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.delete-btn {
  background: #ff4444 !important;
  color: white !important;
  border-color: #ff4444 !important;
}

.delete-btn:hover:not(:disabled) {
  background: #cc3333 !important;
}

.filters {
  display: flex;
  gap: 15px;
  margin-bottom: 20px;
  padding: 15px;
  background: #f8f9fa;
  border-radius: 6px;
}

.filters input,
.filters select {
  padding: 8px 12px;
  border: 1px solid #ddd;
  border-radius: 4px;
  font-size: 14px;
}

.filters input {
  flex: 1;
  min-width: 200px;
}

.table-wrapper {
  overflow-x: auto;
  border: 1px solid #ddd;
  border-radius: 6px;
  margin-bottom: 20px;
}

table {
  width: 100%;
  border-collapse: collapse;
  background: white;
}

thead {
  background: #f8f9fa;
}

th {
  padding: 12px 8px;
  text-align: left;
  font-weight: 600;
  color: #333;
  border-bottom: 2px solid #ddd;
  cursor: pointer;
  user-select: none;
  position: relative;
}

th:hover {
  background: #e9ecef;
}

th span {
  margin-left: 5px;
  font-size: 12px;
  color: #666;
}

td {
  padding: 10px 8px;
  border-bottom: 1px solid #eee;
  vertical-align: middle;
}

tr:hover {
  background: #f8f9fa;
}

tr.selected {
  background: #e3f2fd;
}

tr.selected:hover {
  background: #bbdefb;
}

.status {
  font-size: 16px;
  margin-right: 5px;
}

.status.active {
  color: #4caf50;
}

.status.inactive {
  color: #f44336;
}

td button {
  padding: 4px 8px;
  margin: 0 2px;
  border: 1px solid #ddd;
  background: white;
  cursor: pointer;
  border-radius: 3px;
  font-size: 12px;
}

td button:hover {
  background: #f5f5f5;
}

.pagination {
  display: flex;
  justify-content: center;
  align-items: center;
  gap: 15px;
  margin-bottom: 20px;
}

.pagination button {
  padding: 8px 16px;
  border: 1px solid #ddd;
  background: white;
  cursor: pointer;
  border-radius: 4px;
}

.pagination button:hover:not(:disabled) {
  background: #f5f5f5;
}

.pagination button:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.pagination span {
  color: #666;
  font-size: 14px;
}

.selection-info {
  text-align: center;
  padding: 10px;
  background: #e3f2fd;
  color: #1976d2;
  border-radius: 4px;
  font-weight: 500;
}

@media (max-width: 768px) {
  .table-header {
    flex-direction: column;
    gap: 15px;
    align-items: stretch;
  }
  
  .bulk-actions {
    justify-content: center;
  }
  
  .filters {
    flex-direction: column;
  }
  
  .filters input {
    min-width: auto;
  }
  
  .pagination {
    flex-direction: column;
    gap: 10px;
  }
}
</style>
