// scenarios/moderate/web/nuxt/CustomDropdownNavigation.vue
<template>
  <div class="main-container">
    <div class="main-content">
      <h1>Product Filter</h1>
      <p>Filter products by category using the dropdown below.</p>
      
      <div class="filter-section">
        <label 
          for="category-filter" 
          class="filter-label"
        >
          Filter by Category:
        </label>
        <div class="custom-dropdown" ref="dropdownRef">
          <button
            ref="triggerRef"
            id="category-filter"
            @click="toggleDropdown"
            @keydown="handleKeyDown"
            :aria-expanded="isOpen"
            aria-haspopup="listbox"
            aria-labelledby="category-filter-label"
            :aria-activedescendant="isOpen ? `option-${currentIndex}` : undefined"
            class="dropdown-trigger"
            :class="{ open: isOpen }"
          >
            <span>{{ selectedText }}</span>
            <span class="dropdown-arrow" :class="{ rotated: isOpen }">▼</span>
          </button>
          
          <div
            v-if="isOpen"
            role="listbox"
            aria-labelledby="category-filter-label"
            class="dropdown-menu"
          >
            <div
              v-for="(option, index) in options"
              :key="option.value"
              :ref="el => setOptionRef(el, index)"
              :id="`option-${index}`"
              role="option"
              :aria-selected="selectedValue === option.value"
              :tabindex="index === currentIndex ? 0 : -1"
              @click="selectOption(option.value, option.text, index)"
              @keydown="handleOptionKeyDown($event, option.value, option.text, index)"
              @mouseenter="currentIndex = index"
              class="dropdown-option"
              :class="{ selected: selectedValue === option.value }"
            >
              {{ option.text }}
            </div>
          </div>
        </div>
      </div>
      
      <div class="results-section">
        <h2>Filtered Results</h2>
        <div class="results-grid">
          <div
            v-for="(product, index) in filteredProducts"
            :key="index"
            class="result-card"
          >
            <h3>{{ product.name }}</h3>
            <p>{{ product.category }}</p>
          </div>
        </div>
      </div>
    </div>

    <div class="accessibility-info">
      <h3>Accessibility Issues:</h3>
      <ul>
        <li><strong>Incomplete keyboard navigation:</strong> Arrow keys don't navigate through options</li>
        <li><strong>Missing ARIA attributes:</strong> No aria-activedescendant or proper role attributes</li>
        <li><strong>Focus management:</strong> Focus doesn't move to options when dropdown opens</li>
        <li><strong>Screen reader announcements:</strong> No announcements when selection changes</li>
        <li><strong>Escape key handling:</strong> Escape doesn't close dropdown</li>
        <li><strong>Tab order:</strong> Options are not in proper tab sequence</li>
      </ul>
      
      <h3>How to Fix:</h3>
      <ul>
        <li>Add <code>aria-activedescendant</code> to track focused option</li>
        <li>Implement arrow key navigation (Up/Down)</li>
        <li>Add <code>aria-selected</code> to indicate selected state</li>
        <li>Handle Escape key to close dropdown</li>
        <li>Add <code>aria-live</code> region for selection announcements</li>
        <li>Ensure proper focus management when opening/closing</li>
      </ul>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted, onUnmounted } from 'vue'

// Reactive state
const isOpen = ref(false)
const selectedValue = ref('all')
const selectedText = ref('All Categories')
const currentIndex = ref(0)
const dropdownRef = ref(null)
const triggerRef = ref(null)
const optionsRef = ref([])

// Data
const options = [
  { value: 'all', text: 'All Categories' },
  { value: 'electronics', text: 'Electronics' },
  { value: 'clothing', text: 'Clothing' },
  { value: 'books', text: 'Books' },
  { value: 'home', text: 'Home & Garden' }
]

const products = {
  all: [
    { name: 'iPhone 15', category: 'Electronics' },
    { name: 'MacBook Pro', category: 'Electronics' },
    { name: 'Cotton T-Shirt', category: 'Clothing' },
    { name: 'JavaScript Guide', category: 'Books' },
    { name: 'Garden Tools', category: 'Home & Garden' }
  ],
  electronics: [
    { name: 'iPhone 15', category: 'Electronics' },
    { name: 'MacBook Pro', category: 'Electronics' }
  ],
  clothing: [
    { name: 'Cotton T-Shirt', category: 'Clothing' }
  ],
  books: [
    { name: 'JavaScript Guide', category: 'Books' }
  ],
  home: [
    { name: 'Garden Tools', category: 'Home & Garden' }
  ]
}

// Computed
const filteredProducts = computed(() => {
  return products[selectedValue.value] || []
})

// Methods
const setOptionRef = (el, index) => {
  if (el) {
    optionsRef.value[index] = el
  }
}

const toggleDropdown = () => {
  isOpen.value = !isOpen.value
  if (isOpen.value) {
    // Focus first option when opening
    setTimeout(() => {
      if (optionsRef.value[0]) {
        optionsRef.value[0].focus()
      }
    }, 0)
  }
}

const selectOption = (value, text, index) => {
  selectedValue.value = value
  selectedText.value = text
  currentIndex.value = index
  isOpen.value = false
  // Return focus to trigger
  if (triggerRef.value) {
    triggerRef.value.focus()
  }
}

const handleKeyDown = (event) => {
  if (!isOpen.value) {
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault()
      toggleDropdown()
    }
    return
  }

  switch (event.key) {
    case 'ArrowDown':
      event.preventDefault()
      const nextIndex = currentIndex.value < options.length - 1 ? currentIndex.value + 1 : 0
      currentIndex.value = nextIndex
      if (optionsRef.value[nextIndex]) {
        optionsRef.value[nextIndex].focus()
      }
      break
    case 'ArrowUp':
      event.preventDefault()
      const prevIndex = currentIndex.value > 0 ? currentIndex.value - 1 : options.length - 1
      currentIndex.value = prevIndex
      if (optionsRef.value[prevIndex]) {
        optionsRef.value[prevIndex].focus()
      }
      break
    case 'Enter':
    case ' ':
      event.preventDefault()
      selectOption(options[currentIndex.value].value, options[currentIndex.value].text, currentIndex.value)
      break
    case 'Escape':
      isOpen.value = false
      if (triggerRef.value) {
        triggerRef.value.focus()
      }
      break
  }
}

const handleOptionKeyDown = (event, value, text, index) => {
  if (event.key === 'Enter' || event.key === ' ') {
    event.preventDefault()
    selectOption(value, text, index)
  } else if (event.key === 'Escape') {
    isOpen.value = false
    if (triggerRef.value) {
      triggerRef.value.focus()
    }
  }
}

const handleClickOutside = (event) => {
  if (dropdownRef.value && !dropdownRef.value.contains(event.target)) {
    isOpen.value = false
  }
}

// Lifecycle
onMounted(() => {
  document.addEventListener('mousedown', handleClickOutside)
})

onUnmounted(() => {
  document.removeEventListener('mousedown', handleClickOutside)
})
</script>

<style scoped>
.main-container {
  font-family: Arial, sans-serif;
  max-width: 800px;
  margin: 50px auto;
  padding: 20px;
  background-color: #f5f5f5;
}

.main-content {
  background: white;
  padding: 30px;
  border-radius: 8px;
  box-shadow: 0 2px 10px rgba(0,0,0,0.1);
}

.filter-section {
  margin-bottom: 30px;
}

.filter-label {
  display: block;
  margin-bottom: 10px;
  font-weight: bold;
  color: #333;
}

.custom-dropdown {
  position: relative;
  display: inline-block;
  width: 200px;
}

.dropdown-trigger {
  background-color: #f8f9fa;
  border: 2px solid #ddd;
  border-radius: 4px;
  padding: 12px 16px;
  cursor: pointer;
  display: flex;
  justify-content: space-between;
  align-items: center;
  font-size: 16px;
  width: 100%;
  box-sizing: border-box;
}

.dropdown-trigger:hover {
  border-color: #007bff;
}

.dropdown-trigger:focus {
  outline: none;
  border-color: #007bff;
  box-shadow: 0 0 0 2px rgba(0, 123, 255, 0.25);
}

.dropdown-trigger.open {
  border-color: #007bff;
  border-bottom-left-radius: 0;
  border-bottom-right-radius: 0;
}

.dropdown-arrow {
  transition: transform 0.2s ease;
}

.dropdown-arrow.rotated {
  transform: rotate(180deg);
}

.dropdown-menu {
  position: absolute;
  top: 100%;
  left: 0;
  right: 0;
  background: white;
  border: 2px solid #007bff;
  border-top: none;
  border-radius: 0 0 4px 4px;
  box-shadow: 0 4px 12px rgba(0,0,0,0.15);
  z-index: 1000;
}

.dropdown-option {
  padding: 12px 16px;
  cursor: pointer;
  border-bottom: 1px solid #eee;
  transition: background-color 0.2s ease;
}

.dropdown-option:last-child {
  border-bottom: none;
}

.dropdown-option:hover {
  background-color: #f8f9fa;
}

.dropdown-option.selected {
  background-color: #007bff;
  color: white;
}

.dropdown-option.selected:hover {
  background-color: #0056b3;
}

.results-section {
  margin-top: 30px;
}

.results-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
  gap: 20px;
  margin-top: 20px;
}

.result-card {
  background: white;
  border: 1px solid #ddd;
  border-radius: 8px;
  padding: 20px;
  text-align: center;
  box-shadow: 0 2px 4px rgba(0,0,0,0.1);
}

.result-card h3 {
  margin: 0 0 10px 0;
  color: #333;
}

.result-card p {
  margin: 0;
  color: #666;
}

.accessibility-info {
  margin-top: 30px;
  padding: 20px;
  background-color: #e9ecef;
  border-radius: 4px;
}
</style>

// scenarios/moderate/web/svelte/CustomDropdownNavigation.svelte
<script>
  import { onMount } from 'svelte';
  
  let isOpen = false;
  let selectedValue = 'all';
  let selectedText = 'All Categories';
  let currentIndex = 0;
  let dropdownRef;
  let triggerRef;
  let optionsRef = [];

  const options = [
    { value: 'all', text: 'All Categories' },
    { value: 'electronics', text: 'Electronics' },
    { value: 'clothing', text: 'Clothing' },
    { value: 'books', text: 'Books' },
    { value: 'home', text: 'Home & Garden' }
  ];

  const products = {
    all: [
      { name: 'iPhone 15', category: 'Electronics' },
      { name: 'MacBook Pro', category: 'Electronics' },
      { name: 'Cotton T-Shirt', category: 'Clothing' },
      { name: 'JavaScript Guide', category: 'Books' },
      { name: 'Garden Tools', category: 'Home & Garden' }
    ],
    electronics: [
      { name: 'iPhone 15', category: 'Electronics' },
      { name: 'MacBook Pro', category: 'Electronics' }
    ],
    clothing: [
      { name: 'Cotton T-Shirt', category: 'Clothing' }
    ],
    books: [
      { name: 'JavaScript Guide', category: 'Books' }
    ],
    home: [
      { name: 'Garden Tools', category: 'Home & Garden' }
    ]
  };

  $: filteredProducts = products[selectedValue] || [];

  function toggleDropdown() {
    isOpen = !isOpen;
    if (isOpen) {
      // Focus first option when opening
      setTimeout(() => {
        if (optionsRef[0]) {
          optionsRef[0].focus();
        }
      }, 0);
    }
  }

  function selectOption(value, text, index) {
    selectedValue = value;
    selectedText = text;
    currentIndex = index;
    isOpen = false;
    // Return focus to trigger
    if (triggerRef) {
      triggerRef.focus();
    }
  }

  function handleKeyDown(event) {
    if (!isOpen) {
      if (event.key === 'Enter' || event.key === ' ') {
        event.preventDefault();
        toggleDropdown();
      }
      return;
    }

    switch (event.key) {
      case 'ArrowDown':
        event.preventDefault();
        const nextIndex = currentIndex < options.length - 1 ? currentIndex + 1 : 0;
        currentIndex = nextIndex;
        if (optionsRef[nextIndex]) {
          optionsRef[nextIndex].focus();
        }
        break;
      case 'ArrowUp':
        event.preventDefault();
        const prevIndex = currentIndex > 0 ? currentIndex - 1 : options.length - 1;
        currentIndex = prevIndex;
        if (optionsRef[prevIndex]) {
          optionsRef[prevIndex].focus();
        }
        break;
      case 'Enter':
      case ' ':
        event.preventDefault();
        selectOption(options[currentIndex].value, options[currentIndex].text, currentIndex);
        break;
      case 'Escape':
        isOpen = false;
        if (triggerRef) {
          triggerRef.focus();
        }
        break;
    }
  }

  function handleOptionKeyDown(event, value, text, index) {
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault();
      selectOption(value, text, index);
    } else if (event.key === 'Escape') {
      isOpen = false;
      if (triggerRef) {
        triggerRef.focus();
      }
    }
  }

  function handleClickOutside(event) {
    if (dropdownRef && !dropdownRef.contains(event.target)) {
      isOpen = false;
    }
  }

  onMount(() => {
    document.addEventListener('mousedown', handleClickOutside);
    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  });
</script>

<div class="main-container">
  <div class="main-content">
    <h1>Product Filter</h1>
    <p>Filter products by category using the dropdown below.</p>
    
    <div class="filter-section">
      <label 
        for="category-filter" 
        class="filter-label"
      >
        Filter by Category:
      </label>
      <div class="custom-dropdown" bind:this={dropdownRef}>
        <button
          bind:this={triggerRef}
          id="category-filter"
          on:click={toggleDropdown}
          on:keydown={handleKeyDown}
          aria-expanded={isOpen}
          aria-haspopup="listbox"
          aria-labelledby="category-filter-label"
          aria-activedescendant={isOpen ? `option-${currentIndex}` : undefined}
          class="dropdown-trigger"
          class:open={isOpen}
        >
          <span>{selectedText}</span>
          <span class="dropdown-arrow" class:rotated={isOpen}>▼</span>
        </button>
        
        {#if isOpen}
          <div
            role="listbox"
            aria-labelledby="category-filter-label"
            class="dropdown-menu"
          >
            {#each options as option, index (option.value)}
              <div
                bind:this={optionsRef[index]}
                id="option-{index}"
                role="option"
                aria-selected={selectedValue === option.value}
                tabindex={index === currentIndex ? 0 : -1}
                on:click={() => selectOption(option.value, option.text, index)}
                on:keydown={(e) => handleOptionKeyDown(e, option.value, option.text, index)}
                on:mouseenter={() => currentIndex = index}
                class="dropdown-option"
                class:selected={selectedValue === option.value}
              >
                {option.text}
              </div>
            {/each}
          </div>
        {/if}
      </div>
    </div>
    
    <div class="results-section">
      <h2>Filtered Results</h2>
      <div class="results-grid">
        {#each filteredProducts as product, index (product.name)}
          <div class="result-card">
            <h3>{product.name}</h3>
            <p>{product.category}</p>
          </div>
        {/each}
      </div>
    </div>
  </div>

  <div class="accessibility-info">
    <h3>Accessibility Issues:</h3>
    <ul>
      <li><strong>Incomplete keyboard navigation:</strong> Arrow keys don't navigate through options</li>
      <li><strong>Missing ARIA attributes:</strong> No aria-activedescendant or proper role attributes</li>
      <li><strong>Focus management:</strong> Focus doesn't move to options when dropdown opens</li>
      <li><strong>Screen reader announcements:</strong> No announcements when selection changes</li>
      <li><strong>Escape key handling:</strong> Escape doesn't close dropdown</li>
      <li><strong>Tab order:</strong> Options are not in proper tab sequence</li>
    </ul>
    
    <h3>How to Fix:</h3>
    <ul>
      <li>Add <code>aria-activedescendant</code> to track focused option</li>
      <li>Implement arrow key navigation (Up/Down)</li>
      <li>Add <code>aria-selected</code> to indicate selected state</li>
      <li>Handle Escape key to close dropdown</li>
      <li>Add <code>aria-live</code> region for selection announcements</li>
      <li>Ensure proper focus management when opening/closing</li>
    </ul>
  </div>
</div>

<style>
  .main-container {
    font-family: Arial, sans-serif;
    max-width: 800px;
    margin: 50px auto;
    padding: 20px;
    background-color: #f5f5f5;
  }

  .main-content {
    background: white;
    padding: 30px;
    border-radius: 8px;
    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
  }

  .filter-section {
    margin-bottom: 30px;
  }

  .filter-label {
    display: block;
    margin-bottom: 10px;
    font-weight: bold;
    color: #333;
  }

  .custom-dropdown {
    position: relative;
    display: inline-block;
    width: 200px;
  }

  .dropdown-trigger {
    background-color: #f8f9fa;
    border: 2px solid #ddd;
    border-radius: 4px;
    padding: 12px 16px;
    cursor: pointer;
    display: flex;
    justify-content: space-between;
    align-items: center;
    font-size: 16px;
    width: 100%;
    box-sizing: border-box;
  }

  .dropdown-trigger:hover {
    border-color: #007bff;
  }

  .dropdown-trigger:focus {
    outline: none;
    border-color: #007bff;
    box-shadow: 0 0 0 2px rgba(0, 123, 255, 0.25);
  }

  .dropdown-trigger.open {
    border-color: #007bff;
    border-bottom-left-radius: 0;
    border-bottom-right-radius: 0;
  }

  .dropdown-arrow {
    transition: transform 0.2s ease;
  }

  .dropdown-arrow.rotated {
    transform: rotate(180deg);
  }

  .dropdown-menu {
    position: absolute;
    top: 100%;
    left: 0;
    right: 0;
    background: white;
    border: 2px solid #007bff;
    border-top: none;
    border-radius: 0 0 4px 4px;
    box-shadow: 0 4px 12px rgba(0,0,0,0.15);
    z-index: 1000;
  }

  .dropdown-option {
    padding: 12px 16px;
    cursor: pointer;
    border-bottom: 1px solid #eee;
    transition: background-color 0.2s ease;
  }

  .dropdown-option:last-child {
    border-bottom: none;
  }

  .dropdown-option:hover {
    background-color: #f8f9fa;
  }

  .dropdown-option.selected {
    background-color: #007bff;
    color: white;
  }

  .dropdown-option.selected:hover {
    background-color: #0056b3;
  }

  .results-section {
    margin-top: 30px;
  }

  .results-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
    gap: 20px;
    margin-top: 20px;
  }

  .result-card {
    background: white;
    border: 1px solid #ddd;
    border-radius: 8px;
    padding: 20px;
    text-align: center;
    box-shadow: 0 2px 4px rgba(0,0,0,0.1);
  }

  .result-card h3 {
    margin: 0 0 10px 0;
    color: #333;
  }

  .result-card p {
    margin: 0;
    color: #666;
  }

  .accessibility-info {
    margin-top: 30px;
    padding: 20px;
    background-color: #e9ecef;
    border-radius: 4px;
  }
</style>
