// scenarios/basic/web/nuxt/MissingTableHeader.vue
<template>
  <div class="data-dashboard">
    <header class="dashboard-header">
      <h1>Analytics Dashboard</h1>
      <div class="header-controls">
        <select v-model="selectedPeriod" class="period-select">
          <option value="7d">Last 7 Days</option>
          <option value="30d">Last 30 Days</option>
          <option value="90d">Last 90 Days</option>
          <option value="1y">Last Year</option>
        </select>
        <button class="export-btn">Export Data</button>
      </div>
    </header>

    <div class="dashboard-content">
      <div class="stats-overview">
        <div class="stat-card">
          <div class="stat-icon">👥</div>
          <div class="stat-content">
            <div class="stat-number">{{ stats.totalUsers }}</div>
            <div class="stat-label">Total Users</div>
            <div class="stat-change positive">+12.5%</div>
          </div>
        </div>
        <div class="stat-card">
          <div class="stat-icon">📊</div>
          <div class="stat-content">
            <div class="stat-number">{{ stats.totalRevenue }}</div>
            <div class="stat-label">Revenue</div>
            <div class="stat-change positive">+8.3%</div>
          </div>
        </div>
        <div class="stat-card">
          <div class="stat-icon">🛒</div>
          <div class="stat-content">
            <div class="stat-number">{{ stats.totalOrders }}</div>
            <div class="stat-label">Orders</div>
            <div class="stat-change negative">-2.1%</div>
          </div>
        </div>
        <div class="stat-card">
          <div class="stat-icon">📈</div>
          <div class="stat-content">
            <div class="stat-number">{{ stats.conversionRate }}%</div>
            <div class="stat-label">Conversion Rate</div>
            <div class="stat-change positive">+1.2%</div>
          </div>
        </div>
      </div>

      <div class="data-tables">
        <div class="table-section">
          <h2>User Activity</h2>
          <div class="table-container">
            <table class="data-table">
              <tbody>
                <tr v-for="user in userActivity" :key="user.id" class="table-row">
                  <td class="user-info">
                    <div class="user-avatar">
                      <img :src="user.avatar" :alt="user.name" />
                    </div>
                    <div class="user-details">
                      <div class="user-name">{{ user.name }}</div>
                      <div class="user-email">{{ user.email }}</div>
                    </div>
                  </td>
                  <td class="activity-type">{{ user.activity }}</td>
                  <td class="activity-time">{{ formatTime(user.timestamp) }}</td>
                  <td class="activity-duration">{{ user.duration }}</td>
                  <td class="activity-status">
                    <span class="status-badge" :class="user.status">{{ user.status }}</span>
                  </td>
                  <td class="activity-actions">
                    <button class="action-btn">View</button>
                    <button class="action-btn">Edit</button>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        <div class="table-section">
          <h2>Sales Performance</h2>
          <div class="table-container">
            <table class="data-table">
              <tbody>
                <tr v-for="sale in salesData" :key="sale.id" class="table-row">
                  <td class="sale-id">#{{ sale.id }}</td>
                  <td class="sale-product">
                    <div class="product-info">
                      <img :src="sale.productImage" :alt="sale.productName" class="product-image" />
                      <span class="product-name">{{ sale.productName }}</span>
                    </div>
                  </td>
                  <td class="sale-customer">{{ sale.customer }}</td>
                  <td class="sale-amount">${{ sale.amount }}</td>
                  <td class="sale-quantity">{{ sale.quantity }}</td>
                  <td class="sale-date">{{ formatDate(sale.date) }}</td>
                  <td class="sale-status">
                    <span class="status-badge" :class="sale.status">{{ sale.status }}</span>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        <div class="table-section">
          <h2>Website Traffic</h2>
          <div class="table-container">
            <table class="data-table">
              <tbody>
                <tr v-for="page in trafficData" :key="page.id" class="table-row">
                  <td class="page-url">{{ page.url }}</td>
                  <td class="page-title">{{ page.title }}</td>
                  <td class="page-views">{{ page.views.toLocaleString() }}</td>
                  <td class="page-unique">{{ page.uniqueVisitors.toLocaleString() }}</td>
                  <td class="page-bounce">{{ page.bounceRate }}%</td>
                  <td class="page-time">{{ page.avgTimeOnPage }}</td>
                  <td class="page-source">{{ page.trafficSource }}</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        <div class="table-section">
          <h2>Product Inventory</h2>
          <div class="table-container">
            <table class="data-table">
              <tbody>
                <tr v-for="product in inventoryData" :key="product.id" class="table-row">
                  <td class="product-sku">{{ product.sku }}</td>
                  <td class="product-details">
                    <div class="product-info">
                      <img :src="product.image" :alt="product.name" class="product-image" />
                      <div class="product-text">
                        <div class="product-name">{{ product.name }}</div>
                        <div class="product-category">{{ product.category }}</div>
                      </div>
                    </div>
                  </td>
                  <td class="product-price">${{ product.price }}</td>
                  <td class="product-stock">{{ product.stock }}</td>
                  <td class="product-sold">{{ product.sold }}</td>
                  <td class="product-revenue">${{ product.revenue }}</td>
                  <td class="product-trend">
                    <span class="trend-indicator" :class="product.trend">
                      {{ product.trend === 'up' ? '↗️' : product.trend === 'down' ? '↘️' : '→' }}
                    </span>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        <div class="table-section">
          <h2>Customer Support Tickets</h2>
          <div class="table-container">
            <table class="data-table">
              <tbody>
                <tr v-for="ticket in supportTickets" :key="ticket.id" class="table-row">
                  <td class="ticket-id">#{{ ticket.id }}</td>
                  <td class="ticket-subject">{{ ticket.subject }}</td>
                  <td class="ticket-customer">{{ ticket.customer }}</td>
                  <td class="ticket-priority">
                    <span class="priority-badge" :class="ticket.priority">{{ ticket.priority }}</span>
                  </td>
                  <td class="ticket-assignee">{{ ticket.assignee }}</td>
                  <td class="ticket-created">{{ formatDate(ticket.created) }}</td>
                  <td class="ticket-status">
                    <span class="status-badge" :class="ticket.status">{{ ticket.status }}</span>
                  </td>
                  <td class="ticket-actions">
                    <button class="action-btn">Reply</button>
                    <button class="action-btn">Close</button>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'

const selectedPeriod = ref('30d')

const stats = ref({
  totalUsers: '12,547',
  totalRevenue: '$45,230',
  totalOrders: '3,421',
  conversionRate: '3.2'
})

const userActivity = ref([
  {
    id: 1,
    name: 'John Doe',
    email: 'john.doe@example.com',
    avatar: '/api/placeholder/40/40',
    activity: 'Login',
    timestamp: '2024-01-15T10:30:00Z',
    duration: '2h 15m',
    status: 'active'
  },
  {
    id: 2,
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    avatar: '/api/placeholder/40/40',
    activity: 'Purchase',
    timestamp: '2024-01-15T09:45:00Z',
    duration: '45m',
    status: 'completed'
  },
  {
    id: 3,
    name: 'Mike Johnson',
    email: 'mike.johnson@example.com',
    avatar: '/api/placeholder/40/40',
    activity: 'Profile Update',
    timestamp: '2024-01-15T08:20:00Z',
    duration: '15m',
    status: 'pending'
  },
  {
    id: 4,
    name: 'Sarah Wilson',
    email: 'sarah.wilson@example.com',
    avatar: '/api/placeholder/40/40',
    activity: 'Logout',
    timestamp: '2024-01-15T07:15:00Z',
    duration: '1h 30m',
    status: 'completed'
  }
])

const salesData = ref([
  {
    id: 1001,
    productName: 'Wireless Headphones',
    productImage: '/api/placeholder/50/50',
    customer: 'John Doe',
    amount: 199.99,
    quantity: 1,
    date: '2024-01-15',
    status: 'completed'
  },
  {
    id: 1002,
    productName: 'Smart Watch',
    productImage: '/api/placeholder/50/50',
    customer: 'Jane Smith',
    amount: 299.99,
    quantity: 1,
    date: '2024-01-14',
    status: 'shipped'
  },
  {
    id: 1003,
    productName: 'Laptop Stand',
    productImage: '/api/placeholder/50/50',
    customer: 'Mike Johnson',
    amount: 49.99,
    quantity: 2,
    date: '2024-01-14',
    status: 'processing'
  },
  {
    id: 1004,
    productName: 'USB Cable',
    productImage: '/api/placeholder/50/50',
    customer: 'Sarah Wilson',
    amount: 12.99,
    quantity: 3,
    date: '2024-01-13',
    status: 'completed'
  }
])

const trafficData = ref([
  {
    id: 1,
    url: '/home',
    title: 'Homepage',
    views: 15420,
    uniqueVisitors: 12350,
    bounceRate: 35.2,
    avgTimeOnPage: '2m 30s',
    trafficSource: 'Direct'
  },
  {
    id: 2,
    url: '/products',
    title: 'Products Page',
    views: 8750,
    uniqueVisitors: 7200,
    bounceRate: 42.1,
    avgTimeOnPage: '3m 15s',
    trafficSource: 'Google'
  },
  {
    id: 3,
    url: '/about',
    title: 'About Us',
    views: 3200,
    uniqueVisitors: 2800,
    bounceRate: 28.5,
    avgTimeOnPage: '4m 10s',
    trafficSource: 'Social Media'
  },
  {
    id: 4,
    url: '/contact',
    title: 'Contact Page',
    views: 1800,
    uniqueVisitors: 1650,
    bounceRate: 55.3,
    avgTimeOnPage: '1m 45s',
    trafficSource: 'Email'
  }
])

const inventoryData = ref([
  {
    id: 1,
    sku: 'WH-001',
    name: 'Wireless Headphones',
    category: 'Electronics',
    image: '/api/placeholder/50/50',
    price: 199.99,
    stock: 45,
    sold: 23,
    revenue: 4597.77,
    trend: 'up'
  },
  {
    id: 2,
    sku: 'SW-002',
    name: 'Smart Watch',
    category: 'Electronics',
    image: '/api/placeholder/50/50',
    price: 299.99,
    stock: 12,
    sold: 8,
    revenue: 2399.92,
    trend: 'down'
  },
  {
    id: 3,
    sku: 'LS-003',
    name: 'Laptop Stand',
    category: 'Accessories',
    image: '/api/placeholder/50/50',
    price: 49.99,
    stock: 78,
    sold: 15,
    revenue: 749.85,
    trend: 'stable'
  },
  {
    id: 4,
    sku: 'UC-004',
    name: 'USB Cable',
    category: 'Accessories',
    image: '/api/placeholder/50/50',
    price: 12.99,
    stock: 200,
    sold: 45,
    revenue: 584.55,
    trend: 'up'
  }
])

const supportTickets = ref([
  {
    id: 1001,
    subject: 'Login Issues',
    customer: 'John Doe',
    priority: 'high',
    assignee: 'Support Team',
    created: '2024-01-15',
    status: 'open'
  },
  {
    id: 1002,
    subject: 'Refund Request',
    customer: 'Jane Smith',
    priority: 'medium',
    assignee: 'Sarah Wilson',
    created: '2024-01-14',
    status: 'in-progress'
  },
  {
    id: 1003,
    subject: 'Feature Request',
    customer: 'Mike Johnson',
    priority: 'low',
    assignee: 'Product Team',
    created: '2024-01-13',
    status: 'closed'
  },
  {
    id: 1004,
    subject: 'Billing Question',
    customer: 'Sarah Wilson',
    priority: 'medium',
    assignee: 'Billing Team',
    created: '2024-01-12',
    status: 'resolved'
  }
])

const formatTime = (timestamp) => {
  const date = new Date(timestamp)
  return date.toLocaleTimeString('en-US', {
    hour: '2-digit',
    minute: '2-digit'
  })
}

const formatDate = (dateString) => {
  const date = new Date(dateString)
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric'
  })
}
</script>

<style scoped>
.data-dashboard {
  max-width: 1400px;
  margin: 0 auto;
  padding: 20px;
  font-family: Arial, sans-serif;
}

.dashboard-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 30px;
  padding-bottom: 20px;
  border-bottom: 2px solid #e9ecef;
}

.dashboard-header h1 {
  margin: 0;
  font-size: 32px;
  color: #333;
}

.header-controls {
  display: flex;
  gap: 15px;
  align-items: center;
}

.period-select {
  padding: 8px 12px;
  border: 1px solid #ddd;
  border-radius: 4px;
  background: white;
  cursor: pointer;
}

.export-btn {
  padding: 8px 16px;
  background: #007bff;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-weight: bold;
}

.export-btn:hover {
  background: #0056b3;
}

.stats-overview {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
  gap: 20px;
  margin-bottom: 40px;
}

.stat-card {
  background: white;
  padding: 25px;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0,0,0,0.1);
  display: flex;
  align-items: center;
  gap: 20px;
}

.stat-icon {
  font-size: 32px;
  opacity: 0.7;
}

.stat-content {
  flex: 1;
}

.stat-number {
  font-size: 24px;
  font-weight: bold;
  color: #333;
  margin-bottom: 5px;
}

.stat-label {
  font-size: 14px;
  color: #666;
  margin-bottom: 5px;
}

.stat-change {
  font-size: 12px;
  font-weight: bold;
}

.stat-change.positive {
  color: #28a745;
}

.stat-change.negative {
  color: #dc3545;
}

.data-tables {
  display: flex;
  flex-direction: column;
  gap: 40px;
}

.table-section {
  background: white;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0,0,0,0.1);
  overflow: hidden;
}

.table-section h2 {
  margin: 0;
  padding: 20px 25px;
  background: #f8f9fa;
  border-bottom: 1px solid #e9ecef;
  font-size: 20px;
  color: #333;
}

.table-container {
  overflow-x: auto;
}

.data-table {
  width: 100%;
  border-collapse: collapse;
}

.table-row {
  border-bottom: 1px solid #e9ecef;
  transition: background-color 0.2s ease;
}

.table-row:hover {
  background: #f8f9fa;
}

.table-row:last-child {
  border-bottom: none;
}

.table-row td {
  padding: 15px 20px;
  vertical-align: middle;
}

.user-info {
  display: flex;
  align-items: center;
  gap: 12px;
}

.user-avatar img {
  width: 40px;
  height: 40px;
  border-radius: 50%;
  object-fit: cover;
}

.user-name {
  font-weight: bold;
  color: #333;
  margin-bottom: 2px;
}

.user-email {
  font-size: 12px;
  color: #666;
}

.activity-type,
.activity-time,
.activity-duration {
  color: #666;
  font-size: 14px;
}

.status-badge {
  padding: 4px 8px;
  border-radius: 12px;
  font-size: 11px;
  font-weight: bold;
  text-transform: uppercase;
}

.status-badge.active {
  background: #d4edda;
  color: #155724;
}

.status-badge.completed {
  background: #cce5ff;
  color: #004085;
}

.status-badge.pending {
  background: #fff3cd;
  color: #856404;
}

.status-badge.open {
  background: #f8d7da;
  color: #721c24;
}

.status-badge.in-progress {
  background: #d1ecf1;
  color: #0c5460;
}

.status-badge.closed {
  background: #e2e3e5;
  color: #383d41;
}

.status-badge.resolved {
  background: #d4edda;
  color: #155724;
}

.status-badge.shipped {
  background: #cce5ff;
  color: #004085;
}

.status-badge.processing {
  background: #fff3cd;
  color: #856404;
}

.action-btn {
  padding: 6px 12px;
  background: #f8f9fa;
  border: 1px solid #ddd;
  border-radius: 4px;
  cursor: pointer;
  font-size: 12px;
  font-weight: bold;
  margin-right: 5px;
  transition: all 0.2s ease;
}

.action-btn:hover {
  background: #e9ecef;
  border-color: #007bff;
  color: #007bff;
}

.sale-id {
  font-weight: bold;
  color: #007bff;
}

.product-info {
  display: flex;
  align-items: center;
  gap: 10px;
}

.product-image {
  width: 40px;
  height: 40px;
  object-fit: cover;
  border-radius: 4px;
}

.product-name {
  font-weight: bold;
  color: #333;
}

.product-category {
  font-size: 12px;
  color: #666;
}

.sale-amount {
  font-weight: bold;
  color: #28a745;
}

.page-url {
  font-family: monospace;
  color: #007bff;
  font-size: 12px;
}

.page-title {
  font-weight: bold;
  color: #333;
}

.page-views,
.page-unique {
  font-weight: bold;
  color: #333;
}

.page-bounce {
  color: #666;
}

.page-time {
  color: #666;
  font-size: 12px;
}

.page-source {
  color: #666;
  font-size: 12px;
}

.product-sku {
  font-family: monospace;
  color: #666;
  font-size: 12px;
}

.product-details {
  min-width: 200px;
}

.product-text {
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.product-price {
  font-weight: bold;
  color: #28a745;
}

.product-stock {
  font-weight: bold;
  color: #333;
}

.product-sold {
  color: #666;
}

.product-revenue {
  font-weight: bold;
  color: #007bff;
}

.trend-indicator {
  font-size: 16px;
}

.trend-indicator.up {
  color: #28a745;
}

.trend-indicator.down {
  color: #dc3545;
}

.trend-indicator.stable {
  color: #6c757d;
}

.ticket-id {
  font-weight: bold;
  color: #007bff;
}

.ticket-subject {
  font-weight: bold;
  color: #333;
}

.ticket-customer {
  color: #666;
}

.priority-badge {
  padding: 4px 8px;
  border-radius: 12px;
  font-size: 11px;
  font-weight: bold;
  text-transform: uppercase;
}

.priority-badge.high {
  background: #f8d7da;
  color: #721c24;
}

.priority-badge.medium {
  background: #fff3cd;
  color: #856404;
}

.priority-badge.low {
  background: #d4edda;
  color: #155724;
}

.ticket-assignee {
  color: #666;
  font-size: 12px;
}

.ticket-created {
  color: #666;
  font-size: 12px;
}

@media (max-width: 768px) {
  .dashboard-header {
    flex-direction: column;
    gap: 20px;
    align-items: flex-start;
  }

  .stats-overview {
    grid-template-columns: 1fr;
  }

  .table-container {
    font-size: 12px;
  }

  .table-row td {
    padding: 10px 15px;
  }

  .user-info {
    flex-direction: column;
    align-items: flex-start;
    gap: 5px;
  }

  .product-info {
    flex-direction: column;
    align-items: flex-start;
    gap: 5px;
  }
}
</style>

// scenarios/basic/cross-platform/tauri/MissingTableHeader.svelte
<script>
  import { onMount } from 'svelte';
  
  let employees = [
    { id: 1, name: 'John Doe', department: 'Engineering', salary: 75000, startDate: '2020-01-15' },
    { id: 2, name: 'Jane Smith', department: 'Marketing', salary: 65000, startDate: '2019-03-22' },
    { id: 3, name: 'Mike Johnson', department: 'Sales', salary: 70000, startDate: '2021-06-10' },
    { id: 4, name: 'Sarah Wilson', department: 'Engineering', salary: 80000, startDate: '2018-09-05' },
    { id: 5, name: 'David Brown', department: 'HR', salary: 60000, startDate: '2022-02-14' },
    { id: 6, name: 'Lisa Davis', department: 'Marketing', salary: 68000, startDate: '2020-11-30' },
    { id: 7, name: 'Tom Anderson', department: 'Sales', salary: 72000, startDate: '2019-08-18' },
    { id: 8, name: 'Amy Taylor', department: 'Engineering', salary: 85000, startDate: '2017-12-03' }
  ];
  
  let sortField = 'name';
  let sortDirection = 'asc';
  let filteredEmployees = [...employees];
  
  function sortTable(field) {
    if (sortField === field) {
      sortDirection = sortDirection === 'asc' ? 'desc' : 'asc';
    } else {
      sortField = field;
      sortDirection = 'asc';
    }
    
    filteredEmployees.sort((a, b) => {
      let aVal = a[field];
      let bVal = b[field];
      
      if (typeof aVal === 'string') {
        aVal = aVal.toLowerCase();
        bVal = bVal.toLowerCase();
      }
      
      if (sortDirection === 'asc') {
        return aVal > bVal ? 1 : -1;
      } else {
        return aVal < bVal ? 1 : -1;
      }
    });
  }
  
  function filterByDepartment(department) {
    if (department === 'all') {
      filteredEmployees = [...employees];
    } else {
      filteredEmployees = employees.filter(emp => emp.department === department);
    }
  }
  
  function getDepartments() {
    return [...new Set(employees.map(emp => emp.department))];
  }
  
  function formatSalary(salary) {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 0
    }).format(salary);
  }
  
  function formatDate(dateString) {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric'
    });
  }
</script>

<div class="employee-dashboard">
  <header class="header">
    <div class="header-content">
      <h1 class="logo">Employee Management</h1>
      <div class="header-actions">
        <button class="header-btn" on:click={() => alert('Add Employee clicked')}>
          ➕ Add Employee
        </button>
        <button class="header-btn" on:click={() => alert('Export clicked')}>
          📊 Export
        </button>
      </div>
    </div>
  </header>
  
  <main class="main-content">
    <div class="page-header">
      <h2 class="page-title">Employee Directory</h2>
      <p class="page-subtitle">Manage and view employee information</p>
    </div>
    
    <div class="controls">
      <div class="filter-group">
        <label for="departmentFilter" class="filter-label">Filter by Department:</label>
        <select id="departmentFilter" class="filter-select" on:change={(e) => filterByDepartment(e.target.value)}>
          <option value="all">All Departments</option>
          {#each getDepartments() as dept}
            <option value={dept}>{dept}</option>
          {/each}
        </select>
      </div>
      
      <div class="stats">
        <div class="stat-item">
          <span class="stat-label">Total Employees:</span>
          <span class="stat-value">{filteredEmployees.length}</span>
        </div>
        <div class="stat-item">
          <span class="stat-label">Average Salary:</span>
          <span class="stat-value">
            {formatSalary(filteredEmployees.reduce((sum, emp) => sum + emp.salary, 0) / filteredEmployees.length)}
          </span>
        </div>
      </div>
    </div>
    
    <div class="table-container">
      <!-- MISSING TABLE HEADER - Data table using <td> elements instead of <th> for column headers -->
      <table class="employee-table">
        <thead>
          <tr class="table-row">
            <!-- MISSING TABLE HEADER - Data table using <td> elements instead of <th> for column headers -->
            <td class="table-cell header-cell" on:click={() => sortTable('name')}>
              <div class="header-content">
                <span>Name</span>
                <span class="sort-indicator">
                  {sortField === 'name' ? (sortDirection === 'asc' ? '↑' : '↓') : '↕️'}
                </span>
              </div>
            </td>
            <td class="table-cell header-cell" on:click={() => sortTable('department')}>
              <div class="header-content">
                <span>Department</span>
                <span class="sort-indicator">
                  {sortField === 'department' ? (sortDirection === 'asc' ? '↑' : '↓') : '↕️'}
                </span>
              </div>
            </td>
            <td class="table-cell header-cell" on:click={() => sortTable('salary')}>
              <div class="header-content">
                <span>Salary</span>
                <span class="sort-indicator">
                  {sortField === 'salary' ? (sortDirection === 'asc' ? '↑' : '↓') : '↕️'}
                </span>
              </div>
            </td>
            <td class="table-cell header-cell" on:click={() => sortTable('startDate')}>
              <div class="header-content">
                <span>Start Date</span>
                <span class="sort-indicator">
                  {sortField === 'startDate' ? (sortDirection === 'asc' ? '↑' : '↓') : '↕️'}
                </span>
              </div>
            </td>
            <td class="table-cell header-cell">
              <div class="header-content">
                <span>Actions</span>
                <span class="sort-indicator"></span>
              </div>
            </td>
          </tr>
        </thead>
        <tbody>
          {#each filteredEmployees as employee}
            <tr class="table-row">
              <td class="table-cell">
                <div class="employee-info">
                  <div class="employee-avatar">👤</div>
                  <div class="employee-details">
                    <div class="employee-name">{employee.name}</div>
                    <div class="employee-id">ID: {employee.id}</div>
                  </div>
                </div>
              </td>
              <td class="table-cell">
                <span class="department-badge department-{employee.department.toLowerCase()}">
                  {employee.department}
                </span>
              </td>
              <td class="table-cell">
                <span class="salary-amount">{formatSalary(employee.salary)}</span>
              </td>
              <td class="table-cell">
                <span class="start-date">{formatDate(employee.startDate)}</span>
              </td>
              <td class="table-cell">
                <div class="action-buttons">
                  <button class="action-btn edit" on:click={() => alert(`Edit ${employee.name}`)}>
                    ✏️
                  </button>
                  <button class="action-btn delete" on:click={() => alert(`Delete ${employee.name}`)}>
                    🗑️
                  </button>
                  <button class="action-btn view" on:click={() => alert(`View ${employee.name}`)}>
                    👁️
                  </button>
                </div>
              </td>
            </tr>
          {/each}
        </tbody>
      </table>
    </div>
  </main>
</div>

<style>
  .employee-dashboard {
    min-height: 100vh;
    background: #f8f9fa;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  }
  
  .header {
    background: white;
    border-bottom: 1px solid #ddd;
    padding: 15px 0;
  }
  
  .header-content {
    max-width: 1200px;
    margin: 0 auto;
    padding: 0 20px;
    display: flex;
    justify-content: space-between;
    align-items: center;
  }
  
  .logo {
    font-size: 24px;
    font-weight: bold;
    color: #333;
    margin: 0;
  }
  
  .header-actions {
    display: flex;
    gap: 15px;
  }
  
  .header-btn {
    padding: 8px 16px;
    border: 1px solid #ddd;
    border-radius: 6px;
    background: white;
    color: #333;
    cursor: pointer;
    font-size: 14px;
    transition: all 0.2s;
  }
  
  .header-btn:hover {
    background: #f8f9fa;
  }
  
  .main-content {
    max-width: 1200px;
    margin: 0 auto;
    padding: 30px 20px;
  }
  
  .page-header {
    text-align: center;
    margin-bottom: 30px;
  }
  
  .page-title {
    font-size: 32px;
    font-weight: bold;
    color: #333;
    margin: 0 0 10px 0;
  }
  
  .page-subtitle {
    font-size: 18px;
    color: #666;
    margin: 0;
  }
  
  .controls {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 30px;
    padding: 20px;
    background: white;
    border-radius: 8px;
    box-shadow: 0 2px 8px rgba(0,0,0,0.1);
  }
  
  .filter-group {
    display: flex;
    align-items: center;
    gap: 10px;
  }
  
  .filter-label {
    font-weight: bold;
    color: #333;
  }
  
  .filter-select {
    padding: 8px 12px;
    border: 1px solid #ddd;
    border-radius: 6px;
    background: white;
    color: #333;
    cursor: pointer;
  }
  
  .stats {
    display: flex;
    gap: 30px;
  }
  
  .stat-item {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 5px;
  }
  
  .stat-label {
    font-size: 14px;
    color: #666;
  }
  
  .stat-value {
    font-size: 18px;
    font-weight: bold;
    color: #333;
  }
  
  .table-container {
    background: white;
    border-radius: 8px;
    overflow: hidden;
    box-shadow: 0 2px 8px rgba(0,0,0,0.1);
  }
  
  .employee-table {
    width: 100%;
    border-collapse: collapse;
  }
  
  .table-row {
    border-bottom: 1px solid #eee;
  }
  
  .table-row:hover {
    background: #f8f9fa;
  }
  
  .table-cell {
    padding: 15px;
    text-align: left;
    vertical-align: middle;
  }
  
  .header-cell {
    background: #f8f9fa;
    font-weight: bold;
    color: #333;
    cursor: pointer;
    user-select: none;
  }
  
  .header-cell:hover {
    background: #e9ecef;
  }
  
  .header-content {
    display: flex;
    justify-content: space-between;
    align-items: center;
  }
  
  .sort-indicator {
    font-size: 12px;
    color: #666;
  }
  
  .employee-info {
    display: flex;
    align-items: center;
    gap: 12px;
  }
  
  .employee-avatar {
    width: 40px;
    height: 40px;
    background: #007bff;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    color: white;
    font-size: 18px;
  }
  
  .employee-details {
    display: flex;
    flex-direction: column;
  }
  
  .employee-name {
    font-weight: bold;
    color: #333;
    font-size: 16px;
  }
  
  .employee-id {
    font-size: 12px;
    color: #666;
  }
  
  .department-badge {
    padding: 4px 12px;
    border-radius: 20px;
    font-size: 12px;
    font-weight: bold;
    text-transform: uppercase;
  }
  
  .department-engineering {
    background: #e3f2fd;
    color: #1976d2;
  }
  
  .department-marketing {
    background: #f3e5f5;
    color: #7b1fa2;
  }
  
  .department-sales {
    background: #e8f5e8;
    color: #388e3c;
  }
  
  .department-hr {
    background: #fff3e0;
    color: #f57c00;
  }
  
  .salary-amount {
    font-weight: bold;
    color: #333;
  }
  
  .start-date {
    color: #666;
  }
  
  .action-buttons {
    display: flex;
    gap: 8px;
  }
  
  .action-btn {
    background: none;
    border: 1px solid #ddd;
    border-radius: 4px;
    padding: 6px;
    cursor: pointer;
    font-size: 14px;
    transition: all 0.2s;
  }
  
  .action-btn:hover {
    background: #f8f9fa;
  }
  
  .action-btn.edit:hover {
    background: #e3f2fd;
    border-color: #1976d2;
  }
  
  .action-btn.delete:hover {
    background: #ffebee;
    border-color: #d32f2f;
  }
  
  .action-btn.view:hover {
    background: #e8f5e8;
    border-color: #388e3c;
  }
</style>
