// scenarios/basic/web/nextjs/n1.jsx
import { useState, useEffect } from 'react';

export default function AutoPlayingBackgroundVideo() {
  const [isPlaying, setIsPlaying] = useState(true);
  const [currentSlide, setCurrentSlide] = useState(0);
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [isSearchOpen, setIsSearchOpen] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');
  const [isScrolled, setIsScrolled] = useState(false);

  const slides = [
    {
      id: 1,
      title: 'Revolutionary Technology',
      subtitle: 'Experience the future today',
      description: 'Discover cutting-edge solutions that transform how you work and live',
      videoUrl: '/api/placeholder/1920/1080',
      ctaText: 'Explore Now',
      ctaLink: '/technology'
    },
    {
      id: 2,
      title: 'Innovation at Scale',
      subtitle: 'Building tomorrow\'s world',
      description: 'Join thousands of companies already using our platform',
      videoUrl: '/api/placeholder/1920/1080',
      ctaText: 'Get Started',
      ctaLink: '/get-started'
    },
    {
      id: 3,
      title: 'Global Impact',
      subtitle: 'Making a difference worldwide',
      description: 'See how we\'re changing lives across the globe',
      videoUrl: '/api/placeholder/1920/1080',
      ctaText: 'Learn More',
      ctaLink: '/impact'
    }
  ];

  const navigationItems = [
    { name: 'Products', href: '/products' },
    { name: 'Solutions', href: '/solutions' },
    { name: 'Resources', href: '/resources' },
    { name: 'Company', href: '/company' },
    { name: 'Contact', href: '/contact' }
  ];

  const features = [
    {
      icon: '⚡',
      title: 'Lightning Fast',
      description: 'Optimized for speed and performance'
    },
    {
      icon: '🔒',
      title: 'Secure',
      description: 'Enterprise-grade security features'
    },
    {
      icon: '📱',
      title: 'Mobile Ready',
      description: 'Works seamlessly on all devices'
    },
    {
      icon: '🌍',
      title: 'Global',
      description: 'Available worldwide with local support'
    }
  ];

  useEffect(() => {
    const handleScroll = () => {
      setIsScrolled(window.scrollY > 50);
    };

    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  useEffect(() => {
    const interval = setInterval(() => {
      setCurrentSlide((prev) => (prev + 1) % slides.length);
    }, 5000);

    return () => clearInterval(interval);
  }, [slides.length]);

  const handleVideoToggle = () => {
    setIsPlaying(!isPlaying);
  };

  const handleSlideChange = (index) => {
    setCurrentSlide(index);
  };

  const handleSearch = (e) => {
    e.preventDefault();
    alert(`Searching for: ${searchTerm}`);
  };

  const currentSlideData = slides[currentSlide];

  return (
    <div className="hero-section">
      <header className={`main-header ${isScrolled ? 'scrolled' : ''}`}>
        <div className="header-container">
          <div className="logo">
            <h1>TechVision</h1>
          </div>

          <nav className={`main-nav ${isMenuOpen ? 'open' : ''}`}>
            <ul className="nav-list">
              {navigationItems.map((item, index) => (
                <li key={index} className="nav-item">
                  <a href={item.href} className="nav-link">
                    {item.name}
                  </a>
                </li>
              ))}
            </ul>
          </nav>

          <div className="header-actions">
            <div className={`search-container ${isSearchOpen ? 'open' : ''}`}>
              <form onSubmit={handleSearch} className="search-form">
                <input
                  type="text"
                  placeholder="Search..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="search-input"
                />
                <button type="submit" className="search-btn">
                  🔍
                </button>
              </form>
            </div>

            <button 
              className="menu-toggle"
              onClick={() => setIsMenuOpen(!isMenuOpen)}
            >
              ☰
            </button>
          </div>
        </div>
      </header>

      <div className="hero-content">
        <div className="hero-video-container">
          <video
            className="hero-video"
            autoPlay
            muted
            loop
            playsInline
            poster={currentSlideData.videoUrl}
          >
            <source src={currentSlideData.videoUrl} type="video/mp4" />
          </video>

          <div className="video-overlay">
            <div className="video-controls">
              <button 
                className="play-pause-btn"
                onClick={handleVideoToggle}
              >
                {isPlaying ? '⏸️' : '▶️'}
              </button>
            </div>
          </div>
        </div>

        <div className="hero-text">
          <div className="hero-badge">
            <span className="badge-text">New Release</span>
          </div>

          <h2 className="hero-title">
            {currentSlideData.title}
          </h2>

          <h3 className="hero-subtitle">
            {currentSlideData.subtitle}
          </h3>

          <p className="hero-description">
            {currentSlideData.description}
          </p>

          <div className="hero-actions">
            <a 
              href={currentSlideData.ctaLink} 
              className="cta-button primary"
            >
              {currentSlideData.ctaText}
            </a>
            <a 
              href="/demo" 
              className="cta-button secondary"
            >
              Watch Demo
            </a>
          </div>
        </div>

        <div className="slide-indicators">
          {slides.map((_, index) => (
            <button
              key={index}
              className={`indicator ${index === currentSlide ? 'active' : ''}`}
              onClick={() => handleSlideChange(index)}
            />
          ))}
        </div>
      </div>

      <div className="features-section">
        <div className="features-container">
          <h3 className="features-title">Why Choose Us</h3>
          <div className="features-grid">
            {features.map((feature, index) => (
              <div key={index} className="feature-card">
                <div className="feature-icon">{feature.icon}</div>
                <h4 className="feature-title">{feature.title}</h4>
                <p className="feature-description">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </div>

      <div className="stats-section">
        <div className="stats-container">
          <div className="stat-item">
            <div className="stat-number">10M+</div>
            <div className="stat-label">Active Users</div>
          </div>
          <div className="stat-item">
            <div className="stat-number">99.9%</div>
            <div className="stat-label">Uptime</div>
          </div>
          <div className="stat-item">
            <div className="stat-number">150+</div>
            <div className="stat-label">Countries</div>
          </div>
          <div className="stat-item">
            <div className="stat-number">24/7</div>
            <div className="stat-label">Support</div>
          </div>
        </div>
      </div>

      <footer className="main-footer">
        <div className="footer-container">
          <div className="footer-content">
            <div className="footer-section">
              <h4>Company</h4>
              <ul>
                <li><a href="/about">About Us</a></li>
                <li><a href="/careers">Careers</a></li>
                <li><a href="/press">Press</a></li>
                <li><a href="/blog">Blog</a></li>
              </ul>
            </div>
            <div className="footer-section">
              <h4>Products</h4>
              <ul>
                <li><a href="/features">Features</a></li>
                <li><a href="/pricing">Pricing</a></li>
                <li><a href="/integrations">Integrations</a></li>
                <li><a href="/api">API</a></li>
              </ul>
            </div>
            <div className="footer-section">
              <h4>Support</h4>
              <ul>
                <li><a href="/help">Help Center</a></li>
                <li><a href="/contact">Contact</a></li>
                <li><a href="/status">Status</a></li>
                <li><a href="/community">Community</a></li>
              </ul>
            </div>
            <div className="footer-section">
              <h4>Legal</h4>
              <ul>
                <li><a href="/privacy">Privacy</a></li>
                <li><a href="/terms">Terms</a></li>
                <li><a href="/cookies">Cookies</a></li>
                <li><a href="/security">Security</a></li>
              </ul>
            </div>
          </div>
          <div className="footer-bottom">
            <p>&copy; 2024 TechVision. All rights reserved.</p>
          </div>
        </div>
      </footer>

      <style jsx>{`
        .hero-section {
          position: relative;
          min-height: 100vh;
          overflow: hidden;
        }

        .main-header {
          position: fixed;
          top: 0;
          left: 0;
          right: 0;
          z-index: 1000;
          background: rgba(255, 255, 255, 0.95);
          backdrop-filter: blur(10px);
          transition: all 0.3s ease;
        }

        .main-header.scrolled {
          background: rgba(255, 255, 255, 0.98);
          box-shadow: 0 2px 20px rgba(0,0,0,0.1);
        }

        .header-container {
          max-width: 1200px;
          margin: 0 auto;
          padding: 0 20px;
          display: flex;
          align-items: center;
          justify-content: space-between;
          height: 70px;
        }

        .logo h1 {
          margin: 0;
          font-size: 24px;
          font-weight: bold;
          color: #333;
        }

        .main-nav {
          display: flex;
          align-items: center;
        }

        .nav-list {
          display: flex;
          list-style: none;
          margin: 0;
          padding: 0;
          gap: 30px;
        }

        .nav-link {
          text-decoration: none;
          color: #333;
          font-weight: 500;
          transition: color 0.2s ease;
        }

        .nav-link:hover {
          color: #007bff;
        }

        .header-actions {
          display: flex;
          align-items: center;
          gap: 20px;
        }

        .search-container {
          position: relative;
        }

        .search-form {
          display: flex;
          align-items: center;
        }

        .search-input {
          padding: 8px 12px;
          border: 1px solid #ddd;
          border-radius: 20px;
          width: 200px;
          transition: width 0.3s ease;
        }

        .search-container.open .search-input {
          width: 300px;
        }

        .search-btn {
          background: none;
          border: none;
          cursor: pointer;
          font-size: 16px;
          margin-left: 5px;
        }

        .menu-toggle {
          display: none;
          background: none;
          border: none;
          font-size: 20px;
          cursor: pointer;
        }

        .hero-content {
          position: relative;
          height: 100vh;
          display: flex;
          align-items: center;
          justify-content: center;
        }

        .hero-video-container {
          position: absolute;
          top: 0;
          left: 0;
          width: 100%;
          height: 100%;
          z-index: -1;
        }

        .hero-video {
          width: 100%;
          height: 100%;
          object-fit: cover;
        }

        .video-overlay {
          position: absolute;
          top: 0;
          left: 0;
          width: 100%;
          height: 100%;
          background: linear-gradient(
            45deg,
            rgba(0,0,0,0.7) 0%,
            rgba(0,0,0,0.3) 50%,
            rgba(0,0,0,0.7) 100%
          );
        }

        .video-controls {
          position: absolute;
          bottom: 30px;
          right: 30px;
        }

        .play-pause-btn {
          background: rgba(255, 255, 255, 0.9);
          border: none;
          border-radius: 50%;
          width: 50px;
          height: 50px;
          cursor: pointer;
          font-size: 20px;
          display: flex;
          align-items: center;
          justify-content: center;
        }

        .hero-text {
          text-align: center;
          color: white;
          max-width: 800px;
          padding: 0 20px;
          z-index: 10;
        }

        .hero-badge {
          display: inline-block;
          background: rgba(0, 123, 255, 0.9);
          color: white;
          padding: 8px 16px;
          border-radius: 20px;
          font-size: 14px;
          font-weight: bold;
          margin-bottom: 20px;
        }

        .hero-title {
          font-size: 48px;
          font-weight: bold;
          margin: 0 0 20px 0;
          line-height: 1.2;
        }

        .hero-subtitle {
          font-size: 24px;
          margin: 0 0 20px 0;
          opacity: 0.9;
        }

        .hero-description {
          font-size: 18px;
          margin: 0 0 40px 0;
          opacity: 0.8;
          line-height: 1.6;
        }

        .hero-actions {
          display: flex;
          gap: 20px;
          justify-content: center;
          flex-wrap: wrap;
        }

        .cta-button {
          display: inline-block;
          padding: 15px 30px;
          border-radius: 30px;
          text-decoration: none;
          font-weight: bold;
          font-size: 16px;
          transition: all 0.3s ease;
        }

        .cta-button.primary {
          background: #007bff;
          color: white;
        }

        .cta-button.primary:hover {
          background: #0056b3;
          transform: translateY(-2px);
        }

        .cta-button.secondary {
          background: transparent;
          color: white;
          border: 2px solid white;
        }

        .cta-button.secondary:hover {
          background: white;
          color: #333;
        }

        .slide-indicators {
          position: absolute;
          bottom: 50px;
          left: 50%;
          transform: translateX(-50%);
          display: flex;
          gap: 10px;
        }

        .indicator {
          width: 12px;
          height: 12px;
          border-radius: 50%;
          border: 2px solid white;
          background: transparent;
          cursor: pointer;
          transition: all 0.3s ease;
        }

        .indicator.active {
          background: white;
        }

        .features-section {
          padding: 80px 20px;
          background: #f8f9fa;
        }

        .features-container {
          max-width: 1200px;
          margin: 0 auto;
        }

        .features-title {
          text-align: center;
          font-size: 36px;
          margin-bottom: 60px;
          color: #333;
        }

        .features-grid {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
          gap: 40px;
        }

        .feature-card {
          text-align: center;
          padding: 30px;
          background: white;
          border-radius: 8px;
          box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }

        .feature-icon {
          font-size: 48px;
          margin-bottom: 20px;
        }

        .feature-title {
          font-size: 20px;
          margin-bottom: 15px;
          color: #333;
        }

        .feature-description {
          color: #666;
          line-height: 1.6;
        }

        .stats-section {
          padding: 60px 20px;
          background: #007bff;
          color: white;
        }

        .stats-container {
          max-width: 1200px;
          margin: 0 auto;
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
          gap: 40px;
        }

        .stat-item {
          text-align: center;
        }

        .stat-number {
          font-size: 48px;
          font-weight: bold;
          margin-bottom: 10px;
        }

        .stat-label {
          font-size: 16px;
          opacity: 0.9;
        }

        .main-footer {
          background: #333;
          color: white;
          padding: 60px 20px 20px;
        }

        .footer-container {
          max-width: 1200px;
          margin: 0 auto;
        }

        .footer-content {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
          gap: 40px;
          margin-bottom: 40px;
        }

        .footer-section h4 {
          margin-bottom: 20px;
          color: white;
        }

        .footer-section ul {
          list-style: none;
          padding: 0;
          margin: 0;
        }

        .footer-section li {
          margin-bottom: 10px;
        }

        .footer-section a {
          color: #ccc;
          text-decoration: none;
          transition: color 0.2s ease;
        }

        .footer-section a:hover {
          color: white;
        }

        .footer-bottom {
          text-align: center;
          padding-top: 20px;
          border-top: 1px solid #555;
          color: #ccc;
        }

        @media (max-width: 768px) {
          .main-nav {
            display: none;
          }

          .menu-toggle {
            display: block;
          }

          .hero-title {
            font-size: 36px;
          }

          .hero-subtitle {
            font-size: 20px;
          }

          .hero-actions {
            flex-direction: column;
            align-items: center;
          }

          .cta-button {
            width: 100%;
            max-width: 300px;
          }
        }
      `}</style>
    </div>
  );
}

// scenarios/basic/cross-platform/tauri/n1.svelte
<script>
  import { onMount, onDestroy } from 'svelte';
  
  let currentSlide = 0;
  let slides = [
    {
      id: 1,
      title: 'Welcome to Our Platform',
      description: 'Discover amazing features and services designed to help you succeed.',
      video: 'hero-video.mp4',
      cta: 'Get Started'
    },
    {
      id: 2,
      title: 'Advanced Analytics',
      description: 'Get insights into your data with our powerful analytics dashboard.',
      video: 'analytics-video.mp4',
      cta: 'View Dashboard'
    },
    {
      id: 3,
      title: 'Team Collaboration',
      description: 'Work together seamlessly with our collaboration tools.',
      video: 'team-video.mp4',
      cta: 'Join Team'
    }
  ];
  
  let isPlaying = true;
  let isMuted = true;
  let currentVideo = null;
  
  onMount(() => {
    startSlideshow();
  });
  
  onDestroy(() => {
    if (currentVideo) {
      currentVideo.pause();
    }
  });
  
  function startSlideshow() {
    setInterval(() => {
      currentSlide = (currentSlide + 1) % slides.length;
    }, 5000); // Change slide every 5 seconds
  }
  
  function nextSlide() {
    currentSlide = (currentSlide + 1) % slides.length;
  }
  
  function prevSlide() {
    currentSlide = currentSlide === 0 ? slides.length - 1 : currentSlide - 1;
  }
  
  function goToSlide(index) {
    currentSlide = index;
  }
  
  function togglePlayPause() {
    isPlaying = !isPlaying;
    if (currentVideo) {
      if (isPlaying) {
        currentVideo.play();
      } else {
        currentVideo.pause();
      }
    }
  }
  
  function toggleMute() {
    isMuted = !isMuted;
    if (currentVideo) {
      currentVideo.muted = isMuted;
    }
  }
  
  function handleVideoLoad(event) {
    currentVideo = event.target;
    if (isPlaying) {
      currentVideo.play();
    }
    currentVideo.muted = isMuted;
  }
  
  function handleCTA() {
    alert('CTA clicked!');
  }
</script>

<div class="hero-carousel">
  <div class="carousel-container">
    {#each slides as slide, index}
      <div class="slide {index === currentSlide ? 'active' : ''}">
        <div class="slide-content">
          <!-- AUTOPLAYING BACKGROUND VIDEO - Hero section video autoplays without user control -->
          <video 
            class="background-video" 
            autoplay 
            muted 
            loop 
            playsinline
            on:loadeddata={handleVideoLoad}
          >
            <source src={slide.video} type="video/mp4" />
            Your browser does not support the video tag.
          </video>
          
          <div class="video-overlay"></div>
          
          <div class="slide-text">
            <h2 class="slide-title">{slide.title}</h2>
            <p class="slide-description">{slide.description}</p>
            <button class="slide-cta" on:click={handleCTA}>
              {slide.cta}
            </button>
          </div>
        </div>
      </div>
    {/each}
  </div>
  
  <div class="carousel-controls">
    <button class="control-btn prev" on:click={prevSlide}>
      ◀️
    </button>
    
    <div class="slide-indicators">
      {#each slides as _, index}
        <button 
          class="indicator {index === currentSlide ? 'active' : ''}" 
          on:click={() => goToSlide(index)}
        >
          {index + 1}
        </button>
      {/each}
    </div>
    
    <button class="control-btn next" on:click={nextSlide}>
      ▶️
    </button>
  </div>
  
  <div class="video-controls">
    <button class="video-control-btn" on:click={togglePlayPause}>
      {isPlaying ? '⏸️' : '▶️'}
    </button>
    <button class="video-control-btn" on:click={toggleMute}>
      {isMuted ? '🔇' : '🔊'}
    </button>
  </div>
</div>

<div class="content-section">
  <div class="container">
    <h2 class="section-title">Why Choose Our Platform?</h2>
    <div class="features-grid">
      <div class="feature-card">
        <div class="feature-icon">🚀</div>
        <h3 class="feature-title">Fast Performance</h3>
        <p class="feature-description">
          Our platform delivers lightning-fast performance for all users with optimized code and infrastructure.
        </p>
      </div>
      
      <div class="feature-card">
        <div class="feature-icon">🔒</div>
        <h3 class="feature-title">Secure & Reliable</h3>
        <p class="feature-description">
          Enterprise-grade security with 99.9% uptime guarantee and advanced encryption.
        </p>
      </div>
      
      <div class="feature-card">
        <div class="feature-icon">📱</div>
        <h3 class="feature-title">Mobile Ready</h3>
        <p class="feature-description">
          Fully responsive design that works perfectly on all devices and screen sizes.
        </p>
      </div>
      
      <div class="feature-card">
        <div class="feature-icon">🎯</div>
        <h3 class="feature-title">Easy to Use</h3>
        <p class="feature-description">
          Intuitive interface designed for users of all skill levels with comprehensive documentation.
        </p>
      </div>
    </div>
  </div>
</div>

<div class="testimonial-section">
  <div class="container">
    <h2 class="section-title">What Our Customers Say</h2>
    <div class="testimonials-grid">
      <div class="testimonial-card">
        <div class="testimonial-content">
          <p class="testimonial-text">
            "This platform has completely transformed how we manage our projects. The interface is intuitive and the performance is outstanding."
          </p>
          <div class="testimonial-author">
            <div class="author-avatar">👤</div>
            <div class="author-info">
              <div class="author-name">Sarah Johnson</div>
              <div class="author-title">Project Manager</div>
            </div>
          </div>
        </div>
      </div>
      
      <div class="testimonial-card">
        <div class="testimonial-content">
          <p class="testimonial-text">
            "The analytics dashboard provides insights we never had before. It's been a game-changer for our business."
          </p>
          <div class="testimonial-author">
            <div class="author-avatar">👤</div>
            <div class="author-info">
              <div class="author-name">Mike Chen</div>
              <div class="author-title">Data Analyst</div>
            </div>
          </div>
        </div>
      </div>
      
      <div class="testimonial-card">
        <div class="testimonial-content">
          <p class="testimonial-text">
            "The collaboration features have made our team more productive than ever. Highly recommended!"
          </p>
          <div class="testimonial-author">
            <div class="author-avatar">👤</div>
            <div class="author-info">
              <div class="author-name">Emily Davis</div>
              <div class="author-title">Team Lead</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="cta-section">
  <div class="container">
    <div class="cta-content">
      <h2 class="cta-title">Ready to Get Started?</h2>
      <p class="cta-description">
        Join thousands of satisfied customers and experience the power of our platform.
      </p>
      <div class="cta-actions">
        <button class="cta-btn primary" on:click={() => alert('Sign Up clicked')}>
          Sign Up Free
        </button>
        <button class="cta-btn secondary" on:click={() => alert('Learn More clicked')}>
          Learn More
        </button>
      </div>
    </div>
  </div>
</div>

<style>
  .hero-carousel {
    position: relative;
    height: 100vh;
    overflow: hidden;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  }
  
  .carousel-container {
    position: relative;
    width: 100%;
    height: 100%;
  }
  
  .slide {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    opacity: 0;
    transition: opacity 0.5s ease-in-out;
  }
  
  .slide.active {
    opacity: 1;
  }
  
  .slide-content {
    position: relative;
    width: 100%;
    height: 100%;
    display: flex;
    align-items: center;
    justify-content: center;
  }
  
  /* AUTOPLAYING BACKGROUND VIDEO - Hero section video autoplays without user control */
  .background-video {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    object-fit: cover;
    z-index: 1;
  }
  
  .video-overlay {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: rgba(0, 0, 0, 0.4);
    z-index: 2;
  }
  
  .slide-text {
    position: relative;
    z-index: 3;
    text-align: center;
    color: white;
    max-width: 800px;
    padding: 0 20px;
  }
  
  .slide-title {
    font-size: 48px;
    font-weight: bold;
    margin: 0 0 20px 0;
    text-shadow: 2px 2px 4px rgba(0,0,0,0.5);
  }
  
  .slide-description {
    font-size: 24px;
    margin: 0 0 30px 0;
    opacity: 0.9;
    text-shadow: 1px 1px 2px rgba(0,0,0,0.5);
  }
  
  .slide-cta {
    background: white;
    color: #333;
    border: none;
    padding: 15px 30px;
    border-radius: 8px;
    font-size: 18px;
    font-weight: bold;
    cursor: pointer;
    transition: all 0.2s;
  }
  
  .slide-cta:hover {
    background: #f8f9fa;
    transform: translateY(-2px);
  }
  
  .carousel-controls {
    position: absolute;
    bottom: 30px;
    left: 50%;
    transform: translateX(-50%);
    display: flex;
    align-items: center;
    gap: 20px;
    z-index: 4;
  }
  
  .control-btn {
    background: rgba(255, 255, 255, 0.2);
    color: white;
    border: none;
    width: 50px;
    height: 50px;
    border-radius: 50%;
    font-size: 20px;
    cursor: pointer;
    transition: all 0.2s;
    display: flex;
    align-items: center;
    justify-content: center;
  }
  
  .control-btn:hover {
    background: rgba(255, 255, 255, 0.3);
    transform: scale(1.1);
  }
  
  .slide-indicators {
    display: flex;
    gap: 10px;
  }
  
  .indicator {
    background: rgba(255, 255, 255, 0.3);
    color: white;
    border: none;
    width: 40px;
    height: 40px;
    border-radius: 50%;
    font-size: 16px;
    font-weight: bold;
    cursor: pointer;
    transition: all 0.2s;
  }
  
  .indicator.active {
    background: white;
    color: #333;
  }
  
  .indicator:hover {
    background: rgba(255, 255, 255, 0.5);
  }
  
  .video-controls {
    position: absolute;
    top: 30px;
    right: 30px;
    display: flex;
    gap: 10px;
    z-index: 4;
  }
  
  .video-control-btn {
    background: rgba(0, 0, 0, 0.5);
    color: white;
    border: none;
    width: 40px;
    height: 40px;
    border-radius: 50%;
    font-size: 16px;
    cursor: pointer;
    transition: all 0.2s;
    display: flex;
    align-items: center;
    justify-content: center;
  }
  
  .video-control-btn:hover {
    background: rgba(0, 0, 0, 0.7);
  }
  
  .content-section {
    padding: 80px 0;
    background: #f8f9fa;
  }
  
  .container {
    max-width: 1200px;
    margin: 0 auto;
    padding: 0 20px;
  }
  
  .section-title {
    font-size: 32px;
    font-weight: bold;
    color: #333;
    text-align: center;
    margin: 0 0 50px 0;
  }
  
  .features-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
    gap: 30px;
  }
  
  .feature-card {
    background: white;
    border-radius: 12px;
    padding: 30px;
    text-align: center;
    box-shadow: 0 4px 12px rgba(0,0,0,0.1);
    transition: transform 0.2s;
  }
  
  .feature-card:hover {
    transform: translateY(-4px);
  }
  
  .feature-icon {
    font-size: 48px;
    margin-bottom: 20px;
  }
  
  .feature-title {
    font-size: 24px;
    font-weight: bold;
    color: #333;
    margin: 0 0 15px 0;
  }
  
  .feature-description {
    font-size: 16px;
    color: #666;
    line-height: 1.6;
    margin: 0;
  }
  
  .testimonial-section {
    padding: 80px 0;
    background: white;
  }
  
  .testimonials-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
    gap: 30px;
  }
  
  .testimonial-card {
    background: #f8f9fa;
    border-radius: 12px;
    padding: 30px;
    box-shadow: 0 4px 12px rgba(0,0,0,0.1);
  }
  
  .testimonial-content {
    text-align: center;
  }
  
  .testimonial-text {
    font-size: 18px;
    color: #333;
    line-height: 1.6;
    margin: 0 0 20px 0;
    font-style: italic;
  }
  
  .testimonial-author {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 15px;
  }
  
  .author-avatar {
    width: 50px;
    height: 50px;
    background: #007bff;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    color: white;
    font-size: 20px;
  }
  
  .author-name {
    font-weight: bold;
    color: #333;
    font-size: 16px;
  }
  
  .author-title {
    color: #666;
    font-size: 14px;
  }
  
  .cta-section {
    padding: 80px 0;
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    color: white;
  }
  
  .cta-content {
    text-align: center;
    max-width: 600px;
    margin: 0 auto;
  }
  
  .cta-title {
    font-size: 36px;
    font-weight: bold;
    margin: 0 0 20px 0;
  }
  
  .cta-description {
    font-size: 18px;
    margin: 0 0 30px 0;
    opacity: 0.9;
  }
  
  .cta-actions {
    display: flex;
    gap: 20px;
    justify-content: center;
  }
  
  .cta-btn {
    padding: 15px 30px;
    border: none;
    border-radius: 8px;
    font-size: 18px;
    font-weight: bold;
    cursor: pointer;
    transition: all 0.2s;
  }
  
  .cta-btn.primary {
    background: white;
    color: #667eea;
  }
  
  .cta-btn.primary:hover {
    background: #f8f9fa;
    transform: translateY(-2px);
  }
  
  .cta-btn.secondary {
    background: transparent;
    color: white;
    border: 2px solid white;
  }
  
  .cta-btn.secondary:hover {
    background: white;
    color: #667eea;
  }
  
  @media (max-width: 768px) {
    .slide-title {
      font-size: 36px;
    }
    
    .slide-description {
      font-size: 20px;
    }
    
    .cta-actions {
      flex-direction: column;
      align-items: center;
    }
    
    .cta-btn {
      width: 200px;
    }
  }
</style>
