// scenarios/basic/web/vue/n15.vue
<template>
  <div class="file-manager">
    <h1>File Manager</h1>
    <p>Manage your files and documents. Right-click on any file to access additional options.</p>
    
    <div class="stats-section">
      <h2>File Statistics</h2>
      <div class="stats-grid">
        <div class="stat-card">
          <div class="stat-number">{{ files.length }}</div>
          <div class="stat-label">Total Files</div>
        </div>
        <div class="stat-card">
          <div class="stat-number">{{ totalSize }} MB</div>
          <div class="stat-label">Total Size</div>
        </div>
      </div>
    </div>

    <div class="files-container">
      <div class="files-header">
        <h2>Files</h2>
        <p>Right-click on any file to access additional options</p>
      </div>
      
      <div class="files-content">
        <div class="files-list">
          <div 
            v-for="file in files" 
            :key="file.id"
            class="file-item"
            :class="{ 'selected': selectedFile === file.id }"
            @contextmenu="handleContextMenu($event, file.id)"
          >
            <div class="file-icon">{{ getFileIcon(file.type) }}</div>
            
            <div class="file-info">
              <h3>{{ file.name }}</h3>
              <div class="file-details">
                <span>Size: {{ file.size }}</span>
                <span>Modified: {{ file.lastModified }}</span>
                <span class="file-type">{{ file.type.toUpperCase() }}</span>
              </div>
            </div>
            
            <div class="file-actions">
              <button @click="handleAction('View')" class="action-btn view">View</button>
              <button @click="handleAction('Download')" class="action-btn download">Download</button>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Essential delete option only available via right-click -->
    <div v-if="contextMenu.visible" class="context-menu" :style="{ left: contextMenu.x + 'px', top: contextMenu.y + 'px' }">
      <div @click="handleContextAction('Open')" class="context-item">Open</div>
      <div @click="handleContextAction('Download')" class="context-item">Download</div>
      <div @click="handleContextAction('Rename')" class="context-item">Rename</div>
      <div @click="handleContextAction('Move')" class="context-item">Move</div>
      <div @click="handleContextAction('Copy')" class="context-item">Copy</div>
      <div @click="handleContextAction('Delete')" class="context-item delete">Delete</div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'RightClickOnlyMenu',
  data() {
    return {
      files: [
        { id: 1, name: 'Document1.pdf', type: 'pdf', size: '2.3 MB', lastModified: '2024-01-15' },
        { id: 2, name: 'Image1.jpg', type: 'image', size: '1.8 MB', lastModified: '2024-01-14' },
        { id: 3, name: 'Spreadsheet.xlsx', type: 'excel', size: '856 KB', lastModified: '2024-01-13' },
        { id: 4, name: 'Presentation.pptx', type: 'powerpoint', size: '4.2 MB', lastModified: '2024-01-12' },
        { id: 5, name: 'TextFile.txt', type: 'text', size: '12 KB', lastModified: '2024-01-11' }
      ],
      contextMenu: { visible: false, x: 0, y: 0, fileId: null },
      selectedFile: null
    }
  },
  computed: {
    totalSize() {
      return this.files.reduce((total, file) => {
        const size = parseFloat(file.size)
        return total + (isNaN(size) ? 0 : size)
      }, 0).toFixed(1)
    }
  },
  mounted() {
    document.addEventListener('click', this.handleClick)
  },
  beforeDestroy() {
    document.removeEventListener('click', this.handleClick)
  },
  methods: {
    getFileIcon(type) {
      const icons = {
        pdf: '📄',
        image: '🖼️',
        excel: '📊',
        powerpoint: '📈',
        text: '📝'
      }
      return icons[type] || '📄'
    },
    handleContextMenu(e, fileId) {
      e.preventDefault()
      this.contextMenu = {
        visible: true,
        x: e.clientX,
        y: e.clientY,
        fileId: fileId
      }
      this.selectedFile = fileId
    },
    handleClick() {
      this.contextMenu = { visible: false, x: 0, y: 0, fileId: null }
      this.selectedFile = null
    },
    handleAction(action) {
      const file = this.files.find(f => f.id === this.selectedFile)
      alert(`${action} action performed on ${file?.name}`)
    },
    handleContextAction(action) {
      const file = this.files.find(f => f.id === this.contextMenu.fileId)
      alert(`${action} action performed on ${file?.name}`)
      this.contextMenu = { visible: false, x: 0, y: 0, fileId: null }
      this.selectedFile = null
    }
  }
}
</script>

<style scoped>
.file-manager {
  max-width: 1000px;
  margin: 50px auto;
  padding: 20px;
  font-family: Arial, sans-serif;
}

.stats-section {
  background: #f8f9fa;
  padding: 20px;
  border-radius: 8px;
  margin-bottom: 30px;
}

.stats-section h2 {
  margin: 0 0 15px 0;
}

.stats-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 20px;
  margin-top: 15px;
}

.stat-card {
  background: white;
  padding: 15px;
  border-radius: 4px;
  text-align: center;
  border: 1px solid #e0e0e0;
}

.stat-number {
  font-size: 24px;
  font-weight: bold;
  color: #007bff;
  margin-bottom: 5px;
}

.stat-label {
  font-size: 14px;
  color: #666;
}

.files-container {
  background: white;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0,0,0,0.1);
  overflow: hidden;
  border: 1px solid #e0e0e0;
}

.files-header {
  background: #f8f9fa;
  padding: 20px;
  border-bottom: 1px solid #e0e0e0;
}

.files-header h2 {
  margin: 0;
  font-size: 20px;
}

.files-header p {
  margin: 5px 0 0 0;
  color: #666;
  font-size: 14px;
}

.files-content {
  padding: 20px;
}

.files-list {
  display: grid;
  gap: 10px;
}

.file-item {
  display: flex;
  align-items: center;
  padding: 15px;
  border: 1px solid #e0e0e0;
  border-radius: 4px;
  background: #fafafa;
  cursor: pointer;
  transition: background-color 0.2s ease;
}

.file-item.selected {
  background: #e3f2fd;
}

.file-icon {
  font-size: 24px;
  margin-right: 15px;
}

.file-info {
  flex: 1;
}

.file-info h3 {
  margin: 0 0 5px 0;
  font-size: 16px;
  color: #333;
}

.file-details {
  display: flex;
  gap: 20px;
  font-size: 14px;
  color: #666;
}

.file-type {
  color: #007bff;
  font-weight: bold;
}

.file-actions {
  display: flex;
  gap: 10px;
  align-items: center;
}

.action-btn {
  padding: 6px 12px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-size: 12px;
}

.action-btn.view {
  background: #007bff;
  color: white;
}

.action-btn.download {
  background: #6c757d;
  color: white;
}

.context-menu {
  position: fixed;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
  box-shadow: 0 4px 12px rgba(0,0,0,0.15);
  z-index: 1000;
  min-width: 150px;
}

.context-item {
  padding: 10px 15px;
  cursor: pointer;
  border-bottom: 1px solid #eee;
  font-size: 14px;
}

.context-item:hover {
  background: #f8f9fa;
}

.context-item.delete {
  color: #dc3545;
}

.context-item:last-child {
  border-bottom: none;
}
</style>

// scenarios/basic/cross-platform/tauri/n15.svelte
<script>
  import { onMount, onDestroy } from 'svelte';
  
  let files = [
    { id: 1, name: 'document.pdf', type: 'PDF', size: '2.5 MB', modified: '2 hours ago' },
    { id: 2, name: 'spreadsheet.xlsx', type: 'Excel', size: '1.8 MB', modified: '1 day ago' },
    { id: 3, name: 'presentation.pptx', type: 'PowerPoint', size: '3.2 MB', modified: '3 hours ago' },
    { id: 4, name: 'image.jpg', type: 'Image', size: '4.1 MB', modified: '5 hours ago' },
    { id: 5, name: 'video.mp4', type: 'Video', size: '15.7 MB', modified: '1 week ago' },
    { id: 6, name: 'archive.zip', type: 'Archive', size: '8.3 MB', modified: '2 days ago' }
  ];
  
  let contextMenu = {
    visible: false,
    x: 0,
    y: 0,
    fileId: null
  };
  
  function handleContextMenu(event, fileId) {
    event.preventDefault();
    contextMenu = {
      visible: true,
      x: event.clientX,
      y: event.clientY,
      fileId: fileId
    };
  }
  
  function hideContextMenu() {
    contextMenu.visible = false;
  }
  
  function handleContextAction(action) {
    const file = files.find(f => f.id === contextMenu.fileId);
    if (file) {
      alert(`Action: ${action} on file: ${file.name}`);
    }
    hideContextMenu();
  }
  
  function handleFileAction(fileId, action) {
    const file = files.find(f => f.id === fileId);
    if (file) {
      alert(`Action: ${action} on file: ${file.name}`);
    }
  }
  
  function handleKeydown(event) {
    if (event.key === 'Escape' && contextMenu.visible) {
      hideContextMenu();
    }
  }
  
  onMount(() => {
    document.addEventListener('keydown', handleKeydown);
    document.addEventListener('click', hideContextMenu);
  });
  
  onDestroy(() => {
    document.removeEventListener('keydown', handleKeydown);
    document.removeEventListener('click', hideContextMenu);
  });
</script>

<div class="file-manager">
  <header class="header">
    <div class="header-content">
      <h1 class="logo">File Manager</h1>
      <div class="header-actions">
        <button class="header-btn" on:click={() => alert('New Folder clicked')}>
          📁 New Folder
        </button>
        <button class="header-btn" on:click={() => alert('Upload clicked')}>
          📤 Upload
        </button>
        <button class="header-btn" on:click={() => alert('Settings clicked')}>
          ⚙️ Settings
        </button>
      </div>
    </div>
  </header>
  
  <main class="main-content">
    <div class="toolbar">
      <div class="toolbar-group">
        <button class="toolbar-btn" on:click={() => alert('View clicked')}>
          👁️ View
        </button>
        <button class="toolbar-btn" on:click={() => alert('Sort clicked')}>
          ↕️ Sort
        </button>
        <button class="toolbar-btn" on:click={() => alert('Filter clicked')}>
          🔍 Filter
        </button>
      </div>
      
      <div class="toolbar-group">
        <button class="toolbar-btn" on:click={() => alert('Select All clicked')}>
          ☑️ Select All
        </button>
        <button class="toolbar-btn" on:click={() => alert('Deselect clicked')}>
          ☐ Deselect
        </button>
      </div>
    </div>
    
    <div class="files-container">
      <div class="files-grid">
        {#each files as file}
          <div 
            class="file-item" 
            on:contextmenu={(e) => handleContextMenu(e, file.id)}
            on:click={() => handleFileAction(file.id, 'Open')}
          >
            <div class="file-icon">
              {#if file.type === 'PDF'}
                📄
              {:else if file.type === 'Excel'}
                📊
              {:else if file.type === 'PowerPoint'}
                📽️
              {:else if file.type === 'Image'}
                🖼️
              {:else if file.type === 'Video'}
                🎥
              {:else if file.type === 'Archive'}
                📦
              {:else}
                📁
              {/if}
            </div>
            
            <div class="file-info">
              <div class="file-name">{file.name}</div>
              <div class="file-details">
                <span class="file-type">{file.type}</span>
                <span class="file-size">{file.size}</span>
              </div>
              <div class="file-modified">Modified: {file.modified}</div>
            </div>
            
            <div class="file-actions">
              <button 
                class="action-btn" 
                on:click|stopPropagation={() => handleFileAction(file.id, 'View')}
                title="View"
              >
                👁️
              </button>
              <button 
                class="action-btn" 
                on:click|stopPropagation={() => handleFileAction(file.id, 'Download')}
                title="Download"
              >
                📥
              </button>
              <button 
                class="action-btn" 
                on:click|stopPropagation={() => handleFileAction(file.id, 'Share')}
                title="Share"
              >
                📤
              </button>
            </div>
          </div>
        {/each}
      </div>
    </div>
  </main>
  
  <!-- RIGHT-CLICK ONLY MENU - Essential delete option only available via right-click -->
  {#if contextMenu.visible}
    <div 
      class="context-menu" 
      style="left: {contextMenu.x}px; top: {contextMenu.y}px;"
      on:click|stopPropagation
    >
      <div class="context-menu-item" on:click={() => handleContextAction('Open')}>
        <span class="context-icon">👁️</span>
        <span class="context-text">Open</span>
      </div>
      
      <div class="context-menu-item" on:click={() => handleContextAction('Download')}>
        <span class="context-icon">📥</span>
        <span class="context-text">Download</span>
      </div>
      
      <div class="context-menu-item" on:click={() => handleContextAction('Rename')}>
        <span class="context-icon">✏️</span>
        <span class="context-text">Rename</span>
      </div>
      
      <div class="context-menu-item" on:click={() => handleContextAction('Copy')}>
        <span class="context-icon">📋</span>
        <span class="context-text">Copy</span>
      </div>
      
      <div class="context-menu-item" on:click={() => handleContextAction('Move')}>
        <span class="context-icon">📁</span>
        <span class="context-text">Move</span>
      </div>
      
      <div class="context-menu-separator"></div>
      
      <!-- RIGHT-CLICK ONLY MENU - Essential delete option only available via right-click -->
      <div class="context-menu-item danger" on:click={() => handleContextAction('Delete')}>
        <span class="context-icon">🗑️</span>
        <span class="context-text">Delete</span>
      </div>
      
      <div class="context-menu-item" on:click={() => handleContextAction('Properties')}>
        <span class="context-icon">ℹ️</span>
        <span class="context-text">Properties</span>
      </div>
    </div>
  {/if}
  
  <div class="status-bar">
    <div class="status-info">
      <span class="status-item">Ready</span>
      <span class="status-item">Files: {files.length}</span>
    </div>
    <div class="status-actions">
      <button class="status-btn" on:click={() => alert('Refresh clicked')}>
        🔄
      </button>
      <button class="status-btn" on:click={() => alert('Help clicked')}>
        ❓
      </button>
    </div>
  </div>
</div>

<style>
  .file-manager {
    min-height: 100vh;
    background: #f8f9fa;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  }
  
  .header {
    background: white;
    border-bottom: 1px solid #ddd;
    padding: 15px 0;
  }
  
  .header-content {
    max-width: 1200px;
    margin: 0 auto;
    padding: 0 20px;
    display: flex;
    justify-content: space-between;
    align-items: center;
  }
  
  .logo {
    font-size: 24px;
    font-weight: bold;
    color: #333;
    margin: 0;
  }
  
  .header-actions {
    display: flex;
    gap: 15px;
  }
  
  .header-btn {
    padding: 8px 16px;
    border: 1px solid #ddd;
    border-radius: 6px;
    background: white;
    color: #333;
    cursor: pointer;
    font-size: 14px;
    transition: all 0.2s;
  }
  
  .header-btn:hover {
    background: #f8f9fa;
  }
  
  .main-content {
    max-width: 1200px;
    margin: 0 auto;
    padding: 20px;
  }
  
  .toolbar {
    background: white;
    border-radius: 8px;
    padding: 15px 20px;
    margin-bottom: 20px;
    box-shadow: 0 2px 8px rgba(0,0,0,0.1);
    display: flex;
    gap: 20px;
    align-items: center;
  }
  
  .toolbar-group {
    display: flex;
    gap: 10px;
  }
  
  .toolbar-btn {
    padding: 8px 16px;
    border: 1px solid #ddd;
    border-radius: 6px;
    background: white;
    color: #333;
    cursor: pointer;
    font-size: 14px;
    transition: all 0.2s;
  }
  
  .toolbar-btn:hover {
    background: #f8f9fa;
  }
  
  .files-container {
    background: white;
    border-radius: 8px;
    padding: 20px;
    box-shadow: 0 2px 8px rgba(0,0,0,0.1);
  }
  
  .files-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
    gap: 20px;
  }
  
  .file-item {
    background: #f8f9fa;
    border: 1px solid #ddd;
    border-radius: 8px;
    padding: 20px;
    cursor: pointer;
    transition: all 0.2s;
    position: relative;
  }
  
  .file-item:hover {
    background: #e9ecef;
    transform: translateY(-2px);
    box-shadow: 0 4px 12px rgba(0,0,0,0.1);
  }
  
  .file-icon {
    font-size: 48px;
    text-align: center;
    margin-bottom: 15px;
  }
  
  .file-info {
    text-align: center;
    margin-bottom: 15px;
  }
  
  .file-name {
    font-size: 16px;
    font-weight: bold;
    color: #333;
    margin-bottom: 8px;
    word-break: break-word;
  }
  
  .file-details {
    display: flex;
    justify-content: space-between;
    font-size: 12px;
    color: #666;
    margin-bottom: 5px;
  }
  
  .file-modified {
    font-size: 11px;
    color: #999;
  }
  
  .file-actions {
    display: flex;
    gap: 8px;
    justify-content: center;
    opacity: 0;
    transition: opacity 0.2s;
  }
  
  .file-item:hover .file-actions {
    opacity: 1;
  }
  
  .action-btn {
    width: 30px;
    height: 30px;
    border: 1px solid #ddd;
    border-radius: 4px;
    background: white;
    color: #333;
    cursor: pointer;
    font-size: 12px;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: all 0.2s;
  }
  
  .action-btn:hover {
    background: #f8f9fa;
  }
  
  .context-menu {
    position: fixed;
    background: white;
    border: 1px solid #ddd;
    border-radius: 6px;
    box-shadow: 0 4px 12px rgba(0,0,0,0.15);
    padding: 8px 0;
    z-index: 1000;
    min-width: 150px;
  }
  
  .context-menu-item {
    display: flex;
    align-items: center;
    gap: 10px;
    padding: 8px 16px;
    cursor: pointer;
    font-size: 14px;
    color: #333;
    transition: background-color 0.2s;
  }
  
  .context-menu-item:hover {
    background: #f8f9fa;
  }
  
  .context-menu-item.danger {
    color: #dc3545;
  }
  
  .context-menu-item.danger:hover {
    background: #f8d7da;
  }
  
  .context-icon {
    font-size: 16px;
    width: 20px;
    text-align: center;
  }
  
  .context-text {
    flex: 1;
  }
  
  .context-menu-separator {
    height: 1px;
    background: #eee;
    margin: 4px 0;
  }
  
  .status-bar {
    background: #f8f9fa;
    border-top: 1px solid #ddd;
    padding: 10px 20px;
    display: flex;
    justify-content: space-between;
    align-items: center;
    font-size: 14px;
    color: #666;
  }
  
  .status-info {
    display: flex;
    gap: 20px;
  }
  
  .status-item {
    font-weight: bold;
  }
  
  .status-actions {
    display: flex;
    gap: 10px;
  }
  
  .status-btn {
    width: 30px;
    height: 30px;
    border: 1px solid #ddd;
    border-radius: 4px;
    background: white;
    color: #333;
    cursor: pointer;
    font-size: 12px;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: all 0.2s;
  }
  
  .status-btn:hover {
    background: #f8f9fa;
  }
  
  @media (max-width: 768px) {
    .files-grid {
      grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
    }
    
    .toolbar {
      flex-direction: column;
      gap: 10px;
    }
    
    .toolbar-group {
      justify-content: center;
    }
  }
</style>
