// scenarios/basic/web/nextjs/n2.jsx
import { useState } from 'react';

export default function ColorOnlyErrorIndication() {
  const [formData, setFormData] = useState({
    firstName: '',
    lastName: '',
    email: '',
    phone: '',
    password: '',
    confirmPassword: '',
    dateOfBirth: '',
    address: '',
    city: '',
    zipCode: '',
    country: '',
    terms: false,
    newsletter: false
  });

  const [errors, setErrors] = useState({});
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitMessage, setSubmitMessage] = useState('');

  const validateField = (name, value) => {
    const newErrors = { ...errors };

    switch (name) {
      case 'firstName':
        if (!value.trim()) {
          newErrors.firstName = 'First name is required';
        } else if (value.trim().length < 2) {
          newErrors.firstName = 'First name must be at least 2 characters';
        } else {
          delete newErrors.firstName;
        }
        break;

      case 'lastName':
        if (!value.trim()) {
          newErrors.lastName = 'Last name is required';
        } else if (value.trim().length < 2) {
          newErrors.lastName = 'Last name must be at least 2 characters';
        } else {
          delete newErrors.lastName;
        }
        break;

      case 'email':
        if (!value.trim()) {
          newErrors.email = 'Email is required';
        } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)) {
          newErrors.email = 'Please enter a valid email address';
        } else {
          delete newErrors.email;
        }
        break;

      case 'phone':
        if (!value.trim()) {
          newErrors.phone = 'Phone number is required';
        } else if (!/^\(\d{3}\) \d{3}-\d{4}$/.test(value)) {
          newErrors.phone = 'Please enter a valid phone number (e.g., (123) 456-7890)';
        } else {
          delete newErrors.phone;
        }
        break;

      case 'password':
        if (!value) {
          newErrors.password = 'Password is required';
        } else if (value.length < 8) {
          newErrors.password = 'Password must be at least 8 characters';
        } else if (!/(?=.*[a-z])(?=.*[A-Z])(?=.*\d)/.test(value)) {
          newErrors.password = 'Password must contain uppercase, lowercase, and number';
        } else {
          delete newErrors.password;
        }
        break;

      case 'confirmPassword':
        if (!value) {
          newErrors.confirmPassword = 'Please confirm your password';
        } else if (value !== formData.password) {
          newErrors.confirmPassword = 'Passwords do not match';
        } else {
          delete newErrors.confirmPassword;
        }
        break;

      case 'dateOfBirth':
        if (!value) {
          newErrors.dateOfBirth = 'Date of birth is required';
        } else {
          const birthDate = new Date(value);
          const today = new Date();
          const age = today.getFullYear() - birthDate.getFullYear();
          if (age < 18) {
            newErrors.dateOfBirth = 'You must be at least 18 years old';
          } else {
            delete newErrors.dateOfBirth;
          }
        }
        break;

      case 'address':
        if (!value.trim()) {
          newErrors.address = 'Address is required';
        } else if (value.trim().length < 10) {
          newErrors.address = 'Please enter a complete address';
        } else {
          delete newErrors.address;
        }
        break;

      case 'city':
        if (!value.trim()) {
          newErrors.city = 'City is required';
        } else if (value.trim().length < 2) {
          newErrors.city = 'Please enter a valid city name';
        } else {
          delete newErrors.city;
        }
        break;

      case 'zipCode':
        if (!value.trim()) {
          newErrors.zipCode = 'ZIP code is required';
        } else if (!/^\d{5}(-\d{4})?$/.test(value)) {
          newErrors.zipCode = 'Please enter a valid ZIP code';
        } else {
          delete newErrors.zipCode;
        }
        break;

      case 'country':
        if (!value) {
          newErrors.country = 'Please select a country';
        } else {
          delete newErrors.country;
        }
        break;

      case 'terms':
        if (!value) {
          newErrors.terms = 'You must accept the terms and conditions';
        } else {
          delete newErrors.terms;
        }
        break;

      default:
        break;
    }

    setErrors(newErrors);
  };

  const handleInputChange = (e) => {
    const { name, value, type, checked } = e.target;
    const fieldValue = type === 'checkbox' ? checked : value;
    
    setFormData(prev => ({
      ...prev,
      [name]: fieldValue
    }));

    validateField(name, fieldValue);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    const newErrors = {};
    Object.keys(formData).forEach(key => {
      validateField(key, formData[key]);
    });

    if (Object.keys(errors).length > 0) {
      setSubmitMessage('Please fix the errors below before submitting');
      return;
    }

    setIsSubmitting(true);
    setSubmitMessage('');

    try {
      await new Promise(resolve => setTimeout(resolve, 2000));
      setSubmitMessage('Account created successfully! Welcome to our platform.');
      setFormData({
        firstName: '',
        lastName: '',
        email: '',
        phone: '',
        password: '',
        confirmPassword: '',
        dateOfBirth: '',
        address: '',
        city: '',
        zipCode: '',
        country: '',
        terms: false,
        newsletter: false
      });
      setErrors({});
    } catch (error) {
      setSubmitMessage('An error occurred. Please try again.');
    } finally {
      setIsSubmitting(false);
    }
  };

  const hasErrors = Object.keys(errors).length > 0;

  return (
    <div className="registration-form">
      <div className="form-container">
        <header className="form-header">
          <h1>Create Your Account</h1>
          <p>Join thousands of users who trust our platform</p>
        </header>

        <form onSubmit={handleSubmit} className="registration-form-content">
          <div className="form-section">
            <h3>Personal Information</h3>
            
            <div className="form-row">
              <div className="form-group">
                <label htmlFor="firstName" className="form-label">
                  First Name *
                </label>
                <input
                  type="text"
                  id="firstName"
                  name="firstName"
                  value={formData.firstName}
                  onChange={handleInputChange}
                  className={`form-input ${errors.firstName ? 'error' : ''}`}
                  placeholder="Enter your first name"
                />
              </div>

              <div className="form-group">
                <label htmlFor="lastName" className="form-label">
                  Last Name *
                </label>
                <input
                  type="text"
                  id="lastName"
                  name="lastName"
                  value={formData.lastName}
                  onChange={handleInputChange}
                  className={`form-input ${errors.lastName ? 'error' : ''}`}
                  placeholder="Enter your last name"
                />
              </div>
            </div>

            <div className="form-row">
              <div className="form-group">
                <label htmlFor="email" className="form-label">
                  Email Address *
                </label>
                <input
                  type="email"
                  id="email"
                  name="email"
                  value={formData.email}
                  onChange={handleInputChange}
                  className={`form-input ${errors.email ? 'error' : ''}`}
                  placeholder="Enter your email address"
                />
              </div>

              <div className="form-group">
                <label htmlFor="phone" className="form-label">
                  Phone Number *
                </label>
                <input
                  type="tel"
                  id="phone"
                  name="phone"
                  value={formData.phone}
                  onChange={handleInputChange}
                  className={`form-input ${errors.phone ? 'error' : ''}`}
                  placeholder="(123) 456-7890"
                />
              </div>
            </div>

            <div className="form-group">
              <label htmlFor="dateOfBirth" className="form-label">
                Date of Birth *
              </label>
              <input
                type="date"
                id="dateOfBirth"
                name="dateOfBirth"
                value={formData.dateOfBirth}
                onChange={handleInputChange}
                className={`form-input ${errors.dateOfBirth ? 'error' : ''}`}
              />
            </div>
          </div>

          <div className="form-section">
            <h3>Account Security</h3>
            
            <div className="form-row">
              <div className="form-group">
                <label htmlFor="password" className="form-label">
                  Password *
                </label>
                <input
                  type="password"
                  id="password"
                  name="password"
                  value={formData.password}
                  onChange={handleInputChange}
                  className={`form-input ${errors.password ? 'error' : ''}`}
                  placeholder="Create a strong password"
                />
              </div>

              <div className="form-group">
                <label htmlFor="confirmPassword" className="form-label">
                  Confirm Password *
                </label>
                <input
                  type="password"
                  id="confirmPassword"
                  name="confirmPassword"
                  value={formData.confirmPassword}
                  onChange={handleInputChange}
                  className={`form-input ${errors.confirmPassword ? 'error' : ''}`}
                  placeholder="Confirm your password"
                />
              </div>
            </div>
          </div>

          <div className="form-section">
            <h3>Address Information</h3>
            
            <div className="form-group">
              <label htmlFor="address" className="form-label">
                Street Address *
              </label>
              <input
                type="text"
                id="address"
                name="address"
                value={formData.address}
                onChange={handleInputChange}
                className={`form-input ${errors.address ? 'error' : ''}`}
                placeholder="Enter your street address"
              />
            </div>

            <div className="form-row">
              <div className="form-group">
                <label htmlFor="city" className="form-label">
                  City *
                </label>
                <input
                  type="text"
                  id="city"
                  name="city"
                  value={formData.city}
                  onChange={handleInputChange}
                  className={`form-input ${errors.city ? 'error' : ''}`}
                  placeholder="Enter your city"
                />
              </div>

              <div className="form-group">
                <label htmlFor="zipCode" className="form-label">
                  ZIP Code *
                </label>
                <input
                  type="text"
                  id="zipCode"
                  name="zipCode"
                  value={formData.zipCode}
                  onChange={handleInputChange}
                  className={`form-input ${errors.zipCode ? 'error' : ''}`}
                  placeholder="12345"
                />
              </div>
            </div>

            <div className="form-group">
              <label htmlFor="country" className="form-label">
                Country *
              </label>
              <select
                id="country"
                name="country"
                value={formData.country}
                onChange={handleInputChange}
                className={`form-select ${errors.country ? 'error' : ''}`}
              >
                <option value="">Select a country</option>
                <option value="US">United States</option>
                <option value="CA">Canada</option>
                <option value="UK">United Kingdom</option>
                <option value="AU">Australia</option>
                <option value="DE">Germany</option>
                <option value="FR">France</option>
                <option value="JP">Japan</option>
                <option value="other">Other</option>
              </select>
            </div>
          </div>

          <div className="form-section">
            <h3>Preferences</h3>
            
            <div className="checkbox-group">
              <label className="checkbox-label">
                <input
                  type="checkbox"
                  name="terms"
                  checked={formData.terms}
                  onChange={handleInputChange}
                  className={`checkbox-input ${errors.terms ? 'error' : ''}`}
                />
                <span className="checkbox-text">
                  I agree to the <a href="/terms" className="link">Terms and Conditions</a> *
                </span>
              </label>

              <label className="checkbox-label">
                <input
                  type="checkbox"
                  name="newsletter"
                  checked={formData.newsletter}
                  onChange={handleInputChange}
                  className="checkbox-input"
                />
                <span className="checkbox-text">
                  Subscribe to our newsletter for updates and offers
                </span>
              </label>
            </div>
          </div>

          <div className="form-actions">
            <button 
              type="button" 
              className="btn btn-secondary"
              onClick={() => {
                setFormData({
                  firstName: '',
                  lastName: '',
                  email: '',
                  phone: '',
                  password: '',
                  confirmPassword: '',
                  dateOfBirth: '',
                  address: '',
                  city: '',
                  zipCode: '',
                  country: '',
                  terms: false,
                  newsletter: false
                });
                setErrors({});
                setSubmitMessage('');
              }}
            >
              Clear Form
            </button>
            
            <button 
              type="submit" 
              className="btn btn-primary"
              disabled={isSubmitting || hasErrors}
            >
              {isSubmitting ? 'Creating Account...' : 'Create Account'}
            </button>
          </div>

          {submitMessage && (
            <div className={`submit-message ${submitMessage.includes('successfully') ? 'success' : 'error'}`}>
              {submitMessage}
            </div>
          )}
        </form>
      </div>

      <style jsx>{`
        .registration-form {
          min-height: 100vh;
          background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
          padding: 40px 20px;
          display: flex;
          align-items: center;
          justify-content: center;
        }

        .form-container {
          max-width: 800px;
          width: 100%;
          background: white;
          border-radius: 12px;
          box-shadow: 0 20px 40px rgba(0,0,0,0.1);
          overflow: hidden;
        }

        .form-header {
          background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
          color: white;
          padding: 40px;
          text-align: center;
        }

        .form-header h1 {
          margin: 0 0 10px 0;
          font-size: 32px;
          font-weight: bold;
        }

        .form-header p {
          margin: 0;
          font-size: 16px;
          opacity: 0.9;
        }

        .registration-form-content {
          padding: 40px;
        }

        .form-section {
          margin-bottom: 40px;
          padding-bottom: 30px;
          border-bottom: 1px solid #e9ecef;
        }

        .form-section:last-of-type {
          border-bottom: none;
          margin-bottom: 30px;
        }

        .form-section h3 {
          margin: 0 0 20px 0;
          font-size: 20px;
          color: #333;
          font-weight: bold;
        }

        .form-row {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: 20px;
        }

        .form-group {
          display: flex;
          flex-direction: column;
        }

        .form-label {
          margin-bottom: 8px;
          font-weight: bold;
          color: #333;
          font-size: 14px;
        }

        .form-input,
        .form-select {
          padding: 12px 16px;
          border: 2px solid #e9ecef;
          border-radius: 6px;
          font-size: 14px;
          transition: all 0.2s ease;
          background: white;
        }

        .form-input:focus,
        .form-select:focus {
          outline: none;
          border-color: #007bff;
          box-shadow: 0 0 0 3px rgba(0,123,255,0.1);
        }

        .form-input.error,
        .form-select.error {
          border-color: #dc3545;
          background-color: #fff5f5;
        }

        .form-input.error:focus,
        .form-select.error:focus {
          border-color: #dc3545;
          box-shadow: 0 0 0 3px rgba(220,53,69,0.1);
        }

        .checkbox-group {
          display: flex;
          flex-direction: column;
          gap: 15px;
        }

        .checkbox-label {
          display: flex;
          align-items: flex-start;
          gap: 10px;
          cursor: pointer;
        }

        .checkbox-input {
          margin: 0;
          width: 18px;
          height: 18px;
          accent-color: #007bff;
        }

        .checkbox-input.error {
          accent-color: #dc3545;
        }

        .checkbox-text {
          font-size: 14px;
          color: #333;
          line-height: 1.4;
        }

        .link {
          color: #007bff;
          text-decoration: none;
        }

        .link:hover {
          text-decoration: underline;
        }

        .form-actions {
          display: flex;
          gap: 20px;
          justify-content: flex-end;
          margin-top: 40px;
          padding-top: 30px;
          border-top: 1px solid #e9ecef;
        }

        .btn {
          padding: 12px 24px;
          border: none;
          border-radius: 6px;
          font-size: 14px;
          font-weight: bold;
          cursor: pointer;
          transition: all 0.2s ease;
          min-width: 120px;
        }

        .btn:disabled {
          opacity: 0.6;
          cursor: not-allowed;
        }

        .btn-primary {
          background: #007bff;
          color: white;
        }

        .btn-primary:hover:not(:disabled) {
          background: #0056b3;
          transform: translateY(-1px);
        }

        .btn-secondary {
          background: #6c757d;
          color: white;
        }

        .btn-secondary:hover {
          background: #545b62;
          transform: translateY(-1px);
        }

        .submit-message {
          margin-top: 20px;
          padding: 12px 16px;
          border-radius: 6px;
          font-weight: bold;
          text-align: center;
        }

        .submit-message.success {
          background: #d4edda;
          color: #155724;
          border: 1px solid #c3e6cb;
        }

        .submit-message.error {
          background: #f8d7da;
          color: #721c24;
          border: 1px solid #f5c6cb;
        }

        @media (max-width: 768px) {
          .registration-form {
            padding: 20px 10px;
          }

          .form-header {
            padding: 30px 20px;
          }

          .form-header h1 {
            font-size: 24px;
          }

          .registration-form-content {
            padding: 30px 20px;
          }

          .form-row {
            grid-template-columns: 1fr;
            gap: 15px;
          }

          .form-actions {
            flex-direction: column;
          }

          .btn {
            width: 100%;
          }
        }
      `}</style>
    </div>
  );
}

// scenarios/basic/cross-platform/tauri/n2.svelte
<script>
  import { onMount } from 'svelte';
  
  let formData = {
    firstName: '',
    lastName: '',
    email: '',
    password: '',
    confirmPassword: '',
    phone: '',
    address: '',
    city: '',
    zipCode: '',
    country: '',
    terms: false,
    newsletter: false
  };
  
  let errors = {};
  let isSubmitting = false;
  
  function validateForm() {
    errors = {};
    
    if (!formData.firstName.trim()) {
      errors.firstName = 'First name is required';
    }
    
    if (!formData.lastName.trim()) {
      errors.lastName = 'Last name is required';
    }
    
    if (!formData.email.trim()) {
      errors.email = 'Email is required';
    } else if (!isValidEmail(formData.email)) {
      errors.email = 'Please enter a valid email address';
    }
    
    if (!formData.password) {
      errors.password = 'Password is required';
    } else if (formData.password.length < 8) {
      errors.password = 'Password must be at least 8 characters';
    }
    
    if (!formData.confirmPassword) {
      errors.confirmPassword = 'Please confirm your password';
    } else if (formData.password !== formData.confirmPassword) {
      errors.confirmPassword = 'Passwords do not match';
    }
    
    if (!formData.phone.trim()) {
      errors.phone = 'Phone number is required';
    } else if (!isValidPhone(formData.phone)) {
      errors.phone = 'Please enter a valid phone number';
    }
    
    if (!formData.address.trim()) {
      errors.address = 'Address is required';
    }
    
    if (!formData.city.trim()) {
      errors.city = 'City is required';
    }
    
    if (!formData.zipCode.trim()) {
      errors.zipCode = 'ZIP code is required';
    } else if (!isValidZipCode(formData.zipCode)) {
      errors.zipCode = 'Please enter a valid ZIP code';
    }
    
    if (!formData.country) {
      errors.country = 'Country is required';
    }
    
    if (!formData.terms) {
      errors.terms = 'You must accept the terms and conditions';
    }
    
    return Object.keys(errors).length === 0;
  }
  
  function isValidEmail(email) {
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    return emailRegex.test(email);
  }
  
  function isValidPhone(phone) {
    const phoneRegex = /^[\+]?[1-9][\d]{0,15}$/;
    return phoneRegex.test(phone.replace(/[\s\-\(\)]/g, ''));
  }
  
  function isValidZipCode(zipCode) {
    const zipRegex = /^\d{5}(-\d{4})?$/;
    return zipRegex.test(zipCode);
  }
  
  function handleInputChange(field, value) {
    formData[field] = value;
    // Clear error when user starts typing
    if (errors[field]) {
      delete errors[field];
      errors = { ...errors };
    }
  }
  
  function handleSubmit() {
    if (validateForm()) {
      isSubmitting = true;
      // Simulate form submission
      setTimeout(() => {
        isSubmitting = false;
        alert('Account created successfully!');
      }, 2000);
    } else {
      alert('Please fix the errors in the form');
    }
  }
  
  function resetForm() {
    formData = {
      firstName: '',
      lastName: '',
      email: '',
      password: '',
      confirmPassword: '',
      phone: '',
      address: '',
      city: '',
      zipCode: '',
      country: '',
      terms: false,
      newsletter: false
    };
    errors = {};
  }
</script>

<div class="registration-page">
  <header class="header">
    <div class="header-content">
      <h1 class="logo">Create Account</h1>
      <div class="header-actions">
        <button class="header-btn" on:click={() => alert('Login clicked')}>
          🔐 Login
        </button>
        <button class="header-btn" on:click={() => alert('Help clicked')}>
          ❓ Help
        </button>
      </div>
    </div>
  </header>
  
  <main class="main-content">
    <div class="form-container">
      <div class="form-header">
        <h2 class="form-title">Join Our Platform</h2>
        <p class="form-subtitle">Create your account to get started</p>
      </div>
      
      <form class="registration-form" on:submit|preventDefault={handleSubmit}>
        <div class="form-section">
          <h3 class="section-title">Personal Information</h3>
          
          <div class="form-row">
            <div class="form-group">
              <label for="firstName" class="form-label">First Name *</label>
              <!-- COLOR-ONLY ERROR INDICATION - Invalid form field marked only with red border -->
              <input 
                type="text" 
                id="firstName" 
                class="form-input {errors.firstName ? 'error' : ''}" 
                placeholder="Enter your first name"
                value={formData.firstName}
                on:input={(e) => handleInputChange('firstName', e.target.value)}
              />
            </div>
            
            <div class="form-group">
              <label for="lastName" class="form-label">Last Name *</label>
              <!-- COLOR-ONLY ERROR INDICATION - Invalid form field marked only with red border -->
              <input 
                type="text" 
                id="lastName" 
                class="form-input {errors.lastName ? 'error' : ''}" 
                placeholder="Enter your last name"
                value={formData.lastName}
                on:input={(e) => handleInputChange('lastName', e.target.value)}
              />
            </div>
          </div>
          
          <div class="form-group">
            <label for="email" class="form-label">Email Address *</label>
            <!-- COLOR-ONLY ERROR INDICATION - Invalid form field marked only with red border -->
            <input 
              type="email" 
              id="email" 
              class="form-input {errors.email ? 'error' : ''}" 
              placeholder="Enter your email address"
              value={formData.email}
              on:input={(e) => handleInputChange('email', e.target.value)}
            />
          </div>
          
          <div class="form-row">
            <div class="form-group">
              <label for="password" class="form-label">Password *</label>
              <!-- COLOR-ONLY ERROR INDICATION - Invalid form field marked only with red border -->
              <input 
                type="password" 
                id="password" 
                class="form-input {errors.password ? 'error' : ''}" 
                placeholder="Create a password"
                value={formData.password}
                on:input={(e) => handleInputChange('password', e.target.value)}
              />
            </div>
            
            <div class="form-group">
              <label for="confirmPassword" class="form-label">Confirm Password *</label>
              <!-- COLOR-ONLY ERROR INDICATION - Invalid form field marked only with red border -->
              <input 
                type="password" 
                id="confirmPassword" 
                class="form-input {errors.confirmPassword ? 'error' : ''}" 
                placeholder="Confirm your password"
                value={formData.confirmPassword}
                on:input={(e) => handleInputChange('confirmPassword', e.target.value)}
              />
            </div>
          </div>
          
          <div class="form-group">
            <label for="phone" class="form-label">Phone Number *</label>
            <!-- COLOR-ONLY ERROR INDICATION - Invalid form field marked only with red border -->
            <input 
              type="tel" 
              id="phone" 
              class="form-input {errors.phone ? 'error' : ''}" 
              placeholder="Enter your phone number"
              value={formData.phone}
              on:input={(e) => handleInputChange('phone', e.target.value)}
            />
          </div>
        </div>
        
        <div class="form-section">
          <h3 class="section-title">Address Information</h3>
          
          <div class="form-group">
            <label for="address" class="form-label">Street Address *</label>
            <!-- COLOR-ONLY ERROR INDICATION - Invalid form field marked only with red border -->
            <input 
              type="text" 
              id="address" 
              class="form-input {errors.address ? 'error' : ''}" 
              placeholder="Enter your street address"
              value={formData.address}
              on:input={(e) => handleInputChange('address', e.target.value)}
            />
          </div>
          
          <div class="form-row">
            <div class="form-group">
              <label for="city" class="form-label">City *</label>
              <!-- COLOR-ONLY ERROR INDICATION - Invalid form field marked only with red border -->
              <input 
                type="text" 
                id="city" 
                class="form-input {errors.city ? 'error' : ''}" 
                placeholder="Enter your city"
                value={formData.city}
                on:input={(e) => handleInputChange('city', e.target.value)}
              />
            </div>
            
            <div class="form-group">
              <label for="zipCode" class="form-label">ZIP Code *</label>
              <!-- COLOR-ONLY ERROR INDICATION - Invalid form field marked only with red border -->
              <input 
                type="text" 
                id="zipCode" 
                class="form-input {errors.zipCode ? 'error' : ''}" 
                placeholder="Enter your ZIP code"
                value={formData.zipCode}
                on:input={(e) => handleInputChange('zipCode', e.target.value)}
              />
            </div>
          </div>
          
          <div class="form-group">
            <label for="country" class="form-label">Country *</label>
            <!-- COLOR-ONLY ERROR INDICATION - Invalid form field marked only with red border -->
            <select 
              id="country" 
              class="form-select {errors.country ? 'error' : ''}"
              value={formData.country}
              on:change={(e) => handleInputChange('country', e.target.value)}
            >
              <option value="">Select your country</option>
              <option value="US">United States</option>
              <option value="CA">Canada</option>
              <option value="UK">United Kingdom</option>
              <option value="AU">Australia</option>
              <option value="DE">Germany</option>
              <option value="FR">France</option>
              <option value="ES">Spain</option>
              <option value="IT">Italy</option>
              <option value="JP">Japan</option>
              <option value="CN">China</option>
              <option value="IN">India</option>
              <option value="BR">Brazil</option>
              <option value="MX">Mexico</option>
              <option value="other">Other</option>
            </select>
          </div>
        </div>
        
        <div class="form-section">
          <h3 class="section-title">Preferences</h3>
          
          <div class="checkbox-group">
            <label class="checkbox-option {errors.terms ? 'error' : ''}">
              <input 
                type="checkbox" 
                checked={formData.terms}
                on:change={(e) => handleInputChange('terms', e.target.checked)}
              />
              <span class="checkbox-label">
                I agree to the <a href="#" class="link">Terms and Conditions</a> *
              </span>
            </label>
            
            <label class="checkbox-option">
              <input 
                type="checkbox" 
                checked={formData.newsletter}
                on:change={(e) => handleInputChange('newsletter', e.target.checked)}
              />
              <span class="checkbox-label">
                Subscribe to our newsletter for updates and offers
              </span>
            </label>
          </div>
        </div>
        
        <div class="form-actions">
          <button type="button" class="form-btn secondary" on:click={resetForm}>
            Reset Form
          </button>
          <button type="submit" class="form-btn primary" disabled={isSubmitting}>
            {isSubmitting ? 'Creating Account...' : 'Create Account'}
          </button>
        </div>
      </form>
    </div>
  </main>
  
  <footer class="footer">
    <div class="footer-content">
      <div class="footer-section">
        <h4 class="footer-title">About</h4>
        <ul class="footer-links">
          <li><a href="#" class="footer-link">Our Mission</a></li>
          <li><a href="#" class="footer-link">Team</a></li>
          <li><a href="#" class="footer-link">Careers</a></li>
        </ul>
      </div>
      
      <div class="footer-section">
        <h4 class="footer-title">Support</h4>
        <ul class="footer-links">
          <li><a href="#" class="footer-link">Help Center</a></li>
          <li><a href="#" class="footer-link">Contact Us</a></li>
          <li><a href="#" class="footer-link">Documentation</a></li>
        </ul>
      </div>
      
      <div class="footer-section">
        <h4 class="footer-title">Legal</h4>
        <ul class="footer-links">
          <li><a href="#" class="footer-link">Privacy Policy</a></li>
          <li><a href="#" class="footer-link">Terms of Service</a></li>
          <li><a href="#" class="footer-link">Cookie Policy</a></li>
        </ul>
      </div>
    </div>
    
    <div class="footer-bottom">
      <p>&copy; 2024 Company Name. All rights reserved.</p>
    </div>
  </footer>
</div>

<style>
  .registration-page {
    min-height: 100vh;
    background: #f8f9fa;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  }
  
  .header {
    background: white;
    border-bottom: 1px solid #ddd;
    padding: 15px 0;
  }
  
  .header-content {
    max-width: 1200px;
    margin: 0 auto;
    padding: 0 20px;
    display: flex;
    justify-content: space-between;
    align-items: center;
  }
  
  .logo {
    font-size: 24px;
    font-weight: bold;
    color: #333;
    margin: 0;
  }
  
  .header-actions {
    display: flex;
    gap: 15px;
  }
  
  .header-btn {
    padding: 8px 16px;
    border: 1px solid #ddd;
    border-radius: 6px;
    background: white;
    color: #333;
    cursor: pointer;
    font-size: 14px;
    transition: all 0.2s;
  }
  
  .header-btn:hover {
    background: #f8f9fa;
  }
  
  .main-content {
    max-width: 800px;
    margin: 0 auto;
    padding: 30px 20px;
  }
  
  .form-container {
    background: white;
    border-radius: 12px;
    padding: 40px;
    box-shadow: 0 4px 12px rgba(0,0,0,0.1);
  }
  
  .form-header {
    text-align: center;
    margin-bottom: 40px;
  }
  
  .form-title {
    font-size: 32px;
    font-weight: bold;
    color: #333;
    margin: 0 0 10px 0;
  }
  
  .form-subtitle {
    font-size: 18px;
    color: #666;
    margin: 0;
  }
  
  .form-section {
    margin-bottom: 40px;
    padding-bottom: 30px;
    border-bottom: 1px solid #eee;
  }
  
  .form-section:last-child {
    border-bottom: none;
    margin-bottom: 0;
  }
  
  .section-title {
    font-size: 20px;
    font-weight: bold;
    color: #333;
    margin: 0 0 20px 0;
  }
  
  .form-row {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 20px;
  }
  
  .form-group {
    margin-bottom: 25px;
  }
  
  .form-label {
    display: block;
    font-size: 16px;
    font-weight: bold;
    color: #333;
    margin-bottom: 8px;
  }
  
  .form-input,
  .form-select {
    width: 100%;
    padding: 12px;
    border: 2px solid #ddd;
    border-radius: 6px;
    font-size: 16px;
    box-sizing: border-box;
    transition: border-color 0.2s;
  }
  
  .form-input:focus,
  .form-select:focus {
    outline: none;
    border-color: #007bff;
  }
  
  /* COLOR-ONLY ERROR INDICATION - Invalid form field marked only with red border */
  .form-input.error,
  .form-select.error {
    border-color: #dc3545;
  }
  
  .form-input.error:focus,
  .form-select.error:focus {
    border-color: #dc3545;
  }
  
  .checkbox-group {
    display: flex;
    flex-direction: column;
    gap: 15px;
  }
  
  .checkbox-option {
    display: flex;
    align-items: flex-start;
    gap: 10px;
    cursor: pointer;
    padding: 10px;
    border-radius: 6px;
    transition: background-color 0.2s;
  }
  
  .checkbox-option:hover {
    background: #f8f9fa;
  }
  
  /* COLOR-ONLY ERROR INDICATION - Invalid form field marked only with red border */
  .checkbox-option.error {
    border: 2px solid #dc3545;
    border-radius: 6px;
  }
  
  .checkbox-option input[type="checkbox"] {
    width: 20px;
    height: 20px;
    margin: 0;
    margin-top: 2px;
  }
  
  .checkbox-label {
    font-size: 16px;
    color: #333;
    line-height: 1.5;
  }
  
  .link {
    color: #007bff;
    text-decoration: none;
  }
  
  .link:hover {
    text-decoration: underline;
  }
  
  .form-actions {
    display: flex;
    gap: 20px;
    justify-content: center;
    margin-top: 40px;
    padding-top: 30px;
    border-top: 1px solid #eee;
  }
  
  .form-btn {
    padding: 12px 24px;
    border: none;
    border-radius: 6px;
    font-size: 16px;
    font-weight: bold;
    cursor: pointer;
    transition: all 0.2s;
  }
  
  .form-btn:disabled {
    opacity: 0.6;
    cursor: not-allowed;
  }
  
  .form-btn.primary {
    background: #007bff;
    color: white;
  }
  
  .form-btn.primary:hover:not(:disabled) {
    background: #0056b3;
  }
  
  .form-btn.secondary {
    background: #6c757d;
    color: white;
  }
  
  .form-btn.secondary:hover {
    background: #545b62;
  }
  
  .footer {
    background: #333;
    color: white;
    padding: 40px 0 20px 0;
    margin-top: 60px;
  }
  
  .footer-content {
    max-width: 1200px;
    margin: 0 auto;
    padding: 0 20px;
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 40px;
  }
  
  .footer-title {
    font-size: 18px;
    font-weight: bold;
    margin: 0 0 15px 0;
  }
  
  .footer-links {
    list-style: none;
    padding: 0;
    margin: 0;
  }
  
  .footer-links li {
    margin-bottom: 8px;
  }
  
  .footer-link {
    color: #ccc;
    text-decoration: none;
    transition: color 0.2s;
  }
  
  .footer-link:hover {
    color: white;
  }
  
  .footer-bottom {
    border-top: 1px solid #555;
    margin-top: 30px;
    padding-top: 20px;
    text-align: center;
    color: #ccc;
  }
  
  @media (max-width: 768px) {
    .form-container {
      padding: 20px;
    }
    
    .form-title {
      font-size: 24px;
    }
    
    .form-row {
      grid-template-columns: 1fr;
    }
    
    .form-actions {
      flex-direction: column;
    }
  }
</style>
