// scenarios/basic/web/nextjs/n5.jsx
import { useState } from 'react';

export default function GenericLinkText() {
  const [selectedCategory, setSelectedCategory] = useState('all');
  const [searchTerm, setSearchTerm] = useState('');
  const [sortBy, setSortBy] = useState('date');
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 6;

  const categories = [
    { id: 'all', name: 'All Articles' },
    { id: 'technology', name: 'Technology' },
    { id: 'business', name: 'Business' },
    { id: 'lifestyle', name: 'Lifestyle' },
    { id: 'health', name: 'Health' },
    { id: 'education', name: 'Education' }
  ];

  const articles = [
    {
      id: 1,
      title: 'The Future of Artificial Intelligence in Healthcare',
      excerpt: 'Exploring how AI is revolutionizing medical diagnosis and treatment.',
      category: 'technology',
      author: 'Dr. Sarah Johnson',
      publishDate: '2024-01-15',
      readTime: '8 min read',
      image: 'ai-healthcare.jpg',
      views: 1247,
      likes: 89
    },
    {
      id: 2,
      title: 'Sustainable Business Practices for Modern Companies',
      excerpt: 'How companies can implement eco-friendly strategies while maintaining profitability.',
      category: 'business',
      author: 'Michael Chen',
      publishDate: '2024-01-14',
      readTime: '6 min read',
      image: 'sustainable-business.jpg',
      views: 892,
      likes: 67
    },
    {
      id: 3,
      title: 'Mindfulness and Mental Health in the Digital Age',
      excerpt: 'Practical techniques for maintaining mental wellness in our connected world.',
      category: 'lifestyle',
      author: 'Emma Rodriguez',
      publishDate: '2024-01-13',
      readTime: '5 min read',
      image: 'mindfulness.jpg',
      views: 1563,
      likes: 124
    },
    {
      id: 4,
      title: 'Nutrition Science: Debunking Common Myths',
      excerpt: 'Evidence-based insights into healthy eating and nutrition misconceptions.',
      category: 'health',
      author: 'Dr. James Wilson',
      publishDate: '2024-01-12',
      readTime: '7 min read',
      image: 'nutrition-myths.jpg',
      views: 743,
      likes: 56
    },
    {
      id: 5,
      title: 'Online Learning: The New Era of Education',
      excerpt: 'How digital platforms are transforming traditional educational methods.',
      category: 'education',
      author: 'Professor Lisa Kim',
      publishDate: '2024-01-11',
      readTime: '9 min read',
      image: 'online-learning.jpg',
      views: 2105,
      likes: 178
    },
    {
      id: 6,
      title: 'Cybersecurity Best Practices for Small Businesses',
      excerpt: 'Essential security measures every small business should implement.',
      category: 'technology',
      author: 'Alex Thompson',
      publishDate: '2024-01-10',
      readTime: '6 min read',
      image: 'cybersecurity.jpg',
      views: 934,
      likes: 72
    },
    {
      id: 7,
      title: 'The Psychology of Consumer Behavior',
      excerpt: 'Understanding what drives purchasing decisions in the modern marketplace.',
      category: 'business',
      author: 'Dr. Maria Garcia',
      publishDate: '2024-01-09',
      readTime: '8 min read',
      image: 'consumer-psychology.jpg',
      views: 1187,
      likes: 95
    },
    {
      id: 8,
      title: 'Home Workout Routines for Busy Professionals',
      excerpt: 'Effective exercise strategies that fit into a hectic work schedule.',
      category: 'lifestyle',
      author: 'Fitness Coach Tom',
      publishDate: '2024-01-08',
      readTime: '4 min read',
      image: 'home-workouts.jpg',
      views: 1456,
      likes: 103
    }
  ];

  const filteredArticles = articles.filter(article => {
    const matchesCategory = selectedCategory === 'all' || article.category === selectedCategory;
    const matchesSearch = article.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         article.excerpt.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         article.author.toLowerCase().includes(searchTerm.toLowerCase());
    return matchesCategory && matchesSearch;
  });

  const sortedArticles = [...filteredArticles].sort((a, b) => {
    switch(sortBy) {
      case 'views':
        return b.views - a.views;
      case 'likes':
        return b.likes - a.likes;
      case 'title':
        return a.title.localeCompare(b.title);
      case 'date':
      default:
        return new Date(b.publishDate) - new Date(a.publishDate);
    }
  });

  const totalPages = Math.ceil(sortedArticles.length / itemsPerPage);
  const paginatedArticles = sortedArticles.slice(
    (currentPage - 1) * itemsPerPage, 
    currentPage * itemsPerPage
  );

  const getCategoryColor = (category) => {
    const colors = {
      technology: '#007bff',
      business: '#28a745',
      lifestyle: '#ffc107',
      health: '#dc3545',
      education: '#6f42c1'
    };
    return colors[category] || '#6c757d';
  };

  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });
  };

  const handleAction = (action, article) => {
    alert(`${action} action performed on "${article.title}"`);
  };

  const goToPage = (page) => {
    setCurrentPage(page);
  };

  const nextPage = () => {
    if (currentPage < totalPages) {
      setCurrentPage(currentPage + 1);
    }
  };

  const prevPage = () => {
    if (currentPage > 1) {
      setCurrentPage(currentPage - 1);
    }
  };

  return (
    <div className="blog-platform">
      <header className="blog-header">
        <h1>Knowledge Hub</h1>
        <p>Discover insights, trends, and expert perspectives across various topics</p>
      </header>

      <div className="blog-controls">
        <div className="search-section">
          <input 
            type="text" 
            placeholder="Search articles, authors, or topics..." 
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="search-input"
          />
        </div>

        <div className="filter-section">
          <select 
            value={selectedCategory} 
            onChange={(e) => setSelectedCategory(e.target.value)}
            className="category-filter"
          >
            {categories.map(category => (
              <option key={category.id} value={category.id}>
                {category.name}
              </option>
            ))}
          </select>

          <select 
            value={sortBy} 
            onChange={(e) => setSortBy(e.target.value)}
            className="sort-filter"
          >
            <option value="date">Latest First</option>
            <option value="views">Most Viewed</option>
            <option value="likes">Most Liked</option>
            <option value="title">Alphabetical</option>
          </select>
        </div>
      </div>

      <div className="blog-stats">
        <div className="stat-card">
          <div className="stat-number">{articles.length}</div>
          <div className="stat-label">Total Articles</div>
        </div>
        <div className="stat-card">
          <div className="stat-number">{articles.reduce((sum, article) => sum + article.views, 0).toLocaleString()}</div>
          <div className="stat-label">Total Views</div>
        </div>
        <div className="stat-card">
          <div className="stat-number">{articles.reduce((sum, article) => sum + article.likes, 0).toLocaleString()}</div>
          <div className="stat-label">Total Likes</div>
        </div>
        <div className="stat-card">
          <div className="stat-number">{new Set(articles.map(a => a.author)).size}</div>
          <div className="stat-label">Contributors</div>
        </div>
      </div>

      <div className="articles-grid">
        {paginatedArticles.map(article => (
          <article key={article.id} className="article-card">
            <div className="article-image">
              <img src={`/images/${article.image}`} alt="Article image" />
              <div 
                className="category-badge" 
                style={{ backgroundColor: getCategoryColor(article.category) }}
              >
                {article.category}
              </div>
            </div>

            <div className="article-content">
              <h2 className="article-title">{article.title}</h2>
              <p className="article-excerpt">{article.excerpt}</p>
              
              <div className="article-meta">
                <div className="author-info">
                  <span className="author-name">{article.author}</span>
                  <span className="publish-date">{formatDate(article.publishDate)}</span>
                </div>
                <div className="article-stats">
                  <span className="read-time">{article.readTime}</span>
                  <span className="views">👁️ {article.views}</span>
                  <span className="likes">❤️ {article.likes}</span>
                </div>
              </div>

              <div className="article-actions">
                <button 
                  className="action-btn primary" 
                  onClick={() => handleAction('Read More', article)}
                >
                  Read More
                </button>
                <button 
                  className="action-btn secondary" 
                  onClick={() => handleAction('Share', article)}
                >
                  Share
                </button>
                <button 
                  className="action-btn secondary" 
                  onClick={() => handleAction('Bookmark', article)}
                >
                  Bookmark
                </button>
                <button 
                  className="action-btn secondary" 
                  onClick={() => handleAction('Like', article)}
                >
                  Like
                </button>
              </div>
            </div>
          </article>
        ))}
      </div>

      {sortedArticles.length === 0 && (
        <div className="no-results">
          <h3>No articles found</h3>
          <p>Try adjusting your search or filter criteria</p>
        </div>
      )}

      {totalPages > 1 && (
        <div className="pagination">
          <button 
            className="page-btn" 
            onClick={prevPage} 
            disabled={currentPage === 1}
          >
            Previous
          </button>
          
          {Array(totalPages).fill(0).map((_, i) => (
            <button 
              key={i}
              className={`page-btn ${currentPage === i + 1 ? 'active' : ''}`}
              onClick={() => goToPage(i + 1)}
            >
              {i + 1}
            </button>
          ))}
          
          <button 
            className="page-btn" 
            onClick={nextPage} 
            disabled={currentPage === totalPages}
          >
            Next
          </button>
        </div>
      )}

      <div className="newsletter-section">
        <div className="newsletter-content">
          <h3>Stay Updated</h3>
          <p>Get the latest articles delivered to your inbox</p>
          <div className="newsletter-form">
            <input type="email" placeholder="Enter your email address" className="email-input" />
            <button className="subscribe-btn">Subscribe</button>
          </div>
        </div>
      </div>

      <style jsx>{`
        .blog-platform {
          max-width: 1200px;
          margin: 50px auto;
          padding: 20px;
          font-family: Arial, sans-serif;
        }

        .blog-header {
          text-align: center;
          margin-bottom: 40px;
        }

        .blog-header h1 {
          margin: 0 0 10px 0;
          font-size: 36px;
          color: #333;
        }

        .blog-header p {
          margin: 0;
          color: #666;
          font-size: 18px;
        }

        .blog-controls {
          display: flex;
          flex-direction: column;
          gap: 20px;
          margin-bottom: 30px;
          padding: 25px;
          background: #f8f9fa;
          border-radius: 8px;
        }

        .search-section {
          display: flex;
          justify-content: center;
        }

        .search-input {
          width: 100%;
          max-width: 500px;
          padding: 15px 20px;
          border: 2px solid #ddd;
          border-radius: 25px;
          font-size: 16px;
          transition: border-color 0.2s ease;
        }

        .search-input:focus {
          outline: none;
          border-color: #007bff;
        }

        .filter-section {
          display: flex;
          gap: 20px;
          align-items: center;
          justify-content: center;
          flex-wrap: wrap;
        }

        .category-filter,
        .sort-filter {
          padding: 10px 15px;
          border: 2px solid #ddd;
          border-radius: 6px;
          background: white;
          font-size: 14px;
          min-width: 150px;
        }

        .blog-stats {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
          gap: 20px;
          margin-bottom: 40px;
        }

        .stat-card {
          background: white;
          padding: 25px;
          border-radius: 8px;
          text-align: center;
          box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        }

        .stat-number {
          font-size: 28px;
          font-weight: bold;
          color: #007bff;
          margin-bottom: 5px;
        }

        .stat-label {
          font-size: 14px;
          color: #666;
        }

        .articles-grid {
          display: grid;
          grid-template-columns: repeat(auto-fill, minmax(350px, 1fr));
          gap: 30px;
          margin-bottom: 40px;
        }

        .article-card {
          background: white;
          border-radius: 12px;
          box-shadow: 0 4px 12px rgba(0,0,0,0.1);
          overflow: hidden;
          transition: transform 0.2s ease, box-shadow 0.2s ease;
        }

        .article-card:hover {
          transform: translateY(-5px);
          box-shadow: 0 8px 24px rgba(0,0,0,0.15);
        }

        .article-image {
          position: relative;
          height: 200px;
          overflow: hidden;
        }

        .article-image img {
          width: 100%;
          height: 100%;
          object-fit: cover;
        }

        .category-badge {
          position: absolute;
          top: 15px;
          left: 15px;
          color: white;
          padding: 6px 12px;
          border-radius: 20px;
          font-size: 12px;
          font-weight: bold;
          text-transform: uppercase;
        }

        .article-content {
          padding: 25px;
        }

        .article-title {
          margin: 0 0 15px 0;
          font-size: 20px;
          color: #333;
          line-height: 1.3;
        }

        .article-excerpt {
          margin: 0 0 20px 0;
          color: #666;
          line-height: 1.5;
          font-size: 14px;
        }

        .article-meta {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 20px;
          padding-bottom: 15px;
          border-bottom: 1px solid #eee;
        }

        .author-info {
          display: flex;
          flex-direction: column;
          gap: 4px;
        }

        .author-name {
          font-weight: bold;
          color: #333;
          font-size: 14px;
        }

        .publish-date {
          color: #666;
          font-size: 12px;
        }

        .article-stats {
          display: flex;
          gap: 15px;
          font-size: 12px;
          color: #666;
        }

        .article-actions {
          display: flex;
          gap: 10px;
          flex-wrap: wrap;
        }

        .action-btn {
          padding: 8px 16px;
          border: none;
          border-radius: 20px;
          cursor: pointer;
          font-size: 12px;
          font-weight: bold;
          transition: all 0.2s ease;
        }

        .action-btn.primary {
          background: #007bff;
          color: white;
        }

        .action-btn.primary:hover {
          background: #0056b3;
        }

        .action-btn.secondary {
          background: #f8f9fa;
          color: #666;
          border: 1px solid #ddd;
        }

        .action-btn.secondary:hover {
          background: #e9ecef;
          color: #333;
        }

        .no-results {
          text-align: center;
          padding: 60px 20px;
          color: #666;
        }

        .no-results h3 {
          margin: 0 0 10px 0;
          font-size: 24px;
        }

        .pagination {
          display: flex;
          justify-content: center;
          gap: 8px;
          margin: 40px 0;
        }

        .page-btn {
          padding: 10px 16px;
          border: 2px solid #ddd;
          background: white;
          cursor: pointer;
          border-radius: 6px;
          font-weight: bold;
          transition: all 0.2s ease;
        }

        .page-btn:hover:not(:disabled) {
          border-color: #007bff;
          color: #007bff;
        }

        .page-btn.active {
          background: #007bff;
          color: white;
          border-color: #007bff;
        }

        .page-btn:disabled {
          opacity: 0.5;
          cursor: not-allowed;
        }

        .newsletter-section {
          background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
          color: white;
          padding: 40px;
          border-radius: 12px;
          text-align: center;
        }

        .newsletter-content h3 {
          margin: 0 0 10px 0;
          font-size: 28px;
        }

        .newsletter-content p {
          margin: 0 0 25px 0;
          font-size: 16px;
          opacity: 0.9;
        }

        .newsletter-form {
          display: flex;
          gap: 15px;
          max-width: 400px;
          margin: 0 auto;
        }

        .email-input {
          flex: 1;
          padding: 12px 16px;
          border: none;
          border-radius: 25px;
          font-size: 16px;
        }

        .email-input:focus {
          outline: none;
        }

        .subscribe-btn {
          background: white;
          color: #667eea;
          border: none;
          padding: 12px 24px;
          border-radius: 25px;
          font-weight: bold;
          cursor: pointer;
          transition: background-color 0.2s ease;
        }

        .subscribe-btn:hover {
          background: #f8f9fa;
        }
      `}</style>
    </div>
  );
}

// scenarios/basic/cross-platform/tauri/n5.svelte
<script>
  import { onMount } from 'svelte';
  
  let articles = [
    {
      id: 1,
      title: 'The Future of Web Development: Trends and Predictions',
      excerpt: 'Explore the latest trends in web development and what to expect in the coming years...',
      category: 'Technology',
      readTime: '5 min read',
      date: '2024-01-15'
    },
    {
      id: 2,
      title: 'Understanding Accessibility in Modern Web Applications',
      excerpt: 'Learn about the importance of accessibility and how to implement it in your projects...',
      category: 'Accessibility',
      readTime: '8 min read',
      date: '2024-01-12'
    },
    {
      id: 3,
      title: 'Building Scalable React Applications: Best Practices',
      excerpt: 'Discover the best practices for building large-scale React applications that can grow with your business...',
      category: 'React',
      readTime: '12 min read',
      date: '2024-01-10'
    },
    {
      id: 4,
      title: 'CSS Grid vs Flexbox: When to Use Each',
      excerpt: 'A comprehensive comparison of CSS Grid and Flexbox to help you choose the right layout method...',
      category: 'CSS',
      readTime: '6 min read',
      date: '2024-01-08'
    },
    {
      id: 5,
      title: 'JavaScript Performance Optimization Techniques',
      excerpt: 'Learn how to optimize your JavaScript code for better performance and user experience...',
      category: 'JavaScript',
      readTime: '10 min read',
      date: '2024-01-05'
    },
    {
      id: 6,
      title: 'The Complete Guide to TypeScript for Beginners',
      excerpt: 'Everything you need to know to get started with TypeScript and build type-safe applications...',
      category: 'TypeScript',
      readTime: '15 min read',
      date: '2024-01-03'
    }
  ];
  
  let selectedCategory = 'all';
  let filteredArticles = [...articles];
  
  function filterByCategory(category) {
    selectedCategory = category;
    if (category === 'all') {
      filteredArticles = [...articles];
    } else {
      filteredArticles = articles.filter(article => article.category === category);
    }
  }
  
  function getCategories() {
    return ['all', ...new Set(articles.map(article => article.category))];
  }
  
  function formatDate(dateString) {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });
  }
  
  function handleArticleClick(article) {
    alert(`Opening article: ${article.title}`);
  }
</script>

<div class="blog-page">
  <header class="header">
    <div class="header-content">
      <h1 class="logo">TechBlog</h1>
      <nav class="nav">
        <a href="#" class="nav-link">Home</a>
        <a href="#" class="nav-link">Categories</a>
        <a href="#" class="nav-link">About</a>
        <a href="#" class="nav-link">Contact</a>
      </nav>
      <div class="header-actions">
        <button class="header-btn" on:click={() => alert('Search clicked')}>
          🔍 Search
        </button>
        <button class="header-btn" on:click={() => alert('Subscribe clicked')}>
          📧 Subscribe
        </button>
      </div>
    </div>
  </header>
  
  <main class="main-content">
    <div class="page-header">
      <h2 class="page-title">Latest Articles</h2>
      <p class="page-subtitle">Stay updated with the latest trends and insights</p>
    </div>
    
    <div class="filter-section">
      <div class="filter-group">
        <label for="categoryFilter" class="filter-label">Filter by Category:</label>
        <select id="categoryFilter" class="filter-select" on:change={(e) => filterByCategory(e.target.value)}>
          {#each getCategories() as category}
            <option value={category} selected={category === selectedCategory}>
              {category === 'all' ? 'All Categories' : category}
            </option>
          {/each}
        </select>
      </div>
      
      <div class="stats">
        <span class="stat-text">Showing {filteredArticles.length} articles</span>
      </div>
    </div>
    
    <div class="articles-grid">
      {#each filteredArticles as article}
        <article class="article-card">
          <div class="article-header">
            <div class="article-category">{article.category}</div>
            <div class="article-meta">
              <span class="article-date">{formatDate(article.date)}</span>
              <span class="article-read-time">{article.readTime}</span>
            </div>
          </div>
          
          <div class="article-content">
            <h3 class="article-title">{article.title}</h3>
            <p class="article-excerpt">{article.excerpt}</p>
          </div>
          
          <div class="article-footer">
            <div class="article-actions">
              <button class="action-btn bookmark" on:click={() => alert(`Bookmark ${article.title}`)}>
                🔖 Bookmark
              </button>
              <button class="action-btn share" on:click={() => alert(`Share ${article.title}`)}>
                📤 Share
              </button>
            </div>
            
            <!-- GENERIC LINK TEXT - "Read more" link without context about destination -->
            <a href="#" class="read-more-link" on:click|preventDefault={() => handleArticleClick(article)}>
              Read more
            </a>
          </div>
        </article>
      {/each}
    </div>
    
    <div class="pagination">
      <button class="pagination-btn" disabled>Previous</button>
      <div class="pagination-pages">
        <button class="page-btn active">1</button>
        <button class="page-btn">2</button>
        <button class="page-btn">3</button>
        <button class="page-btn">4</button>
        <button class="page-btn">5</button>
      </div>
      <button class="pagination-btn">Next</button>
    </div>
  </main>
  
  <aside class="sidebar">
    <div class="sidebar-section">
      <h3 class="sidebar-title">Popular Tags</h3>
      <div class="tags">
        <span class="tag">JavaScript</span>
        <span class="tag">React</span>
        <span class="tag">CSS</span>
        <span class="tag">Accessibility</span>
        <span class="tag">Performance</span>
        <span class="tag">TypeScript</span>
      </div>
    </div>
    
    <div class="sidebar-section">
      <h3 class="sidebar-title">Recent Posts</h3>
      <div class="recent-posts">
        {#each articles.slice(0, 3) as article}
          <div class="recent-post">
            <h4 class="recent-post-title">
              <!-- GENERIC LINK TEXT - "Read more" link without context about destination -->
              <a href="#" class="recent-post-link" on:click|preventDefault={() => handleArticleClick(article)}>
                {article.title}
              </a>
            </h4>
            <div class="recent-post-meta">
              <span class="recent-post-date">{formatDate(article.date)}</span>
              <span class="recent-post-category">{article.category}</span>
            </div>
          </div>
        {/each}
      </div>
    </div>
    
    <div class="sidebar-section">
      <h3 class="sidebar-title">Newsletter</h3>
      <div class="newsletter-signup">
        <p class="newsletter-text">Get the latest articles delivered to your inbox</p>
        <div class="newsletter-form">
          <input type="email" placeholder="Enter your email" class="newsletter-input" />
          <button class="newsletter-btn">Subscribe</button>
        </div>
      </div>
    </div>
  </aside>
  
  <footer class="footer">
    <div class="footer-content">
      <div class="footer-section">
        <h4 class="footer-title">About</h4>
        <p class="footer-text">TechBlog is your source for the latest in web development, technology trends, and programming insights.</p>
      </div>
      
      <div class="footer-section">
        <h4 class="footer-title">Quick Links</h4>
        <ul class="footer-links">
          <li><a href="#" class="footer-link">Home</a></li>
          <li><a href="#" class="footer-link">Categories</a></li>
          <li><a href="#" class="footer-link">About</a></li>
          <li><a href="#" class="footer-link">Contact</a></li>
        </ul>
      </div>
      
      <div class="footer-section">
        <h4 class="footer-title">Follow Us</h4>
        <div class="social-links">
          <a href="#" class="social-link">Twitter</a>
          <a href="#" class="social-link">LinkedIn</a>
          <a href="#" class="social-link">GitHub</a>
        </div>
      </div>
    </div>
    
    <div class="footer-bottom">
      <p>&copy; 2024 TechBlog. All rights reserved.</p>
    </div>
  </footer>
</div>

<style>
  .blog-page {
    min-height: 100vh;
    background: #f8f9fa;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  }
  
  .header {
    background: white;
    border-bottom: 1px solid #ddd;
    padding: 15px 0;
  }
  
  .header-content {
    max-width: 1200px;
    margin: 0 auto;
    padding: 0 20px;
    display: flex;
    justify-content: space-between;
    align-items: center;
  }
  
  .logo {
    font-size: 24px;
    font-weight: bold;
    color: #333;
    margin: 0;
  }
  
  .nav {
    display: flex;
    gap: 30px;
  }
  
  .nav-link {
    color: #333;
    text-decoration: none;
    font-weight: 500;
    transition: color 0.2s;
  }
  
  .nav-link:hover {
    color: #007bff;
  }
  
  .header-actions {
    display: flex;
    gap: 15px;
  }
  
  .header-btn {
    padding: 8px 16px;
    border: 1px solid #ddd;
    border-radius: 6px;
    background: white;
    color: #333;
    cursor: pointer;
    font-size: 14px;
    transition: all 0.2s;
  }
  
  .header-btn:hover {
    background: #f8f9fa;
  }
  
  .main-content {
    max-width: 1200px;
    margin: 0 auto;
    padding: 30px 20px;
    display: grid;
    grid-template-columns: 1fr 300px;
    gap: 40px;
  }
  
  .page-header {
    text-align: center;
    margin-bottom: 40px;
    grid-column: 1 / -1;
  }
  
  .page-title {
    font-size: 32px;
    font-weight: bold;
    color: #333;
    margin: 0 0 10px 0;
  }
  
  .page-subtitle {
    font-size: 18px;
    color: #666;
    margin: 0;
  }
  
  .filter-section {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 30px;
    padding: 20px;
    background: white;
    border-radius: 8px;
    box-shadow: 0 2px 8px rgba(0,0,0,0.1);
    grid-column: 1 / -1;
  }
  
  .filter-group {
    display: flex;
    align-items: center;
    gap: 10px;
  }
  
  .filter-label {
    font-weight: bold;
    color: #333;
  }
  
  .filter-select {
    padding: 8px 12px;
    border: 1px solid #ddd;
    border-radius: 6px;
    background: white;
    color: #333;
    cursor: pointer;
  }
  
  .stats {
    color: #666;
  }
  
  .articles-grid {
    display: grid;
    gap: 30px;
  }
  
  .article-card {
    background: white;
    border-radius: 12px;
    padding: 25px;
    box-shadow: 0 4px 12px rgba(0,0,0,0.1);
    transition: transform 0.2s, box-shadow 0.2s;
  }
  
  .article-card:hover {
    transform: translateY(-2px);
    box-shadow: 0 8px 24px rgba(0,0,0,0.15);
  }
  
  .article-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 15px;
  }
  
  .article-category {
    background: #007bff;
    color: white;
    padding: 4px 12px;
    border-radius: 20px;
    font-size: 12px;
    font-weight: bold;
    text-transform: uppercase;
  }
  
  .article-meta {
    display: flex;
    gap: 15px;
    font-size: 14px;
    color: #666;
  }
  
  .article-content {
    margin-bottom: 20px;
  }
  
  .article-title {
    font-size: 24px;
    font-weight: bold;
    color: #333;
    margin: 0 0 15px 0;
    line-height: 1.3;
  }
  
  .article-excerpt {
    font-size: 16px;
    color: #666;
    line-height: 1.6;
    margin: 0;
  }
  
  .article-footer {
    display: flex;
    justify-content: space-between;
    align-items: center;
    border-top: 1px solid #eee;
    padding-top: 15px;
  }
  
  .article-actions {
    display: flex;
    gap: 10px;
  }
  
  .action-btn {
    background: none;
    border: 1px solid #ddd;
    border-radius: 6px;
    padding: 6px 12px;
    color: #666;
    cursor: pointer;
    font-size: 14px;
    transition: all 0.2s;
  }
  
  .action-btn:hover {
    background: #f8f9fa;
    color: #333;
  }
  
  .read-more-link {
    color: #007bff;
    text-decoration: none;
    font-weight: bold;
    font-size: 16px;
    transition: color 0.2s;
  }
  
  .read-more-link:hover {
    color: #0056b3;
    text-decoration: underline;
  }
  
  .pagination {
    display: flex;
    justify-content: center;
    align-items: center;
    gap: 10px;
    margin-top: 40px;
    grid-column: 1 / -1;
  }
  
  .pagination-btn {
    padding: 8px 16px;
    border: 1px solid #ddd;
    border-radius: 6px;
    background: white;
    color: #333;
    cursor: pointer;
    transition: all 0.2s;
  }
  
  .pagination-btn:hover:not(:disabled) {
    background: #f8f9fa;
  }
  
  .pagination-btn:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
  
  .pagination-pages {
    display: flex;
    gap: 5px;
  }
  
  .page-btn {
    width: 40px;
    height: 40px;
    border: 1px solid #ddd;
    border-radius: 6px;
    background: white;
    color: #333;
    cursor: pointer;
    transition: all 0.2s;
  }
  
  .page-btn:hover {
    background: #f8f9fa;
  }
  
  .page-btn.active {
    background: #007bff;
    color: white;
    border-color: #007bff;
  }
  
  .sidebar {
    display: flex;
    flex-direction: column;
    gap: 30px;
  }
  
  .sidebar-section {
    background: white;
    border-radius: 12px;
    padding: 25px;
    box-shadow: 0 4px 12px rgba(0,0,0,0.1);
  }
  
  .sidebar-title {
    font-size: 18px;
    font-weight: bold;
    color: #333;
    margin: 0 0 20px 0;
  }
  
  .tags {
    display: flex;
    flex-wrap: wrap;
    gap: 10px;
  }
  
  .tag {
    background: #f8f9fa;
    color: #333;
    padding: 6px 12px;
    border-radius: 20px;
    font-size: 14px;
    cursor: pointer;
    transition: all 0.2s;
  }
  
  .tag:hover {
    background: #007bff;
    color: white;
  }
  
  .recent-posts {
    display: flex;
    flex-direction: column;
    gap: 20px;
  }
  
  .recent-post {
    padding-bottom: 15px;
    border-bottom: 1px solid #eee;
  }
  
  .recent-post:last-child {
    border-bottom: none;
    padding-bottom: 0;
  }
  
  .recent-post-title {
    font-size: 16px;
    font-weight: bold;
    margin: 0 0 8px 0;
  }
  
  .recent-post-link {
    color: #333;
    text-decoration: none;
    transition: color 0.2s;
  }
  
  .recent-post-link:hover {
    color: #007bff;
  }
  
  .recent-post-meta {
    display: flex;
    gap: 10px;
    font-size: 12px;
    color: #666;
  }
  
  .newsletter-signup {
    text-align: center;
  }
  
  .newsletter-text {
    font-size: 14px;
    color: #666;
    margin: 0 0 15px 0;
  }
  
  .newsletter-form {
    display: flex;
    flex-direction: column;
    gap: 10px;
  }
  
  .newsletter-input {
    padding: 10px;
    border: 1px solid #ddd;
    border-radius: 6px;
    font-size: 14px;
  }
  
  .newsletter-btn {
    background: #007bff;
    color: white;
    border: none;
    padding: 10px;
    border-radius: 6px;
    cursor: pointer;
    font-weight: bold;
    transition: background-color 0.2s;
  }
  
  .newsletter-btn:hover {
    background: #0056b3;
  }
  
  .footer {
    background: #333;
    color: white;
    padding: 40px 0 20px 0;
    margin-top: 60px;
  }
  
  .footer-content {
    max-width: 1200px;
    margin: 0 auto;
    padding: 0 20px;
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
    gap: 40px;
  }
  
  .footer-title {
    font-size: 18px;
    font-weight: bold;
    margin: 0 0 15px 0;
  }
  
  .footer-text {
    color: #ccc;
    line-height: 1.6;
    margin: 0;
  }
  
  .footer-links {
    list-style: none;
    padding: 0;
    margin: 0;
  }
  
  .footer-links li {
    margin-bottom: 8px;
  }
  
  .footer-link {
    color: #ccc;
    text-decoration: none;
    transition: color 0.2s;
  }
  
  .footer-link:hover {
    color: white;
  }
  
  .social-links {
    display: flex;
    flex-direction: column;
    gap: 10px;
  }
  
  .social-link {
    color: #ccc;
    text-decoration: none;
    transition: color 0.2s;
  }
  
  .social-link:hover {
    color: white;
  }
  
  .footer-bottom {
    border-top: 1px solid #555;
    margin-top: 30px;
    padding-top: 20px;
    text-align: center;
    color: #ccc;
  }
  
  @media (max-width: 768px) {
    .main-content {
      grid-template-columns: 1fr;
    }
    
    .filter-section {
      flex-direction: column;
      gap: 15px;
    }
  }
</style>
