// scenarios/advanced/web/vue/n5.vue
<template>
  <div class="search-interface">
    <div class="search-header">
      <h1>Product Search</h1>
      <div class="search-stats">
        {{ searchResults.length }} products found
        <span v-if="selectedItems.length > 0" class="selected-count">• {{ selectedItems.length }} selected</span>
      </div>
    </div>

    <div class="search-container">
      <div class="search-main">
        <form @submit.prevent="handleSearch" class="search-form">
          <div class="search-input-container">
            <input
              ref="searchInputRef"
              type="text"
              v-model="searchQuery"
              placeholder="Search for products..."
              class="search-input"
            />
            <button type="submit" class="search-btn">🔍</button>
            
            <div v-if="showSuggestions && suggestions.length > 0" class="search-suggestions">
              <div
                v-for="(suggestion, index) in suggestions"
                :key="index"
                class="suggestion-item"
                @click="handleSuggestionClick(suggestion)"
              >
                {{ suggestion }}
              </div>
            </div>
          </div>
        </form>

        <div class="search-controls">
          <div class="view-controls">
            <button 
              :class="{ active: viewMode === 'grid' }"
              @click="viewMode = 'grid'"
              title="Grid View"
            >
              ⊞
            </button>
            <button 
              :class="{ active: viewMode === 'list' }"
              @click="viewMode = 'list'"
              title="List View"
            >
              ☰
            </button>
          </div>

          <div class="sort-controls">
            <label>Sort by:</label>
            <select v-model="filters.sortBy">
              <option v-for="option in sortOptions" :key="option.id" :value="option.id">
                {{ option.name }}
              </option>
            </select>
          </div>

          <button 
            @click="showFilters = !showFilters"
            class="filters-toggle"
          >
            Filters {{ showFilters ? '▲' : '▼' }}
          </button>
        </div>

        <div v-if="showFilters" class="filters-panel">
          <div class="filter-group">
            <label>Category</label>
            <select v-model="filters.category">
              <option v-for="category in categories" :key="category.id" :value="category.id">
                {{ category.name }}
              </option>
            </select>
          </div>

          <div class="filter-group">
            <label>Brand</label>
            <select v-model="filters.brand">
              <option v-for="brand in brands" :key="brand.id" :value="brand.id">
                {{ brand.name }}
              </option>
            </select>
          </div>

          <div class="filter-group">
            <label>Price Range</label>
            <select v-model="filters.priceRange">
              <option v-for="range in priceRanges" :key="range.id" :value="range.id">
                {{ range.name }}
              </option>
            </select>
          </div>

          <div class="filter-group">
            <label>Rating</label>
            <select v-model="filters.rating">
              <option v-for="rating in ratings" :key="rating.id" :value="rating.id">
                {{ rating.name }}
              </option>
            </select>
          </div>

          <div class="filter-group">
            <label>Availability</label>
            <select v-model="filters.availability">
              <option value="all">All Items</option>
              <option value="in-stock">In Stock</option>
              <option value="limited">Limited Stock</option>
              <option value="out-of-stock">Out of Stock</option>
            </select>
          </div>

          <button @click="clearFilters" class="clear-filters-btn">
            Clear All Filters
          </button>
        </div>

        <div v-if="isLoading" class="loading-state">
          <div class="loading-spinner"></div>
          <span>Searching...</span>
        </div>

        <div v-else class="search-results">
          <div v-if="paginatedResults.length > 0" class="results-header">
            <label class="select-all-label">
              <input
                type="checkbox"
                :checked="selectedItems.length === paginatedResults.length && paginatedResults.length > 0"
                @change="handleSelectAll"
              />
              Select All
            </label>
          </div>

          <div :class="`results-grid ${viewMode}`">
            <div 
              v-for="product in paginatedResults" 
              :key="product.id" 
              :class="`product-card ${selectedItems.includes(product.id) ? 'selected' : ''}`"
            >
              <div class="product-checkbox">
                <input
                  type="checkbox"
                  :checked="selectedItems.includes(product.id)"
                  @change="handleItemSelect(product.id)"
                />
              </div>

              <div class="product-image">
                <img :src="product.image" :alt="product.name" />
                <div v-if="product.availability === 'limited'" class="availability-badge limited">Limited</div>
                <div v-if="product.availability === 'out-of-stock'" class="availability-badge out-of-stock">Out of Stock</div>
              </div>

              <div class="product-info">
                <h3 class="product-name">{{ product.name }}</h3>
                <div class="product-brand">{{ product.brand }}</div>
                <div class="product-rating">
                  <span class="stars">{{ renderStars(product.rating) }}</span>
                  <span class="rating-text">({{ product.reviews }})</span>
                </div>
                <div class="product-price">${{ product.price.toFixed(2) }}</div>
                <div class="product-description">{{ product.description }}</div>
              </div>

              <div class="product-actions">
                <button class="add-to-cart-btn">Add to Cart</button>
                <button class="wishlist-btn">♡</button>
              </div>
            </div>
          </div>

          <div v-if="totalPages > 1" class="pagination">
            <button 
              @click="currentPage = Math.max(1, currentPage - 1)"
              :disabled="currentPage === 1"
            >
              Previous
            </button>
            
            <button
              v-for="page in totalPages"
              :key="page"
              @click="currentPage = page"
              :class="{ active: currentPage === page }"
            >
              {{ page }}
            </button>
            
            <button 
              @click="currentPage = Math.min(totalPages, currentPage + 1)"
              :disabled="currentPage === totalPages"
            >
              Next
            </button>
          </div>
        </div>

        <div v-if="searchResults.length === 0 && !isLoading" class="no-results">
          <div class="no-results-icon">🔍</div>
          <h3>No products found</h3>
          <p>Try adjusting your search terms or filters</p>
          <button @click="clearFilters" class="clear-filters-btn">
            Clear All Filters
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'ComplexSearchInterface',
  data() {
    return {
      searchQuery: '',
      searchResults: [],
      isLoading: false,
      filters: {
        category: 'all',
        priceRange: 'all',
        brand: 'all',
        rating: 'all',
        availability: 'all',
        sortBy: 'relevance'
      },
      showFilters: false,
      viewMode: 'grid',
      currentPage: 1,
      itemsPerPage: 12,
      selectedItems: [],
      showSuggestions: false,
      suggestions: [],
      sampleProducts: [
        {
          id: 1,
          name: 'Wireless Bluetooth Headphones',
          category: 'electronics',
          brand: 'TechSound',
          price: 99.99,
          rating: 4.5,
          reviews: 128,
          availability: 'in-stock',
          image: 'https://via.placeholder.com/200x200/4caf50/fff?text=🎧',
          description: 'High-quality wireless headphones with noise cancellation'
        },
        {
          id: 2,
          name: 'Smart Fitness Watch',
          category: 'electronics',
          brand: 'FitTech',
          price: 199.99,
          rating: 4.2,
          reviews: 89,
          availability: 'in-stock',
          image: 'https://via.placeholder.com/200x200/2196f3/fff?text=⌚',
          description: 'Advanced fitness tracking with heart rate monitoring'
        },
        {
          id: 3,
          name: 'Organic Cotton T-Shirt',
          category: 'clothing',
          brand: 'EcoWear',
          price: 29.99,
          rating: 4.7,
          reviews: 256,
          availability: 'in-stock',
          image: 'https://via.placeholder.com/200x200/ff9800/fff?text=👕',
          description: 'Comfortable organic cotton t-shirt in various colors'
        },
        {
          id: 4,
          name: 'Stainless Steel Water Bottle',
          category: 'home',
          brand: 'HydroMax',
          price: 24.99,
          rating: 4.3,
          reviews: 167,
          availability: 'limited',
          image: 'https://via.placeholder.com/200x200/9c27b0/fff?text=🍶',
          description: 'Insulated stainless steel water bottle keeps drinks cold'
        },
        {
          id: 5,
          name: 'Wireless Charging Pad',
          category: 'electronics',
          brand: 'PowerUp',
          price: 39.99,
          rating: 4.1,
          reviews: 94,
          availability: 'in-stock',
          image: 'https://via.placeholder.com/200x200/f44336/fff?text=🔋',
          description: 'Fast wireless charging pad compatible with all devices'
        },
        {
          id: 6,
          name: 'Yoga Mat Premium',
          category: 'sports',
          brand: 'FlexFit',
          price: 49.99,
          rating: 4.6,
          reviews: 203,
          availability: 'in-stock',
          image: 'https://via.placeholder.com/200x200/4caf50/fff?text=🧘',
          description: 'Non-slip premium yoga mat for all fitness levels'
        }
      ],
      categories: [
        { id: 'all', name: 'All Categories' },
        { id: 'electronics', name: 'Electronics' },
        { id: 'clothing', name: 'Clothing' },
        { id: 'home', name: 'Home & Garden' },
        { id: 'sports', name: 'Sports & Fitness' },
        { id: 'books', name: 'Books' }
      ],
      brands: [
        { id: 'all', name: 'All Brands' },
        { id: 'TechSound', name: 'TechSound' },
        { id: 'FitTech', name: 'FitTech' },
        { id: 'EcoWear', name: 'EcoWear' },
        { id: 'HydroMax', name: 'HydroMax' },
        { id: 'PowerUp', name: 'PowerUp' },
        { id: 'FlexFit', name: 'FlexFit' }
      ],
      priceRanges: [
        { id: 'all', name: 'All Prices' },
        { id: '0-25', name: 'Under $25' },
        { id: '25-50', name: '$25 - $50' },
        { id: '50-100', name: '$50 - $100' },
        { id: '100-200', name: '$100 - $200' },
        { id: '200+', name: 'Over $200' }
      ],
      ratings: [
        { id: 'all', name: 'All Ratings' },
        { id: '4.5+', name: '4.5+ Stars' },
        { id: '4+', name: '4+ Stars' },
        { id: '3+', name: '3+ Stars' },
        { id: '2+', name: '2+ Stars' }
      ],
      sortOptions: [
        { id: 'relevance', name: 'Relevance' },
        { id: 'price-low', name: 'Price: Low to High' },
        { id: 'price-high', name: 'Price: High to Low' },
        { id: 'rating', name: 'Customer Rating' },
        { id: 'newest', name: 'Newest First' },
        { id: 'name', name: 'Name A-Z' }
      ],
      searchSuggestions: [
        'wireless headphones', 'smart watch', 'fitness tracker', 'bluetooth speaker',
        'phone case', 'laptop stand', 'wireless charger', 'yoga mat', 'water bottle',
        'organic cotton', 'stainless steel', 'premium quality'
      ]
    }
  },
  computed: {
    totalPages() {
      return Math.ceil(this.searchResults.length / this.itemsPerPage);
    },
    paginatedResults() {
      const startIndex = (this.currentPage - 1) * this.itemsPerPage;
      return this.searchResults.slice(startIndex, startIndex + this.itemsPerPage);
    }
  },
  watch: {
    searchQuery() {
      if (this.searchQuery.length > 2) {
        const filteredSuggestions = this.searchSuggestions.filter(suggestion =>
          suggestion.toLowerCase().includes(this.searchQuery.toLowerCase())
        );
        this.suggestions = filteredSuggestions.slice(0, 5);
        this.showSuggestions = true;
      } else {
        this.showSuggestions = false;
      }
    },
    filters: {
      handler() {
        this.currentPage = 1;
        this.performSearch();
      },
      deep: true
    },
    currentPage() {
      this.performSearch();
    }
  },
  mounted() {
    this.performSearch();
  },
  methods: {
    performSearch() {
      this.isLoading = true;
      
      setTimeout(() => {
        let filteredProducts = [...this.sampleProducts];

        if (this.searchQuery.trim()) {
          filteredProducts = filteredProducts.filter(product =>
            product.name.toLowerCase().includes(this.searchQuery.toLowerCase()) ||
            product.description.toLowerCase().includes(this.searchQuery.toLowerCase()) ||
            product.brand.toLowerCase().includes(this.searchQuery.toLowerCase())
          );
        }

        if (this.filters.category !== 'all') {
          filteredProducts = filteredProducts.filter(product => product.category === this.filters.category);
        }

        if (this.filters.brand !== 'all') {
          filteredProducts = filteredProducts.filter(product => product.brand === this.filters.brand);
        }

        if (this.filters.priceRange !== 'all') {
          const [min, max] = this.filters.priceRange.split('-').map(Number);
          filteredProducts = filteredProducts.filter(product => {
            if (this.filters.priceRange === '200+') {
              return product.price > 200;
            }
            return product.price >= min && product.price <= max;
          });
        }

        if (this.filters.rating !== 'all') {
          const minRating = parseFloat(this.filters.rating);
          filteredProducts = filteredProducts.filter(product => product.rating >= minRating);
        }

        if (this.filters.availability !== 'all') {
          filteredProducts = filteredProducts.filter(product => product.availability === this.filters.availability);
        }

        switch (this.filters.sortBy) {
          case 'price-low':
            filteredProducts.sort((a, b) => a.price - b.price);
            break;
          case 'price-high':
            filteredProducts.sort((a, b) => b.price - a.price);
            break;
          case 'rating':
            filteredProducts.sort((a, b) => b.rating - a.rating);
            break;
          case 'newest':
            filteredProducts.sort((a, b) => b.id - a.id);
            break;
          case 'name':
            filteredProducts.sort((a, b) => a.name.localeCompare(b.name));
            break;
        }

        this.searchResults = filteredProducts;
        this.isLoading = false;
      }, 500);
    },
    handleSearch() {
      this.currentPage = 1;
      this.performSearch();
    },
    handleSuggestionClick(suggestion) {
      this.searchQuery = suggestion;
      this.showSuggestions = false;
      this.currentPage = 1;
      this.performSearch();
    },
    handleItemSelect(itemId) {
      if (this.selectedItems.includes(itemId)) {
        this.selectedItems = this.selectedItems.filter(id => id !== itemId);
      } else {
        this.selectedItems.push(itemId);
      }
    },
    handleSelectAll() {
      const currentPageItems = this.paginatedResults.map(item => item.id);
      if (this.selectedItems.length === currentPageItems.length) {
        this.selectedItems = this.selectedItems.filter(id => !currentPageItems.includes(id));
      } else {
        this.selectedItems = [...this.selectedItems, ...currentPageItems.filter(id => !this.selectedItems.includes(id))];
      }
    },
    clearFilters() {
      this.filters = {
        category: 'all',
        priceRange: 'all',
        brand: 'all',
        rating: 'all',
        availability: 'all',
        sortBy: 'relevance'
      };
      this.searchQuery = '';
      this.currentPage = 1;
    },
    renderStars(rating) {
      const stars = [];
      const fullStars = Math.floor(rating);
      const hasHalfStar = rating % 1 !== 0;

      for (let i = 0; i < fullStars; i++) {
        stars.push('★');
      }
      if (hasHalfStar) {
        stars.push('☆');
      }
      while (stars.length < 5) {
        stars.push('☆');
      }
      return stars.join('');
    }
  }
}
</script>

<style scoped>
.search-interface {
  max-width: 1200px;
  margin: 0 auto;
  padding: 20px;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}

.search-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 25px;
  padding-bottom: 15px;
  border-bottom: 2px solid #e0e0e0;
}

.search-header h1 {
  margin: 0;
  color: #333;
  font-size: 28px;
}

.search-stats {
  color: #666;
  font-size: 14px;
}

.selected-count {
  color: #4caf50;
  font-weight: 600;
}

.search-container {
  display: flex;
  gap: 20px;
}

.search-main {
  flex: 1;
}

.search-form {
  margin-bottom: 20px;
}

.search-input-container {
  position: relative;
  display: flex;
  align-items: center;
}

.search-input {
  flex: 1;
  padding: 12px 16px;
  border: 2px solid #e0e0e0;
  border-radius: 8px;
  font-size: 16px;
  outline: none;
  transition: border-color 0.3s ease;
}

.search-input:focus {
  border-color: #4caf50;
}

.search-btn {
  position: absolute;
  right: 8px;
  background: #4caf50;
  color: white;
  border: none;
  border-radius: 6px;
  padding: 8px 12px;
  cursor: pointer;
  font-size: 16px;
  transition: background-color 0.3s ease;
}

.search-btn:hover {
  background: #45a049;
}

.search-suggestions {
  position: absolute;
  top: 100%;
  left: 0;
  right: 0;
  background: white;
  border: 1px solid #e0e0e0;
  border-top: none;
  border-radius: 0 0 8px 8px;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
  z-index: 100;
  max-height: 200px;
  overflow-y: auto;
}

.suggestion-item {
  padding: 10px 16px;
  cursor: pointer;
  border-bottom: 1px solid #f0f0f0;
  transition: background-color 0.3s ease;
}

.suggestion-item:hover {
  background: #f8f9fa;
}

.suggestion-item:last-child {
  border-bottom: none;
}

.search-controls {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
  padding: 15px;
  background: #f8f9fa;
  border-radius: 8px;
}

.view-controls {
  display: flex;
  gap: 5px;
  background: white;
  border-radius: 6px;
  padding: 4px;
}

.view-controls button {
  padding: 8px 12px;
  border: none;
  background: transparent;
  cursor: pointer;
  border-radius: 4px;
  font-size: 16px;
  transition: background-color 0.3s ease;
}

.view-controls button.active {
  background: #4caf50;
  color: white;
}

.view-controls button:hover:not(.active) {
  background: #e9ecef;
}

.sort-controls {
  display: flex;
  align-items: center;
  gap: 8px;
}

.sort-controls label {
  font-size: 14px;
  color: #666;
  font-weight: 500;
}

.sort-controls select {
  padding: 6px 10px;
  border: 1px solid #ddd;
  border-radius: 4px;
  font-size: 14px;
  background: white;
  cursor: pointer;
}

.filters-toggle {
  padding: 8px 16px;
  background: white;
  border: 1px solid #ddd;
  border-radius: 6px;
  cursor: pointer;
  font-size: 14px;
  color: #333;
  transition: all 0.3s ease;
}

.filters-toggle:hover {
  background: #f5f5f5;
  border-color: #4caf50;
}

.filters-panel {
  background: #f8f9fa;
  border: 1px solid #e0e0e0;
  border-radius: 8px;
  padding: 20px;
  margin-bottom: 20px;
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 20px;
}

.filter-group {
  display: flex;
  flex-direction: column;
  gap: 5px;
}

.filter-group label {
  font-size: 12px;
  font-weight: 600;
  color: #666;
  text-transform: uppercase;
  letter-spacing: 0.5px;
}

.filter-group select {
  padding: 8px 12px;
  border: 1px solid #ddd;
  border-radius: 4px;
  font-size: 14px;
  background: white;
  cursor: pointer;
}

.filter-group select:focus {
  outline: none;
  border-color: #4caf50;
}

.clear-filters-btn {
  grid-column: 1 / -1;
  justify-self: start;
  padding: 8px 16px;
  background: #f44336;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-size: 14px;
  font-weight: 500;
  transition: background-color 0.3s ease;
}

.clear-filters-btn:hover {
  background: #d32f2f;
}

.loading-state {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 60px 20px;
  color: #666;
}

.loading-spinner {
  width: 40px;
  height: 40px;
  border: 4px solid rgba(76, 175, 80, 0.3);
  border-top: 4px solid #4caf50;
  border-radius: 50%;
  animation: spin 1s linear infinite;
  margin-bottom: 15px;
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

.search-results {
  background: white;
  border-radius: 8px;
  overflow: hidden;
}

.results-header {
  padding: 15px 20px;
  background: #f8f9fa;
  border-bottom: 1px solid #e0e0e0;
}

.select-all-label {
  display: flex;
  align-items: center;
  gap: 8px;
  cursor: pointer;
  font-size: 14px;
  color: #333;
  font-weight: 500;
}

.results-grid {
  padding: 20px;
}

.results-grid.grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
  gap: 20px;
}

.results-grid.list {
  display: flex;
  flex-direction: column;
  gap: 15px;
}

.product-card {
  background: white;
  border: 1px solid #e0e0e0;
  border-radius: 8px;
  overflow: hidden;
  transition: all 0.3s ease;
  position: relative;
}

.product-card:hover {
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
  transform: translateY(-2px);
}

.product-card.selected {
  border-color: #4caf50;
  box-shadow: 0 0 0 2px rgba(76, 175, 80, 0.2);
}

.product-checkbox {
  position: absolute;
  top: 10px;
  left: 10px;
  z-index: 10;
}

.product-checkbox input[type="checkbox"] {
  width: 18px;
  height: 18px;
  cursor: pointer;
}

.product-image {
  position: relative;
  height: 200px;
  overflow: hidden;
}

.product-image img {
  width: 100%;
  height: 100%;
  object-fit: cover;
  transition: transform 0.3s ease;
}

.product-card:hover .product-image img {
  transform: scale(1.05);
}

.availability-badge {
  position: absolute;
  top: 10px;
  right: 10px;
  padding: 4px 8px;
  border-radius: 4px;
  font-size: 10px;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.5px;
}

.availability-badge.limited {
  background: #ff9800;
  color: white;
}

.availability-badge.out-of-stock {
  background: #f44336;
  color: white;
}

.product-info {
  padding: 15px;
}

.product-name {
  margin: 0 0 5px 0;
  font-size: 16px;
  font-weight: 600;
  color: #333;
  line-height: 1.3;
}

.product-brand {
  font-size: 12px;
  color: #666;
  margin-bottom: 8px;
  text-transform: uppercase;
  letter-spacing: 0.5px;
}

.product-rating {
  display: flex;
  align-items: center;
  gap: 5px;
  margin-bottom: 8px;
}

.stars {
  color: #ffc107;
  font-size: 14px;
}

.rating-text {
  font-size: 12px;
  color: #666;
}

.product-price {
  font-size: 18px;
  font-weight: 700;
  color: #4caf50;
  margin-bottom: 8px;
}

.product-description {
  font-size: 12px;
  color: #666;
  line-height: 1.4;
  margin-bottom: 15px;
}

.product-actions {
  display: flex;
  gap: 8px;
  padding: 0 15px 15px;
}

.add-to-cart-btn {
  flex: 1;
  padding: 8px 12px;
  background: #4caf50;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-size: 12px;
  font-weight: 600;
  transition: background-color 0.3s ease;
}

.add-to-cart-btn:hover {
  background: #45a049;
}

.wishlist-btn {
  padding: 8px 12px;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
  cursor: pointer;
  font-size: 16px;
  color: #666;
  transition: all 0.3s ease;
}

.wishlist-btn:hover {
  background: #f5f5f5;
  color: #f44336;
}

.pagination {
  display: flex;
  justify-content: center;
  align-items: center;
  gap: 10px;
  padding: 20px;
  background: #f8f9fa;
  border-top: 1px solid #e0e0e0;
}

.pagination button {
  padding: 8px 12px;
  border: 1px solid #ddd;
  background: white;
  cursor: pointer;
  border-radius: 4px;
  font-size: 14px;
  transition: all 0.3s ease;
}

.pagination button:hover:not(:disabled) {
  background: #f5f5f5;
  border-color: #4caf50;
}

.pagination button.active {
  background: #4caf50;
  color: white;
  border-color: #4caf50;
}

.pagination button:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.no-results {
  text-align: center;
  padding: 60px 20px;
  color: #666;
}

.no-results-icon {
  font-size: 48px;
  margin-bottom: 20px;
}

.no-results h3 {
  margin: 0 0 10px 0;
  color: #333;
  font-size: 20px;
}

.no-results p {
  margin: 0 0 20px 0;
  font-size: 14px;
}

@media (max-width: 768px) {
  .search-interface {
    padding: 15px;
  }
  
  .search-header {
    flex-direction: column;
    gap: 10px;
    align-items: stretch;
  }
  
  .search-controls {
    flex-direction: column;
    gap: 15px;
    align-items: stretch;
  }
  
  .view-controls {
    justify-content: center;
  }
  
  .sort-controls {
    justify-content: center;
  }
  
  .filters-panel {
    grid-template-columns: 1fr;
    gap: 15px;
  }
  
  .results-grid.grid {
    grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
    gap: 15px;
  }
  
  .pagination {
    flex-wrap: wrap;
    gap: 5px;
  }
}

@media (max-width: 480px) {
  .search-input {
    font-size: 14px;
    padding: 10px 14px;
  }
  
  .results-grid.grid {
    grid-template-columns: 1fr;
  }
  
  .product-actions {
    flex-direction: column;
  }
  
  .pagination button {
    padding: 6px 10px;
    font-size: 12px;
  }
}
</style>

// scenarios/advanced/web/svelte/n5.svelte
<script>
  import { onMount } from 'svelte';
  
  let searchQuery = '';
  let searchResults = [];
  let filteredResults = [];
  let isLoading = false;
  let showFilters = false;
  let showSortOptions = false;
  let currentPage = 1;
  let itemsPerPage = 10;
  let selectedCategory = 'all';
  let selectedDateRange = 'all';
  let selectedSort = 'relevance';
  let selectedView = 'list';
  let searchHistory = [];
  let suggestions = [];
  let showSuggestions = false;
  let selectedSuggestion = -1;

  const sampleData = [
    {
      id: 1,
      title: 'Advanced React Patterns',
      description: 'Learn advanced React patterns including hooks, context, and performance optimization techniques.',
      category: 'tutorial',
      author: 'John Smith',
      date: '2024-01-15',
      tags: ['react', 'javascript', 'frontend'],
      rating: 4.8,
      views: 1250,
      type: 'article'
    },
    {
      id: 2,
      title: 'Building Scalable APIs',
      description: 'Comprehensive guide to building RESTful APIs that can handle millions of requests.',
      category: 'guide',
      author: 'Sarah Johnson',
      date: '2024-01-10',
      tags: ['api', 'backend', 'scalability'],
      rating: 4.6,
      views: 890,
      type: 'video'
    },
    {
      id: 3,
      title: 'CSS Grid Mastery',
      description: 'Master CSS Grid layout with practical examples and real-world applications.',
      category: 'tutorial',
      author: 'Mike Chen',
      date: '2024-01-08',
      tags: ['css', 'grid', 'layout'],
      rating: 4.9,
      views: 2100,
      type: 'article'
    },
    {
      id: 4,
      title: 'Database Optimization',
      description: 'Techniques for optimizing database performance and query efficiency.',
      category: 'guide',
      author: 'Emily Davis',
      date: '2024-01-05',
      tags: ['database', 'sql', 'performance'],
      rating: 4.7,
      views: 1560,
      type: 'tutorial'
    },
    {
      id: 5,
      title: 'Machine Learning Basics',
      description: 'Introduction to machine learning concepts and practical implementations.',
      category: 'course',
      author: 'Dr. Alex Wilson',
      date: '2024-01-12',
      tags: ['ml', 'ai', 'python'],
      rating: 4.5,
      views: 3200,
      type: 'course'
    },
    {
      id: 6,
      title: 'Docker Containerization',
      description: 'Complete guide to containerizing applications with Docker.',
      category: 'tutorial',
      author: 'Tom Brown',
      date: '2024-01-03',
      tags: ['docker', 'containers', 'devops'],
      rating: 4.4,
      views: 980,
      type: 'video'
    },
    {
      id: 7,
      title: 'GraphQL Fundamentals',
      description: 'Learn GraphQL from basics to advanced query optimization.',
      category: 'guide',
      author: 'Lisa Garcia',
      date: '2024-01-18',
      tags: ['graphql', 'api', 'query'],
      rating: 4.8,
      views: 1450,
      type: 'article'
    },
    {
      id: 8,
      title: 'Security Best Practices',
      description: 'Essential security practices for web applications and APIs.',
      category: 'guide',
      author: 'Security Expert',
      date: '2024-01-20',
      tags: ['security', 'web', 'best-practices'],
      rating: 4.9,
      views: 2800,
      type: 'tutorial'
    }
  ];

  const categories = [
    { value: 'all', label: 'All Categories' },
    { value: 'tutorial', label: 'Tutorials' },
    { value: 'guide', label: 'Guides' },
    { value: 'course', label: 'Courses' },
    { value: 'article', label: 'Articles' }
  ];

  const dateRanges = [
    { value: 'all', label: 'All Time' },
    { value: 'today', label: 'Today' },
    { value: 'week', label: 'This Week' },
    { value: 'month', label: 'This Month' },
    { value: 'year', label: 'This Year' }
  ];

  const sortOptions = [
    { value: 'relevance', label: 'Relevance' },
    { value: 'date', label: 'Date' },
    { value: 'rating', label: 'Rating' },
    { value: 'views', label: 'Views' },
    { value: 'title', label: 'Title' }
  ];

  const viewOptions = [
    { value: 'list', label: 'List View', icon: '📋' },
    { value: 'grid', label: 'Grid View', icon: '⊞' },
    { value: 'compact', label: 'Compact View', icon: '☰' }
  ];

  $: totalPages = Math.ceil(filteredResults.length / itemsPerPage);
  $: startIndex = (currentPage - 1) * itemsPerPage;
  $: paginatedResults = filteredResults.slice(startIndex, startIndex + itemsPerPage);

  onMount(() => {
    loadSearchHistory();
    performSearch();
  });

  $: performSearch();
  $: applyFilters();

  function loadSearchHistory() {
    const saved = localStorage.getItem('searchHistory');
    if (saved) {
      searchHistory = JSON.parse(saved);
    }
  }

  function saveSearchHistory() {
    localStorage.setItem('searchHistory', JSON.stringify(searchHistory));
  }

  function performSearch() {
    if (!searchQuery.trim()) {
      searchResults = sampleData;
      applyFilters();
      return;
    }

    isLoading = true;
    
    setTimeout(() => {
      const query = searchQuery.toLowerCase();
      const results = sampleData.filter(item => 
        item.title.toLowerCase().includes(query) ||
        item.description.toLowerCase().includes(query) ||
        item.author.toLowerCase().includes(query) ||
        item.tags.some(tag => tag.toLowerCase().includes(query))
      );
      
      searchResults = results;
      applyFilters();
      isLoading = false;
      
      if (searchQuery.trim() && !searchHistory.includes(searchQuery)) {
        searchHistory.unshift(searchQuery);
        searchHistory = searchHistory.slice(0, 10);
        saveSearchHistory();
      }
    }, 500);
  }

  function applyFilters() {
    let filtered = [...searchResults];

    if (selectedCategory !== 'all') {
      filtered = filtered.filter(item => item.category === selectedCategory);
    }

    if (selectedDateRange !== 'all') {
      const now = new Date();
      const filterDate = new Date();
      
      switch (selectedDateRange) {
        case 'today':
          filterDate.setDate(now.getDate() - 1);
          break;
        case 'week':
          filterDate.setDate(now.getDate() - 7);
          break;
        case 'month':
          filterDate.setMonth(now.getMonth() - 1);
          break;
        case 'year':
          filterDate.setFullYear(now.getFullYear() - 1);
          break;
      }
      
      filtered = filtered.filter(item => new Date(item.date) >= filterDate);
    }

    filtered = sortResults(filtered);
    filteredResults = filtered;
    currentPage = 1;
  }

  function sortResults(results) {
    return results.sort((a, b) => {
      switch (selectedSort) {
        case 'date':
          return new Date(b.date) - new Date(a.date);
        case 'rating':
          return b.rating - a.rating;
        case 'views':
          return b.views - a.views;
        case 'title':
          return a.title.localeCompare(b.title);
        case 'relevance':
        default:
          return 0;
      }
    });
  }

  function handleSearch() {
    performSearch();
  }

  function handleKeydown(event) {
    if (event.key === 'Enter') {
      handleSearch();
    } else if (event.key === 'ArrowDown') {
      event.preventDefault();
      selectedSuggestion = Math.min(selectedSuggestion + 1, suggestions.length - 1);
    } else if (event.key === 'ArrowUp') {
      event.preventDefault();
      selectedSuggestion = Math.max(selectedSuggestion - 1, -1);
    } else if (event.key === 'Escape') {
      showSuggestions = false;
      selectedSuggestion = -1;
    }
  }

  function handleSuggestionClick(suggestion) {
    searchQuery = suggestion;
    showSuggestions = false;
    performSearch();
  }

  function handleHistoryClick(historyItem) {
    searchQuery = historyItem;
    showSuggestions = false;
    performSearch();
  }

  function clearSearch() {
    searchQuery = '';
    searchResults = sampleData;
    applyFilters();
  }

  function clearFilters() {
    selectedCategory = 'all';
    selectedDateRange = 'all';
    selectedSort = 'relevance';
    applyFilters();
  }

  function handlePageChange(page) {
    currentPage = page;
  }

  function formatDate(dateString) {
    return new Date(dateString).toLocaleDateString();
  }

  function getRatingStars(rating) {
    const stars = Math.floor(rating);
    const hasHalfStar = rating % 1 >= 0.5;
    return '★'.repeat(stars) + (hasHalfStar ? '☆' : '') + '☆'.repeat(5 - stars - (hasHalfStar ? 1 : 0));
  }

  function getTypeIcon(type) {
    switch (type) {
      case 'video': return '🎥';
      case 'article': return '📄';
      case 'course': return '🎓';
      case 'tutorial': return '📚';
      default: return '📄';
    }
  }

  function getCategoryColor(category) {
    switch (category) {
      case 'tutorial': return '#4caf50';
      case 'guide': return '#2196f3';
      case 'course': return '#ff9800';
      case 'article': return '#9c27b0';
      default: return '#666';
    }
  }
</script>

<div class="search-interface">
  <div class="search-header">
    <h1>Advanced Search</h1>
    <div class="search-stats">
      {filteredResults.length} result{filteredResults.length !== 1 ? 's' : ''} found
    </div>
  </div>

  <div class="search-container">
    <div class="search-input-container">
      <div class="search-input-wrapper">
        <input
          type="text"
          bind:value={searchQuery}
          on:input={() => {
            showSuggestions = searchQuery.length > 0;
            selectedSuggestion = -1;
          }}
          on:keydown={handleKeydown}
          on:focus={() => showSuggestions = searchQuery.length > 0}
          on:blur={() => setTimeout(() => showSuggestions = false, 200)}
          placeholder="Search for tutorials, guides, courses..."
          class="search-input"
        />
        <button 
          on:click={handleSearch}
          disabled={isLoading}
          class="search-btn"
        >
          {isLoading ? '⏳' : '🔍'}
        </button>
        {#if searchQuery}
          <button 
            on:click={clearSearch}
            class="clear-btn"
          >
            ✕
          </button>
        {/if}
      </div>

      {#if showSuggestions}
        <div class="suggestions-dropdown">
          {#if searchHistory.length > 0}
            <div class="suggestions-section">
              <div class="suggestions-header">Recent Searches</div>
              {#each searchHistory.slice(0, 5) as historyItem}
                <div 
                  class="suggestion-item"
                  on:click={() => handleHistoryClick(historyItem)}
                >
                  🕒 {historyItem}
                </div>
              {/each}
            </div>
          {/if}
          
          {#if suggestions.length > 0}
            <div class="suggestions-section">
              <div class="suggestions-header">Suggestions</div>
              {#each suggestions as suggestion, index}
                <div 
                  class="suggestion-item"
                  class:selected={selectedSuggestion === index}
                  on:click={() => handleSuggestionClick(suggestion)}
                >
                  💡 {suggestion}
                </div>
              {/each}
            </div>
          {/if}
        </div>
      {/if}
    </div>

    <div class="search-controls">
      <div class="control-group">
        <button 
          on:click={() => showFilters = !showFilters}
          class="control-btn"
        >
          {showFilters ? 'Hide' : 'Show'} Filters
        </button>
        <button 
          on:click={() => showSortOptions = !showSortOptions}
          class="control-btn"
        >
          Sort: {sortOptions.find(s => s.value === selectedSort)?.label}
        </button>
        <button 
          on:click={clearFilters}
          class="control-btn secondary"
        >
          Clear Filters
        </button>
      </div>

      <div class="view-controls">
        {#each viewOptions as view}
          <button 
            on:click={() => selectedView = view.value}
            class="view-btn"
            class:active={selectedView === view.value}
            title={view.label}
          >
            {view.icon}
          </button>
        {/each}
      </div>
    </div>

    {#if showFilters}
      <div class="filters-panel">
        <div class="filter-row">
          <div class="filter-group">
            <label class="filter-label">Category</label>
            <select bind:value={selectedCategory} class="filter-select">
              {#each categories as category}
                <option value={category.value}>{category.label}</option>
              {/each}
            </select>
          </div>
          
          <div class="filter-group">
            <label class="filter-label">Date Range</label>
            <select bind:value={selectedDateRange} class="filter-select">
              {#each dateRanges as range}
                <option value={range.value}>{range.label}</option>
              {/each}
            </select>
          </div>
          
          <div class="filter-group">
            <label class="filter-label">Sort By</label>
            <select bind:value={selectedSort} class="filter-select">
              {#each sortOptions as option}
                <option value={option.value}>{option.label}</option>
              {/each}
            </select>
          </div>
        </div>
      </div>
    {/if}

    {#if showSortOptions}
      <div class="sort-panel">
        <div class="sort-options">
          {#each sortOptions as option}
            <button 
              on:click={() => { selectedSort = option.value; showSortOptions = false; }}
              class="sort-option"
              class:active={selectedSort === option.value}
            >
              {option.label}
            </button>
          {/each}
        </div>
      </div>
    {/if}
  </div>

  <div class="search-results">
    {#if isLoading}
      <div class="loading-state">
        <div class="loading-spinner"></div>
        <span>Searching...</span>
      </div>
    {:else if paginatedResults.length === 0}
      <div class="no-results">
        <div class="no-results-icon">🔍</div>
        <h3>No results found</h3>
        <p>Try adjusting your search terms or filters</p>
      </div>
    {:else}
      <div class="results-container" class:grid-view={selectedView === 'grid'} class:compact-view={selectedView === 'compact'}>
        {#each paginatedResults as result}
          <div class="result-item">
            <div class="result-header">
              <div class="result-type">
                <span class="type-icon">{getTypeIcon(result.type)}</span>
                <span class="type-label">{result.type}</span>
              </div>
              <div 
                class="result-category"
                style="background-color: {getCategoryColor(result.category)}"
              >
                {result.category}
              </div>
            </div>
            
            <div class="result-content">
              <h3 class="result-title">{result.title}</h3>
              <p class="result-description">{result.description}</p>
              
              <div class="result-meta">
                <div class="result-author">
                  <span class="author-label">By:</span>
                  <span class="author-name">{result.author}</span>
                </div>
                <div class="result-date">{formatDate(result.date)}</div>
                <div class="result-rating">
                  <span class="rating-stars">{getRatingStars(result.rating)}</span>
                  <span class="rating-value">{result.rating}</span>
                </div>
                <div class="result-views">
                  <span class="views-count">{result.views} views</span>
                </div>
              </div>
              
              <div class="result-tags">
                {#each result.tags as tag}
                  <span class="result-tag">#{tag}</span>
                {/each}
              </div>
            </div>
            
            <div class="result-actions">
              <button class="action-btn primary">View</button>
              <button class="action-btn secondary">Save</button>
              <button class="action-btn secondary">Share</button>
            </div>
          </div>
        {/each}
      </div>

      {#if totalPages > 1}
        <div class="pagination">
          <button 
            on:click={() => handlePageChange(currentPage - 1)}
            disabled={currentPage === 1}
            class="pagination-btn"
          >
            Previous
          </button>
          
          {#each Array(totalPages) as _, i}
            <button
              on:click={() => handlePageChange(i + 1)}
              class="pagination-btn"
              class:active={currentPage === i + 1}
            >
              {i + 1}
            </button>
          {/each}
          
          <button 
            on:click={() => handlePageChange(currentPage + 1)}
            disabled={currentPage === totalPages}
            class="pagination-btn"
          >
            Next
          </button>
        </div>
      {/if}
    {/if}
  </div>
</div>

<style>
  .search-interface {
    max-width: 1200px;
    margin: 0 auto;
    padding: 20px;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  }

  .search-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 30px;
    padding-bottom: 15px;
    border-bottom: 2px solid #e0e0e0;
  }

  .search-header h1 {
    margin: 0;
    color: #333;
    font-size: 28px;
  }

  .search-stats {
    color: #666;
    font-size: 14px;
    font-weight: 500;
  }

  .search-container {
    background: white;
    border-radius: 8px;
    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
    padding: 20px;
    margin-bottom: 30px;
  }

  .search-input-container {
    position: relative;
    margin-bottom: 20px;
  }

  .search-input-wrapper {
    display: flex;
    align-items: center;
    border: 2px solid #e0e0e0;
    border-radius: 8px;
    overflow: hidden;
    transition: border-color 0.3s ease;
  }

  .search-input-wrapper:focus-within {
    border-color: #4caf50;
  }

  .search-input {
    flex: 1;
    padding: 15px 20px;
    border: none;
    outline: none;
    font-size: 16px;
    color: #333;
  }

  .search-input::placeholder {
    color: #999;
  }

  .search-btn {
    padding: 15px 20px;
    background: #4caf50;
    color: white;
    border: none;
    cursor: pointer;
    font-size: 16px;
    transition: background-color 0.3s ease;
  }

  .search-btn:hover:not(:disabled) {
    background: #45a049;
  }

  .search-btn:disabled {
    background: #ccc;
    cursor: not-allowed;
  }

  .clear-btn {
    padding: 15px 20px;
    background: #f5f5f5;
    color: #666;
    border: none;
    cursor: pointer;
    font-size: 16px;
    transition: background-color 0.3s ease;
  }

  .clear-btn:hover {
    background: #e0e0e0;
  }

  .suggestions-dropdown {
    position: absolute;
    top: 100%;
    left: 0;
    right: 0;
    background: white;
    border: 1px solid #e0e0e0;
    border-radius: 8px;
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
    z-index: 100;
    max-height: 300px;
    overflow-y: auto;
  }

  .suggestions-section {
    border-bottom: 1px solid #f0f0f0;
  }

  .suggestions-section:last-child {
    border-bottom: none;
  }

  .suggestions-header {
    padding: 10px 15px;
    background: #f8f9fa;
    font-weight: 600;
    color: #333;
    font-size: 12px;
    text-transform: uppercase;
    letter-spacing: 0.5px;
  }

  .suggestion-item {
    padding: 12px 15px;
    cursor: pointer;
    transition: background-color 0.3s ease;
    font-size: 14px;
    color: #333;
  }

  .suggestion-item:hover,
  .suggestion-item.selected {
    background: #f0f8ff;
  }

  .search-controls {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 20px;
  }

  .control-group {
    display: flex;
    gap: 10px;
    align-items: center;
  }

  .control-btn {
    padding: 8px 16px;
    background: #f5f5f5;
    border: 1px solid #ddd;
    border-radius: 6px;
    cursor: pointer;
    font-size: 14px;
    color: #333;
    transition: all 0.3s ease;
  }

  .control-btn:hover {
    background: #e0e0e0;
    border-color: #4caf50;
  }

  .control-btn.secondary {
    background: #ffebee;
    border-color: #f44336;
    color: #f44336;
  }

  .control-btn.secondary:hover {
    background: #f44336;
    color: white;
  }

  .view-controls {
    display: flex;
    gap: 5px;
  }

  .view-btn {
    padding: 8px 12px;
    background: #f5f5f5;
    border: 1px solid #ddd;
    border-radius: 6px;
    cursor: pointer;
    font-size: 16px;
    transition: all 0.3s ease;
  }

  .view-btn:hover {
    background: #e0e0e0;
  }

  .view-btn.active {
    background: #4caf50;
    color: white;
    border-color: #4caf50;
  }

  .filters-panel {
    background: #f8f9fa;
    border: 1px solid #e0e0e0;
    border-radius: 8px;
    padding: 20px;
    margin-bottom: 20px;
  }

  .filter-row {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 20px;
  }

  .filter-group {
    display: flex;
    flex-direction: column;
    gap: 5px;
  }

  .filter-label {
    font-weight: 600;
    color: #333;
    font-size: 14px;
  }

  .filter-select {
    padding: 10px 12px;
    border: 1px solid #ddd;
    border-radius: 6px;
    font-size: 14px;
    background: white;
    cursor: pointer;
    transition: border-color 0.3s ease;
  }

  .filter-select:focus {
    outline: none;
    border-color: #4caf50;
  }

  .sort-panel {
    background: #f8f9fa;
    border: 1px solid #e0e0e0;
    border-radius: 8px;
    padding: 15px;
    margin-bottom: 20px;
  }

  .sort-options {
    display: flex;
    gap: 10px;
    flex-wrap: wrap;
  }

  .sort-option {
    padding: 8px 16px;
    background: white;
    border: 1px solid #ddd;
    border-radius: 6px;
    cursor: pointer;
    font-size: 14px;
    color: #333;
    transition: all 0.3s ease;
  }

  .sort-option:hover {
    background: #f0f0f0;
  }

  .sort-option.active {
    background: #4caf50;
    color: white;
    border-color: #4caf50;
  }

  .search-results {
    background: white;
    border-radius: 8px;
    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
    padding: 20px;
  }

  .loading-state {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding: 60px;
    color: #666;
  }

  .loading-spinner {
    width: 40px;
    height: 40px;
    border: 4px solid rgba(76, 175, 80, 0.3);
    border-top: 4px solid #4caf50;
    border-radius: 50%;
    animation: spin 1s linear infinite;
    margin-bottom: 15px;
  }

  @keyframes spin {
    0% { transform: rotate(0deg); }
    100% { transform: rotate(360deg); }
  }

  .no-results {
    text-align: center;
    padding: 60px;
    color: #666;
  }

  .no-results-icon {
    font-size: 48px;
    margin-bottom: 20px;
  }

  .no-results h3 {
    margin: 0 0 10px 0;
    color: #333;
    font-size: 20px;
  }

  .no-results p {
    margin: 0;
    font-size: 14px;
  }

  .results-container {
    display: flex;
    flex-direction: column;
    gap: 20px;
  }

  .results-container.grid-view {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
    gap: 20px;
  }

  .results-container.compact-view {
    gap: 10px;
  }

  .result-item {
    border: 1px solid #e0e0e0;
    border-radius: 8px;
    padding: 20px;
    transition: all 0.3s ease;
  }

  .result-item:hover {
    border-color: #4caf50;
    box-shadow: 0 4px 12px rgba(76, 175, 80, 0.2);
  }

  .result-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 15px;
  }

  .result-type {
    display: flex;
    align-items: center;
    gap: 5px;
    font-size: 12px;
    color: #666;
  }

  .type-icon {
    font-size: 14px;
  }

  .result-category {
    padding: 4px 8px;
    border-radius: 4px;
    color: white;
    font-size: 11px;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.5px;
  }

  .result-content {
    margin-bottom: 15px;
  }

  .result-title {
    margin: 0 0 10px 0;
    color: #333;
    font-size: 18px;
    font-weight: 600;
    line-height: 1.4;
  }

  .result-description {
    margin: 0 0 15px 0;
    color: #666;
    font-size: 14px;
    line-height: 1.5;
  }

  .result-meta {
    display: flex;
    flex-wrap: wrap;
    gap: 15px;
    margin-bottom: 10px;
    font-size: 12px;
    color: #666;
  }

  .result-author {
    display: flex;
    align-items: center;
    gap: 4px;
  }

  .author-label {
    font-weight: 600;
  }

  .author-name {
    color: #333;
  }

  .result-date {
    color: #999;
  }

  .result-rating {
    display: flex;
    align-items: center;
    gap: 5px;
  }

  .rating-stars {
    color: #ff9800;
    font-size: 14px;
  }

  .rating-value {
    font-weight: 600;
    color: #333;
  }

  .views-count {
    color: #999;
  }

  .result-tags {
    display: flex;
    flex-wrap: wrap;
    gap: 5px;
  }

  .result-tag {
    padding: 2px 6px;
    background: #f0f0f0;
    color: #666;
    border-radius: 3px;
    font-size: 11px;
    font-weight: 500;
  }

  .result-actions {
    display: flex;
    gap: 10px;
  }

  .action-btn {
    padding: 6px 12px;
    border: 1px solid #ddd;
    border-radius: 4px;
    cursor: pointer;
    font-size: 12px;
    font-weight: 600;
    transition: all 0.3s ease;
  }

  .action-btn.primary {
    background: #4caf50;
    color: white;
    border-color: #4caf50;
  }

  .action-btn.primary:hover {
    background: #45a049;
  }

  .action-btn.secondary {
    background: white;
    color: #666;
  }

  .action-btn.secondary:hover {
    background: #f0f0f0;
    color: #333;
  }

  .pagination {
    display: flex;
    justify-content: center;
    gap: 5px;
    margin-top: 30px;
  }

  .pagination-btn {
    padding: 8px 12px;
    border: 1px solid #ddd;
    background: white;
    cursor: pointer;
    border-radius: 4px;
    font-size: 14px;
    color: #333;
    transition: all 0.3s ease;
  }

  .pagination-btn:hover:not(:disabled) {
    background: #f5f5f5;
    border-color: #4caf50;
  }

  .pagination-btn:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  .pagination-btn.active {
    background: #4caf50;
    color: white;
    border-color: #4caf50;
  }

  @media (max-width: 768px) {
    .search-interface {
      padding: 15px;
    }
    
    .search-header {
      flex-direction: column;
      gap: 15px;
      align-items: stretch;
    }
    
    .search-controls {
      flex-direction: column;
      gap: 15px;
      align-items: stretch;
    }
    
    .control-group {
      justify-content: center;
      flex-wrap: wrap;
    }
    
    .view-controls {
      justify-content: center;
    }
    
    .filter-row {
      grid-template-columns: 1fr;
      gap: 15px;
    }
    
    .results-container.grid-view {
      grid-template-columns: 1fr;
    }
    
    .result-meta {
      flex-direction: column;
      gap: 8px;
    }
    
    .result-actions {
      flex-direction: column;
    }
  }

  @media (max-width: 480px) {
    .search-interface {
      padding: 10px;
    }
    
    .search-container {
      padding: 15px;
    }
    
    .search-results {
      padding: 15px;
    }
    
    .result-item {
      padding: 15px;
    }
    
    .result-title {
      font-size: 16px;
    }
    
    .result-description {
      font-size: 13px;
    }
    
    .pagination {
      flex-wrap: wrap;
    }
  }
</style>
