// scenarios/advanced/web-frameworks/vue/src/App.vue
<template>
  <div id="app">
    <nav class="navbar">
      <div class="container">
        <router-link to="/" class="navbar-brand">
          Accessibility Benchmark - Vue.js
        </router-link>
        <div class="navbar-nav">
          <router-link to="/" class="nav-link">Home</router-link>
          <router-link to="/data-table" class="nav-link">Data Table</router-link>
          <router-link to="/wizard" class="nav-link">Wizard</router-link>
          <router-link to="/dashboard" class="nav-link">Dashboard</router-link>
          <router-link to="/media-player" class="nav-link">Media Player</router-link>
          <router-link to="/shopping-cart" class="nav-link">Shopping Cart</router-link>
          <router-link to="/calendar" class="nav-link">Calendar</router-link>
          <router-link to="/rich-text-editor" class="nav-link">Rich Text Editor</router-link>
          <router-link to="/search-interface" class="nav-link">Search Interface</router-link>
          <router-link to="/interactive-map" class="nav-link">Interactive Map</router-link>
          <router-link to="/social-feed" class="nav-link">Social Feed</router-link>
        </div>
      </div>
    </nav>

    <main class="main-content">
      <router-view />
    </main>
  </div>
</template>

<script>
export default {
  name: 'App'
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  color: #2c3e50;
  min-height: 100vh;
  background-color: #f5f7fa;
}

.navbar {
  background-color: #007bff;
  color: white;
  padding: 1rem 0;
  box-shadow: 0 2px 4px rgba(0,0,0,0.1);
}

.navbar .container {
  display: flex;
  justify-content: space-between;
  align-items: center;
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 20px;
}

.navbar-brand {
  color: white;
  text-decoration: none;
  font-size: 1.5rem;
  font-weight: bold;
}

.navbar-nav {
  display: flex;
  gap: 1rem;
}

.nav-link {
  color: white;
  text-decoration: none;
  padding: 0.5rem 1rem;
  border-radius: 4px;
  transition: background-color 0.2s;
}

.nav-link:hover {
  background-color: rgba(255, 255, 255, 0.1);
}

.main-content {
  min-height: calc(100vh - 80px);
  padding: 2rem 0;
}

.container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 20px;
}

.card {
  background: white;
  border-radius: 8px;
  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
  padding: 20px;
  margin-bottom: 20px;
}

.btn {
  background-color: #007bff;
  color: white;
  border: none;
  padding: 10px 20px;
  border-radius: 4px;
  cursor: pointer;
  font-size: 14px;
  font-weight: 500;
  transition: background-color 0.2s;
}

.btn:hover {
  background-color: #0056b3;
}

.btn:disabled {
  background-color: #6c757d;
  cursor: not-allowed;
}

.btn-secondary {
  background-color: #6c757d;
}

.btn-secondary:hover {
  background-color: #545b62;
}

.form-group {
  margin-bottom: 15px;
}

.form-label {
  display: block;
  margin-bottom: 5px;
  font-weight: 600;
  color: #333;
}

.form-control {
  width: 100%;
  padding: 8px 12px;
  border: 1px solid #ddd;
  border-radius: 4px;
  font-size: 14px;
}

.form-control:focus {
  outline: none;
  border-color: #007bff;
  box-shadow: 0 0 0 2px rgba(0, 123, 255, 0.25);
}

.table {
  width: 100%;
  border-collapse: collapse;
  margin-top: 15px;
}

.table th,
.table td {
  padding: 12px;
  text-align: left;
  border-bottom: 1px solid #ddd;
}

.table th {
  background-color: #f8f9fa;
  font-weight: 600;
  color: #333;
}

.table tbody tr:hover {
  background-color: #f5f5f5;
}

.alert {
  padding: 12px 16px;
  margin-bottom: 20px;
  border: 1px solid transparent;
  border-radius: 4px;
}

.alert-success {
  color: #155724;
  background-color: #d4edda;
  border-color: #c3e6cb;
}

.alert-danger {
  color: #721c24;
  background-color: #f8d7da;
  border-color: #f5c6cb;
}

.alert-warning {
  color: #856404;
  background-color: #fff3cd;
  border-color: #ffeaa7;
}

.alert-info {
  color: #0c5460;
  background-color: #d1ecf1;
  border-color: #bee5eb;
}

.modal {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.5);
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 1000;
}

.modal-content {
  background: white;
  padding: 20px;
  border-radius: 8px;
  max-width: 500px;
  width: 90%;
  max-height: 80vh;
  overflow-y: auto;
}

.modal-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
  padding-bottom: 10px;
  border-bottom: 1px solid #eee;
}

.modal-title {
  margin: 0;
  font-size: 18px;
  font-weight: 600;
}

.modal-close {
  background: none;
  border: none;
  font-size: 24px;
  cursor: pointer;
  color: #666;
}

.modal-close:hover {
  color: #000;
}

.modal-footer {
  display: flex;
  justify-content: flex-end;
  gap: 10px;
  margin-top: 20px;
  padding-top: 10px;
  border-top: 1px solid #eee;
}

.loading {
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 40px;
}

.spinner {
  border: 4px solid #f3f3f3;
  border-top: 4px solid #007bff;
  border-radius: 50%;
  width: 40px;
  height: 40px;
  animation: spin 1s linear infinite;
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

.grid {
  display: grid;
  gap: 20px;
}

.grid-2 {
  grid-template-columns: repeat(2, 1fr);
}

.grid-3 {
  grid-template-columns: repeat(3, 1fr);
}

.grid-4 {
  grid-template-columns: repeat(4, 1fr);
}

@media (max-width: 768px) {
  .grid-2,
  .grid-3,
  .grid-4 {
    grid-template-columns: 1fr;
  }
}

.text-center {
  text-align: center;
}

.text-left {
  text-align: left;
}

.text-right {
  text-align: right;
}

.mb-0 { margin-bottom: 0; }
.mb-1 { margin-bottom: 0.25rem; }
.mb-2 { margin-bottom: 0.5rem; }
.mb-3 { margin-bottom: 1rem; }
.mb-4 { margin-bottom: 1.5rem; }
.mb-5 { margin-bottom: 3rem; }

.mt-0 { margin-top: 0; }
.mt-1 { margin-top: 0.25rem; }
.mt-2 { margin-top: 0.5rem; }
.mt-3 { margin-top: 1rem; }
.mt-4 { margin-top: 1.5rem; }
.mt-5 { margin-top: 3rem; }

.p-0 { padding: 0; }
.p-1 { padding: 0.25rem; }
.p-2 { padding: 0.5rem; }
.p-3 { padding: 1rem; }
.p-4 { padding: 1.5rem; }
.p-5 { padding: 3rem; }

.d-flex {
  display: flex;
}

.justify-content-center {
  justify-content: center;
}

.justify-content-between {
  justify-content: space-between;
}

.align-items-center {
  align-items: center;
}

.w-100 {
  width: 100%;
}

.h-100 {
  height: 100%;
}
</style>

// scenarios/advanced/cross-platform/tauri/src/App.svelte
<script>
  import { invoke } from '@tauri-apps/api/tauri'
  import { onMount } from 'svelte'
  
  let currentView = 'data-table'
  let data = null
  let loading = false
  
  const views = [
    { id: 'data-table', name: 'Data Table', icon: '📊' },
    { id: 'wizard', name: 'Multi-Step Wizard', icon: '🧙' },
    { id: 'dashboard', name: 'Dashboard Widget', icon: '📈' },
    { id: 'media-player', name: 'Media Player', icon: '🎵' },
    { id: 'shopping-cart', name: 'Shopping Cart', icon: '🛒' },
    { id: 'calendar', name: 'Calendar', icon: '📅' },
    { id: 'rich-text', name: 'Rich Text Editor', icon: '✏️' },
    { id: 'search', name: 'Search Interface', icon: '🔍' },
    { id: 'map', name: 'Interactive Map', icon: '🗺️' },
    { id: 'social-feed', name: 'Social Media Feed', icon: '📱' }
  ]
  
  async function loadData(view) {
    loading = true
    currentView = view
    
    try {
      let command = ''
      switch(view) {
        case 'data-table':
          command = 'get_data_table_data'
          break
        case 'wizard':
          command = 'get_wizard_data'
          break
        case 'dashboard':
          command = 'get_dashboard_data'
          break
        case 'media-player':
          command = 'get_media_player_data'
          break
        case 'shopping-cart':
          command = 'get_shopping_cart_data'
          break
        case 'calendar':
          command = 'get_calendar_data'
          break
        case 'rich-text':
          command = 'get_rich_text_data'
          break
        case 'search':
          command = 'get_search_data'
          break
        case 'map':
          command = 'get_map_data'
          break
        case 'social-feed':
          command = 'get_social_feed_data'
          break
      }
      
      if (command) {
        data = await invoke(command)
      }
    } catch (error) {
      console.error('Error loading data:', error)
    } finally {
      loading = false
    }
  }
  
  onMount(() => {
    loadData('data-table')
  })
</script>

<main>
  <header>
    <h1>Accessibility Benchmark Testing</h1>
    <p>Advanced Scenarios - Tauri Implementation</p>
  </header>
  
  <nav>
    <div class="nav-grid">
      {#each views as view}
        <button 
          class="nav-item {currentView === view.id ? 'active' : ''}"
          on:click={() => loadData(view.id)}
        >
          <span class="nav-icon">{view.icon}</span>
          <span class="nav-name">{view.name}</span>
        </button>
      {/each}
    </div>
  </nav>
  
  <section class="content">
    {#if loading}
      <div class="loading">
        <div class="spinner"></div>
        <p>Loading {views.find(v => v.id === currentView)?.name}...</p>
      </div>
    {:else if data}
      <div class="scenario-content">
        {#if currentView === 'data-table'}
          <DataTable data={data} />
        {:else if currentView === 'wizard'}
          <Wizard data={data} />
        {:else if currentView === 'dashboard'}
          <Dashboard data={data} />
        {:else if currentView === 'media-player'}
          <MediaPlayer data={data} />
        {:else if currentView === 'shopping-cart'}
          <ShoppingCart data={data} />
        {:else if currentView === 'calendar'}
          <Calendar data={data} />
        {:else if currentView === 'rich-text'}
          <RichTextEditor data={data} />
        {:else if currentView === 'search'}
          <SearchInterface data={data} />
        {:else if currentView === 'map'}
          <InteractiveMap data={data} />
        {:else if currentView === 'social-feed'}
          <SocialFeed data={data} />
        {/if}
      </div>
    {/if}
  </section>
</main>

<style>
  :global(body) {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 20px;
    background: #f5f7fa;
  }
  
  main {
    max-width: 1400px;
    margin: 0 auto;
  }
  
  header {
    background: white;
    padding: 20px;
    border-radius: 12px;
    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
    margin-bottom: 20px;
    text-align: center;
  }
  
  header h1 {
    margin: 0 0 10px 0;
    color: #333;
    font-size: 28px;
  }
  
  header p {
    margin: 0;
    color: #666;
    font-size: 16px;
  }
  
  nav {
    background: white;
    padding: 20px;
    border-radius: 12px;
    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
    margin-bottom: 20px;
  }
  
  .nav-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 15px;
  }
  
  .nav-item {
    display: flex;
    flex-direction: column;
    align-items: center;
    padding: 20px;
    border: 2px solid #e9ecef;
    border-radius: 8px;
    background: white;
    cursor: pointer;
    transition: all 0.3s ease;
    text-decoration: none;
    color: #333;
  }
  
  .nav-item:hover {
    border-color: #007bff;
    background: #f8f9fa;
    transform: translateY(-2px);
  }
  
  .nav-item.active {
    border-color: #007bff;
    background: #e3f2fd;
  }
  
  .nav-icon {
    font-size: 32px;
    margin-bottom: 10px;
  }
  
  .nav-name {
    font-size: 14px;
    font-weight: 600;
    text-align: center;
  }
  
  .content {
    background: white;
    border-radius: 12px;
    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
    min-height: 600px;
  }
  
  .loading {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding: 60px 20px;
    color: #666;
  }
  
  .spinner {
    width: 40px;
    height: 40px;
    border: 3px solid #f3f3f3;
    border-top: 3px solid #007bff;
    border-radius: 50%;
    animation: spin 1s linear infinite;
    margin-bottom: 20px;
  }
  
  @keyframes spin {
    0% { transform: rotate(0deg); }
    100% { transform: rotate(360deg); }
  }
  
  .scenario-content {
    padding: 20px;
  }
</style>
