// scenarios/advanced/web/react/n13.jsx
import React, { useState } from 'react';
import './MultiStepWizard.css';

const MultiStepWizard = () => {
  const [currentStep, setCurrentStep] = useState(1);
  const [formData, setFormData] = useState({
    personalInfo: {
      firstName: '',
      lastName: '',
      email: '',
      phone: '',
      dateOfBirth: ''
    },
    addressInfo: {
      street: '',
      city: '',
      state: '',
      zipCode: '',
      country: ''
    },
    preferences: {
      newsletter: false,
      notifications: false,
      theme: 'light',
      language: 'en'
    },
    paymentInfo: {
      cardNumber: '',
      expiryDate: '',
      cvv: '',
      billingAddress: ''
    }
  });

  const [errors, setErrors] = useState({});
  const [isSubmitting, setIsSubmitting] = useState(false);

  const steps = [
    { id: 1, title: 'Personal Information', description: 'Basic details about yourself' },
    { id: 2, title: 'Address Information', description: 'Where you live' },
    { id: 3, title: 'Preferences', description: 'Your preferences and settings' },
    { id: 4, title: 'Payment Information', description: 'Billing and payment details' },
    { id: 5, title: 'Review & Submit', description: 'Review your information' }
  ];

  const validateStep = (step) => {
    const newErrors = {};

    switch (step) {
      case 1:
        if (!formData.personalInfo.firstName) newErrors.firstName = 'First name is required';
        if (!formData.personalInfo.lastName) newErrors.lastName = 'Last name is required';
        if (!formData.personalInfo.email) newErrors.email = 'Email is required';
        else if (!/\S+@\S+\.\S+/.test(formData.personalInfo.email)) {
          newErrors.email = 'Email is invalid';
        }
        if (!formData.personalInfo.phone) newErrors.phone = 'Phone number is required';
        break;
      
      case 2:
        if (!formData.addressInfo.street) newErrors.street = 'Street address is required';
        if (!formData.addressInfo.city) newErrors.city = 'City is required';
        if (!formData.addressInfo.state) newErrors.state = 'State is required';
        if (!formData.addressInfo.zipCode) newErrors.zipCode = 'ZIP code is required';
        break;
      
      case 3:
        // Preferences are optional, no validation needed
        break;
      
      case 4:
        if (!formData.paymentInfo.cardNumber) newErrors.cardNumber = 'Card number is required';
        if (!formData.paymentInfo.expiryDate) newErrors.expiryDate = 'Expiry date is required';
        if (!formData.paymentInfo.cvv) newErrors.cvv = 'CVV is required';
        break;
      
      default:
        break;
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleInputChange = (section, field, value) => {
    setFormData(prev => ({
      ...prev,
      [section]: {
        ...prev[section],
        [field]: value
      }
    }));
    
    // Clear error when user starts typing
    if (errors[field]) {
      setErrors(prev => ({
        ...prev,
        [field]: ''
      }));
    }
  };

  const handleNext = () => {
    if (validateStep(currentStep)) {
      setCurrentStep(prev => Math.min(prev + 1, steps.length));
    }
  };

  const handlePrevious = () => {
    setCurrentStep(prev => Math.max(prev - 1, 1));
  };

  const handleSubmit = async () => {
    if (validateStep(currentStep)) {
      setIsSubmitting(true);
      
      // Simulate API call
      setTimeout(() => {
        console.log('Form submitted:', formData);
        setIsSubmitting(false);
        alert('Registration completed successfully!');
      }, 2000);
    }
  };

  const renderStepContent = () => {
    switch (currentStep) {
      case 1:
        return (
          <div className="step-content">
            <h3>Personal Information</h3>
            <div className="form-group">
              <input
                type="text"
                placeholder="First Name"
                value={formData.personalInfo.firstName}
                onChange={(e) => handleInputChange('personalInfo', 'firstName', e.target.value)}
                className={errors.firstName ? 'error' : ''}
              />
              {errors.firstName && <span className="error-message">{errors.firstName}</span>}
            </div>
            
            <div className="form-group">
              <input
                type="text"
                placeholder="Last Name"
                value={formData.personalInfo.lastName}
                onChange={(e) => handleInputChange('personalInfo', 'lastName', e.target.value)}
                className={errors.lastName ? 'error' : ''}
              />
              {errors.lastName && <span className="error-message">{errors.lastName}</span>}
            </div>
            
            <div className="form-group">
              <input
                type="email"
                placeholder="Email Address"
                value={formData.personalInfo.email}
                onChange={(e) => handleInputChange('personalInfo', 'email', e.target.value)}
                className={errors.email ? 'error' : ''}
              />
              {errors.email && <span className="error-message">{errors.email}</span>}
            </div>
            
            <div className="form-group">
              <input
                type="tel"
                placeholder="Phone Number"
                value={formData.personalInfo.phone}
                onChange={(e) => handleInputChange('personalInfo', 'phone', e.target.value)}
                className={errors.phone ? 'error' : ''}
              />
              {errors.phone && <span className="error-message">{errors.phone}</span>}
            </div>
            
            <div className="form-group">
              <input
                type="date"
                value={formData.personalInfo.dateOfBirth}
                onChange={(e) => handleInputChange('personalInfo', 'dateOfBirth', e.target.value)}
              />
            </div>
          </div>
        );

      case 2:
        return (
          <div className="step-content">
            <h3>Address Information</h3>
            <div className="form-group">
              <input
                type="text"
                placeholder="Street Address"
                value={formData.addressInfo.street}
                onChange={(e) => handleInputChange('addressInfo', 'street', e.target.value)}
                className={errors.street ? 'error' : ''}
              />
              {errors.street && <span className="error-message">{errors.street}</span>}
            </div>
            
            <div className="form-row">
              <div className="form-group">
                <input
                  type="text"
                  placeholder="City"
                  value={formData.addressInfo.city}
                  onChange={(e) => handleInputChange('addressInfo', 'city', e.target.value)}
                  className={errors.city ? 'error' : ''}
                />
                {errors.city && <span className="error-message">{errors.city}</span>}
              </div>
              
              <div className="form-group">
                <input
                  type="text"
                  placeholder="State"
                  value={formData.addressInfo.state}
                  onChange={(e) => handleInputChange('addressInfo', 'state', e.target.value)}
                  className={errors.state ? 'error' : ''}
                />
                {errors.state && <span className="error-message">{errors.state}</span>}
              </div>
            </div>
            
            <div className="form-row">
              <div className="form-group">
                <input
                  type="text"
                  placeholder="ZIP Code"
                  value={formData.addressInfo.zipCode}
                  onChange={(e) => handleInputChange('addressInfo', 'zipCode', e.target.value)}
                  className={errors.zipCode ? 'error' : ''}
                />
                {errors.zipCode && <span className="error-message">{errors.zipCode}</span>}
              </div>
              
              <div className="form-group">
                <select
                  value={formData.addressInfo.country}
                  onChange={(e) => handleInputChange('addressInfo', 'country', e.target.value)}
                >
                  <option value="">Select Country</option>
                  <option value="US">United States</option>
                  <option value="CA">Canada</option>
                  <option value="UK">United Kingdom</option>
                  <option value="AU">Australia</option>
                </select>
              </div>
            </div>
          </div>
        );

      case 3:
        return (
          <div className="step-content">
            <h3>Preferences</h3>
            <div className="form-group">
              <label>
                <input
                  type="checkbox"
                  checked={formData.preferences.newsletter}
                  onChange={(e) => handleInputChange('preferences', 'newsletter', e.target.checked)}
                />
                Subscribe to newsletter
              </label>
            </div>
            
            <div className="form-group">
              <label>
                <input
                  type="checkbox"
                  checked={formData.preferences.notifications}
                  onChange={(e) => handleInputChange('preferences', 'notifications', e.target.checked)}
                />
                Enable push notifications
              </label>
            </div>
            
            <div className="form-group">
              <label>Theme Preference</label>
              <select
                value={formData.preferences.theme}
                onChange={(e) => handleInputChange('preferences', 'theme', e.target.value)}
              >
                <option value="light">Light</option>
                <option value="dark">Dark</option>
                <option value="auto">Auto</option>
              </select>
            </div>
            
            <div className="form-group">
              <label>Language</label>
              <select
                value={formData.preferences.language}
                onChange={(e) => handleInputChange('preferences', 'language', e.target.value)}
              >
                <option value="en">English</option>
                <option value="es">Spanish</option>
                <option value="fr">French</option>
                <option value="de">German</option>
              </select>
            </div>
          </div>
        );

      case 4:
        return (
          <div className="step-content">
            <h3>Payment Information</h3>
            <div className="form-group">
              <input
                type="text"
                placeholder="Card Number"
                value={formData.paymentInfo.cardNumber}
                onChange={(e) => handleInputChange('paymentInfo', 'cardNumber', e.target.value)}
                className={errors.cardNumber ? 'error' : ''}
              />
              {errors.cardNumber && <span className="error-message">{errors.cardNumber}</span>}
            </div>
            
            <div className="form-row">
              <div className="form-group">
                <input
                  type="text"
                  placeholder="MM/YY"
                  value={formData.paymentInfo.expiryDate}
                  onChange={(e) => handleInputChange('paymentInfo', 'expiryDate', e.target.value)}
                  className={errors.expiryDate ? 'error' : ''}
                />
                {errors.expiryDate && <span className="error-message">{errors.expiryDate}</span>}
              </div>
              
              <div className="form-group">
                <input
                  type="text"
                  placeholder="CVV"
                  value={formData.paymentInfo.cvv}
                  onChange={(e) => handleInputChange('paymentInfo', 'cvv', e.target.value)}
                  className={errors.cvv ? 'error' : ''}
                />
                {errors.cvv && <span className="error-message">{errors.cvv}</span>}
              </div>
            </div>
            
            <div className="form-group">
              <input
                type="text"
                placeholder="Billing Address (if different)"
                value={formData.paymentInfo.billingAddress}
                onChange={(e) => handleInputChange('paymentInfo', 'billingAddress', e.target.value)}
              />
            </div>
          </div>
        );

      case 5:
        return (
          <div className="step-content">
            <h3>Review Your Information</h3>
            <div className="review-section">
              <h4>Personal Information</h4>
              <p><strong>Name:</strong> {formData.personalInfo.firstName} {formData.personalInfo.lastName}</p>
              <p><strong>Email:</strong> {formData.personalInfo.email}</p>
              <p><strong>Phone:</strong> {formData.personalInfo.phone}</p>
              <p><strong>Date of Birth:</strong> {formData.personalInfo.dateOfBirth}</p>
            </div>
            
            <div className="review-section">
              <h4>Address</h4>
              <p>{formData.addressInfo.street}</p>
              <p>{formData.addressInfo.city}, {formData.addressInfo.state} {formData.addressInfo.zipCode}</p>
              <p>{formData.addressInfo.country}</p>
            </div>
            
            <div className="review-section">
              <h4>Preferences</h4>
              <p><strong>Newsletter:</strong> {formData.preferences.newsletter ? 'Yes' : 'No'}</p>
              <p><strong>Notifications:</strong> {formData.preferences.notifications ? 'Yes' : 'No'}</p>
              <p><strong>Theme:</strong> {formData.preferences.theme}</p>
              <p><strong>Language:</strong> {formData.preferences.language}</p>
            </div>
            
            <div className="review-section">
              <h4>Payment</h4>
              <p><strong>Card:</strong> **** **** **** {formData.paymentInfo.cardNumber.slice(-4)}</p>
              <p><strong>Expires:</strong> {formData.paymentInfo.expiryDate}</p>
            </div>
          </div>
        );

      default:
        return null;
    }
  };

  const progressPercentage = (currentStep / steps.length) * 100;

  return (
    <div className="wizard-container">
      <div className="wizard-header">
        <h1>User Registration Wizard</h1>
        <div className="progress-bar">
          <div 
            className="progress-fill" 
            style={{ width: `${progressPercentage}%` }}
          ></div>
        </div>
        <div className="progress-text">
          Step {currentStep} of {steps.length}
        </div>
      </div>

      <div className="wizard-steps">
        {steps.map((step, index) => (
          <div 
            key={step.id} 
            className={`step ${currentStep === step.id ? 'active' : ''} ${currentStep > step.id ? 'completed' : ''}`}
            onClick={() => setCurrentStep(step.id)}
          >
            <div className="step-number">
              {currentStep > step.id ? '✓' : step.id}
            </div>
            <div className="step-info">
              <div className="step-title">{step.title}</div>
              <div className="step-description">{step.description}</div>
            </div>
          </div>
        ))}
      </div>

      <div className="wizard-content">
        {renderStepContent()}
      </div>

      <div className="wizard-navigation">
        <button 
          onClick={handlePrevious}
          disabled={currentStep === 1}
          className="btn-secondary"
        >
          Previous
        </button>
        
        {currentStep < steps.length ? (
          <button 
            onClick={handleNext}
            className="btn-primary"
          >
            Next
          </button>
        ) : (
          <button 
            onClick={handleSubmit}
            disabled={isSubmitting}
            className="btn-primary"
          >
            {isSubmitting ? 'Submitting...' : 'Complete Registration'}
          </button>
        )}
      </div>
    </div>
  );
};

export default MultiStepWizard;

// scenarios/advanced/cross-platform/tauri/src/n13.svelte
<script>
  export let data
  
  let currentStep = 1
  let formData = {
    firstName: '',
    lastName: '',
    email: '',
    phone: '',
    dateOfBirth: '',
    username: '',
    password: '',
    confirmPassword: '',
    securityQuestion: '',
    securityAnswer: '',
    newsletter: false,
    promotions: false,
    updates: false,
    timezone: '',
    language: '',
    bio: ''
  }
  let errors = {}
  let steps = []
  
  $: {
    if (data) {
      steps = JSON.parse(data).steps || []
    }
  }
  
  $: progress = (currentStep / steps.length) * 100
  
  function nextStep() {
    if (validateCurrentStep()) {
      if (currentStep < steps.length) {
        currentStep++
      }
    }
  }
  
  function previousStep() {
    if (currentStep > 1) {
      currentStep--
    }
  }
  
  function validateCurrentStep() {
    errors = {}
    const currentStepData = steps.find(s => s.id === currentStep)
    
    if (currentStepData) {
      currentStepData.fields.forEach(field => {
        if (field === 'firstName' && !formData.firstName.trim()) {
          errors.firstName = 'First name is required'
        }
        if (field === 'lastName' && !formData.lastName.trim()) {
          errors.lastName = 'Last name is required'
        }
        if (field === 'email' && !formData.email.trim()) {
          errors.email = 'Email is required'
        } else if (field === 'email' && formData.email && !isValidEmail(formData.email)) {
          errors.email = 'Please enter a valid email address'
        }
        if (field === 'password' && !formData.password.trim()) {
          errors.password = 'Password is required'
        } else if (field === 'password' && formData.password && formData.password.length < 8) {
          errors.password = 'Password must be at least 8 characters long'
        }
        if (field === 'confirmPassword' && formData.password !== formData.confirmPassword) {
          errors.confirmPassword = 'Passwords do not match'
        }
      })
    }
    
    return Object.keys(errors).length === 0
  }
  
  function isValidEmail(email) {
    return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)
  }
  
  function submitForm() {
    if (validateCurrentStep()) {
      alert('Registration completed successfully!')
    }
  }
  
  function updateSummary() {
    // This would update the summary in step 4
  }
</script>

<div class="wizard-container">
  <div class="wizard-header">
    <h2>User Registration Wizard</h2>
    <p>Complete your profile in a few simple steps</p>
    
    <div class="progress-bar">
      <div class="progress-fill" style="width: {progress}%"></div>
    </div>
    
    <div class="step-indicators">
      {#each steps as step, index}
        <div class="step {currentStep === step.id ? 'active' : ''} {currentStep > step.id ? 'completed' : ''}">
          <div class="step-number">{step.id}</div>
          <div class="step-label">{step.title}</div>
          {#if index < steps.length - 1}
            <div class="step-line"></div>
          {/if}
        </div>
      {/each}
    </div>
  </div>
  
  <div class="wizard-content">
    {#if Object.keys(errors).length > 0}
      <div class="validation-summary">
        <h3>Please fix the following errors:</h3>
        <ul>
          {#each Object.entries(errors) as [field, error]}
            <li>{error}</li>
          {/each}
        </ul>
      </div>
    {/if}
    
    {#if currentStep === 1}
      <div class="step-content">
        <h3>Personal Information</h3>
        <p>Tell us about yourself</p>
        
        <div class="form-row">
          <div class="form-group">
            <label for="firstName">First Name</label>
            <input type="text" id="firstName" bind:value={formData.firstName} class={errors.firstName ? 'error' : ''}>
            {#if errors.firstName}
              <div class="error-message">{errors.firstName}</div>
            {/if}
          </div>
          <div class="form-group">
            <label for="lastName">Last Name</label>
            <input type="text" id="lastName" bind:value={formData.lastName} class={errors.lastName ? 'error' : ''}>
            {#if errors.lastName}
              <div class="error-message">{errors.lastName}</div>
            {/if}
          </div>
        </div>
        
        <div class="form-group">
          <label for="email">Email Address</label>
          <input type="email" id="email" bind:value={formData.email} class={errors.email ? 'error' : ''}>
          {#if errors.email}
            <div class="error-message">{errors.email}</div>
          {/if}
        </div>
        
        <div class="form-group">
          <label for="phone">Phone Number</label>
          <input type="tel" id="phone" bind:value={formData.phone}>
        </div>
        
        <div class="form-group">
          <label for="dateOfBirth">Date of Birth</label>
          <input type="date" id="dateOfBirth" bind:value={formData.dateOfBirth}>
        </div>
      </div>
    {:else if currentStep === 2}
      <div class="step-content">
        <h3>Account Details</h3>
        <p>Set up your login credentials</p>
        
        <div class="form-group">
          <label for="username">Username</label>
          <input type="text" id="username" bind:value={formData.username}>
        </div>
        
        <div class="form-group">
          <label for="password">Password</label>
          <input type="password" id="password" bind:value={formData.password} class={errors.password ? 'error' : ''}>
          {#if errors.password}
            <div class="error-message">{errors.password}</div>
          {/if}
        </div>
        
        <div class="form-group">
          <label for="confirmPassword">Confirm Password</label>
          <input type="password" id="confirmPassword" bind:value={formData.confirmPassword} class={errors.confirmPassword ? 'error' : ''}>
          {#if errors.confirmPassword}
            <div class="error-message">{errors.confirmPassword}</div>
          {/if}
        </div>
        
        <div class="form-group">
          <label for="securityQuestion">Security Question</label>
          <select id="securityQuestion" bind:value={formData.securityQuestion}>
            <option value="">Select a security question</option>
            <option value="mother">What is your mother's maiden name?</option>
            <option value="pet">What was the name of your first pet?</option>
            <option value="school">What was the name of your first school?</option>
            <option value="city">In what city were you born?</option>
          </select>
        </div>
        
        <div class="form-group">
          <label for="securityAnswer">Security Answer</label>
          <input type="text" id="securityAnswer" bind:value={formData.securityAnswer}>
        </div>
      </div>
    {:else if currentStep === 3}
      <div class="step-content">
        <h3>Preferences</h3>
        <p>Customize your experience</p>
        
        <div class="form-group">
          <label>Communication Preferences</label>
          <div class="checkbox-group">
            <label>
              <input type="checkbox" bind:checked={formData.newsletter}>
              Subscribe to newsletter
            </label>
          </div>
          <div class="checkbox-group">
            <label>
              <input type="checkbox" bind:checked={formData.promotions}>
              Receive promotional emails
            </label>
          </div>
          <div class="checkbox-group">
            <label>
              <input type="checkbox" bind:checked={formData.updates}>
              Get product updates
            </label>
          </div>
        </div>
        
        <div class="form-group">
          <label for="timezone">Timezone</label>
          <select id="timezone" bind:value={formData.timezone}>
            <option value="">Select your timezone</option>
            <option value="UTC-8">UTC-8 (Pacific Time)</option>
            <option value="UTC-7">UTC-7 (Mountain Time)</option>
            <option value="UTC-6">UTC-6 (Central Time)</option>
            <option value="UTC-5">UTC-5 (Eastern Time)</option>
            <option value="UTC+0">UTC+0 (Greenwich)</option>
          </select>
        </div>
        
        <div class="form-group">
          <label for="language">Preferred Language</label>
          <select id="language" bind:value={formData.language}>
            <option value="">Select your language</option>
            <option value="en">English</option>
            <option value="es">Spanish</option>
            <option value="fr">French</option>
            <option value="de">German</option>
          </select>
        </div>
        
        <div class="form-group">
          <label for="bio">Bio (Optional)</label>
          <textarea id="bio" bind:value={formData.bio} rows="4" placeholder="Tell us a bit about yourself..."></textarea>
        </div>
      </div>
    {:else if currentStep === 4}
      <div class="step-content">
        <h3>Review Your Information</h3>
        <p>Please review your information before submitting</p>
        
        <div class="summary-item">
          <span class="summary-label">Name:</span>
          <span class="summary-value">{formData.firstName} {formData.lastName}</span>
        </div>
        <div class="summary-item">
          <span class="summary-label">Email:</span>
          <span class="summary-value">{formData.email}</span>
        </div>
        <div class="summary-item">
          <span class="summary-label">Phone:</span>
          <span class="summary-value">{formData.phone || 'Not provided'}</span>
        </div>
        <div class="summary-item">
          <span class="summary-label">Username:</span>
          <span class="summary-value">{formData.username}</span>
        </div>
        <div class="summary-item">
          <span class="summary-label">Timezone:</span>
          <span class="summary-value">{formData.timezone || 'Not selected'}</span>
        </div>
        <div class="summary-item">
          <span class="summary-label">Language:</span>
          <span class="summary-value">{formData.language || 'Not selected'}</span>
        </div>
        <div class="summary-item">
          <span class="summary-label">Newsletter:</span>
          <span class="summary-value">{formData.newsletter ? 'Yes' : 'No'}</span>
        </div>
      </div>
    {/if}
  </div>
  
  <div class="wizard-footer">
    <button class="btn btn-secondary" on:click={previousStep} disabled={currentStep === 1}>Previous</button>
    <div>
      {#if currentStep < steps.length}
        <button class="btn btn-primary" on:click={nextStep}>Next</button>
      {:else}
        <button class="btn btn-success" on:click={submitForm}>Complete Registration</button>
      {/if}
    </div>
  </div>
</div>

<style>
  .wizard-container {
    max-width: 800px;
    margin: 0 auto;
    background: white;
    border-radius: 12px;
    box-shadow: 0 4px 20px rgba(0,0,0,0.1);
    overflow: hidden;
  }
  
  .wizard-header {
    background: #f8f9fa;
    padding: 20px;
    border-bottom: 1px solid #dee2e6;
  }
  
  .wizard-header h2 {
    margin: 0 0 10px 0;
    color: #333;
  }
  
  .wizard-header p {
    margin: 0 0 20px 0;
    color: #666;
  }
  
  .progress-bar {
    width: 100%;
    height: 8px;
    background: #e9ecef;
    border-radius: 4px;
    overflow: hidden;
    margin-bottom: 20px;
  }
  
  .progress-fill {
    height: 100%;
    background: linear-gradient(90deg, #28a745, #20c997);
    transition: width 0.3s ease;
  }
  
  .step-indicators {
    display: flex;
    justify-content: space-between;
  }
  
  .step {
    display: flex;
    align-items: center;
    flex: 1;
  }
  
  .step-number {
    width: 30px;
    height: 30px;
    border-radius: 50%;
    background: #6c757d;
    color: white;
    display: flex;
    align-items: center;
    justify-content: center;
    font-weight: bold;
    margin-right: 10px;
  }
  
  .step.active .step-number {
    background: #007bff;
  }
  
  .step.completed .step-number {
    background: #28a745;
  }
  
  .step-label {
    font-weight: 500;
    color: #495057;
  }
  
  .step.active .step-label {
    color: #007bff;
  }
  
  .step.completed .step-label {
    color: #28a745;
  }
  
  .step-line {
    flex: 1;
    height: 2px;
    background: #dee2e6;
    margin: 0 10px;
  }
  
  .step.completed + .step .step-line {
    background: #28a745;
  }
  
  .wizard-content {
    padding: 30px;
    min-height: 400px;
  }
  
  .step-content h3 {
    margin: 0 0 10px 0;
    color: #333;
  }
  
  .step-content p {
    margin: 0 0 20px 0;
    color: #666;
  }
  
  .form-row {
    display: flex;
    gap: 20px;
  }
  
  .form-row .form-group {
    flex: 1;
  }
  
  .form-group {
    margin-bottom: 20px;
  }
  
  .form-group label {
    display: block;
    margin-bottom: 8px;
    font-weight: 600;
    color: #495057;
  }
  
  .form-group input,
  .form-group select,
  .form-group textarea {
    width: 100%;
    padding: 12px;
    border: 2px solid #e9ecef;
    border-radius: 6px;
    font-size: 16px;
    transition: border-color 0.3s ease;
  }
  
  .form-group input:focus,
  .form-group select:focus,
  .form-group textarea:focus {
    outline: none;
    border-color: #007bff;
  }
  
  .form-group input.error,
  .form-group select.error,
  .form-group textarea.error {
    border-color: #dc3545;
  }
  
  .error-message {
    color: #dc3545;
    font-size: 14px;
    margin-top: 5px;
  }
  
  .checkbox-group {
    display: flex;
    align-items: center;
    margin-bottom: 15px;
  }
  
  .checkbox-group input[type="checkbox"] {
    width: auto;
    margin-right: 10px;
  }
  
  .validation-summary {
    background: #f8d7da;
    color: #721c24;
    padding: 15px;
    border-radius: 6px;
    margin-bottom: 20px;
  }
  
  .validation-summary h3 {
    margin: 0 0 10px 0;
  }
  
  .validation-summary ul {
    margin: 0;
    padding-left: 20px;
  }
  
  .summary-item {
    display: flex;
    justify-content: space-between;
    padding: 10px 0;
    border-bottom: 1px solid #e9ecef;
  }
  
  .summary-item:last-child {
    border-bottom: none;
  }
  
  .summary-label {
    font-weight: 600;
    color: #495057;
  }
  
  .summary-value {
    color: #6c757d;
  }
  
  .wizard-footer {
    padding: 20px 30px;
    background: #f8f9fa;
    border-top: 1px solid #dee2e6;
    display: flex;
    justify-content: space-between;
    align-items: center;
  }
  
  .btn {
    padding: 12px 24px;
    border: none;
    border-radius: 6px;
    font-size: 16px;
    font-weight: 600;
    cursor: pointer;
    transition: all 0.3s ease;
  }
  
  .btn:disabled {
    opacity: 0.6;
    cursor: not-allowed;
  }
  
  .btn-primary {
    background: #007bff;
    color: white;
  }
  
  .btn-primary:hover {
    background: #0056b3;
  }
  
  .btn-secondary {
    background: #6c757d;
    color: white;
  }
  
  .btn-secondary:hover {
    background: #545b62;
  }
  
  .btn-success {
    background: #28a745;
    color: white;
  }
  
  .btn-success:hover {
    background: #1e7e34;
  }
</style>
