// scenarios/basic/web/nextjs/n19.jsx
import { useState } from 'react';

export default function UngroupedRadioButtons() {
  const [formData, setFormData] = useState({
    contactMethod: '',
    notificationFrequency: '',
    preferredLanguage: '',
    accountType: '',
    subscriptionPlan: '',
    marketingConsent: '',
    dataProcessing: '',
    communicationChannel: '',
    reportFormat: '',
    timezone: ''
  });

  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitMessage, setSubmitMessage] = useState('');

  const handleInputChange = (field, value) => {
    setFormData(prev => ({
      ...prev,
      [field]: value
    }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setIsSubmitting(true);
    
    try {
      await new Promise(resolve => setTimeout(resolve, 1000));
      setSubmitMessage('Preferences saved successfully!');
      setTimeout(() => setSubmitMessage(''), 3000);
    } catch (error) {
      setSubmitMessage('Error saving preferences. Please try again.');
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleReset = () => {
    setFormData({
      contactMethod: '',
      notificationFrequency: '',
      preferredLanguage: '',
      accountType: '',
      subscriptionPlan: '',
      marketingConsent: '',
      dataProcessing: '',
      communicationChannel: '',
      reportFormat: '',
      timezone: ''
    });
    setSubmitMessage('');
  };

  return (
    <div className="preferences-form">
      <div className="form-container">
        <header className="form-header">
          <h1>User Preferences</h1>
          <p>Customize your account settings and preferences</p>
        </header>

        <form onSubmit={handleSubmit} className="preferences-form-content">
          <div className="form-section">
            <h3>Contact Preferences</h3>
            <p>How would you like us to contact you?</p>
            
            <div className="radio-group">
              <label className="radio-option">
                <input
                  type="radio"
                  name="contactMethod"
                  value="email"
                  checked={formData.contactMethod === 'email'}
                  onChange={(e) => handleInputChange('contactMethod', e.target.value)}
                />
                <span className="radio-label">Email</span>
              </label>

              <label className="radio-option">
                <input
                  type="radio"
                  name="contactMethod"
                  value="phone"
                  checked={formData.contactMethod === 'phone'}
                  onChange={(e) => handleInputChange('contactMethod', e.target.value)}
                />
                <span className="radio-label">Phone</span>
              </label>

              <label className="radio-option">
                <input
                  type="radio"
                  name="contactMethod"
                  value="sms"
                  checked={formData.contactMethod === 'sms'}
                  onChange={(e) => handleInputChange('contactMethod', e.target.value)}
                />
                <span className="radio-label">SMS</span>
              </label>

              <label className="radio-option">
                <input
                  type="radio"
                  name="contactMethod"
                  value="none"
                  checked={formData.contactMethod === 'none'}
                  onChange={(e) => handleInputChange('contactMethod', e.target.value)}
                />
                <span className="radio-label">No contact</span>
              </label>
            </div>
          </div>

          <div className="form-section">
            <h3>Notification Settings</h3>
            <p>How often would you like to receive notifications?</p>
            
            <div className="radio-group">
              <label className="radio-option">
                <input
                  type="radio"
                  name="notificationFrequency"
                  value="immediate"
                  checked={formData.notificationFrequency === 'immediate'}
                  onChange={(e) => handleInputChange('notificationFrequency', e.target.value)}
                />
                <span className="radio-label">Immediately</span>
              </label>

              <label className="radio-option">
                <input
                  type="radio"
                  name="notificationFrequency"
                  value="daily"
                  checked={formData.notificationFrequency === 'daily'}
                  onChange={(e) => handleInputChange('notificationFrequency', e.target.value)}
                />
                <span className="radio-label">Daily digest</span>
              </label>

              <label className="radio-option">
                <input
                  type="radio"
                  name="notificationFrequency"
                  value="weekly"
                  checked={formData.notificationFrequency === 'weekly'}
                  onChange={(e) => handleInputChange('notificationFrequency', e.target.value)}
                />
                <span className="radio-label">Weekly summary</span>
              </label>

              <label className="radio-option">
                <input
                  type="radio"
                  name="notificationFrequency"
                  value="never"
                  checked={formData.notificationFrequency === 'never'}
                  onChange={(e) => handleInputChange('notificationFrequency', e.target.value)}
                />
                <span className="radio-label">Never</span>
              </label>
            </div>
          </div>

          <div className="form-section">
            <h3>Language Preferences</h3>
            <p>Select your preferred language for the interface</p>
            
            <div className="radio-group">
              <label className="radio-option">
                <input
                  type="radio"
                  name="preferredLanguage"
                  value="en"
                  checked={formData.preferredLanguage === 'en'}
                  onChange={(e) => handleInputChange('preferredLanguage', e.target.value)}
                />
                <span className="radio-label">English</span>
              </label>

              <label className="radio-option">
                <input
                  type="radio"
                  name="preferredLanguage"
                  value="es"
                  checked={formData.preferredLanguage === 'es'}
                  onChange={(e) => handleInputChange('preferredLanguage', e.target.value)}
                />
                <span className="radio-label">Spanish</span>
              </label>

              <label className="radio-option">
                <input
                  type="radio"
                  name="preferredLanguage"
                  value="fr"
                  checked={formData.preferredLanguage === 'fr'}
                  onChange={(e) => handleInputChange('preferredLanguage', e.target.value)}
                />
                <span className="radio-label">French</span>
              </label>

              <label className="radio-option">
                <input
                  type="radio"
                  name="preferredLanguage"
                  value="de"
                  checked={formData.preferredLanguage === 'de'}
                  onChange={(e) => handleInputChange('preferredLanguage', e.target.value)}
                />
                <span className="radio-label">German</span>
              </label>
            </div>
          </div>

          <div className="form-section">
            <h3>Account Type</h3>
            <p>What type of account do you have?</p>
            
            <div className="radio-group">
              <label className="radio-option">
                <input
                  type="radio"
                  name="accountType"
                  value="personal"
                  checked={formData.accountType === 'personal'}
                  onChange={(e) => handleInputChange('accountType', e.target.value)}
                />
                <span className="radio-label">Personal</span>
              </label>

              <label className="radio-option">
                <input
                  type="radio"
                  name="accountType"
                  value="business"
                  checked={formData.accountType === 'business'}
                  onChange={(e) => handleInputChange('accountType', e.target.value)}
                />
                <span className="radio-label">Business</span>
              </label>

              <label className="radio-option">
                <input
                  type="radio"
                  name="accountType"
                  value="enterprise"
                  checked={formData.accountType === 'enterprise'}
                  onChange={(e) => handleInputChange('accountType', e.target.value)}
                />
                <span className="radio-label">Enterprise</span>
              </label>
            </div>
          </div>

          <div className="form-section">
            <h3>Subscription Plan</h3>
            <p>Choose your subscription plan</p>
            
            <div className="radio-group">
              <label className="radio-option">
                <input
                  type="radio"
                  name="subscriptionPlan"
                  value="free"
                  checked={formData.subscriptionPlan === 'free'}
                  onChange={(e) => handleInputChange('subscriptionPlan', e.target.value)}
                />
                <span className="radio-label">Free Plan</span>
              </label>

              <label className="radio-option">
                <input
                  type="radio"
                  name="subscriptionPlan"
                  value="basic"
                  checked={formData.subscriptionPlan === 'basic'}
                  onChange={(e) => handleInputChange('subscriptionPlan', e.target.value)}
                />
                <span className="radio-label">Basic Plan ($9.99/month)</span>
              </label>

              <label className="radio-option">
                <input
                  type="radio"
                  name="subscriptionPlan"
                  value="premium"
                  checked={formData.subscriptionPlan === 'premium'}
                  onChange={(e) => handleInputChange('subscriptionPlan', e.target.value)}
                />
                <span className="radio-label">Premium Plan ($19.99/month)</span>
              </label>

              <label className="radio-option">
                <input
                  type="radio"
                  name="subscriptionPlan"
                  value="pro"
                  checked={formData.subscriptionPlan === 'pro'}
                  onChange={(e) => handleInputChange('subscriptionPlan', e.target.value)}
                />
                <span className="radio-label">Pro Plan ($39.99/month)</span>
              </label>
            </div>
          </div>

          <div className="form-section">
            <h3>Marketing Consent</h3>
            <p>Would you like to receive marketing communications?</p>
            
            <div className="radio-group">
              <label className="radio-option">
                <input
                  type="radio"
                  name="marketingConsent"
                  value="yes"
                  checked={formData.marketingConsent === 'yes'}
                  onChange={(e) => handleInputChange('marketingConsent', e.target.value)}
                />
                <span className="radio-label">Yes, send me marketing emails</span>
              </label>

              <label className="radio-option">
                <input
                  type="radio"
                  name="marketingConsent"
                  value="no"
                  checked={formData.marketingConsent === 'no'}
                  onChange={(e) => handleInputChange('marketingConsent', e.target.value)}
                />
                <span className="radio-label">No, don't send marketing emails</span>
              </label>
            </div>
          </div>

          <div className="form-section">
            <h3>Data Processing</h3>
            <p>How should we process your data?</p>
            
            <div className="radio-group">
              <label className="radio-option">
                <input
                  type="radio"
                  name="dataProcessing"
                  value="minimal"
                  checked={formData.dataProcessing === 'minimal'}
                  onChange={(e) => handleInputChange('dataProcessing', e.target.value)}
                />
                <span className="radio-label">Minimal processing only</span>
              </label>

              <label className="radio-option">
                <input
                  type="radio"
                  name="dataProcessing"
                  value="standard"
                  checked={formData.dataProcessing === 'standard'}
                  onChange={(e) => handleInputChange('dataProcessing', e.target.value)}
                />
                <span className="radio-label">Standard processing</span>
              </label>

              <label className="radio-option">
                <input
                  type="radio"
                  name="dataProcessing"
                  value="full"
                  checked={formData.dataProcessing === 'full'}
                  onChange={(e) => handleInputChange('dataProcessing', e.target.value)}
                />
                <span className="radio-label">Full processing for personalization</span>
              </label>
            </div>
          </div>

          <div className="form-section">
            <h3>Communication Channel</h3>
            <p>Preferred method for important updates</p>
            
            <div className="radio-group">
              <label className="radio-option">
                <input
                  type="radio"
                  name="communicationChannel"
                  value="email"
                  checked={formData.communicationChannel === 'email'}
                  onChange={(e) => handleInputChange('communicationChannel', e.target.value)}
                />
                <span className="radio-label">Email</span>
              </label>

              <label className="radio-option">
                <input
                  type="radio"
                  name="communicationChannel"
                  value="in-app"
                  checked={formData.communicationChannel === 'in-app'}
                  onChange={(e) => handleInputChange('communicationChannel', e.target.value)}
                />
                <span className="radio-label">In-app notifications</span>
              </label>

              <label className="radio-option">
                <input
                  type="radio"
                  name="communicationChannel"
                  value="both"
                  checked={formData.communicationChannel === 'both'}
                  onChange={(e) => handleInputChange('communicationChannel', e.target.value)}
                />
                <span className="radio-label">Both email and in-app</span>
              </label>
            </div>
          </div>

          <div className="form-section">
            <h3>Report Format</h3>
            <p>How would you like to receive reports?</p>
            
            <div className="radio-group">
              <label className="radio-option">
                <input
                  type="radio"
                  name="reportFormat"
                  value="pdf"
                  checked={formData.reportFormat === 'pdf'}
                  onChange={(e) => handleInputChange('reportFormat', e.target.value)}
                />
                <span className="radio-label">PDF format</span>
              </label>

              <label className="radio-option">
                <input
                  type="radio"
                  name="reportFormat"
                  value="excel"
                  checked={formData.reportFormat === 'excel'}
                  onChange={(e) => handleInputChange('reportFormat', e.target.value)}
                />
                <span className="radio-label">Excel format</span>
              </label>

              <label className="radio-option">
                <input
                  type="radio"
                  name="reportFormat"
                  value="csv"
                  checked={formData.reportFormat === 'csv'}
                  onChange={(e) => handleInputChange('reportFormat', e.target.value)}
                />
                <span className="radio-label">CSV format</span>
              </label>

              <label className="radio-option">
                <input
                  type="radio"
                  name="reportFormat"
                  value="web"
                  checked={formData.reportFormat === 'web'}
                  onChange={(e) => handleInputChange('reportFormat', e.target.value)}
                />
                <span className="radio-label">Web dashboard only</span>
              </label>
            </div>
          </div>

          <div className="form-section">
            <h3>Timezone</h3>
            <p>Select your timezone for accurate scheduling</p>
            
            <div className="radio-group">
              <label className="radio-option">
                <input
                  type="radio"
                  name="timezone"
                  value="est"
                  checked={formData.timezone === 'est'}
                  onChange={(e) => handleInputChange('timezone', e.target.value)}
                />
                <span className="radio-label">Eastern Time (EST/EDT)</span>
              </label>

              <label className="radio-option">
                <input
                  type="radio"
                  name="timezone"
                  value="cst"
                  checked={formData.timezone === 'cst'}
                  onChange={(e) => handleInputChange('timezone', e.target.value)}
                />
                <span className="radio-label">Central Time (CST/CDT)</span>
              </label>

              <label className="radio-option">
                <input
                  type="radio"
                  name="timezone"
                  value="mst"
                  checked={formData.timezone === 'mst'}
                  onChange={(e) => handleInputChange('timezone', e.target.value)}
                />
                <span className="radio-label">Mountain Time (MST/MDT)</span>
              </label>

              <label className="radio-option">
                <input
                  type="radio"
                  name="timezone"
                  value="pst"
                  checked={formData.timezone === 'pst'}
                  onChange={(e) => handleInputChange('timezone', e.target.value)}
                />
                <span className="radio-label">Pacific Time (PST/PDT)</span>
              </label>

              <label className="radio-option">
                <input
                  type="radio"
                  name="timezone"
                  value="utc"
                  checked={formData.timezone === 'utc'}
                  onChange={(e) => handleInputChange('timezone', e.target.value)}
                />
                <span className="radio-label">UTC (Coordinated Universal Time)</span>
              </label>
            </div>
          </div>

          <div className="form-actions">
            <button 
              type="button" 
              className="btn btn-secondary" 
              onClick={handleReset}
            >
              Reset Form
            </button>
            
            <button 
              type="submit" 
              className="btn btn-primary" 
              disabled={isSubmitting}
            >
              {isSubmitting ? 'Saving...' : 'Save Preferences'}
            </button>
          </div>

          {submitMessage && (
            <div className={`submit-message ${submitMessage.includes('Error') ? 'error' : 'success'}`}>
              {submitMessage}
            </div>
          )}
        </form>
      </div>

      <style jsx>{`
        .preferences-form {
          min-height: 100vh;
          background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
          padding: 40px 20px;
        }

        .form-container {
          max-width: 800px;
          margin: 0 auto;
          background: white;
          border-radius: 12px;
          box-shadow: 0 10px 30px rgba(0,0,0,0.1);
          overflow: hidden;
        }

        .form-header {
          background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
          color: white;
          padding: 40px;
          text-align: center;
        }

        .form-header h1 {
          margin: 0 0 10px 0;
          font-size: 32px;
          font-weight: bold;
        }

        .form-header p {
          margin: 0;
          font-size: 16px;
          opacity: 0.9;
        }

        .preferences-form-content {
          padding: 40px;
        }

        .form-section {
          margin-bottom: 40px;
          padding-bottom: 30px;
          border-bottom: 1px solid #e9ecef;
        }

        .form-section:last-of-type {
          border-bottom: none;
          margin-bottom: 30px;
        }

        .form-section h3 {
          margin: 0 0 10px 0;
          font-size: 20px;
          color: #333;
          font-weight: bold;
        }

        .form-section p {
          margin: 0 0 20px 0;
          color: #666;
          font-size: 14px;
        }

        .radio-group {
          display: flex;
          flex-direction: column;
          gap: 12px;
        }

        .radio-option {
          display: flex;
          align-items: center;
          cursor: pointer;
          padding: 12px 16px;
          border: 2px solid #e9ecef;
          border-radius: 8px;
          transition: all 0.2s ease;
          background: #f8f9fa;
        }

        .radio-option:hover {
          border-color: #007bff;
          background: #e3f2fd;
        }

        .radio-option input[type="radio"] {
          margin: 0 12px 0 0;
          width: 18px;
          height: 18px;
          accent-color: #007bff;
        }

        .radio-option input[type="radio"]:checked + .radio-label {
          color: #007bff;
          font-weight: bold;
        }

        .radio-option:has(input[type="radio"]:checked) {
          border-color: #007bff;
          background: #e3f2fd;
        }

        .radio-label {
          font-size: 14px;
          color: #333;
          transition: color 0.2s ease;
        }

        .form-actions {
          display: flex;
          gap: 20px;
          justify-content: flex-end;
          margin-top: 40px;
          padding-top: 30px;
          border-top: 1px solid #e9ecef;
        }

        .btn {
          padding: 12px 24px;
          border: none;
          border-radius: 6px;
          font-size: 14px;
          font-weight: bold;
          cursor: pointer;
          transition: all 0.2s ease;
          min-width: 120px;
        }

        .btn-primary {
          background: #007bff;
          color: white;
        }

        .btn-primary:hover:not(:disabled) {
          background: #0056b3;
          transform: translateY(-1px);
        }

        .btn-primary:disabled {
          background: #6c757d;
          cursor: not-allowed;
          transform: none;
        }

        .btn-secondary {
          background: #6c757d;
          color: white;
        }

        .btn-secondary:hover {
          background: #545b62;
          transform: translateY(-1px);
        }

        .submit-message {
          margin-top: 20px;
          padding: 12px 16px;
          border-radius: 6px;
          font-weight: bold;
          text-align: center;
        }

        .submit-message.success {
          background: #d4edda;
          color: #155724;
          border: 1px solid #c3e6cb;
        }

        .submit-message.error {
          background: #f8d7da;
          color: #721c24;
          border: 1px solid #f5c6cb;
        }

        @media (max-width: 768px) {
          .preferences-form {
            padding: 20px 10px;
          }

          .form-header {
            padding: 30px 20px;
          }

          .form-header h1 {
            font-size: 24px;
          }

          .preferences-form-content {
            padding: 30px 20px;
          }

          .form-actions {
            flex-direction: column;
          }

          .btn {
            width: 100%;
          }
        }
      `}</style>
    </div>
  );
}

// scenarios/basic/web/sveltekit/n19.svelte
<script>
  let formData = {
    name: '',
    email: '',
    phone: '',
    company: '',
    industry: '',
    budget: '',
    timeline: '',
    features: [],
    preferences: [],
    communication: '',
    newsletter: false,
    notifications: false,
    terms: false
  };
  
  let errors = {};
  let isSubmitting = false;
  let showSuccess = false;
  
  const industries = [
    'Technology',
    'Healthcare',
    'Finance',
    'Education',
    'Retail',
    'Manufacturing',
    'Other'
  ];
  
  const budgetRanges = [
    'Under $10,000',
    '$10,000 - $25,000',
    '$25,000 - $50,000',
    '$50,000 - $100,000',
    'Over $100,000'
  ];
  
  const timelines = [
    'ASAP',
    'Within 1 month',
    '1-3 months',
    '3-6 months',
    '6+ months'
  ];
  
  const features = [
    'User Authentication',
    'Payment Processing',
    'Real-time Chat',
    'File Upload',
    'Analytics Dashboard',
    'Mobile App',
    'API Integration',
    'Custom Design'
  ];
  
  const preferences = [
    'Email Updates',
    'Phone Calls',
    'SMS Notifications',
    'Video Meetings',
    'In-person Meetings'
  ];
  
  function validateForm() {
    errors = {};
    
    if (!formData.name.trim()) {
      errors.name = 'Name is required';
    }
    
    if (!formData.email.trim()) {
      errors.email = 'Email is required';
    } else if (!/\S+@\S+\.\S+/.test(formData.email)) {
      errors.email = 'Email is invalid';
    }
    
    if (!formData.phone.trim()) {
      errors.phone = 'Phone number is required';
    }
    
    if (!formData.company.trim()) {
      errors.company = 'Company name is required';
    }
    
    if (!formData.industry) {
      errors.industry = 'Please select an industry';
    }
    
    if (!formData.budget) {
      errors.budget = 'Please select a budget range';
    }
    
    if (!formData.timeline) {
      errors.timeline = 'Please select a timeline';
    }
    
    if (formData.features.length === 0) {
      errors.features = 'Please select at least one feature';
    }
    
    if (formData.preferences.length === 0) {
      errors.preferences = 'Please select at least one communication preference';
    }
    
    if (!formData.communication) {
      errors.communication = 'Please select your preferred communication method';
    }
    
    if (!formData.terms) {
      errors.terms = 'You must accept the terms and conditions';
    }
    
    return Object.keys(errors).length === 0;
  }
  
  function handleSubmit() {
    if (validateForm()) {
      isSubmitting = true;
      
      // Simulate form submission
      setTimeout(() => {
        isSubmitting = false;
        showSuccess = true;
        formData = {
          name: '',
          email: '',
          phone: '',
          company: '',
          industry: '',
          budget: '',
          timeline: '',
          features: [],
          preferences: [],
          communication: '',
          newsletter: false,
          notifications: false,
          terms: false
        };
      }, 2000);
    }
  }
  
  function handleFeatureChange(feature) {
    if (formData.features.includes(feature)) {
      formData.features = formData.features.filter(f => f !== feature);
    } else {
      formData.features = [...formData.features, feature];
    }
  }
  
  function handlePreferenceChange(preference) {
    if (formData.preferences.includes(preference)) {
      formData.preferences = formData.preferences.filter(p => p !== preference);
    } else {
      formData.preferences = [...formData.preferences, preference];
    }
  }
</script>

<div class="contact-form">
  <header class="form-header">
    <h1 class="form-title">Get Started Today</h1>
    <p class="form-subtitle">Tell us about your project and we'll help you bring it to life</p>
  </header>

  {#if showSuccess}
    <div class="success-message">
      <div class="success-icon">✓</div>
      <h2 class="success-title">Thank You!</h2>
      <p class="success-description">Your information has been submitted successfully. We'll be in touch within 24 hours.</p>
      <button 
        class="success-btn" 
        on:click={() => showSuccess = false}
      >
        Submit Another Request
      </button>
    </div>
  {:else}
    <form class="form-container" on:submit|preventDefault={handleSubmit}>
      <div class="form-section">
        <h2 class="section-title">Personal Information</h2>
        
        <div class="form-row">
          <div class="form-group">
            <label class="form-label" for="name">Full Name *</label>
            <input 
              type="text" 
              id="name"
              bind:value={formData.name}
              class="form-input" 
              class:error={errors.name}
              placeholder="Enter your full name"
            />
            {#if errors.name}
              <span class="error-message">{errors.name}</span>
            {/if}
          </div>
          
          <div class="form-group">
            <label class="form-label" for="email">Email Address *</label>
            <input 
              type="email" 
              id="email"
              bind:value={formData.email}
              class="form-input" 
              class:error={errors.email}
              placeholder="Enter your email address"
            />
            {#if errors.email}
              <span class="error-message">{errors.email}</span>
            {/if}
          </div>
        </div>
        
        <div class="form-row">
          <div class="form-group">
            <label class="form-label" for="phone">Phone Number *</label>
            <input 
              type="tel" 
              id="phone"
              bind:value={formData.phone}
              class="form-input" 
              class:error={errors.phone}
              placeholder="Enter your phone number"
            />
            {#if errors.phone}
              <span class="error-message">{errors.phone}</span>
            {/if}
          </div>
          
          <div class="form-group">
            <label class="form-label" for="company">Company Name *</label>
            <input 
              type="text" 
              id="company"
              bind:value={formData.company}
              class="form-input" 
              class:error={errors.company}
              placeholder="Enter your company name"
            />
            {#if errors.company}
              <span class="error-message">{errors.company}</span>
            {/if}
          </div>
        </div>
      </div>

      <div class="form-section">
        <h2 class="section-title">Project Details</h2>
        
        <div class="form-group">
          <label class="form-label">Industry *</label>
          <div class="radio-group">
            {#each industries as industry (industry)}
              <label class="radio-option">
                <input 
                  type="radio" 
                  bind:group={formData.industry} 
                  value={industry}
                  class="radio-input"
                />
                <span class="radio-label">{industry}</span>
              </label>
            {/each}
          </div>
          {#if errors.industry}
            <span class="error-message">{errors.industry}</span>
          {/if}
        </div>
        
        <div class="form-group">
          <label class="form-label">Budget Range *</label>
          <div class="radio-group">
            {#each budgetRanges as budget (budget)}
              <label class="radio-option">
                <input 
                  type="radio" 
                  bind:group={formData.budget} 
                  value={budget}
                  class="radio-input"
                />
                <span class="radio-label">{budget}</span>
              </label>
            {/each}
          </div>
          {#if errors.budget}
            <span class="error-message">{errors.budget}</span>
          {/if}
        </div>
        
        <div class="form-group">
          <label class="form-label">Project Timeline *</label>
          <div class="radio-group">
            {#each timelines as timeline (timeline)}
              <label class="radio-option">
                <input 
                  type="radio" 
                  bind:group={formData.timeline} 
                  value={timeline}
                  class="radio-input"
                />
                <span class="radio-label">{timeline}</span>
              </label>
            {/each}
          </div>
          {#if errors.timeline}
            <span class="error-message">{errors.timeline}</span>
          {/if}
        </div>
      </div>

      <div class="form-section">
        <h2 class="section-title">Features & Requirements</h2>
        
        <div class="form-group">
          <label class="form-label">Desired Features * (Select all that apply)</label>
          <div class="checkbox-group">
            {#each features as feature (feature)}
              <label class="checkbox-option">
                <input 
                  type="checkbox" 
                  checked={formData.features.includes(feature)}
                  on:change={() => handleFeatureChange(feature)}
                  class="checkbox-input"
                />
                <span class="checkbox-label">{feature}</span>
              </label>
            {/each}
          </div>
          {#if errors.features}
            <span class="error-message">{errors.features}</span>
          {/if}
        </div>
      </div>

      <div class="form-section">
        <h2 class="section-title">Communication Preferences</h2>
        
        <div class="form-group">
          <label class="form-label">How would you like us to contact you? *</label>
          <div class="radio-group">
            <label class="radio-option">
              <input 
                type="radio" 
                bind:group={formData.communication} 
                value="email"
                class="radio-input"
              />
              <span class="radio-label">Email</span>
            </label>
            <label class="radio-option">
              <input 
                type="radio" 
                bind:group={formData.communication} 
                value="phone"
                class="radio-input"
              />
              <span class="radio-label">Phone Call</span>
            </label>
            <label class="radio-option">
              <input 
                type="radio" 
                bind:group={formData.communication} 
                value="video"
                class="radio-input"
              />
              <span class="radio-label">Video Meeting</span>
            </label>
            <label class="radio-option">
              <input 
                type="radio" 
                bind:group={formData.communication} 
                value="in-person"
                class="radio-input"
              />
              <span class="radio-label">In-Person Meeting</span>
            </label>
          </div>
          {#if errors.communication}
            <span class="error-message">{errors.communication}</span>
          {/if}
        </div>
        
        <div class="form-group">
          <label class="form-label">Update Preferences * (Select all that apply)</label>
          <div class="checkbox-group">
            {#each preferences as preference (preference)}
              <label class="checkbox-option">
                <input 
                  type="checkbox" 
                  checked={formData.preferences.includes(preference)}
                  on:change={() => handlePreferenceChange(preference)}
                  class="checkbox-input"
                />
                <span class="checkbox-label">{preference}</span>
              </label>
            {/each}
          </div>
          {#if errors.preferences}
            <span class="error-message">{errors.preferences}</span>
          {/if}
        </div>
      </div>

      <div class="form-section">
        <h2 class="section-title">Additional Options</h2>
        
        <div class="form-group">
          <div class="checkbox-option">
            <input 
              type="checkbox" 
              bind:checked={formData.newsletter}
              class="checkbox-input"
            />
            <span class="checkbox-label">Subscribe to our newsletter for project updates and tips</span>
          </div>
        </div>
        
        <div class="form-group">
          <div class="checkbox-option">
            <input 
              type="checkbox" 
              bind:checked={formData.notifications}
              class="checkbox-input"
            />
            <span class="checkbox-label">Receive notifications about new features and services</span>
          </div>
        </div>
        
        <div class="form-group">
          <div class="checkbox-option">
            <input 
              type="checkbox" 
              bind:checked={formData.terms}
              class="checkbox-input"
            />
            <span class="checkbox-label">I agree to the <a href="#" class="terms-link">Terms and Conditions</a> and <a href="#" class="terms-link">Privacy Policy</a> *</span>
          </div>
          {#if errors.terms}
            <span class="error-message">{errors.terms}</span>
          {/if}
        </div>
      </div>

      <div class="form-actions">
        <button 
          type="button" 
          class="btn btn-secondary"
          on:click={() => {
            formData = {
              name: '',
              email: '',
              phone: '',
              company: '',
              industry: '',
              budget: '',
              timeline: '',
              features: [],
              preferences: [],
              communication: '',
              newsletter: false,
              notifications: false,
              terms: false
            };
            errors = {};
          }}
        >
          Reset Form
        </button>
        <button 
          type="submit" 
          class="btn btn-primary"
          disabled={isSubmitting}
        >
          {isSubmitting ? 'Submitting...' : 'Submit Request'}
        </button>
      </div>
    </form>
  {/if}
</div>

<style>
  .contact-form {
    font-family: Arial, sans-serif;
    line-height: 1.6;
    color: #333;
    background: #f8f9fa;
    min-height: 100vh;
    padding: 20px;
  }
  
  .form-header {
    text-align: center;
    margin-bottom: 40px;
    background: white;
    padding: 40px;
    border-radius: 12px;
    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
  }
  
  .form-title {
    margin: 0 0 15px 0;
    font-size: 32px;
    color: #333;
  }
  
  .form-subtitle {
    margin: 0;
    font-size: 18px;
    color: #666;
  }
  
  .form-container {
    max-width: 800px;
    margin: 0 auto;
    background: white;
    border-radius: 12px;
    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
    overflow: hidden;
  }
  
  .form-section {
    padding: 30px;
    border-bottom: 1px solid #eee;
  }
  
  .form-section:last-child {
    border-bottom: none;
  }
  
  .section-title {
    margin: 0 0 25px 0;
    font-size: 20px;
    color: #333;
    border-bottom: 2px solid #007bff;
    padding-bottom: 10px;
  }
  
  .form-row {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 20px;
    margin-bottom: 20px;
  }
  
  .form-group {
    margin-bottom: 25px;
  }
  
  .form-label {
    display: block;
    margin-bottom: 8px;
    font-weight: bold;
    color: #333;
  }
  
  .form-input {
    width: 100%;
    padding: 12px 16px;
    border: 1px solid #ddd;
    border-radius: 6px;
    font-size: 16px;
    transition: border-color 0.2s ease;
  }
  
  .form-input:focus {
    outline: none;
    border-color: #007bff;
    box-shadow: 0 0 0 3px rgba(0,123,255,0.1);
  }
  
  .form-input.error {
    border-color: #dc3545;
  }
  
  .radio-group {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 15px;
  }
  
  .radio-option {
    display: flex;
    align-items: center;
    gap: 10px;
    cursor: pointer;
    padding: 12px;
    border: 1px solid #ddd;
    border-radius: 6px;
    transition: all 0.2s ease;
  }
  
  .radio-option:hover {
    background: #f8f9fa;
    border-color: #007bff;
  }
  
  .radio-input {
    margin: 0;
  }
  
  .radio-label {
    font-weight: 500;
    color: #333;
  }
  
  .checkbox-group {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
    gap: 15px;
  }
  
  .checkbox-option {
    display: flex;
    align-items: center;
    gap: 10px;
    cursor: pointer;
    padding: 12px;
    border: 1px solid #ddd;
    border-radius: 6px;
    transition: all 0.2s ease;
  }
  
  .checkbox-option:hover {
    background: #f8f9fa;
    border-color: #007bff;
  }
  
  .checkbox-input {
    margin: 0;
  }
  
  .checkbox-label {
    font-weight: 500;
    color: #333;
  }
  
  .terms-link {
    color: #007bff;
    text-decoration: none;
  }
  
  .terms-link:hover {
    text-decoration: underline;
  }
  
  .error-message {
    display: block;
    color: #dc3545;
    font-size: 14px;
    margin-top: 5px;
  }
  
  .form-actions {
    padding: 30px;
    background: #f8f9fa;
    display: flex;
    gap: 15px;
    justify-content: flex-end;
  }
  
  .btn {
    padding: 12px 24px;
    border: none;
    border-radius: 6px;
    font-weight: bold;
    cursor: pointer;
    transition: all 0.2s ease;
    font-size: 16px;
  }
  
  .btn-primary {
    background: #007bff;
    color: white;
  }
  
  .btn-primary:hover:not(:disabled) {
    background: #0056b3;
  }
  
  .btn-primary:disabled {
    background: #6c757d;
    cursor: not-allowed;
  }
  
  .btn-secondary {
    background: #6c757d;
    color: white;
  }
  
  .btn-secondary:hover {
    background: #545b62;
  }
  
  .success-message {
    text-align: center;
    padding: 60px 40px;
    background: white;
    border-radius: 12px;
    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
    max-width: 600px;
    margin: 0 auto;
  }
  
  .success-icon {
    width: 80px;
    height: 80px;
    background: #28a745;
    color: white;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 40px;
    margin: 0 auto 30px;
  }
  
  .success-title {
    margin: 0 0 15px 0;
    font-size: 28px;
    color: #333;
  }
  
  .success-description {
    margin: 0 0 30px 0;
    color: #666;
    font-size: 16px;
  }
  
  .success-btn {
    padding: 15px 30px;
    background: #007bff;
    color: white;
    border: none;
    border-radius: 6px;
    font-weight: bold;
    cursor: pointer;
    transition: all 0.2s ease;
  }
  
  .success-btn:hover {
    background: #0056b3;
  }
  
  @media (max-width: 768px) {
    .form-row {
      grid-template-columns: 1fr;
    }
    
    .radio-group {
      grid-template-columns: 1fr;
    }
    
    .checkbox-group {
      grid-template-columns: 1fr;
    }
    
    .form-actions {
      flex-direction: column;
    }
    
    .btn {
      width: 100%;
    }
  }
</style>
