// frameworks/web/react/ShoppingCartSystem.jsx
import React, { useState, useEffect } from 'react';
import './ShoppingCartSystem.css';

const ShoppingCartSystem = () => {
  const [cartItems, setCartItems] = useState([
    {
      id: 1,
      name: 'Wireless Bluetooth Headphones',
      price: 99.99,
      quantity: 1,
      image: 'https://via.placeholder.com/80x80/4caf50/fff?text=🎧',
      inStock: true,
      maxQuantity: 5
    },
    {
      id: 2,
      name: 'Smart Fitness Watch',
      price: 199.99,
      quantity: 2,
      image: 'https://via.placeholder.com/80x80/2196f3/fff?text=⌚',
      inStock: true,
      maxQuantity: 3
    },
    {
      id: 3,
      name: 'USB-C Charging Cable',
      price: 19.99,
      quantity: 1,
      image: 'https://via.placeholder.com/80x80/ff9800/fff?text=🔌',
      inStock: false,
      maxQuantity: 10
    }
  ]);

  const [promoCode, setPromoCode] = useState('');
  const [appliedPromo, setAppliedPromo] = useState(null);
  const [shippingOption, setShippingOption] = useState('standard');
  const [showPromoForm, setShowPromoForm] = useState(false);
  const [isCheckingOut, setIsCheckingOut] = useState(false);

  const shippingOptions = [
    { id: 'standard', name: 'Standard Shipping', price: 5.99, days: '5-7 business days' },
    { id: 'express', name: 'Express Shipping', price: 12.99, days: '2-3 business days' },
    { id: 'overnight', name: 'Overnight Shipping', price: 24.99, days: 'Next business day' }
  ];

  const promoCodes = {
    'SAVE10': { discount: 0.1, type: 'percentage', description: '10% off your order' },
    'FREESHIP': { discount: 0, type: 'shipping', description: 'Free standard shipping' },
    'WELCOME20': { discount: 20, type: 'fixed', description: '$20 off your order' }
  };

  const updateQuantity = (id, newQuantity) => {
    if (newQuantity < 1) return;
    
    setCartItems(prev => prev.map(item => {
      if (item.id === id) {
        const updatedQuantity = Math.min(newQuantity, item.maxQuantity);
        return { ...item, quantity: updatedQuantity };
      }
      return item;
    }));
  };

  const removeItem = (id) => {
    setCartItems(prev => prev.filter(item => item.id !== id));
  };

  const applyPromoCode = () => {
    const promo = promoCodes[promoCode.toUpperCase()];
    if (promo) {
      setAppliedPromo(promo);
      setPromoCode('');
      setShowPromoForm(false);
    } else {
      alert('Invalid promo code');
    }
  };

  const removePromoCode = () => {
    setAppliedPromo(null);
  };

  const calculateSubtotal = () => {
    return cartItems.reduce((total, item) => total + (item.price * item.quantity), 0);
  };

  const calculateShipping = () => {
    if (appliedPromo && appliedPromo.type === 'shipping') {
      return 0;
    }
    return shippingOptions.find(option => option.id === shippingOption)?.price || 0;
  };

  const calculateDiscount = () => {
    if (!appliedPromo) return 0;
    
    const subtotal = calculateSubtotal();
    
    switch (appliedPromo.type) {
      case 'percentage':
        return subtotal * appliedPromo.discount;
      case 'fixed':
        return appliedPromo.discount;
      default:
        return 0;
    }
  };

  const calculateTotal = () => {
    const subtotal = calculateSubtotal();
    const shipping = calculateShipping();
    const discount = calculateDiscount();
    return subtotal + shipping - discount;
  };

  const handleCheckout = async () => {
    if (cartItems.length === 0) {
      alert('Your cart is empty');
      return;
    }

    setIsCheckingOut(true);
    
    // Simulate checkout process
    setTimeout(() => {
      console.log('Checkout completed:', {
        items: cartItems,
        subtotal: calculateSubtotal(),
        shipping: calculateShipping(),
        discount: calculateDiscount(),
        total: calculateTotal(),
        promoCode: appliedPromo
      });
      setIsCheckingOut(false);
      alert('Order placed successfully!');
    }, 2000);
  };

  const subtotal = calculateSubtotal();
  const shipping = calculateShipping();
  const discount = calculateDiscount();
  const total = calculateTotal();

  return (
    <div className="shopping-cart">
      <div className="cart-header">
        <h1>Shopping Cart</h1>
        <div className="cart-summary">
          {cartItems.length} item{cartItems.length !== 1 ? 's' : ''} in cart
        </div>
      </div>

      {cartItems.length === 0 ? (
        <div className="empty-cart">
          <div className="empty-cart-icon">🛒</div>
          <h2>Your cart is empty</h2>
          <p>Add some items to get started</p>
          <button className="continue-shopping-btn">Continue Shopping</button>
        </div>
      ) : (
        <div className="cart-content">
          <div className="cart-items">
            <h2>Items in your cart</h2>
            {cartItems.map(item => (
              <div key={item.id} className="cart-item">
                <div className="item-image">
                  <img src={item.image} alt={item.name} />
                </div>
                
                <div className="item-details">
                  <h3 className="item-name">{item.name}</h3>
                  <div className="item-price">${item.price.toFixed(2)}</div>
                  {!item.inStock && (
                    <div className="out-of-stock">Out of Stock</div>
                  )}
                </div>

                <div className="quantity-controls">
                  <button 
                    onClick={() => updateQuantity(item.id, item.quantity - 1)}
                    disabled={item.quantity <= 1}
                    className="quantity-btn"
                  >
                    −
                  </button>
                  <span className="quantity-display">{item.quantity}</span>
                  <button 
                    onClick={() => updateQuantity(item.id, item.quantity + 1)}
                    disabled={item.quantity >= item.maxQuantity}
                    className="quantity-btn"
                  >
                    +
                  </button>
                </div>

                <div className="item-total">
                  ${(item.price * item.quantity).toFixed(2)}
                </div>

                <button 
                  onClick={() => removeItem(item.id)}
                  className="remove-btn"
                >
                  🗑️
                </button>
              </div>
            ))}
          </div>

          <div className="cart-summary-section">
            <div className="promo-section">
              {!appliedPromo ? (
                <div className="promo-form">
                  {!showPromoForm ? (
                    <button 
                      onClick={() => setShowPromoForm(true)}
                      className="promo-toggle-btn"
                    >
                      Have a promo code?
                    </button>
                  ) : (
                    <div className="promo-input-group">
                      <input
                        type="text"
                        placeholder="Enter promo code"
                        value={promoCode}
                        onChange={(e) => setPromoCode(e.target.value)}
                        className="promo-input"
                      />
                      <button onClick={applyPromoCode} className="apply-btn">
                        Apply
                      </button>
                      <button 
                        onClick={() => setShowPromoForm(false)}
                        className="cancel-btn"
                      >
                        Cancel
                      </button>
                    </div>
                  )}
                </div>
              ) : (
                <div className="applied-promo">
                  <span className="promo-code">{Object.keys(promoCodes).find(code => promoCodes[code] === appliedPromo)}</span>
                  <span className="promo-description">{appliedPromo.description}</span>
                  <button onClick={removePromoCode} className="remove-promo-btn">
                    ✕
                  </button>
                </div>
              )}
            </div>

            <div className="shipping-section">
              <h3>Shipping Options</h3>
              {shippingOptions.map(option => (
                <label key={option.id} className="shipping-option">
                  <input
                    type="radio"
                    name="shipping"
                    value={option.id}
                    checked={shippingOption === option.id}
                    onChange={(e) => setShippingOption(e.target.value)}
                  />
                  <div className="shipping-details">
                    <div className="shipping-name">{option.name}</div>
                    <div className="shipping-info">
                      {option.days} • ${option.price.toFixed(2)}
                    </div>
                  </div>
                </label>
              ))}
            </div>

            <div className="order-summary">
              <h3>Order Summary</h3>
              <div className="summary-row">
                <span>Subtotal</span>
                <span>${subtotal.toFixed(2)}</span>
              </div>
              <div className="summary-row">
                <span>Shipping</span>
                <span>${shipping.toFixed(2)}</span>
              </div>
              {discount > 0 && (
                <div className="summary-row discount">
                  <span>Discount</span>
                  <span>-${discount.toFixed(2)}</span>
                </div>
              )}
              <div className="summary-row total">
                <span>Total</span>
                <span>${total.toFixed(2)}</span>
              </div>
            </div>

            <div className="checkout-section">
              <button 
                onClick={handleCheckout}
                disabled={isCheckingOut || cartItems.some(item => !item.inStock)}
                className="checkout-btn"
              >
                {isCheckingOut ? 'Processing...' : 'Proceed to Checkout'}
              </button>
              
              {cartItems.some(item => !item.inStock) && (
                <div className="checkout-warning">
                  Please remove out-of-stock items before checkout
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default ShoppingCartSystem;

// frameworks/web/svelte/ShoppingCartSystem.svelte
<script>
  import { onMount } from 'svelte';
  
  let cartItems = [];
  let promoCode = '';
  let shippingOption = 'standard';
  let isCheckingOut = false;
  let showPromoForm = false;
  let promoApplied = false;
  let promoDiscount = 0;
  let promoMessage = '';

  const sampleProducts = [
    {
      id: 1,
      name: 'Wireless Headphones',
      price: 99.99,
      image: 'https://via.placeholder.com/80x80/4caf50/fff?text=WH',
      category: 'Electronics',
      inStock: true,
      stockCount: 15
    },
    {
      id: 2,
      name: 'Smart Watch',
      price: 199.99,
      image: 'https://via.placeholder.com/80x80/2196f3/fff?text=SW',
      category: 'Electronics',
      inStock: true,
      stockCount: 8
    },
    {
      id: 3,
      name: 'Laptop Stand',
      price: 49.99,
      image: 'https://via.placeholder.com/80x80/ff9800/fff?text=LS',
      category: 'Accessories',
      inStock: true,
      stockCount: 25
    },
    {
      id: 4,
      name: 'Bluetooth Speaker',
      price: 79.99,
      image: 'https://via.placeholder.com/80x80/9c27b0/fff?text=BS',
      category: 'Electronics',
      inStock: false,
      stockCount: 0
    },
    {
      id: 5,
      name: 'Phone Case',
      price: 24.99,
      image: 'https://via.placeholder.com/80x80/f44336/fff?text=PC',
      category: 'Accessories',
      inStock: true,
      stockCount: 50
    }
  ];

  const shippingOptions = [
    { value: 'standard', label: 'Standard Shipping', price: 5.99, days: '5-7 business days' },
    { value: 'express', label: 'Express Shipping', price: 12.99, days: '2-3 business days' },
    { value: 'overnight', label: 'Overnight Shipping', price: 24.99, days: '1 business day' }
  ];

  const promoCodes = {
    'SAVE10': { discount: 0.1, type: 'percentage', description: '10% off your order' },
    'WELCOME20': { discount: 20, type: 'fixed', description: '$20 off your order' },
    'FREESHIP': { discount: 0, type: 'shipping', description: 'Free shipping on your order' }
  };

  onMount(() => {
    loadCartFromStorage();
  });

  function loadCartFromStorage() {
    const saved = localStorage.getItem('shoppingCart');
    if (saved) {
      cartItems = JSON.parse(saved);
    }
  }

  function saveCartToStorage() {
    localStorage.setItem('shoppingCart', JSON.stringify(cartItems));
  }

  function addToCart(product) {
    const existingItem = cartItems.find(item => item.id === product.id);
    
    if (existingItem) {
      if (existingItem.quantity < product.stockCount) {
        existingItem.quantity += 1;
      } else {
        alert('Not enough stock available');
        return;
      }
    } else {
      cartItems = [...cartItems, { ...product, quantity: 1 }];
    }
    
    saveCartToStorage();
  }

  function removeFromCart(productId) {
    cartItems = cartItems.filter(item => item.id !== productId);
    saveCartToStorage();
  }

  function updateQuantity(productId, newQuantity) {
    if (newQuantity <= 0) {
      removeFromCart(productId);
      return;
    }

    const product = sampleProducts.find(p => p.id === productId);
    if (product && newQuantity > product.stockCount) {
      alert('Not enough stock available');
      return;
    }

    cartItems = cartItems.map(item => 
      item.id === productId ? { ...item, quantity: newQuantity } : item
    );
    saveCartToStorage();
  }

  function applyPromoCode() {
    const code = promoCode.toUpperCase();
    const promo = promoCodes[code];
    
    if (promo) {
      promoApplied = true;
      promoDiscount = promo.discount;
      promoMessage = `Promo code applied: ${promo.description}`;
    } else {
      promoMessage = 'Invalid promo code';
    }
  }

  function removePromoCode() {
    promoCode = '';
    promoApplied = false;
    promoDiscount = 0;
    promoMessage = '';
  }

  function calculateSubtotal() {
    return cartItems.reduce((total, item) => total + (item.price * item.quantity), 0);
  }

  function calculateShipping() {
    if (promoApplied && promoCodes[promoCode.toUpperCase()]?.type === 'shipping') {
      return 0;
    }
    const option = shippingOptions.find(opt => opt.value === shippingOption);
    return option ? option.price : 0;
  }

  function calculateDiscount() {
    if (!promoApplied) return 0;
    
    const promo = promoCodes[promoCode.toUpperCase()];
    if (promo.type === 'percentage') {
      return calculateSubtotal() * promo.discount;
    } else if (promo.type === 'fixed') {
      return Math.min(promo.discount, calculateSubtotal());
    }
    return 0;
  }

  function calculateTax() {
    const subtotal = calculateSubtotal() - calculateDiscount();
    return subtotal * 0.08;
  }

  function calculateTotal() {
    const subtotal = calculateSubtotal();
    const discount = calculateDiscount();
    const shipping = calculateShipping();
    const tax = calculateTax();
    
    return subtotal - discount + shipping + tax;
  }

  function getItemTotal(item) {
    return item.price * item.quantity;
  }

  function formatPrice(price) {
    return `$${price.toFixed(2)}`;
  }

  function handleCheckout() {
    if (cartItems.length === 0) {
      alert('Your cart is empty');
      return;
    }

    isCheckingOut = true;
    
    setTimeout(() => {
      console.log('Checkout completed:', {
        items: cartItems,
        subtotal: calculateSubtotal(),
        discount: calculateDiscount(),
        shipping: calculateShipping(),
        tax: calculateTax(),
        total: calculateTotal()
      });
      
      cartItems = [];
      promoCode = '';
      promoApplied = false;
      promoDiscount = 0;
      promoMessage = '';
      isCheckingOut = false;
      saveCartToStorage();
      
      alert('Order placed successfully!');
    }, 2000);
  }

  function clearCart() {
    cartItems = [];
    saveCartToStorage();
  }

  function getShippingOption() {
    return shippingOptions.find(opt => opt.value === shippingOption);
  }
</script>

<div class="shopping-cart">
  <div class="cart-header">
    <h1>Shopping Cart</h1>
    <div class="cart-actions">
      <button 
        on:click={clearCart}
        disabled={cartItems.length === 0}
        class="clear-cart-btn"
      >
        Clear Cart
      </button>
    </div>
  </div>

  <div class="cart-content">
    <div class="cart-items">
      {#if cartItems.length === 0}
        <div class="empty-cart">
          <div class="empty-icon">🛒</div>
          <h3>Your cart is empty</h3>
          <p>Add some items to get started</p>
        </div>
      {:else}
        <div class="items-list">
          {#each cartItems as item}
            <div class="cart-item">
              <div class="item-image">
                <img src={item.image} alt={item.name} />
              </div>
              
              <div class="item-details">
                <h4 class="item-name">{item.name}</h4>
                <p class="item-category">{item.category}</p>
                <p class="item-price">{formatPrice(item.price)} each</p>
                
                {#if !item.inStock}
                  <span class="out-of-stock">Out of Stock</span>
                {/if}
              </div>
              
              <div class="item-controls">
                <div class="quantity-controls">
                  <button 
                    on:click={() => updateQuantity(item.id, item.quantity - 1)}
                    disabled={item.quantity <= 1}
                    class="quantity-btn"
                  >
                    −
                  </button>
                  <input
                    type="number"
                    bind:value={item.quantity}
                    on:change={(e) => updateQuantity(item.id, parseInt(e.target.value) || 1)}
                    min="1"
                    max={item.stockCount}
                    class="quantity-input"
                  />
                  <button 
                    on:click={() => updateQuantity(item.id, item.quantity + 1)}
                    disabled={item.quantity >= item.stockCount}
                    class="quantity-btn"
                  >
                    +
                  </button>
                </div>
                
                <div class="item-total">
                  {formatPrice(getItemTotal(item))}
                </div>
                
                <button 
                  on:click={() => removeFromCart(item.id)}
                  class="remove-btn"
                >
                  Remove
                </button>
              </div>
            </div>
          {/each}
        </div>
      {/if}
    </div>

    <div class="cart-summary">
      <div class="summary-section">
        <h3>Order Summary</h3>
        
        <div class="summary-row">
          <span>Subtotal ({cartItems.length} item{cartItems.length !== 1 ? 's' : ''})</span>
          <span>{formatPrice(calculateSubtotal())}</span>
        </div>

        {#if promoApplied && calculateDiscount() > 0}
          <div class="summary-row discount">
            <span>Discount ({promoCode})</span>
            <span>-{formatPrice(calculateDiscount())}</span>
          </div>
        {/if}

        <div class="summary-row">
          <span>Shipping</span>
          <span>{formatPrice(calculateShipping())}</span>
        </div>

        <div class="summary-row">
          <span>Tax</span>
          <span>{formatPrice(calculateTax())}</span>
        </div>

        <div class="summary-row total">
          <span>Total</span>
          <span>{formatPrice(calculateTotal())}</span>
        </div>
      </div>

      <div class="promo-section">
        <div class="promo-header">
          <h4>Promo Code</h4>
          {#if !promoApplied}
            <button 
              on:click={() => showPromoForm = !showPromoForm}
              class="promo-toggle"
            >
              {showPromoForm ? 'Cancel' : 'Add Code'}
            </button>
          {/if}
        </div>

        {#if showPromoForm && !promoApplied}
          <div class="promo-form">
            <input
              type="text"
              bind:value={promoCode}
              placeholder="Enter promo code"
              class="promo-input"
            />
            <button 
              on:click={applyPromoCode}
              disabled={!promoCode.trim()}
              class="apply-promo-btn"
            >
              Apply
            </button>
          </div>
        {/if}

        {#if promoMessage}
          <div class="promo-message" class:error={!promoApplied}>
            {promoMessage}
          </div>
        {/if}

        {#if promoApplied}
          <div class="applied-promo">
            <span>Applied: {promoCode}</span>
            <button 
              on:click={removePromoCode}
              class="remove-promo-btn"
            >
              Remove
            </button>
          </div>
        {/if}
      </div>

      <div class="shipping-section">
        <h4>Shipping Options</h4>
        <div class="shipping-options">
          {#each shippingOptions as option}
            <label class="shipping-option">
              <input
                type="radio"
                bind:group={shippingOption}
                value={option.value}
                name="shipping"
              />
              <div class="shipping-info">
                <div class="shipping-label">{option.label}</div>
                <div class="shipping-details">
                  {option.days} • {formatPrice(option.price)}
                </div>
              </div>
            </label>
          {/each}
        </div>
      </div>

      <div class="checkout-section">
        <button 
          on:click={handleCheckout}
          disabled={cartItems.length === 0 || isCheckingOut}
          class="checkout-btn"
        >
          {isCheckingOut ? 'Processing...' : `Checkout ${formatPrice(calculateTotal())}`}
        </button>
        
        <div class="checkout-info">
          <p>Secure checkout with SSL encryption</p>
          <p>We accept Visa, MasterCard, American Express</p>
        </div>
      </div>
    </div>
  </div>

  <div class="product-suggestions">
    <h3>You might also like</h3>
    <div class="suggestions-grid">
      {#each sampleProducts.slice(0, 3) as product}
        <div class="suggestion-item">
          <img src={product.image} alt={product.name} />
          <h4>{product.name}</h4>
          <p class="suggestion-price">{formatPrice(product.price)}</p>
          <button 
            on:click={() => addToCart(product)}
            disabled={!product.inStock}
            class="add-to-cart-btn"
          >
            {product.inStock ? 'Add to Cart' : 'Out of Stock'}
          </button>
        </div>
      {/each}
    </div>
  </div>
</div>

<style>
  .shopping-cart {
    max-width: 1200px;
    margin: 0 auto;
    padding: 20px;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  }

  .cart-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 30px;
    padding-bottom: 15px;
    border-bottom: 2px solid #e0e0e0;
  }

  .cart-header h1 {
    margin: 0;
    color: #333;
    font-size: 28px;
  }

  .clear-cart-btn {
    padding: 8px 16px;
    background: #f44336;
    color: white;
    border: none;
    border-radius: 6px;
    cursor: pointer;
    font-size: 14px;
    font-weight: 600;
    transition: background-color 0.3s ease;
  }

  .clear-cart-btn:hover:not(:disabled) {
    background: #d32f2f;
  }

  .clear-cart-btn:disabled {
    background: #ccc;
    cursor: not-allowed;
  }

  .cart-content {
    display: grid;
    grid-template-columns: 1fr 400px;
    gap: 30px;
    margin-bottom: 40px;
  }

  .cart-items {
    background: white;
    border: 1px solid #e0e0e0;
    border-radius: 8px;
    overflow: hidden;
  }

  .empty-cart {
    text-align: center;
    padding: 60px 20px;
    color: #666;
  }

  .empty-icon {
    font-size: 48px;
    margin-bottom: 20px;
  }

  .empty-cart h3 {
    margin: 0 0 10px 0;
    color: #333;
    font-size: 20px;
  }

  .empty-cart p {
    margin: 0;
    font-size: 14px;
  }

  .items-list {
    padding: 20px;
  }

  .cart-item {
    display: flex;
    gap: 15px;
    padding: 20px 0;
    border-bottom: 1px solid #f0f0f0;
  }

  .cart-item:last-child {
    border-bottom: none;
  }

  .item-image img {
    width: 80px;
    height: 80px;
    object-fit: cover;
    border-radius: 6px;
  }

  .item-details {
    flex: 1;
  }

  .item-name {
    margin: 0 0 5px 0;
    color: #333;
    font-size: 16px;
    font-weight: 600;
  }

  .item-category {
    margin: 0 0 5px 0;
    color: #666;
    font-size: 12px;
    text-transform: uppercase;
    letter-spacing: 0.5px;
  }

  .item-price {
    margin: 0 0 5px 0;
    color: #666;
    font-size: 14px;
  }

  .out-of-stock {
    color: #f44336;
    font-size: 12px;
    font-weight: 600;
  }

  .item-controls {
    display: flex;
    flex-direction: column;
    align-items: flex-end;
    gap: 10px;
  }

  .quantity-controls {
    display: flex;
    align-items: center;
    gap: 5px;
  }

  .quantity-btn {
    width: 30px;
    height: 30px;
    border: 1px solid #ddd;
    background: white;
    cursor: pointer;
    border-radius: 4px;
    font-size: 16px;
    font-weight: bold;
    transition: all 0.3s ease;
  }

  .quantity-btn:hover:not(:disabled) {
    background: #4caf50;
    color: white;
    border-color: #4caf50;
  }

  .quantity-btn:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  .quantity-input {
    width: 50px;
    height: 30px;
    border: 1px solid #ddd;
    border-radius: 4px;
    text-align: center;
    font-size: 14px;
  }

  .quantity-input:focus {
    outline: none;
    border-color: #4caf50;
  }

  .item-total {
    font-size: 16px;
    font-weight: bold;
    color: #333;
  }

  .remove-btn {
    padding: 4px 8px;
    background: #f44336;
    color: white;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    font-size: 12px;
    transition: background-color 0.3s ease;
  }

  .remove-btn:hover {
    background: #d32f2f;
  }

  .cart-summary {
    background: #f8f9fa;
    border: 1px solid #e0e0e0;
    border-radius: 8px;
    padding: 20px;
    height: fit-content;
  }

  .summary-section {
    margin-bottom: 25px;
  }

  .summary-section h3 {
    margin: 0 0 15px 0;
    color: #333;
    font-size: 18px;
  }

  .summary-row {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 8px 0;
    font-size: 14px;
  }

  .summary-row.discount {
    color: #4caf50;
    font-weight: 600;
  }

  .summary-row.total {
    border-top: 2px solid #e0e0e0;
    padding-top: 15px;
    margin-top: 10px;
    font-size: 18px;
    font-weight: bold;
    color: #333;
  }

  .promo-section {
    margin-bottom: 25px;
    padding: 15px;
    background: white;
    border-radius: 6px;
    border: 1px solid #e0e0e0;
  }

  .promo-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 10px;
  }

  .promo-header h4 {
    margin: 0;
    color: #333;
    font-size: 14px;
  }

  .promo-toggle {
    background: none;
    border: none;
    color: #4caf50;
    cursor: pointer;
    font-size: 12px;
    font-weight: 600;
  }

  .promo-form {
    display: flex;
    gap: 8px;
  }

  .promo-input {
    flex: 1;
    padding: 8px 12px;
    border: 1px solid #ddd;
    border-radius: 4px;
    font-size: 14px;
  }

  .promo-input:focus {
    outline: none;
    border-color: #4caf50;
  }

  .apply-promo-btn {
    padding: 8px 16px;
    background: #4caf50;
    color: white;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    font-size: 14px;
    font-weight: 600;
    transition: background-color 0.3s ease;
  }

  .apply-promo-btn:hover:not(:disabled) {
    background: #45a049;
  }

  .apply-promo-btn:disabled {
    background: #ccc;
    cursor: not-allowed;
  }

  .promo-message {
    margin-top: 8px;
    padding: 6px 8px;
    border-radius: 4px;
    font-size: 12px;
    background: #e8f5e8;
    color: #4caf50;
  }

  .promo-message.error {
    background: #ffebee;
    color: #f44336;
  }

  .applied-promo {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 8px;
    background: #e8f5e8;
    border-radius: 4px;
    font-size: 12px;
    color: #4caf50;
  }

  .remove-promo-btn {
    background: none;
    border: none;
    color: #f44336;
    cursor: pointer;
    font-size: 12px;
    font-weight: 600;
  }

  .shipping-section {
    margin-bottom: 25px;
  }

  .shipping-section h4 {
    margin: 0 0 15px 0;
    color: #333;
    font-size: 14px;
  }

  .shipping-options {
    display: flex;
    flex-direction: column;
    gap: 10px;
  }

  .shipping-option {
    display: flex;
    align-items: center;
    gap: 10px;
    cursor: pointer;
    padding: 10px;
    border: 1px solid #e0e0e0;
    border-radius: 6px;
    transition: all 0.3s ease;
  }

  .shipping-option:hover {
    border-color: #4caf50;
    background: #f8f9fa;
  }

  .shipping-option input[type="radio"] {
    margin: 0;
  }

  .shipping-info {
    flex: 1;
  }

  .shipping-label {
    font-weight: 600;
    color: #333;
    font-size: 14px;
  }

  .shipping-details {
    font-size: 12px;
    color: #666;
    margin-top: 2px;
  }

  .checkout-section {
    text-align: center;
  }

  .checkout-btn {
    width: 100%;
    padding: 15px;
    background: #4caf50;
    color: white;
    border: none;
    border-radius: 6px;
    cursor: pointer;
    font-size: 16px;
    font-weight: bold;
    transition: background-color 0.3s ease;
    margin-bottom: 15px;
  }

  .checkout-btn:hover:not(:disabled) {
    background: #45a049;
  }

  .checkout-btn:disabled {
    background: #ccc;
    cursor: not-allowed;
  }

  .checkout-info {
    font-size: 11px;
    color: #666;
    line-height: 1.4;
  }

  .checkout-info p {
    margin: 2px 0;
  }

  .product-suggestions {
    background: white;
    border: 1px solid #e0e0e0;
    border-radius: 8px;
    padding: 20px;
  }

  .product-suggestions h3 {
    margin: 0 0 20px 0;
    color: #333;
    font-size: 18px;
  }

  .suggestions-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 20px;
  }

  .suggestion-item {
    text-align: center;
    padding: 15px;
    border: 1px solid #e0e0e0;
    border-radius: 6px;
    transition: all 0.3s ease;
  }

  .suggestion-item:hover {
    border-color: #4caf50;
    transform: translateY(-2px);
    box-shadow: 0 4px 12px rgba(76, 175, 80, 0.2);
  }

  .suggestion-item img {
    width: 100%;
    height: 120px;
    object-fit: cover;
    border-radius: 4px;
    margin-bottom: 10px;
  }

  .suggestion-item h4 {
    margin: 0 0 8px 0;
    color: #333;
    font-size: 14px;
    font-weight: 600;
  }

  .suggestion-price {
    margin: 0 0 10px 0;
    color: #4caf50;
    font-size: 16px;
    font-weight: bold;
  }

  .add-to-cart-btn {
    width: 100%;
    padding: 8px 12px;
    background: #4caf50;
    color: white;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    font-size: 12px;
    font-weight: 600;
    transition: background-color 0.3s ease;
  }

  .add-to-cart-btn:hover:not(:disabled) {
    background: #45a049;
  }

  .add-to-cart-btn:disabled {
    background: #ccc;
    cursor: not-allowed;
  }

  @media (max-width: 768px) {
    .shopping-cart {
      padding: 15px;
    }
    
    .cart-content {
      grid-template-columns: 1fr;
      gap: 20px;
    }
    
    .cart-summary {
      order: -1;
    }
    
    .cart-item {
      flex-direction: column;
      gap: 10px;
    }
    
    .item-controls {
      align-items: stretch;
    }
    
    .quantity-controls {
      justify-content: center;
    }
    
    .suggestions-grid {
      grid-template-columns: 1fr;
    }
  }

  @media (max-width: 480px) {
    .shopping-cart {
      padding: 10px;
    }
    
    .cart-header {
      flex-direction: column;
      gap: 15px;
      align-items: stretch;
    }
    
    .cart-item {
      padding: 15px 0;
    }
    
    .item-image img {
      width: 60px;
      height: 60px;
    }
    
    .promo-form {
      flex-direction: column;
    }
    
    .shipping-option {
      flex-direction: column;
      align-items: stretch;
      text-align: center;
    }
  }
</style>
