// scenarios/advanced/web/vue/n12.vue
<template>
  <div class="main-container">
    <div class="main-content">
      <h1>Settings Dashboard</h1>
      <p>Manage your application preferences and settings.</p>
      
      <div class="dashboard-content">
        <button @click="openModal" class="open-modal-btn">
          Open Settings Modal
        </button>
        
        <div class="current-settings">
          <h3>Current Settings:</h3>
          <p><strong>Theme:</strong> {{ settings.theme }}</p>
          <p><strong>Language:</strong> {{ settings.language }}</p>
          <p><strong>Notifications:</strong> {{ settings.notifications }}</p>
        </div>
      </div>
    </div>

    <!-- Modal -->
    <div v-if="isModalOpen" class="modal-overlay" @click="closeModalOnOverlay">
      <div class="modal-content" @click.stop>
        <div class="modal-header">
          <h2 class="modal-title">Settings</h2>
          <button @click="closeModal" class="close-btn" aria-label="Close modal">
            ×
          </button>
        </div>
        
        <form>
          <div class="form-group">
            <label for="theme">Theme:</label>
            <select id="theme" v-model="settings.theme">
              <option value="light">Light</option>
              <option value="dark">Dark</option>
              <option value="auto">Auto</option>
            </select>
          </div>
          
          <div class="form-group">
            <label for="language">Language:</label>
            <select id="language" v-model="settings.language">
              <option value="en">English</option>
              <option value="es">Spanish</option>
              <option value="fr">French</option>
            </select>
          </div>
          
          <div class="form-group">
            <label for="notifications">Email Notifications:</label>
            <select id="notifications" v-model="settings.notifications">
              <option value="all">All</option>
              <option value="important">Important Only</option>
              <option value="none">None</option>
            </select>
          </div>
        </form>
        
        <div class="modal-actions">
          <button type="button" @click="closeModal" class="btn btn-secondary">
            Cancel
          </button>
          <button type="button" @click="saveSettings" class="btn btn-primary">
            Save Settings
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { ref, reactive } from 'vue'

export default {
  name: 'ModalWithoutFocusManagement',
  setup() {
    const isModalOpen = ref(false)
    const settings = reactive({
      theme: 'light',
      language: 'en',
      notifications: 'all'
    })

    const openModal = () => {
      isModalOpen.value = true
    }

    const closeModal = () => {
      isModalOpen.value = false
    }

    const closeModalOnOverlay = (event) => {
      if (event.target === event.currentTarget) {
        closeModal()
      }
    }

    const saveSettings = () => {
      alert('Settings saved successfully!')
      closeModal()
    }

    return {
      isModalOpen,
      settings,
      openModal,
      closeModal,
      closeModalOnOverlay,
      saveSettings
    }
  }
}
</script>

<style scoped>
.main-container {
  font-family: Arial, sans-serif;
  max-width: 800px;
  margin: 50px auto;
  padding: 20px;
  background-color: #f5f5f5;
}

.main-content {
  background: white;
  padding: 30px;
  border-radius: 8px;
  box-shadow: 0 2px 10px rgba(0,0,0,0.1);
}

.dashboard-content {
  margin-top: 30px;
}

.open-modal-btn {
  background-color: #007bff;
  color: white;
  padding: 12px 24px;
  border: none;
  border-radius: 4px;
  font-size: 16px;
  cursor: pointer;
}

.open-modal-btn:hover {
  background-color: #0056b3;
}

.current-settings {
  margin-top: 20px;
  padding: 20px;
  background-color: #f8f9fa;
  border-radius: 4px;
}

.current-settings h3 {
  margin-top: 0;
}

.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.5);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1000;
}

.modal-content {
  background: white;
  padding: 30px;
  border-radius: 8px;
  box-shadow: 0 4px 20px rgba(0,0,0,0.3);
  max-width: 500px;
  width: 90%;
  position: relative;
}

.modal-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
  padding-bottom: 10px;
  border-bottom: 1px solid #eee;
}

.modal-title {
  margin: 0;
  font-size: 24px;
  color: #333;
}

.close-btn {
  background: none;
  border: none;
  font-size: 24px;
  cursor: pointer;
  color: #666;
  padding: 0;
  width: 30px;
  height: 30px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.close-btn:hover {
  color: #333;
}

.form-group {
  margin-bottom: 20px;
}

.form-group label {
  display: block;
  margin-bottom: 5px;
  font-weight: bold;
  color: #333;
}

.form-group input, .form-group select {
  width: 100%;
  padding: 10px;
  border: 1px solid #ddd;
  border-radius: 4px;
  font-size: 16px;
  box-sizing: border-box;
}

.modal-actions {
  display: flex;
  gap: 10px;
  justify-content: flex-end;
  margin-top: 30px;
}

.btn {
  padding: 10px 20px;
  border: none;
  border-radius: 4px;
  font-size: 16px;
  cursor: pointer;
}

.btn-primary {
  background-color: #007bff;
  color: white;
}

.btn-primary:hover {
  background-color: #0056b3;
}

.btn-secondary {
  background-color: #6c757d;
  color: white;
}

.btn-secondary:hover {
  background-color: #545b62;
}
</style>

// scenarios/basic/web/angular/n12.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-missing-page-title',
  template: `
    <div class="settings-page">
      <!-- This page intentionally lacks a proper <title> element -->
      <h1>Settings</h1>
      <p>Configure your application preferences and account settings.</p>
      
      <div class="settings-grid">
        <!-- Appearance Settings -->
        <div class="settings-card">
          <h2>Appearance</h2>
          
          <div class="setting-group">
            <label class="setting-label">Theme</label>
            <select [(ngModel)]="settings.theme" class="setting-select">
              <option value="light">Light</option>
              <option value="dark">Dark</option>
              <option value="auto">Auto</option>
            </select>
          </div>
          
          <div class="setting-group">
            <label class="setting-label">Font Size</label>
            <select [(ngModel)]="settings.fontSize" class="setting-select">
              <option value="small">Small</option>
              <option value="medium">Medium</option>
              <option value="large">Large</option>
            </select>
          </div>
        </div>

        <!-- Language Settings -->
        <div class="settings-card">
          <h2>Language & Region</h2>
          
          <div class="setting-group">
            <label class="setting-label">Language</label>
            <select [(ngModel)]="settings.language" class="setting-select">
              <option value="en">English</option>
              <option value="es">Spanish</option>
              <option value="fr">French</option>
              <option value="de">German</option>
              <option value="it">Italian</option>
            </select>
          </div>
          
          <div class="setting-group">
            <label class="setting-label">Time Zone</label>
            <select class="setting-select">
              <option value="utc">UTC</option>
              <option value="est">Eastern Time</option>
              <option value="pst">Pacific Time</option>
              <option value="cet">Central European Time</option>
            </select>
          </div>
        </div>

        <!-- Notification Settings -->
        <div class="settings-card">
          <h2>Notifications</h2>
          
          <div class="checkbox-group">
            <div class="checkbox-item">
              <input
                type="checkbox"
                id="newsletter"
                [(ngModel)]="settings.newsletter"
                name="newsletter"
                class="checkbox-input"
              />
              <label for="newsletter" class="checkbox-label">Enable notifications</label>
            </div>
            
            <div class="checkbox-item">
              <input
                type="checkbox"
                id="autoSave"
                [(ngModel)]="settings.autoSave"
                name="autoSave"
                class="checkbox-input"
              />
              <label for="autoSave" class="checkbox-label">Auto-save changes</label>
            </div>
            
            <div class="checkbox-item">
              <input
                type="checkbox"
                id="emailNotifications"
                class="checkbox-input"
              />
              <label for="emailNotifications" class="checkbox-label">Email notifications</label>
            </div>
          </div>
        </div>

        <!-- Privacy Settings -->
        <div class="settings-card">
          <h2>Privacy & Security</h2>
          
          <div class="setting-group">
            <label class="setting-label">Data Collection</label>
            <select class="setting-select">
              <option value="minimal">Minimal</option>
              <option value="standard">Standard</option>
              <option value="comprehensive">Comprehensive</option>
            </select>
          </div>
          
          <div class="setting-group">
            <label class="setting-label">Session Timeout</label>
            <select class="setting-select">
              <option value="15">15 minutes</option>
              <option value="30">30 minutes</option>
              <option value="60">1 hour</option>
              <option value="240">4 hours</option>
            </select>
          </div>
        </div>
      </div>

      <div class="form-actions">
        <button class="btn-secondary">Cancel</button>
        <button class="btn-primary">Save Changes</button>
      </div>
    </div>
  `,
  styles: [`
    .settings-page {
      max-width: 800px;
      margin: 50px auto;
      padding: 20px;
      font-family: Arial, sans-serif;
    }

    .settings-grid {
      display: grid;
      gap: 30px;
    }

    .settings-card {
      background: white;
      padding: 25px;
      border-radius: 8px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.1);
      border: 1px solid #e0e0e0;
    }

    .settings-card h2 {
      font-size: 20px;
      margin: 0 0 20px 0;
      color: #333;
      border-bottom: 2px solid #007bff;
      padding-bottom: 10px;
    }

    .setting-group {
      margin-bottom: 20px;
    }

    .setting-label {
      display: block;
      margin-bottom: 8px;
      font-weight: bold;
      color: #333;
    }

    .setting-select {
      padding: 8px 12px;
      border: 1px solid #ddd;
      border-radius: 4px;
      font-size: 14px;
      width: 200px;
    }

    .checkbox-group {
      margin-top: 10px;
    }

    .checkbox-item {
      margin-bottom: 15px;
    }

    .checkbox-input {
      margin-right: 10px;
    }

    .checkbox-label {
      display: flex;
      align-items: center;
      cursor: pointer;
      font-weight: bold;
      color: #333;
    }

    .form-actions {
      display: flex;
      gap: 15px;
      justify-content: flex-end;
      margin-top: 30px;
    }

    .btn-primary {
      background: #007bff;
      color: white;
      border: none;
      padding: 12px 24px;
      border-radius: 4px;
      cursor: pointer;
      font-size: 16px;
    }

    .btn-secondary {
      background: #6c757d;
      color: white;
      border: none;
      padding: 12px 24px;
      border-radius: 4px;
      cursor: pointer;
      font-size: 16px;
    }
  `]
})
export class MissingPageTitleComponent {
  settings = {
    theme: 'light',
    language: 'en',
    newsletter: true,
    autoSave: true,
    fontSize: 'medium'
  };
}
