// scenarios/basic/web/react/RightClickOnlyMenu.jsx
import React, { useState } from 'react';

const RightClickOnlyMenu = () => {
  const [files] = useState([
    { id: 1, name: 'Document1.pdf', type: 'pdf', size: '2.3 MB', lastModified: '2024-01-15' },
    { id: 2, name: 'Image1.jpg', type: 'image', size: '1.8 MB', lastModified: '2024-01-14' },
    { id: 3, name: 'Spreadsheet.xlsx', type: 'excel', size: '856 KB', lastModified: '2024-01-13' },
    { id: 4, name: 'Presentation.pptx', type: 'powerpoint', size: '4.2 MB', lastModified: '2024-01-12' },
    { id: 5, name: 'TextFile.txt', type: 'text', size: '12 KB', lastModified: '2024-01-11' }
  ]);

  const [contextMenu, setContextMenu] = useState({ visible: false, x: 0, y: 0, fileId: null });
  const [selectedFile, setSelectedFile] = useState(null);

  const getFileIcon = (type) => {
    const icons = {
      pdf: '📄',
      image: '🖼️',
      excel: '📊',
      powerpoint: '📈',
      text: '📝'
    };
    return icons[type] || '📄';
  };

  const handleContextMenu = (e, fileId) => {
    e.preventDefault();
    setContextMenu({
      visible: true,
      x: e.clientX,
      y: e.clientY,
      fileId: fileId
    });
    setSelectedFile(fileId);
  };

  const handleClick = () => {
    setContextMenu({ visible: false, x: 0, y: 0, fileId: null });
    setSelectedFile(null);
  };

  const handleAction = (action) => {
    const file = files.find(f => f.id === selectedFile);
    alert(`${action} action performed on ${file?.name}`);
  };

  const handleContextAction = (action) => {
    const file = files.find(f => f.id === contextMenu.fileId);
    alert(`${action} action performed on ${file?.name}`);
    setContextMenu({ visible: false, x: 0, y: 0, fileId: null });
    setSelectedFile(null);
  };

  const totalSize = files.reduce((total, file) => {
    const size = parseFloat(file.size);
    return total + (isNaN(size) ? 0 : size);
  }, 0).toFixed(1);

  return (
    <div style={{ 
      maxWidth: '1000px', 
      margin: '50px auto', 
      padding: '20px',
      fontFamily: 'Arial, sans-serif'
    }}>
      <h1>File Manager</h1>
      <p>Manage your files and documents. Right-click on any file to access additional options.</p>
      
      <div style={{
        background: '#f8f9fa',
        padding: '20px',
        borderRadius: '8px',
        marginBottom: '30px'
      }}>
        <h2>File Statistics</h2>
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
          gap: '20px',
          marginTop: '15px'
        }}>
          <div style={{
            background: 'white',
            padding: '15px',
            borderRadius: '4px',
            textAlign: 'center',
            border: '1px solid #e0e0e0'
          }}>
            <div style={{ fontSize: '24px', fontWeight: 'bold', color: '#007bff', marginBottom: '5px' }}>
              {files.length}
            </div>
            <div style={{ fontSize: '14px', color: '#666' }}>Total Files</div>
          </div>
          <div style={{
            background: 'white',
            padding: '15px',
            borderRadius: '4px',
            textAlign: 'center',
            border: '1px solid #e0e0e0'
          }}>
            <div style={{ fontSize: '24px', fontWeight: 'bold', color: '#28a745', marginBottom: '5px' }}>
              {totalSize} MB
            </div>
            <div style={{ fontSize: '14px', color: '#666' }}>Total Size</div>
          </div>
        </div>
      </div>

      <div style={{
        background: 'white',
        borderRadius: '8px',
        boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
        overflow: 'hidden',
        border: '1px solid #e0e0e0'
      }}>
        <div style={{
          background: '#f8f9fa',
          padding: '20px',
          borderBottom: '1px solid #e0e0e0'
        }}>
          <h2 style={{ margin: 0, fontSize: '20px' }}>Files</h2>
          <p style={{ margin: '5px 0 0 0', color: '#666', fontSize: '14px' }}>
            Right-click on any file to access additional options
          </p>
        </div>
        
        <div style={{ padding: '20px' }}>
          <div style={{
            display: 'grid',
            gap: '10px'
          }}>
            {files.map((file) => (
              <div 
                key={file.id}
                onContextMenu={(e) => handleContextMenu(e, file.id)}
                onClick={handleClick}
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  padding: '15px',
                  border: '1px solid #e0e0e0',
                  borderRadius: '4px',
                  background: selectedFile === file.id ? '#e3f2fd' : '#fafafa',
                  cursor: 'pointer',
                  transition: 'background-color 0.2s ease'
                }}
              >
                <div style={{
                  fontSize: '24px',
                  marginRight: '15px'
                }}>
                  {getFileIcon(file.type)}
                </div>
                
                <div style={{ flex: 1 }}>
                  <h3 style={{ 
                    margin: '0 0 5px 0', 
                    fontSize: '16px',
                    color: '#333'
                  }}>
                    {file.name}
                  </h3>
                  <div style={{
                    display: 'flex',
                    gap: '20px',
                    fontSize: '14px',
                    color: '#666'
                  }}>
                    <span>Size: {file.size}</span>
                    <span>Modified: {file.lastModified}</span>
                    <span style={{ color: '#007bff', fontWeight: 'bold' }}>
                      {file.type.toUpperCase()}
                    </span>
                  </div>
                </div>
                
                <div style={{
                  display: 'flex',
                  gap: '10px',
                  alignItems: 'center'
                }}>
                  <button 
                    onClick={(e) => {
                      e.stopPropagation();
                      handleAction('View');
                    }}
                    style={{
                      background: '#007bff',
                      color: 'white',
                      border: 'none',
                      padding: '6px 12px',
                      borderRadius: '4px',
                      cursor: 'pointer',
                      fontSize: '12px'
                    }}
                  >
                    View
                  </button>
                  <button 
                    onClick={(e) => {
                      e.stopPropagation();
                      handleAction('Download');
                    }}
                    style={{
                      background: '#6c757d',
                      color: 'white',
                      border: 'none',
                      padding: '6px 12px',
                      borderRadius: '4px',
                      cursor: 'pointer',
                      fontSize: '12px'
                    }}
                  >
                    Download
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Essential delete option only available via right-click */}
      {contextMenu.visible && (
        <div 
          style={{
            position: 'fixed',
            left: contextMenu.x + 'px',
            top: contextMenu.y + 'px',
            background: 'white',
            border: '1px solid #ddd',
            borderRadius: '4px',
            boxShadow: '0 4px 12px rgba(0,0,0,0.15)',
            zIndex: 1000,
            minWidth: '150px'
          }}
        >
          <div 
            onClick={() => handleContextAction('Open')}
            style={{
              padding: '10px 15px',
              cursor: 'pointer',
              borderBottom: '1px solid #eee',
              fontSize: '14px'
            }}
          >
            Open
          </div>
          <div 
            onClick={() => handleContextAction('Download')}
            style={{
              padding: '10px 15px',
              cursor: 'pointer',
              borderBottom: '1px solid #eee',
              fontSize: '14px'
            }}
          >
            Download
          </div>
          <div 
            onClick={() => handleContextAction('Rename')}
            style={{
              padding: '10px 15px',
              cursor: 'pointer',
              borderBottom: '1px solid #eee',
              fontSize: '14px'
            }}
          >
            Rename
          </div>
          <div 
            onClick={() => handleContextAction('Move')}
            style={{
              padding: '10px 15px',
              cursor: 'pointer',
              borderBottom: '1px solid #eee',
              fontSize: '14px'
            }}
          >
            Move
          </div>
          <div 
            onClick={() => handleContextAction('Copy')}
            style={{
              padding: '10px 15px',
              cursor: 'pointer',
              borderBottom: '1px solid #eee',
              fontSize: '14px'
            }}
          >
            Copy
          </div>
          <div 
            onClick={() => handleContextAction('Delete')}
            style={{
              padding: '10px 15px',
              cursor: 'pointer',
              color: '#dc3545',
              fontSize: '14px'
            }}
          >
            Delete
          </div>
        </div>
      )}
    </div>
  );
};

export default RightClickOnlyMenu;

// scenarios/basic/web/angular/right-click-only-menu.component.ts
import { Component, HostListener } from '@angular/core';

@Component({
  selector: 'app-right-click-only-menu',
  template: `
    <div class="file-manager">
      <h1>File Manager</h1>
      <p>Manage your files and documents. Right-click on any file to access additional options.</p>
      
      <div class="stats-section">
        <h2>File Statistics</h2>
        <div class="stats-grid">
          <div class="stat-card">
            <div class="stat-number">{{ files.length }}</div>
            <div class="stat-label">Total Files</div>
          </div>
          <div class="stat-card">
            <div class="stat-number">{{ totalSize }} MB</div>
            <div class="stat-label">Total Size</div>
          </div>
        </div>
      </div>

      <div class="files-container">
        <div class="files-header">
          <h2>Files</h2>
          <p>Right-click on any file to access additional options</p>
        </div>
        
        <div class="files-content">
          <div class="files-list">
            <div 
              *ngFor="let file of files" 
              class="file-item"
              [class.selected]="selectedFile === file.id"
              (contextmenu)="handleContextMenu($event, file.id)"
            >
              <div class="file-icon">{{ getFileIcon(file.type) }}</div>
              
              <div class="file-info">
                <h3>{{ file.name }}</h3>
                <div class="file-details">
                  <span>Size: {{ file.size }}</span>
                  <span>Modified: {{ file.lastModified }}</span>
                  <span class="file-type">{{ file.type.toUpperCase() }}</span>
                </div>
              </div>
              
              <div class="file-actions">
                <button (click)="handleAction('View')" class="action-btn view">View</button>
                <button (click)="handleAction('Download')" class="action-btn download">Download</button>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Essential delete option only available via right-click -->
      <div *ngIf="contextMenu.visible" class="context-menu" [style.left.px]="contextMenu.x" [style.top.px]="contextMenu.y">
        <div (click)="handleContextAction('Open')" class="context-item">Open</div>
        <div (click)="handleContextAction('Download')" class="context-item">Download</div>
        <div (click)="handleContextAction('Rename')" class="context-item">Rename</div>
        <div (click)="handleContextAction('Move')" class="context-item">Move</div>
        <div (click)="handleContextAction('Copy')" class="context-item">Copy</div>
        <div (click)="handleContextAction('Delete')" class="context-item delete">Delete</div>
      </div>
    </div>
  `,
  styles: [`
    .file-manager {
      max-width: 1000px;
      margin: 50px auto;
      padding: 20px;
      font-family: Arial, sans-serif;
    }

    .stats-section {
      background: #f8f9fa;
      padding: 20px;
      border-radius: 8px;
      margin-bottom: 30px;
    }

    .stats-section h2 {
      margin: 0 0 15px 0;
    }

    .stats-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 20px;
      margin-top: 15px;
    }

    .stat-card {
      background: white;
      padding: 15px;
      border-radius: 4px;
      text-align: center;
      border: 1px solid #e0e0e0;
    }

    .stat-number {
      font-size: 24px;
      font-weight: bold;
      color: #007bff;
      margin-bottom: 5px;
    }

    .stat-label {
      font-size: 14px;
      color: #666;
    }

    .files-container {
      background: white;
      border-radius: 8px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.1);
      overflow: hidden;
      border: 1px solid #e0e0e0;
    }

    .files-header {
      background: #f8f9fa;
      padding: 20px;
      border-bottom: 1px solid #e0e0e0;
    }

    .files-header h2 {
      margin: 0;
      font-size: 20px;
    }

    .files-header p {
      margin: 5px 0 0 0;
      color: #666;
      font-size: 14px;
    }

    .files-content {
      padding: 20px;
    }

    .files-list {
      display: grid;
      gap: 10px;
    }

    .file-item {
      display: flex;
      align-items: center;
      padding: 15px;
      border: 1px solid #e0e0e0;
      border-radius: 4px;
      background: #fafafa;
      cursor: pointer;
      transition: background-color 0.2s ease;
    }

    .file-item.selected {
      background: #e3f2fd;
    }

    .file-icon {
      font-size: 24px;
      margin-right: 15px;
    }

    .file-info {
      flex: 1;
    }

    .file-info h3 {
      margin: 0 0 5px 0;
      font-size: 16px;
      color: #333;
    }

    .file-details {
      display: flex;
      gap: 20px;
      font-size: 14px;
      color: #666;
    }

    .file-type {
      color: #007bff;
      font-weight: bold;
    }

    .file-actions {
      display: flex;
      gap: 10px;
      align-items: center;
    }

    .action-btn {
      padding: 6px 12px;
      border: none;
      border-radius: 4px;
      cursor: pointer;
      font-size: 12px;
    }

    .action-btn.view {
      background: #007bff;
      color: white;
    }

    .action-btn.download {
      background: #6c757d;
      color: white;
    }

    .context-menu {
      position: fixed;
      background: white;
      border: 1px solid #ddd;
      border-radius: 4px;
      box-shadow: 0 4px 12px rgba(0,0,0,0.15);
      z-index: 1000;
      min-width: 150px;
    }

    .context-item {
      padding: 10px 15px;
      cursor: pointer;
      border-bottom: 1px solid #eee;
      font-size: 14px;
    }

    .context-item:hover {
      background: #f8f9fa;
    }

    .context-item.delete {
      color: #dc3545;
    }

    .context-item:last-child {
      border-bottom: none;
    }
  `]
})
export class RightClickOnlyMenuComponent {
  files = [
    { id: 1, name: 'Document1.pdf', type: 'pdf', size: '2.3 MB', lastModified: '2024-01-15' },
    { id: 2, name: 'Image1.jpg', type: 'image', size: '1.8 MB', lastModified: '2024-01-14' },
    { id: 3, name: 'Spreadsheet.xlsx', type: 'excel', size: '856 KB', lastModified: '2024-01-13' },
    { id: 4, name: 'Presentation.pptx', type: 'powerpoint', size: '4.2 MB', lastModified: '2024-01-12' },
    { id: 5, name: 'TextFile.txt', type: 'text', size: '12 KB', lastModified: '2024-01-11' }
  ];

  contextMenu = { visible: false, x: 0, y: 0, fileId: null };
  selectedFile: number | null = null;

  get totalSize() {
    return this.files.reduce((total, file) => {
      const size = parseFloat(file.size);
      return total + (isNaN(size) ? 0 : size);
    }, 0).toFixed(1);
  }

  getFileIcon(type: string) {
    const icons: { [key: string]: string } = {
      pdf: '📄',
      image: '🖼️',
      excel: '📊',
      powerpoint: '📈',
      text: '📝'
    };
    return icons[type] || '📄';
  }

  handleContextMenu(e: MouseEvent, fileId: number) {
    e.preventDefault();
    this.contextMenu = {
      visible: true,
      x: e.clientX,
      y: e.clientY,
      fileId: fileId
    };
    this.selectedFile = fileId;
  }

  @HostListener('document:click')
  handleClick() {
    this.contextMenu = { visible: false, x: 0, y: 0, fileId: null };
    this.selectedFile = null;
  }

  handleAction(action: string) {
    const file = this.files.find(f => f.id === this.selectedFile);
    alert(`${action} action performed on ${file?.name}`);
  }

  handleContextAction(action: string) {
    const file = this.files.find(f => f.id === this.contextMenu.fileId);
    alert(`${action} action performed on ${file?.name}`);
    this.contextMenu = { visible: false, x: 0, y: 0, fileId: null };
    this.selectedFile = null;
  }
}
