// scenarios/basic/web/angular/n4.ts
import { Component, OnInit, OnDestroy } from '@angular/core';

@Component({
  selector: 'app-flashing-advertisement',
  template: `
    <div class="news-website">
      <h1>News Website</h1>
      <p>Stay informed with the latest news and updates from around the world.</p>
      
      <!-- Sale banner flashing 5 times per second -->
      <div *ngIf="showAd" class="ad-banner" [class.flashing]="isFlashing">
        <button (click)="closeAd()" class="close-btn">×</button>
        
        <h2>🔥 LIMITED TIME OFFER! 🔥</h2>
        <p>Get 50% OFF on Premium Subscription</p>
        <div class="ad-controls">
          <button class="claim-btn">CLAIM OFFER NOW</button>
        </div>
      </div>

      <div class="articles-grid">
        <article class="article-card">
          <h2>Breaking: New Technology Breakthrough</h2>
          <p>
            Scientists have made a significant breakthrough in quantum computing that 
            could revolutionize how we process information and solve complex problems.
          </p>
          <div class="article-footer">
            <span class="publish-time">2 hours ago</span>
            <button class="read-more-btn">Read More</button>
          </div>
        </article>

        <article class="article-card">
          <h2>Market Update: Stocks Reach New High</h2>
          <p>
            The stock market has reached new all-time highs as investors show 
            confidence in the economic recovery and technological innovation.
          </p>
          <div class="article-footer">
            <span class="publish-time">4 hours ago</span>
            <button class="read-more-btn">Read More</button>
          </div>
        </article>
      </div>

      <div class="newsletter-section">
        <h2>Subscribe to Our Newsletter</h2>
        <p>Get the latest news delivered directly to your inbox.</p>
        
        <div class="newsletter-form">
          <input 
            type="email" 
            placeholder="Enter your email address"
            class="email-input"
          />
          <button class="subscribe-btn">Subscribe</button>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .news-website {
      max-width: 1000px;
      margin: 50px auto;
      padding: 20px;
      font-family: Arial, sans-serif;
    }

    .ad-banner {
      position: relative;
      background: #ff4444;
      color: white;
      padding: 20px;
      border-radius: 8px;
      margin-bottom: 30px;
      text-align: center;
      box-shadow: 0 4px 12px rgba(255, 68, 68, 0.3);
      transition: background-color 0.2s ease;
    }

    .ad-banner.flashing {
      background: #ff6b6b;
    }

    .close-btn {
      position: absolute;
      top: 10px;
      right: 15px;
      background: rgba(255,255,255,0.2);
      color: white;
      border: none;
      border-radius: 50%;
      width: 30px;
      height: 30px;
      cursor: pointer;
      font-size: 16px;
      font-weight: bold;
    }

    .ad-banner h2 {
      margin: 0 0 10px 0;
      font-size: 24px;
      font-weight: bold;
    }

    .ad-banner p {
      margin: 0 0 15px 0;
      font-size: 18px;
    }

    .ad-controls {
      display: flex;
      justify-content: center;
      align-items: center;
      gap: 20px;
      flex-wrap: wrap;
    }

    .claim-btn {
      background: white;
      color: #ff4444;
      border: none;
      padding: 12px 24px;
      border-radius: 25px;
      font-size: 16px;
      font-weight: bold;
      cursor: pointer;
      box-shadow: 0 2px 8px rgba(0,0,0,0.2);
    }

    .articles-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
      gap: 30px;
      margin-bottom: 30px;
    }

    .article-card {
      background: white;
      padding: 25px;
      border-radius: 8px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.1);
      border: 1px solid #e0e0e0;
    }

    .article-card h2 {
      font-size: 22px;
      margin: 0 0 15px 0;
      color: #333;
    }

    .article-card p {
      font-size: 16px;
      line-height: 1.6;
      color: #666;
      margin: 0 0 20px 0;
    }

    .article-footer {
      display: flex;
      justify-content: space-between;
      align-items: center;
    }

    .publish-time {
      font-size: 14px;
      color: #999;
    }

    .read-more-btn {
      background: #007bff;
      color: white;
      border: none;
      padding: 8px 16px;
      border-radius: 4px;
      cursor: pointer;
      font-size: 14px;
    }

    .newsletter-section {
      background: #f8f9fa;
      padding: 30px;
      border-radius: 8px;
      text-align: center;
    }

    .newsletter-section h2 {
      font-size: 24px;
      margin: 0 0 15px 0;
      color: #333;
    }

    .newsletter-section p {
      font-size: 16px;
      margin: 0 0 25px 0;
      color: #666;
    }

    .newsletter-form {
      display: flex;
      gap: 10px;
      justify-content: center;
      flex-wrap: wrap;
    }

    .email-input {
      padding: 12px 16px;
      border: 1px solid #ddd;
      border-radius: 4px;
      font-size: 16px;
      min-width: 250px;
    }

    .subscribe-btn {
      background: #28a745;
      color: white;
      border: none;
      padding: 12px 24px;
      border-radius: 4px;
      cursor: pointer;
      font-size: 16px;
    }
  `]
})
export class FlashingAdvertisementComponent implements OnInit, OnDestroy {
  isFlashing = true;
  showAd = true;
  private flashInterval: any;

  ngOnInit() {
    // Flash every 200ms (5 times per second)
    this.flashInterval = setInterval(() => {
      if (this.showAd) {
        this.isFlashing = !this.isFlashing;
      }
    }, 200);
  }

  ngOnDestroy() {
    if (this.flashInterval) {
      clearInterval(this.flashInterval);
    }
  }

  closeAd() {
    this.showAd = false;
  }
}

// scenarios/basic/web/svelte/n4.svelte
<script>
  let currentAd = 0;
  let isPlaying = true;
  let adSpeed = 200; // milliseconds
  let intervalId = null;

  const advertisements = [
    {
      id: 1,
      title: 'Mega Sale - 70% Off!',
      description: 'Everything must go! Limited time offer.',
      image: 'sale-banner-1.jpg',
      link: '/sale',
      color: '#ff4757',
      textColor: '#ffffff'
    },
    {
      id: 2,
      title: 'New Collection',
      description: 'Discover our latest fashion trends.',
      image: 'fashion-banner.jpg',
      link: '/new-collection',
      color: '#2ed573',
      textColor: '#ffffff'
    },
    {
      id: 3,
      title: 'Free Shipping',
      description: 'On orders over $50. Shop now!',
      image: 'shipping-banner.jpg',
      link: '/shipping',
      color: '#ffa502',
      textColor: '#ffffff'
    },
    {
      id: 4,
      title: 'Tech Deals',
      description: 'Latest gadgets at unbeatable prices.',
      image: 'tech-banner.jpg',
      link: '/tech-deals',
      color: '#3742fa',
      textColor: '#ffffff'
    },
    {
      id: 5,
      title: 'Flash Sale',
      description: '24 hours only! Don\'t miss out.',
      image: 'flash-sale.jpg',
      link: '/flash-sale',
      color: '#ff3838',
      textColor: '#ffffff'
    }
  ];

  function startRotation() {
    if (intervalId) {
      clearInterval(intervalId);
    }
    
    if (isPlaying) {
      intervalId = setInterval(() => {
        currentAd = (currentAd + 1) % advertisements.length;
      }, adSpeed);
    }
  }

  function stopRotation() {
    if (intervalId) {
      clearInterval(intervalId);
      intervalId = null;
    }
  }

  function togglePlayPause() {
    isPlaying = !isPlaying;
    if (isPlaying) {
      startRotation();
    } else {
      stopRotation();
    }
  }

  function goToAd(index) {
    currentAd = index;
    if (isPlaying) {
      startRotation();
    }
  }

  function handleAdClick(ad) {
    alert(`Redirecting to: ${ad.link}`);
  }

  function adjustSpeed(newSpeed) {
    adSpeed = newSpeed;
    if (isPlaying) {
      startRotation();
    }
  }

  // Start rotation on component mount
  startRotation();

  // Cleanup on component destroy
  $: if (typeof window !== 'undefined') {
    return () => {
      if (intervalId) {
        clearInterval(intervalId);
      }
    };
  }
</script>

<div class="advertisement-banner">
  <div class="banner-container">
    <div class="banner-content">
      <div class="banner-image">
        <img 
          src="/images/{advertisements[currentAd].image}" 
          alt="Advertisement banner"
        />
      </div>
      
      <div 
        class="banner-text" 
        style="background-color: {advertisements[currentAd].color}; color: {advertisements[currentAd].textColor};"
      >
        <h2 class="banner-title">{advertisements[currentAd].title}</h2>
        <p class="banner-description">{advertisements[currentAd].description}</p>
        <button 
          class="banner-cta"
          on:click={() => handleAdClick(advertisements[currentAd])}
        >
          Shop Now
        </button>
      </div>
    </div>

    <div class="banner-controls">
      <div class="control-group">
        <button 
          class="control-btn {isPlaying ? 'pause' : 'play'}" 
          on:click={togglePlayPause}
          title={isPlaying ? 'Pause rotation' : 'Start rotation'}
        >
          {isPlaying ? '⏸️' : '▶️'}
        </button>
        
        <div class="speed-control">
          <label for="speed-slider">Speed:</label>
          <input 
            id="speed-slider"
            type="range" 
            min="100" 
            max="1000" 
            step="100"
            bind:value={adSpeed}
            on:input={(e) => adjustSpeed(parseInt(e.target.value))}
            class="speed-slider"
          />
          <span class="speed-value">{adSpeed}ms</span>
        </div>
      </div>

      <div class="ad-indicators">
        {#each advertisements as ad, index}
          <button 
            class="indicator {currentAd === index ? 'active' : ''}" 
            on:click={() => goToAd(index)}
            title="Go to advertisement {index + 1}"
          >
            {index + 1}
          </button>
        {/each}
      </div>
    </div>
  </div>

  <div class="advertisement-stats">
    <div class="stat-item">
      <span class="stat-label">Current Ad:</span>
      <span class="stat-value">{currentAd + 1} of {advertisements.length}</span>
    </div>
    <div class="stat-item">
      <span class="stat-label">Status:</span>
      <span class="stat-value">{isPlaying ? 'Playing' : 'Paused'}</span>
    </div>
    <div class="stat-item">
      <span class="stat-label">Speed:</span>
      <span class="stat-value">{adSpeed}ms</span>
    </div>
  </div>

  <div class="advertisement-list">
    <h3>All Advertisements</h3>
    <div class="ad-grid">
      {#each advertisements as ad, index}
        <div 
          class="ad-preview {currentAd === index ? 'active' : ''}"
          on:click={() => goToAd(index)}
        >
          <div class="preview-image">
            <img src="/images/{ad.image}" alt="Ad preview" />
          </div>
          <div class="preview-content">
            <h4 class="preview-title">{ad.title}</h4>
            <p class="preview-description">{ad.description}</p>
            <div class="preview-meta">
              <span class="preview-id">Ad #{ad.id}</span>
              <span class="preview-link">{ad.link}</span>
            </div>
          </div>
        </div>
      {/each}
    </div>
  </div>
</div>

<style>
  .advertisement-banner {
    max-width: 1200px;
    margin: 50px auto;
    padding: 20px;
    font-family: Arial, sans-serif;
  }

  .banner-container {
    background: white;
    border-radius: 12px;
    box-shadow: 0 4px 16px rgba(0,0,0,0.1);
    overflow: hidden;
    margin-bottom: 30px;
  }

  .banner-content {
    position: relative;
    height: 400px;
    display: flex;
    align-items: center;
    overflow: hidden;
  }

  .banner-image {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 1;
  }

  .banner-image img {
    width: 100%;
    height: 100%;
    object-fit: cover;
  }

  .banner-text {
    position: relative;
    z-index: 2;
    padding: 40px;
    max-width: 500px;
    background: rgba(0,0,0,0.7);
    backdrop-filter: blur(10px);
    border-radius: 8px;
    margin: 20px;
  }

  .banner-title {
    margin: 0 0 15px 0;
    font-size: 36px;
    font-weight: bold;
    text-shadow: 2px 2px 4px rgba(0,0,0,0.5);
  }

  .banner-description {
    margin: 0 0 25px 0;
    font-size: 18px;
    line-height: 1.4;
    text-shadow: 1px 1px 2px rgba(0,0,0,0.5);
  }

  .banner-cta {
    background: rgba(255,255,255,0.2);
    color: white;
    border: 2px solid white;
    padding: 12px 30px;
    border-radius: 25px;
    font-size: 16px;
    font-weight: bold;
    cursor: pointer;
    transition: all 0.3s ease;
  }

  .banner-cta:hover {
    background: white;
    color: #333;
  }

  .banner-controls {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 20px;
    background: #f8f9fa;
    border-top: 1px solid #eee;
  }

  .control-group {
    display: flex;
    align-items: center;
    gap: 20px;
  }

  .control-btn {
    background: #007bff;
    color: white;
    border: none;
    border-radius: 50%;
    width: 40px;
    height: 40px;
    cursor: pointer;
    font-size: 16px;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: background-color 0.2s ease;
  }

  .control-btn:hover {
    background: #0056b3;
  }

  .speed-control {
    display: flex;
    align-items: center;
    gap: 10px;
  }

  .speed-control label {
    font-size: 14px;
    color: #666;
  }

  .speed-slider {
    width: 100px;
  }

  .speed-value {
    font-size: 12px;
    color: #666;
    min-width: 50px;
  }

  .ad-indicators {
    display: flex;
    gap: 8px;
  }

  .indicator {
    width: 32px;
    height: 32px;
    border: 2px solid #ddd;
    background: white;
    border-radius: 50%;
    cursor: pointer;
    font-size: 12px;
    font-weight: bold;
    color: #666;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: all 0.2s ease;
  }

  .indicator:hover {
    border-color: #007bff;
    color: #007bff;
  }

  .indicator.active {
    background: #007bff;
    border-color: #007bff;
    color: white;
  }

  .advertisement-stats {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 20px;
    margin-bottom: 30px;
  }

  .stat-item {
    background: white;
    padding: 20px;
    border-radius: 8px;
    box-shadow: 0 2px 8px rgba(0,0,0,0.1);
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  .stat-label {
    font-weight: bold;
    color: #333;
  }

  .stat-value {
    color: #007bff;
    font-weight: bold;
  }

  .advertisement-list {
    background: white;
    padding: 30px;
    border-radius: 8px;
    box-shadow: 0 2px 8px rgba(0,0,0,0.1);
  }

  .advertisement-list h3 {
    margin: 0 0 20px 0;
    font-size: 24px;
    color: #333;
  }

  .ad-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
    gap: 20px;
  }

  .ad-preview {
    border: 2px solid #eee;
    border-radius: 8px;
    overflow: hidden;
    cursor: pointer;
    transition: all 0.2s ease;
  }

  .ad-preview:hover {
    border-color: #007bff;
    transform: translateY(-2px);
    box-shadow: 0 4px 12px rgba(0,0,0,0.15);
  }

  .ad-preview.active {
    border-color: #007bff;
    box-shadow: 0 0 0 2px rgba(0,123,255,0.2);
  }

  .preview-image {
    height: 150px;
    overflow: hidden;
  }

  .preview-image img {
    width: 100%;
    height: 100%;
    object-fit: cover;
  }

  .preview-content {
    padding: 15px;
  }

  .preview-title {
    margin: 0 0 8px 0;
    font-size: 16px;
    color: #333;
  }

  .preview-description {
    margin: 0 0 10px 0;
    font-size: 14px;
    color: #666;
    line-height: 1.4;
  }

  .preview-meta {
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  .preview-id {
    font-size: 12px;
    color: #007bff;
    font-weight: bold;
  }

  .preview-link {
    font-size: 12px;
    color: #666;
    font-family: monospace;
  }
</style>
