// frameworks/mobile/react-native/MultiStepWizard.jsx
import React, { useState } from 'react';
import {
  View,
  Text,
  TextInput,
  TouchableOpacity,
  ScrollView,
  StyleSheet,
  Alert,
  Switch,
  Modal,
  Dimensions,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';

const { width } = Dimensions.get('window');

const MultiStepWizard = () => {
  const [currentStep, setCurrentStep] = useState(1);
  const [formData, setFormData] = useState({
    personalInfo: {
      firstName: '',
      lastName: '',
      email: '',
      phone: '',
      dateOfBirth: '',
    },
    addressInfo: {
      street: '',
      city: '',
      state: '',
      zipCode: '',
      country: '',
    },
    preferences: {
      newsletter: false,
      notifications: true,
      theme: 'light',
      language: 'en',
    },
    paymentInfo: {
      cardNumber: '',
      expiryDate: '',
      cvv: '',
      cardholderName: '',
    },
    review: {
      termsAccepted: false,
      privacyAccepted: false,
    },
  });
  const [errors, setErrors] = useState({});
  const [isSubmitting, setIsSubmitting] = useState(false);

  const totalSteps = 5;
  const steps = [
    { id: 1, title: 'Personal Info', icon: 'person' },
    { id: 2, title: 'Address', icon: 'location' },
    { id: 3, title: 'Preferences', icon: 'settings' },
    { id: 4, title: 'Payment', icon: 'card' },
    { id: 5, title: 'Review', icon: 'checkmark-circle' },
  ];

  const validateStep = (step) => {
    const newErrors = {};
    
    switch (step) {
      case 1:
        if (!formData.personalInfo.firstName.trim()) {
          newErrors.firstName = 'First name is required';
        }
        if (!formData.personalInfo.lastName.trim()) {
          newErrors.lastName = 'Last name is required';
        }
        if (!formData.personalInfo.email.trim()) {
          newErrors.email = 'Email is required';
        } else if (!/\S+@\S+\.\S+/.test(formData.personalInfo.email)) {
          newErrors.email = 'Email is invalid';
        }
        if (!formData.personalInfo.phone.trim()) {
          newErrors.phone = 'Phone number is required';
        }
        break;
      case 2:
        if (!formData.addressInfo.street.trim()) {
          newErrors.street = 'Street address is required';
        }
        if (!formData.addressInfo.city.trim()) {
          newErrors.city = 'City is required';
        }
        if (!formData.addressInfo.state.trim()) {
          newErrors.state = 'State is required';
        }
        if (!formData.addressInfo.zipCode.trim()) {
          newErrors.zipCode = 'ZIP code is required';
        }
        break;
      case 3:
        // Preferences are optional, no validation needed
        break;
      case 4:
        if (!formData.paymentInfo.cardNumber.trim()) {
          newErrors.cardNumber = 'Card number is required';
        } else if (formData.paymentInfo.cardNumber.replace(/\s/g, '').length < 16) {
          newErrors.cardNumber = 'Card number must be 16 digits';
        }
        if (!formData.paymentInfo.expiryDate.trim()) {
          newErrors.expiryDate = 'Expiry date is required';
        }
        if (!formData.paymentInfo.cvv.trim()) {
          newErrors.cvv = 'CVV is required';
        }
        if (!formData.paymentInfo.cardholderName.trim()) {
          newErrors.cardholderName = 'Cardholder name is required';
        }
        break;
      case 5:
        if (!formData.review.termsAccepted) {
          newErrors.termsAccepted = 'You must accept the terms and conditions';
        }
        if (!formData.review.privacyAccepted) {
          newErrors.privacyAccepted = 'You must accept the privacy policy';
        }
        break;
    }
    
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleNext = () => {
    if (validateStep(currentStep)) {
      if (currentStep < totalSteps) {
        setCurrentStep(currentStep + 1);
      }
    }
  };

  const handlePrevious = () => {
    if (currentStep > 1) {
      setCurrentStep(currentStep - 1);
    }
  };

  const handleSubmit = async () => {
    if (validateStep(currentStep)) {
      setIsSubmitting(true);
      
      // Simulate API call
      setTimeout(() => {
        setIsSubmitting(false);
        Alert.alert(
          'Success!',
          'Your registration has been completed successfully.',
          [{ text: 'OK', onPress: () => setCurrentStep(1) }]
        );
      }, 2000);
    }
  };

  const updateFormData = (section, field, value) => {
    setFormData(prev => ({
      ...prev,
      [section]: {
        ...prev[section],
        [field]: value,
      },
    }));
    
    // Clear error when user starts typing
    if (errors[field]) {
      setErrors(prev => ({
        ...prev,
        [field]: undefined,
      }));
    }
  };

  const renderStepIndicator = () => (
    <View style={styles.stepIndicator}>
      {steps.map((step, index) => (
        <View key={step.id} style={styles.stepContainer}>
          <View style={[
            styles.stepCircle,
            currentStep >= step.id && styles.stepCircleActive,
            currentStep === step.id && styles.stepCircleCurrent,
          ]}>
            <Ionicons
              name={step.icon}
              size={20}
              color={currentStep >= step.id ? '#fff' : '#666'}
            />
          </View>
          <Text style={[
            styles.stepTitle,
            currentStep >= step.id && styles.stepTitleActive,
          ]}>
            {step.title}
          </Text>
          {index < steps.length - 1 && (
            <View style={[
              styles.stepConnector,
              currentStep > step.id && styles.stepConnectorActive,
            ]} />
          )}
        </View>
      ))}
    </View>
  );

  const renderPersonalInfo = () => (
    <ScrollView style={styles.stepContent}>
      <Text style={styles.stepHeader}>Personal Information</Text>
      <Text style={styles.stepDescription}>
        Please provide your basic personal details.
      </Text>

      <View style={styles.inputGroup}>
        <Text style={styles.inputLabel}>First Name *</Text>
        <TextInput
          style={[styles.input, errors.firstName && styles.inputError]}
          value={formData.personalInfo.firstName}
          onChangeText={(value) => updateFormData('personalInfo', 'firstName', value)}
          placeholder="Enter your first name"
          placeholderTextColor="#999"
        />
        {errors.firstName && <Text style={styles.errorText}>{errors.firstName}</Text>}
      </View>

      <View style={styles.inputGroup}>
        <Text style={styles.inputLabel}>Last Name *</Text>
        <TextInput
          style={[styles.input, errors.lastName && styles.inputError]}
          value={formData.personalInfo.lastName}
          onChangeText={(value) => updateFormData('personalInfo', 'lastName', value)}
          placeholder="Enter your last name"
          placeholderTextColor="#999"
        />
        {errors.lastName && <Text style={styles.errorText}>{errors.lastName}</Text>}
      </View>

      <View style={styles.inputGroup}>
        <Text style={styles.inputLabel}>Email Address *</Text>
        <TextInput
          style={[styles.input, errors.email && styles.inputError]}
          value={formData.personalInfo.email}
          onChangeText={(value) => updateFormData('personalInfo', 'email', value)}
          placeholder="Enter your email"
          placeholderTextColor="#999"
          keyboardType="email-address"
          autoCapitalize="none"
        />
        {errors.email && <Text style={styles.errorText}>{errors.email}</Text>}
      </View>

      <View style={styles.inputGroup}>
        <Text style={styles.inputLabel}>Phone Number *</Text>
        <TextInput
          style={[styles.input, errors.phone && styles.inputError]}
          value={formData.personalInfo.phone}
          onChangeText={(value) => updateFormData('personalInfo', 'phone', value)}
          placeholder="Enter your phone number"
          placeholderTextColor="#999"
          keyboardType="phone-pad"
        />
        {errors.phone && <Text style={styles.errorText}>{errors.phone}</Text>}
      </View>

      <View style={styles.inputGroup}>
        <Text style={styles.inputLabel}>Date of Birth</Text>
        <TextInput
          style={styles.input}
          value={formData.personalInfo.dateOfBirth}
          onChangeText={(value) => updateFormData('personalInfo', 'dateOfBirth', value)}
          placeholder="MM/DD/YYYY"
          placeholderTextColor="#999"
        />
      </View>
    </ScrollView>
  );

  const renderAddressInfo = () => (
    <ScrollView style={styles.stepContent}>
      <Text style={styles.stepHeader}>Address Information</Text>
      <Text style={styles.stepDescription}>
        Please provide your current address details.
      </Text>

      <View style={styles.inputGroup}>
        <Text style={styles.inputLabel}>Street Address *</Text>
        <TextInput
          style={[styles.input, errors.street && styles.inputError]}
          value={formData.addressInfo.street}
          onChangeText={(value) => updateFormData('addressInfo', 'street', value)}
          placeholder="Enter your street address"
          placeholderTextColor="#999"
        />
        {errors.street && <Text style={styles.errorText}>{errors.street}</Text>}
      </View>

      <View style={styles.inputRow}>
        <View style={[styles.inputGroup, styles.inputGroupHalf]}>
          <Text style={styles.inputLabel}>City *</Text>
          <TextInput
            style={[styles.input, errors.city && styles.inputError]}
            value={formData.addressInfo.city}
            onChangeText={(value) => updateFormData('addressInfo', 'city', value)}
            placeholder="City"
            placeholderTextColor="#999"
          />
          {errors.city && <Text style={styles.errorText}>{errors.city}</Text>}
        </View>

        <View style={[styles.inputGroup, styles.inputGroupHalf]}>
          <Text style={styles.inputLabel}>State *</Text>
          <TextInput
            style={[styles.input, errors.state && styles.inputError]}
            value={formData.addressInfo.state}
            onChangeText={(value) => updateFormData('addressInfo', 'state', value)}
            placeholder="State"
            placeholderTextColor="#999"
          />
          {errors.state && <Text style={styles.errorText}>{errors.state}</Text>}
        </View>
      </View>

      <View style={styles.inputRow}>
        <View style={[styles.inputGroup, styles.inputGroupHalf]}>
          <Text style={styles.inputLabel}>ZIP Code *</Text>
          <TextInput
            style={[styles.input, errors.zipCode && styles.inputError]}
            value={formData.addressInfo.zipCode}
            onChangeText={(value) => updateFormData('addressInfo', 'zipCode', value)}
            placeholder="ZIP Code"
            placeholderTextColor="#999"
            keyboardType="numeric"
          />
          {errors.zipCode && <Text style={styles.errorText}>{errors.zipCode}</Text>}
        </View>

        <View style={[styles.inputGroup, styles.inputGroupHalf]}>
          <Text style={styles.inputLabel}>Country</Text>
          <TextInput
            style={styles.input}
            value={formData.addressInfo.country}
            onChangeText={(value) => updateFormData('addressInfo', 'country', value)}
            placeholder="Country"
            placeholderTextColor="#999"
          />
        </View>
      </View>
    </ScrollView>
  );

  const renderPreferences = () => (
    <ScrollView style={styles.stepContent}>
      <Text style={styles.stepHeader}>Preferences</Text>
      <Text style={styles.stepDescription}>
        Customize your experience with these optional settings.
      </Text>

      <View style={styles.preferenceItem}>
        <View style={styles.preferenceContent}>
          <Text style={styles.preferenceTitle}>Newsletter Subscription</Text>
          <Text style={styles.preferenceDescription}>
            Receive updates and news via email
          </Text>
        </View>
        <Switch
          value={formData.preferences.newsletter}
          onValueChange={(value) => updateFormData('preferences', 'newsletter', value)}
          trackColor={{ false: '#e0e0e0', true: '#007AFF' }}
          thumbColor={formData.preferences.newsletter ? '#fff' : '#f4f3f4'}
        />
      </View>

      <View style={styles.preferenceItem}>
        <View style={styles.preferenceContent}>
          <Text style={styles.preferenceTitle}>Push Notifications</Text>
          <Text style={styles.preferenceDescription}>
            Get notified about important updates
          </Text>
        </View>
        <Switch
          value={formData.preferences.notifications}
          onValueChange={(value) => updateFormData('preferences', 'notifications', value)}
          trackColor={{ false: '#e0e0e0', true: '#007AFF' }}
          thumbColor={formData.preferences.notifications ? '#fff' : '#f4f3f4'}
        />
      </View>

      <View style={styles.inputGroup}>
        <Text style={styles.inputLabel}>Theme Preference</Text>
        <View style={styles.radioGroup}>
          {['light', 'dark', 'auto'].map((theme) => (
            <TouchableOpacity
              key={theme}
              style={[
                styles.radioOption,
                formData.preferences.theme === theme && styles.radioOptionSelected,
              ]}
              onPress={() => updateFormData('preferences', 'theme', theme)}
            >
              <View style={styles.radioCircle}>
                {formData.preferences.theme === theme && (
                  <View style={styles.radioCircleInner} />
                )}
              </View>
              <Text style={[
                styles.radioText,
                formData.preferences.theme === theme && styles.radioTextSelected,
              ]}>
                {theme.charAt(0).toUpperCase() + theme.slice(1)}
              </Text>
            </TouchableOpacity>
          ))}
        </View>
      </View>

      <View style={styles.inputGroup}>
        <Text style={styles.inputLabel}>Language</Text>
        <View style={styles.radioGroup}>
          {[
            { value: 'en', label: 'English' },
            { value: 'es', label: 'Spanish' },
            { value: 'fr', label: 'French' },
          ].map((lang) => (
            <TouchableOpacity
              key={lang.value}
              style={[
                styles.radioOption,
                formData.preferences.language === lang.value && styles.radioOptionSelected,
              ]}
              onPress={() => updateFormData('preferences', 'language', lang.value)}
            >
              <View style={styles.radioCircle}>
                {formData.preferences.language === lang.value && (
                  <View style={styles.radioCircleInner} />
                )}
              </View>
              <Text style={[
                styles.radioText,
                formData.preferences.language === lang.value && styles.radioTextSelected,
              ]}>
                {lang.label}
              </Text>
            </TouchableOpacity>
          ))}
        </View>
      </View>
    </ScrollView>
  );

  const renderPaymentInfo = () => (
    <ScrollView style={styles.stepContent}>
      <Text style={styles.stepHeader}>Payment Information</Text>
      <Text style={styles.stepDescription}>
        Enter your payment details securely.
      </Text>

      <View style={styles.inputGroup}>
        <Text style={styles.inputLabel}>Cardholder Name *</Text>
        <TextInput
          style={[styles.input, errors.cardholderName && styles.inputError]}
          value={formData.paymentInfo.cardholderName}
          onChangeText={(value) => updateFormData('paymentInfo', 'cardholderName', value)}
          placeholder="Name on card"
          placeholderTextColor="#999"
        />
        {errors.cardholderName && <Text style={styles.errorText}>{errors.cardholderName}</Text>}
      </View>

      <View style={styles.inputGroup}>
        <Text style={styles.inputLabel}>Card Number *</Text>
        <TextInput
          style={[styles.input, errors.cardNumber && styles.inputError]}
          value={formData.paymentInfo.cardNumber}
          onChangeText={(value) => updateFormData('paymentInfo', 'cardNumber', value)}
          placeholder="1234 5678 9012 3456"
          placeholderTextColor="#999"
          keyboardType="numeric"
        />
        {errors.cardNumber && <Text style={styles.errorText}>{errors.cardNumber}</Text>}
      </View>

      <View style={styles.inputRow}>
        <View style={[styles.inputGroup, styles.inputGroupHalf]}>
          <Text style={styles.inputLabel}>Expiry Date *</Text>
          <TextInput
            style={[styles.input, errors.expiryDate && styles.inputError]}
            value={formData.paymentInfo.expiryDate}
            onChangeText={(value) => updateFormData('paymentInfo', 'expiryDate', value)}
            placeholder="MM/YY"
            placeholderTextColor="#999"
            keyboardType="numeric"
          />
          {errors.expiryDate && <Text style={styles.errorText}>{errors.expiryDate}</Text>}
        </View>

        <View style={[styles.inputGroup, styles.inputGroupHalf]}>
          <Text style={styles.inputLabel}>CVV *</Text>
          <TextInput
            style={[styles.input, errors.cvv && styles.inputError]}
            value={formData.paymentInfo.cvv}
            onChangeText={(value) => updateFormData('paymentInfo', 'cvv', value)}
            placeholder="123"
            placeholderTextColor="#999"
            keyboardType="numeric"
            secureTextEntry
          />
          {errors.cvv && <Text style={styles.errorText}>{errors.cvv}</Text>}
        </View>
      </View>
    </ScrollView>
  );

  const renderReview = () => (
    <ScrollView style={styles.stepContent}>
      <Text style={styles.stepHeader}>Review & Confirm</Text>
      <Text style={styles.stepDescription}>
        Please review your information and accept the terms.
      </Text>

      <View style={styles.reviewSection}>
        <Text style={styles.reviewSectionTitle}>Personal Information</Text>
        <View style={styles.reviewItem}>
          <Text style={styles.reviewLabel}>Name:</Text>
          <Text style={styles.reviewValue}>
            {formData.personalInfo.firstName} {formData.personalInfo.lastName}
          </Text>
        </View>
        <View style={styles.reviewItem}>
          <Text style={styles.reviewLabel}>Email:</Text>
          <Text style={styles.reviewValue}>{formData.personalInfo.email}</Text>
        </View>
        <View style={styles.reviewItem}>
          <Text style={styles.reviewLabel}>Phone:</Text>
          <Text style={styles.reviewValue}>{formData.personalInfo.phone}</Text>
        </View>
      </View>

      <View style={styles.reviewSection}>
        <Text style={styles.reviewSectionTitle}>Address</Text>
        <View style={styles.reviewItem}>
          <Text style={styles.reviewLabel}>Address:</Text>
          <Text style={styles.reviewValue}>{formData.addressInfo.street}</Text>
        </View>
        <View style={styles.reviewItem}>
          <Text style={styles.reviewLabel}>City, State ZIP:</Text>
          <Text style={styles.reviewValue}>
            {formData.addressInfo.city}, {formData.addressInfo.state} {formData.addressInfo.zipCode}
          </Text>
        </View>
      </View>

      <View style={styles.reviewSection}>
        <Text style={styles.reviewSectionTitle}>Preferences</Text>
        <View style={styles.reviewItem}>
          <Text style={styles.reviewLabel}>Newsletter:</Text>
          <Text style={styles.reviewValue}>
            {formData.preferences.newsletter ? 'Yes' : 'No'}
          </Text>
        </View>
        <View style={styles.reviewItem}>
          <Text style={styles.reviewLabel}>Notifications:</Text>
          <Text style={styles.reviewValue}>
            {formData.preferences.notifications ? 'Enabled' : 'Disabled'}
          </Text>
        </View>
        <View style={styles.reviewItem}>
          <Text style={styles.reviewLabel}>Theme:</Text>
          <Text style={styles.reviewValue}>
            {formData.preferences.theme.charAt(0).toUpperCase() + formData.preferences.theme.slice(1)}
          </Text>
        </View>
      </View>

      <View style={styles.checkboxGroup}>
        <TouchableOpacity
          style={styles.checkboxItem}
          onPress={() => updateFormData('review', 'termsAccepted', !formData.review.termsAccepted)}
        >
          <View style={[
            styles.checkbox,
            formData.review.termsAccepted && styles.checkboxChecked,
          ]}>
            {formData.review.termsAccepted && (
              <Ionicons name="checkmark" size={16} color="#fff" />
            )}
          </View>
          <Text style={styles.checkboxText}>
            I accept the Terms and Conditions
          </Text>
        </TouchableOpacity>
        {errors.termsAccepted && <Text style={styles.errorText}>{errors.termsAccepted}</Text>}

        <TouchableOpacity
          style={styles.checkboxItem}
          onPress={() => updateFormData('review', 'privacyAccepted', !formData.review.privacyAccepted)}
        >
          <View style={[
            styles.checkbox,
            formData.review.privacyAccepted && styles.checkboxChecked,
          ]}>
            {formData.review.privacyAccepted && (
              <Ionicons name="checkmark" size={16} color="#fff" />
            )}
          </View>
          <Text style={styles.checkboxText}>
            I accept the Privacy Policy
          </Text>
        </TouchableOpacity>
        {errors.privacyAccepted && <Text style={styles.errorText}>{errors.privacyAccepted}</Text>}
      </View>
    </ScrollView>
  );

  const renderStepContent = () => {
    switch (currentStep) {
      case 1:
        return renderPersonalInfo();
      case 2:
        return renderAddressInfo();
      case 3:
        return renderPreferences();
      case 4:
        return renderPaymentInfo();
      case 5:
        return renderReview();
      default:
        return null;
    }
  };

  const renderNavigation = () => (
    <View style={styles.navigation}>
      <TouchableOpacity
        style={[styles.navButton, currentStep === 1 && styles.navButtonDisabled]}
        onPress={handlePrevious}
        disabled={currentStep === 1}
      >
        <Ionicons name="chevron-back" size={20} color={currentStep === 1 ? '#999' : '#007AFF'} />
        <Text style={[styles.navButtonText, currentStep === 1 && styles.navButtonTextDisabled]}>
          Previous
        </Text>
      </TouchableOpacity>

      <View style={styles.stepIndicator}>
        <Text style={styles.stepText}>
          Step {currentStep} of {totalSteps}
        </Text>
      </View>

      {currentStep < totalSteps ? (
        <TouchableOpacity
          style={styles.navButton}
          onPress={handleNext}
        >
          <Text style={styles.navButtonText}>Next</Text>
          <Ionicons name="chevron-forward" size={20} color="#007AFF" />
        </TouchableOpacity>
      ) : (
        <TouchableOpacity
          style={[styles.navButton, styles.submitButton]}
          onPress={handleSubmit}
          disabled={isSubmitting}
        >
          {isSubmitting ? (
            <Text style={styles.submitButtonText}>Submitting...</Text>
          ) : (
            <>
              <Text style={styles.submitButtonText}>Submit</Text>
              <Ionicons name="checkmark" size={20} color="#fff" />
            </>
          )}
        </TouchableOpacity>
      )}
    </View>
  );

  return (
    <View style={styles.container}>
      {renderStepIndicator()}
      {renderStepContent()}
      {renderNavigation()}
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  stepIndicator: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 20,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  stepContainer: {
    flex: 1,
    alignItems: 'center',
    position: 'relative',
  },
  stepCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#e0e0e0',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  stepCircleActive: {
    backgroundColor: '#007AFF',
  },
  stepCircleCurrent: {
    backgroundColor: '#0056b3',
  },
  stepTitle: {
    fontSize: 12,
    color: '#666',
    textAlign: 'center',
  },
  stepTitleActive: {
    color: '#007AFF',
    fontWeight: '600',
  },
  stepConnector: {
    position: 'absolute',
    top: 20,
    left: '60%',
    right: '-60%',
    height: 2,
    backgroundColor: '#e0e0e0',
    zIndex: -1,
  },
  stepConnectorActive: {
    backgroundColor: '#007AFF',
  },
  stepContent: {
    flex: 1,
    padding: 20,
  },
  stepHeader: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 8,
  },
  stepDescription: {
    fontSize: 16,
    color: '#666',
    marginBottom: 24,
  },
  inputGroup: {
    marginBottom: 20,
  },
  inputGroupHalf: {
    flex: 1,
    marginRight: 10,
  },
  inputRow: {
    flexDirection: 'row',
    marginBottom: 20,
  },
  inputLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 8,
  },
  input: {
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    backgroundColor: '#fff',
  },
  inputError: {
    borderColor: '#F44336',
  },
  errorText: {
    color: '#F44336',
    fontSize: 14,
    marginTop: 4,
  },
  preferenceItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  preferenceContent: {
    flex: 1,
    marginRight: 16,
  },
  preferenceTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 4,
  },
  preferenceDescription: {
    fontSize: 14,
    color: '#666',
  },
  radioGroup: {
    marginTop: 8,
  },
  radioOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
  },
  radioOptionSelected: {
    // Add selected styling if needed
  },
  radioCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#e0e0e0',
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  radioCircleInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#007AFF',
  },
  radioText: {
    fontSize: 16,
    color: '#333',
  },
  radioTextSelected: {
    color: '#007AFF',
    fontWeight: '600',
  },
  reviewSection: {
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 16,
    marginBottom: 16,
  },
  reviewSectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 12,
  },
  reviewItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  reviewLabel: {
    fontSize: 14,
    color: '#666',
    fontWeight: '500',
  },
  reviewValue: {
    fontSize: 14,
    color: '#333',
    flex: 1,
    textAlign: 'right',
  },
  checkboxGroup: {
    marginTop: 20,
  },
  checkboxItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: '#e0e0e0',
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxChecked: {
    backgroundColor: '#007AFF',
    borderColor: '#007AFF',
  },
  checkboxText: {
    fontSize: 16,
    color: '#333',
    flex: 1,
  },
  navigation: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
  },
  navButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#007AFF',
    backgroundColor: '#fff',
  },
  navButtonDisabled: {
    borderColor: '#e0e0e0',
    backgroundColor: '#f5f5f5',
  },
  navButtonText: {
    color: '#007AFF',
    fontSize: 16,
    fontWeight: '600',
    marginHorizontal: 8,
  },
  navButtonTextDisabled: {
    color: '#999',
  },
  submitButton: {
    backgroundColor: '#007AFF',
    borderColor: '#007AFF',
  },
  submitButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    marginHorizontal: 8,
  },
  stepText: {
    fontSize: 14,
    color: '#666',
    fontWeight: '500',
  },
});

export default MultiStepWizard;

// frameworks/web/vue/MultiStepWizard.vue
<template>
  <div class="wizard-container">
    <div class="wizard-header">
      <h1>User Registration Wizard</h1>
      <div class="progress-bar">
        <div 
          class="progress-fill" 
          :style="{ width: `${progressPercentage}%` }"
        ></div>
      </div>
      <div class="progress-text">
        Step {{ currentStep }} of {{ steps.length }}
      </div>
    </div>

    <div class="wizard-steps">
      <div 
        v-for="(step, index) in steps" 
        :key="step.id" 
        :class="`step ${currentStep === step.id ? 'active' : ''} ${currentStep > step.id ? 'completed' : ''}`"
        @click="currentStep = step.id"
      >
        <div class="step-number">
          {{ currentStep > step.id ? '✓' : step.id }}
        </div>
        <div class="step-info">
          <div class="step-title">{{ step.title }}</div>
          <div class="step-description">{{ step.description }}</div>
        </div>
      </div>
    </div>

    <div class="wizard-content">
      <!-- Step 1: Personal Information -->
      <div v-if="currentStep === 1" class="step-content">
        <h3>Personal Information</h3>
        <div class="form-group">
          <input
            type="text"
            placeholder="First Name"
            v-model="formData.personalInfo.firstName"
            :class="{ error: errors.firstName }"
          />
          <span v-if="errors.firstName" class="error-message">{{ errors.firstName }}</span>
        </div>
        
        <div class="form-group">
          <input
            type="text"
            placeholder="Last Name"
            v-model="formData.personalInfo.lastName"
            :class="{ error: errors.lastName }"
          />
          <span v-if="errors.lastName" class="error-message">{{ errors.lastName }}</span>
        </div>
        
        <div class="form-group">
          <input
            type="email"
            placeholder="Email Address"
            v-model="formData.personalInfo.email"
            :class="{ error: errors.email }"
          />
          <span v-if="errors.email" class="error-message">{{ errors.email }}</span>
        </div>
        
        <div class="form-group">
          <input
            type="tel"
            placeholder="Phone Number"
            v-model="formData.personalInfo.phone"
            :class="{ error: errors.phone }"
          />
          <span v-if="errors.phone" class="error-message">{{ errors.phone }}</span>
        </div>
        
        <div class="form-group">
          <input
            type="date"
            v-model="formData.personalInfo.dateOfBirth"
          />
        </div>
      </div>

      <!-- Step 2: Address Information -->
      <div v-if="currentStep === 2" class="step-content">
        <h3>Address Information</h3>
        <div class="form-group">
          <input
            type="text"
            placeholder="Street Address"
            v-model="formData.addressInfo.street"
            :class="{ error: errors.street }"
          />
          <span v-if="errors.street" class="error-message">{{ errors.street }}</span>
        </div>
        
        <div class="form-row">
          <div class="form-group">
            <input
              type="text"
              placeholder="City"
              v-model="formData.addressInfo.city"
              :class="{ error: errors.city }"
            />
            <span v-if="errors.city" class="error-message">{{ errors.city }}</span>
          </div>
          
          <div class="form-group">
            <input
              type="text"
              placeholder="State"
              v-model="formData.addressInfo.state"
              :class="{ error: errors.state }"
            />
            <span v-if="errors.state" class="error-message">{{ errors.state }}</span>
          </div>
        </div>
        
        <div class="form-row">
          <div class="form-group">
            <input
              type="text"
              placeholder="ZIP Code"
              v-model="formData.addressInfo.zipCode"
              :class="{ error: errors.zipCode }"
            />
            <span v-if="errors.zipCode" class="error-message">{{ errors.zipCode }}</span>
          </div>
          
          <div class="form-group">
            <select v-model="formData.addressInfo.country">
              <option value="">Select Country</option>
              <option value="US">United States</option>
              <option value="CA">Canada</option>
              <option value="UK">United Kingdom</option>
              <option value="AU">Australia</option>
            </select>
          </div>
        </div>
      </div>

      <!-- Step 3: Preferences -->
      <div v-if="currentStep === 3" class="step-content">
        <h3>Preferences</h3>
        <div class="form-group">
          <label>
            <input
              type="checkbox"
              v-model="formData.preferences.newsletter"
            />
            Subscribe to newsletter
          </label>
        </div>
        
        <div class="form-group">
          <label>
            <input
              type="checkbox"
              v-model="formData.preferences.notifications"
            />
            Enable push notifications
          </label>
        </div>
        
        <div class="form-group">
          <label>Theme Preference</label>
          <select v-model="formData.preferences.theme">
            <option value="light">Light</option>
            <option value="dark">Dark</option>
            <option value="auto">Auto</option>
          </select>
        </div>
        
        <div class="form-group">
          <label>Language</label>
          <select v-model="formData.preferences.language">
            <option value="en">English</option>
            <option value="es">Spanish</option>
            <option value="fr">French</option>
            <option value="de">German</option>
          </select>
        </div>
      </div>

      <!-- Step 4: Payment Information -->
      <div v-if="currentStep === 4" class="step-content">
        <h3>Payment Information</h3>
        <div class="form-group">
          <input
            type="text"
            placeholder="Card Number"
            v-model="formData.paymentInfo.cardNumber"
            :class="{ error: errors.cardNumber }"
          />
          <span v-if="errors.cardNumber" class="error-message">{{ errors.cardNumber }}</span>
        </div>
        
        <div class="form-row">
          <div class="form-group">
            <input
              type="text"
              placeholder="MM/YY"
              v-model="formData.paymentInfo.expiryDate"
              :class="{ error: errors.expiryDate }"
            />
            <span v-if="errors.expiryDate" class="error-message">{{ errors.expiryDate }}</span>
          </div>
          
          <div class="form-group">
            <input
              type="text"
              placeholder="CVV"
              v-model="formData.paymentInfo.cvv"
              :class="{ error: errors.cvv }"
            />
            <span v-if="errors.cvv" class="error-message">{{ errors.cvv }}</span>
          </div>
        </div>
        
        <div class="form-group">
          <input
            type="text"
            placeholder="Billing Address (if different)"
            v-model="formData.paymentInfo.billingAddress"
          />
        </div>
      </div>

      <!-- Step 5: Review -->
      <div v-if="currentStep === 5" class="step-content">
        <h3>Review Your Information</h3>
        <div class="review-section">
          <h4>Personal Information</h4>
          <p><strong>Name:</strong> {{ formData.personalInfo.firstName }} {{ formData.personalInfo.lastName }}</p>
          <p><strong>Email:</strong> {{ formData.personalInfo.email }}</p>
          <p><strong>Phone:</strong> {{ formData.personalInfo.phone }}</p>
          <p><strong>Date of Birth:</strong> {{ formData.personalInfo.dateOfBirth }}</p>
        </div>
        
        <div class="review-section">
          <h4>Address</h4>
          <p>{{ formData.addressInfo.street }}</p>
          <p>{{ formData.addressInfo.city }}, {{ formData.addressInfo.state }} {{ formData.addressInfo.zipCode }}</p>
          <p>{{ formData.addressInfo.country }}</p>
        </div>
        
        <div class="review-section">
          <h4>Preferences</h4>
          <p><strong>Newsletter:</strong> {{ formData.preferences.newsletter ? 'Yes' : 'No' }}</p>
          <p><strong>Notifications:</strong> {{ formData.preferences.notifications ? 'Yes' : 'No' }}</p>
          <p><strong>Theme:</strong> {{ formData.preferences.theme }}</p>
          <p><strong>Language:</strong> {{ formData.preferences.language }}</p>
        </div>
        
        <div class="review-section">
          <h4>Payment</h4>
          <p><strong>Card:</strong> **** **** **** {{ formData.paymentInfo.cardNumber.slice(-4) }}</p>
          <p><strong>Expires:</strong> {{ formData.paymentInfo.expiryDate }}</p>
        </div>
      </div>
    </div>

    <div class="wizard-navigation">
      <button 
        @click="handlePrevious"
        :disabled="currentStep === 1"
        class="btn-secondary"
      >
        Previous
      </button>
      
      <button 
        v-if="currentStep < steps.length"
        @click="handleNext"
        class="btn-primary"
      >
        Next
      </button>
      <button 
        v-else
        @click="handleSubmit"
        :disabled="isSubmitting"
        class="btn-primary"
      >
        {{ isSubmitting ? 'Submitting...' : 'Complete Registration' }}
      </button>
    </div>
  </div>
</template>

<script>
export default {
  name: 'MultiStepWizard',
  data() {
    return {
      currentStep: 1,
      formData: {
        personalInfo: {
          firstName: '',
          lastName: '',
          email: '',
          phone: '',
          dateOfBirth: ''
        },
        addressInfo: {
          street: '',
          city: '',
          state: '',
          zipCode: '',
          country: ''
        },
        preferences: {
          newsletter: false,
          notifications: false,
          theme: 'light',
          language: 'en'
        },
        paymentInfo: {
          cardNumber: '',
          expiryDate: '',
          cvv: '',
          billingAddress: ''
        }
      },
      errors: {},
      isSubmitting: false,
      steps: [
        { id: 1, title: 'Personal Information', description: 'Basic details about yourself' },
        { id: 2, title: 'Address Information', description: 'Where you live' },
        { id: 3, title: 'Preferences', description: 'Your preferences and settings' },
        { id: 4, title: 'Payment Information', description: 'Billing and payment details' },
        { id: 5, title: 'Review & Submit', description: 'Review your information' }
      ]
    }
  },
  computed: {
    progressPercentage() {
      return (this.currentStep / this.steps.length) * 100;
    }
  },
  methods: {
    validateStep(step) {
      this.errors = {};

      switch (step) {
        case 1:
          if (!this.formData.personalInfo.firstName) this.errors.firstName = 'First name is required';
          if (!this.formData.personalInfo.lastName) this.errors.lastName = 'Last name is required';
          if (!this.formData.personalInfo.email) this.errors.email = 'Email is required';
          else if (!/\S+@\S+\.\S+/.test(this.formData.personalInfo.email)) {
            this.errors.email = 'Email is invalid';
          }
          if (!this.formData.personalInfo.phone) this.errors.phone = 'Phone number is required';
          break;
        
        case 2:
          if (!this.formData.addressInfo.street) this.errors.street = 'Street address is required';
          if (!this.formData.addressInfo.city) this.errors.city = 'City is required';
          if (!this.formData.addressInfo.state) this.errors.state = 'State is required';
          if (!this.formData.addressInfo.zipCode) this.errors.zipCode = 'ZIP code is required';
          break;
        
        case 3:
          // Preferences are optional, no validation needed
          break;
        
        case 4:
          if (!this.formData.paymentInfo.cardNumber) this.errors.cardNumber = 'Card number is required';
          if (!this.formData.paymentInfo.expiryDate) this.errors.expiryDate = 'Expiry date is required';
          if (!this.formData.paymentInfo.cvv) this.errors.cvv = 'CVV is required';
          break;
        
        default:
          break;
      }

      return Object.keys(this.errors).length === 0;
    },
    handleNext() {
      if (this.validateStep(this.currentStep)) {
        this.currentStep = Math.min(this.currentStep + 1, this.steps.length);
      }
    },
    handlePrevious() {
      this.currentStep = Math.max(this.currentStep - 1, 1);
    },
    async handleSubmit() {
      if (this.validateStep(this.currentStep)) {
        this.isSubmitting = true;
        
        // Simulate API call
        setTimeout(() => {
          console.log('Form submitted:', this.formData);
          this.isSubmitting = false;
          alert('Registration completed successfully!');
        }, 2000);
      }
    }
  }
}
</script>

<style scoped>
.wizard-container {
  max-width: 800px;
  margin: 0 auto;
  padding: 20px;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}

.wizard-header {
  text-align: center;
  margin-bottom: 30px;
}

.wizard-header h1 {
  margin: 0 0 20px 0;
  color: #333;
  font-size: 28px;
}

.progress-bar {
  width: 100%;
  height: 8px;
  background: #e0e0e0;
  border-radius: 4px;
  overflow: hidden;
  margin-bottom: 10px;
}

.progress-fill {
  height: 100%;
  background: linear-gradient(90deg, #4caf50, #8bc34a);
  transition: width 0.3s ease;
}

.progress-text {
  color: #666;
  font-size: 14px;
  font-weight: 500;
}

.wizard-steps {
  display: flex;
  justify-content: space-between;
  margin-bottom: 40px;
  position: relative;
}

.wizard-steps::before {
  content: '';
  position: absolute;
  top: 20px;
  left: 40px;
  right: 40px;
  height: 2px;
  background: #e0e0e0;
  z-index: 1;
}

.step {
  display: flex;
  flex-direction: column;
  align-items: center;
  cursor: pointer;
  position: relative;
  z-index: 2;
  flex: 1;
}

.step-number {
  width: 40px;
  height: 40px;
  border-radius: 50%;
  background: #e0e0e0;
  color: #666;
  display: flex;
  align-items: center;
  justify-content: center;
  font-weight: bold;
  font-size: 16px;
  margin-bottom: 8px;
  transition: all 0.3s ease;
}

.step.active .step-number {
  background: #4caf50;
  color: white;
  transform: scale(1.1);
}

.step.completed .step-number {
  background: #8bc34a;
  color: white;
}

.step-info {
  text-align: center;
  max-width: 120px;
}

.step-title {
  font-weight: 600;
  font-size: 12px;
  color: #333;
  margin-bottom: 2px;
}

.step-description {
  font-size: 10px;
  color: #666;
  line-height: 1.3;
}

.step.active .step-title {
  color: #4caf50;
}

.step.completed .step-title {
  color: #8bc34a;
}

.wizard-content {
  background: white;
  border: 1px solid #e0e0e0;
  border-radius: 8px;
  padding: 30px;
  margin-bottom: 30px;
  min-height: 400px;
}

.step-content h3 {
  margin: 0 0 20px 0;
  color: #333;
  font-size: 20px;
  border-bottom: 2px solid #4caf50;
  padding-bottom: 10px;
}

.form-group {
  margin-bottom: 20px;
}

.form-row {
  display: flex;
  gap: 15px;
}

.form-row .form-group {
  flex: 1;
}

.form-group input,
.form-group select {
  width: 100%;
  padding: 12px 15px;
  border: 2px solid #e0e0e0;
  border-radius: 6px;
  font-size: 14px;
  transition: border-color 0.3s ease;
  box-sizing: border-box;
}

.form-group input:focus,
.form-group select:focus {
  outline: none;
  border-color: #4caf50;
}

.form-group input.error {
  border-color: #f44336;
}

.error-message {
  display: block;
  color: #f44336;
  font-size: 12px;
  margin-top: 5px;
  font-weight: 500;
}

.form-group label {
  display: flex;
  align-items: center;
  gap: 8px;
  cursor: pointer;
  font-size: 14px;
  color: #333;
}

.form-group label input[type="checkbox"] {
  width: auto;
  margin: 0;
}

.review-section {
  margin-bottom: 25px;
  padding: 15px;
  background: #f8f9fa;
  border-radius: 6px;
  border-left: 4px solid #4caf50;
}

.review-section h4 {
  margin: 0 0 10px 0;
  color: #333;
  font-size: 16px;
}

.review-section p {
  margin: 5px 0;
  color: #666;
  font-size: 14px;
}

.wizard-navigation {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.btn-primary,
.btn-secondary {
  padding: 12px 24px;
  border: none;
  border-radius: 6px;
  font-size: 14px;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.3s ease;
  min-width: 120px;
}

.btn-primary {
  background: #4caf50;
  color: white;
}

.btn-primary:hover:not(:disabled) {
  background: #45a049;
  transform: translateY(-1px);
}

.btn-primary:disabled {
  background: #ccc;
  cursor: not-allowed;
  transform: none;
}

.btn-secondary {
  background: #f5f5f5;
  color: #333;
  border: 2px solid #e0e0e0;
}

.btn-secondary:hover:not(:disabled) {
  background: #e0e0e0;
  transform: translateY(-1px);
}

.btn-secondary:disabled {
  background: #f5f5f5;
  color: #ccc;
  cursor: not-allowed;
  transform: none;
}

@media (max-width: 768px) {
  .wizard-container {
    padding: 15px;
  }
  
  .wizard-steps {
    flex-direction: column;
    gap: 20px;
  }
  
  .wizard-steps::before {
    display: none;
  }
  
  .step {
    flex-direction: row;
    text-align: left;
  }
  
  .step-number {
    margin-right: 15px;
    margin-bottom: 0;
  }
  
  .step-info {
    text-align: left;
    max-width: none;
  }
  
  .step-title {
    font-size: 14px;
  }
  
  .step-description {
    font-size: 12px;
  }
  
  .wizard-content {
    padding: 20px;
  }
  
  .form-row {
    flex-direction: column;
    gap: 0;
  }
  
  .wizard-navigation {
    flex-direction: column;
    gap: 15px;
  }
  
  .btn-primary,
  .btn-secondary {
    width: 100%;
  }
}
</style>
