// scenarios/basic/web/sveltekit/MissingImageAltText.svelte
<script>
  let products = [
    {
      id: 1,
      name: "Wireless Headphones",
      price: 199.99,
      image: "/api/placeholder/300/300",
      description: "High-quality wireless headphones with noise cancellation"
    },
    {
      id: 2,
      name: "Smart Watch",
      price: 299.99,
      image: "/api/placeholder/300/300",
      description: "Advanced fitness tracking smartwatch with heart rate monitoring"
    },
    {
      id: 3,
      name: "Bluetooth Speaker",
      price: 149.99,
      image: "/api/placeholder/300/300",
      description: "Portable Bluetooth speaker with 360-degree sound"
    },
    {
      id: 4,
      name: "Gaming Mouse",
      price: 79.99,
      image: "/api/placeholder/300/300",
      description: "Precision gaming mouse with customizable RGB lighting"
    },
    {
      id: 5,
      name: "Mechanical Keyboard",
      price: 129.99,
      image: "/api/placeholder/300/300",
      description: "Mechanical keyboard with Cherry MX switches"
    },
    {
      id: 6,
      name: "USB-C Hub",
      price: 59.99,
      image: "/api/placeholder/300/300",
      description: "Multi-port USB-C hub with HDMI and USB 3.0"
    }
  ];
  
  let selectedCategory = "all";
  let sortBy = "name";
  let viewMode = "grid";
  
  function filterProducts() {
    return products.filter(product => {
      if (selectedCategory === "all") return true;
      return product.category === selectedCategory;
    });
  }
  
  function sortProducts(products) {
    return [...products].sort((a, b) => {
      switch(sortBy) {
        case "price":
          return a.price - b.price;
        case "name":
        default:
          return a.name.localeCompare(b.name);
      }
    });
  }
  
  $: filteredProducts = sortProducts(filterProducts());
</script>

<div class="product-catalog">
  <header class="catalog-header">
    <h1 class="catalog-title">Electronics Store</h1>
    <p class="catalog-subtitle">Discover the latest in technology and gadgets</p>
  </header>
  
  <div class="catalog-controls">
    <div class="filter-section">
      <label class="filter-label">Category:</label>
      <select bind:value={selectedCategory} class="filter-select">
        <option value="all">All Products</option>
        <option value="audio">Audio</option>
        <option value="wearables">Wearables</option>
        <option value="gaming">Gaming</option>
        <option value="accessories">Accessories</option>
      </select>
    </div>
    
    <div class="sort-section">
      <label class="sort-label">Sort by:</label>
      <select bind:value={sortBy} class="sort-select">
        <option value="name">Name</option>
        <option value="price">Price</option>
      </select>
    </div>
    
    <div class="view-section">
      <button 
        class="view-btn" 
        class:active={viewMode === 'grid'}
        on:click={() => viewMode = 'grid'}
      >
        Grid
      </button>
      <button 
        class="view-btn" 
        class:active={viewMode === 'list'}
        on:click={() => viewMode = 'list'}
      >
        List
      </button>
    </div>
  </div>
  
  <div class="products-section">
    <div class="products-header">
      <h2 class="section-title">Featured Products</h2>
      <div class="results-count">{filteredProducts.length} products found</div>
    </div>
    
    {#if viewMode === 'grid'}
      <div class="products-grid">
        {#each filteredProducts as product (product.id)}
          <div class="product-card">
            <div class="product-image-container">
              <img 
                src={product.image} 
                class="product-image"
              />
              <div class="product-badge">New</div>
              <div class="product-actions">
                <button class="action-btn wishlist">♡</button>
                <button class="action-btn quick-view">👁</button>
                <button class="action-btn compare">⚖</button>
              </div>
            </div>
            
            <div class="product-info">
              <h3 class="product-name">{product.name}</h3>
              <p class="product-description">{product.description}</p>
              
              <div class="product-rating">
                <div class="stars">★★★★☆</div>
                <span class="rating-count">(24 reviews)</span>
              </div>
              
              <div class="product-price">
                <span class="current-price">${product.price}</span>
                <span class="original-price">$249.99</span>
                <span class="discount">20% OFF</span>
              </div>
              
              <div class="product-availability">
                <span class="availability-status">In Stock</span>
                <span class="stock-count">12 available</span>
              </div>
              
              <div class="product-options">
                <div class="color-options">
                  <span class="option-label">Color:</span>
                  <div class="color-swatches">
                    <div class="color-swatch black"></div>
                    <div class="color-swatch white"></div>
                    <div class="color-swatch blue"></div>
                  </div>
                </div>
                
                <div class="size-options">
                  <span class="option-label">Size:</span>
                  <select class="size-select">
                    <option value="s">S</option>
                    <option value="m">M</option>
                    <option value="l">L</option>
                    <option value="xl">XL</option>
                  </select>
                </div>
              </div>
              
              <div class="product-actions-bottom">
                <button class="add-to-cart-btn">Add to Cart</button>
                <button class="buy-now-btn">Buy Now</button>
              </div>
            </div>
          </div>
        {/each}
      </div>
    {:else}
      <div class="products-list">
        {#each filteredProducts as product (product.id)}
          <div class="product-list-item">
            <div class="list-image-container">
              <img 
                src={product.image} 
                class="list-image"
              />
            </div>
            
            <div class="list-product-info">
              <h3 class="list-product-name">{product.name}</h3>
              <p class="list-product-description">{product.description}</p>
              
              <div class="list-product-details">
                <div class="list-rating">
                  <span class="list-stars">★★★★☆</span>
                  <span class="list-rating-count">(24 reviews)</span>
                </div>
                
                <div class="list-price">
                  <span class="list-current-price">${product.price}</span>
                  <span class="list-original-price">$249.99</span>
                </div>
                
                <div class="list-availability">
                  <span class="list-stock">In Stock (12 available)</span>
                </div>
              </div>
            </div>
            
            <div class="list-actions">
              <button class="list-action-btn wishlist">♡</button>
              <button class="list-action-btn compare">⚖</button>
              <button class="list-add-to-cart">Add to Cart</button>
            </div>
          </div>
        {/each}
      </div>
    {/if}
  </div>
  
  <div class="pagination">
    <button class="page-btn prev">Previous</button>
    <button class="page-btn active">1</button>
    <button class="page-btn">2</button>
    <button class="page-btn">3</button>
    <button class="page-btn next">Next</button>
  </div>
</div>

<style>
  .product-catalog {
    max-width: 1200px;
    margin: 0 auto;
    padding: 30px 20px;
    font-family: Arial, sans-serif;
  }
  
  .catalog-header {
    text-align: center;
    margin-bottom: 40px;
  }
  
  .catalog-title {
    margin: 0 0 10px 0;
    font-size: 32px;
    color: #333;
  }
  
  .catalog-subtitle {
    margin: 0;
    font-size: 16px;
    color: #666;
  }
  
  .catalog-controls {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 30px;
    padding: 20px;
    background: #f8f9fa;
    border-radius: 8px;
  }
  
  .filter-section,
  .sort-section {
    display: flex;
    align-items: center;
    gap: 10px;
  }
  
  .filter-label,
  .sort-label {
    font-weight: bold;
    color: #333;
  }
  
  .filter-select,
  .sort-select {
    padding: 8px 12px;
    border: 1px solid #ddd;
    border-radius: 4px;
    background: white;
    cursor: pointer;
  }
  
  .view-section {
    display: flex;
    gap: 5px;
  }
  
  .view-btn {
    padding: 8px 16px;
    border: 1px solid #ddd;
    background: white;
    color: #333;
    cursor: pointer;
    transition: all 0.2s ease;
  }
  
  .view-btn.active {
    background: #007bff;
    color: white;
    border-color: #007bff;
  }
  
  .view-btn:hover:not(.active) {
    background: #f8f9fa;
    border-color: #007bff;
    color: #007bff;
  }
  
  .products-section {
    margin-bottom: 40px;
  }
  
  .products-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 30px;
  }
  
  .section-title {
    margin: 0;
    font-size: 24px;
    color: #333;
  }
  
  .results-count {
    color: #666;
    font-size: 14px;
  }
  
  .products-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
    gap: 30px;
  }
  
  .product-card {
    background: white;
    border-radius: 12px;
    box-shadow: 0 4px 20px rgba(0,0,0,0.1);
    overflow: hidden;
    transition: transform 0.2s ease;
  }
  
  .product-card:hover {
    transform: translateY(-4px);
  }
  
  .product-image-container {
    position: relative;
    height: 250px;
    overflow: hidden;
  }
  
  .product-image {
    width: 100%;
    height: 100%;
    object-fit: cover;
  }
  
  .product-badge {
    position: absolute;
    top: 15px;
    left: 15px;
    background: #28a745;
    color: white;
    padding: 6px 12px;
    border-radius: 20px;
    font-size: 12px;
    font-weight: bold;
  }
  
  .product-actions {
    position: absolute;
    top: 15px;
    right: 15px;
    display: flex;
    flex-direction: column;
    gap: 8px;
    opacity: 0;
    transition: opacity 0.2s ease;
  }
  
  .product-card:hover .product-actions {
    opacity: 1;
  }
  
  .action-btn {
    width: 35px;
    height: 35px;
    border: none;
    border-radius: 50%;
    background: rgba(255,255,255,0.9);
    color: #333;
    cursor: pointer;
    font-size: 16px;
    transition: all 0.2s ease;
  }
  
  .action-btn:hover {
    background: #007bff;
    color: white;
  }
  
  .product-info {
    padding: 25px;
  }
  
  .product-name {
    margin: 0 0 10px 0;
    font-size: 18px;
    color: #333;
    font-weight: bold;
  }
  
  .product-description {
    margin: 0 0 15px 0;
    color: #666;
    line-height: 1.5;
  }
  
  .product-rating {
    display: flex;
    align-items: center;
    gap: 10px;
    margin-bottom: 15px;
  }
  
  .stars {
    color: #ffc107;
    font-size: 16px;
  }
  
  .rating-count {
    color: #666;
    font-size: 12px;
  }
  
  .product-price {
    display: flex;
    align-items: center;
    gap: 10px;
    margin-bottom: 15px;
  }
  
  .current-price {
    font-size: 24px;
    font-weight: bold;
    color: #007bff;
  }
  
  .original-price {
    font-size: 16px;
    color: #999;
    text-decoration: line-through;
  }
  
  .discount {
    background: #dc3545;
    color: white;
    padding: 4px 8px;
    border-radius: 4px;
    font-size: 12px;
    font-weight: bold;
  }
  
  .product-availability {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 20px;
  }
  
  .availability-status {
    color: #28a745;
    font-weight: bold;
  }
  
  .stock-count {
    color: #666;
    font-size: 12px;
  }
  
  .product-options {
    margin-bottom: 20px;
  }
  
  .color-options,
  .size-options {
    display: flex;
    align-items: center;
    gap: 10px;
    margin-bottom: 10px;
  }
  
  .option-label {
    font-weight: bold;
    color: #333;
    font-size: 14px;
  }
  
  .color-swatches {
    display: flex;
    gap: 8px;
  }
  
  .color-swatch {
    width: 20px;
    height: 20px;
    border-radius: 50%;
    border: 2px solid #ddd;
    cursor: pointer;
  }
  
  .color-swatch.black {
    background: #333;
  }
  
  .color-swatch.white {
    background: #fff;
  }
  
  .color-swatch.blue {
    background: #007bff;
  }
  
  .size-select {
    padding: 4px 8px;
    border: 1px solid #ddd;
    border-radius: 4px;
    background: white;
  }
  
  .product-actions-bottom {
    display: flex;
    gap: 10px;
  }
  
  .add-to-cart-btn,
  .buy-now-btn {
    flex: 1;
    padding: 12px;
    border: none;
    border-radius: 6px;
    font-weight: bold;
    cursor: pointer;
    transition: all 0.2s ease;
  }
  
  .add-to-cart-btn {
    background: #f8f9fa;
    color: #333;
    border: 1px solid #ddd;
  }
  
  .add-to-cart-btn:hover {
    background: #e9ecef;
  }
  
  .buy-now-btn {
    background: #007bff;
    color: white;
  }
  
  .buy-now-btn:hover {
    background: #0056b3;
  }
  
  .products-list {
    display: flex;
    flex-direction: column;
    gap: 20px;
  }
  
  .product-list-item {
    display: flex;
    background: white;
    border-radius: 12px;
    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
    overflow: hidden;
    transition: transform 0.2s ease;
  }
  
  .product-list-item:hover {
    transform: translateY(-2px);
  }
  
  .list-image-container {
    width: 200px;
    height: 150px;
    overflow: hidden;
  }
  
  .list-image {
    width: 100%;
    height: 100%;
    object-fit: cover;
  }
  
  .list-product-info {
    flex: 1;
    padding: 20px;
  }
  
  .list-product-name {
    margin: 0 0 10px 0;
    font-size: 20px;
    color: #333;
    font-weight: bold;
  }
  
  .list-product-description {
    margin: 0 0 15px 0;
    color: #666;
    line-height: 1.5;
  }
  
  .list-product-details {
    display: flex;
    gap: 30px;
  }
  
  .list-rating {
    display: flex;
    align-items: center;
    gap: 8px;
  }
  
  .list-stars {
    color: #ffc107;
    font-size: 16px;
  }
  
  .list-rating-count {
    color: #666;
    font-size: 12px;
  }
  
  .list-price {
    display: flex;
    align-items: center;
    gap: 10px;
  }
  
  .list-current-price {
    font-size: 20px;
    font-weight: bold;
    color: #007bff;
  }
  
  .list-original-price {
    font-size: 14px;
    color: #999;
    text-decoration: line-through;
  }
  
  .list-availability {
    display: flex;
    align-items: center;
  }
  
  .list-stock {
    color: #28a745;
    font-weight: bold;
  }
  
  .list-actions {
    display: flex;
    flex-direction: column;
    gap: 10px;
    padding: 20px;
    justify-content: center;
  }
  
  .list-action-btn {
    width: 40px;
    height: 40px;
    border: 1px solid #ddd;
    background: white;
    color: #333;
    border-radius: 50%;
    cursor: pointer;
    font-size: 16px;
    transition: all 0.2s ease;
  }
  
  .list-action-btn:hover {
    background: #f8f9fa;
    border-color: #007bff;
    color: #007bff;
  }
  
  .list-add-to-cart {
    padding: 10px 20px;
    background: #007bff;
    color: white;
    border: none;
    border-radius: 6px;
    font-weight: bold;
    cursor: pointer;
    transition: all 0.2s ease;
  }
  
  .list-add-to-cart:hover {
    background: #0056b3;
  }
  
  .pagination {
    display: flex;
    justify-content: center;
    gap: 10px;
  }
  
  .page-btn {
    padding: 10px 15px;
    border: 1px solid #ddd;
    background: white;
    color: #333;
    cursor: pointer;
    border-radius: 4px;
    transition: all 0.2s ease;
  }
  
  .page-btn:hover {
    background: #f8f9fa;
    border-color: #007bff;
    color: #007bff;
  }
  
  .page-btn.active {
    background: #007bff;
    color: white;
    border-color: #007bff;
  }
  
  @media (max-width: 768px) {
    .catalog-controls {
      flex-direction: column;
      gap: 15px;
      align-items: stretch;
    }
    
    .filter-section,
    .sort-section {
      justify-content: space-between;
    }
    
    .products-grid {
      grid-template-columns: 1fr;
    }
    
    .product-list-item {
      flex-direction: column;
    }
    
    .list-image-container {
      width: 100%;
      height: 200px;
    }
    
    .list-product-details {
      flex-direction: column;
      gap: 15px;
    }
    
    .list-actions {
      flex-direction: row;
      justify-content: space-between;
    }
  }
</style>

// scenarios/basic/web/nextjs/MissingImageAltText.jsx
import { useState } from 'react';

export default function MissingImageAltText() {
  const [selectedCategory, setSelectedCategory] = useState('all');
  const [searchTerm, setSearchTerm] = useState('');
  const [sortBy, setSortBy] = useState('popular');
  const [viewMode, setViewMode] = useState('grid');

  const categories = [
    { id: 'all', name: 'All Products' },
    { id: 'electronics', name: 'Electronics' },
    { id: 'clothing', name: 'Clothing' },
    { id: 'home', name: 'Home & Garden' },
    { id: 'sports', name: 'Sports' }
  ];

  const products = [
    {
      id: 1,
      name: 'Wireless Headphones',
      price: 99.99,
      category: 'electronics',
      image: 'headphones.jpg',
      rating: 4.5,
      reviews: 128,
      inStock: true
    },
    {
      id: 2,
      name: 'Cotton T-Shirt',
      price: 24.99,
      category: 'clothing',
      image: 'tshirt.jpg',
      rating: 4.2,
      reviews: 89,
      inStock: true
    },
    {
      id: 3,
      name: 'Coffee Maker',
      price: 149.99,
      category: 'home',
      image: 'coffeemaker.jpg',
      rating: 4.7,
      reviews: 203,
      inStock: false
    },
    {
      id: 4,
      name: 'Running Shoes',
      price: 129.99,
      category: 'sports',
      image: 'shoes.jpg',
      rating: 4.4,
      reviews: 156,
      inStock: true
    },
    {
      id: 5,
      name: 'Smartphone Case',
      price: 19.99,
      category: 'electronics',
      image: 'phonecase.jpg',
      rating: 4.1,
      reviews: 67,
      inStock: true
    },
    {
      id: 6,
      name: 'Garden Tools Set',
      price: 79.99,
      category: 'home',
      image: 'gardentools.jpg',
      rating: 4.6,
      reviews: 94,
      inStock: true
    }
  ];

  const filteredProducts = products.filter(product => {
    const matchesCategory = selectedCategory === 'all' || product.category === selectedCategory;
    const matchesSearch = product.name.toLowerCase().includes(searchTerm.toLowerCase());
    return matchesCategory && matchesSearch;
  });

  const sortedProducts = [...filteredProducts].sort((a, b) => {
    switch(sortBy) {
      case 'price-low':
        return a.price - b.price;
      case 'price-high':
        return b.price - a.price;
      case 'rating':
        return b.rating - a.rating;
      case 'name':
      default:
        return a.name.localeCompare(b.name);
    }
  });

  const addToCart = (product) => {
    alert(`Added ${product.name} to cart!`);
  };

  const toggleWishlist = (product) => {
    alert(`${product.name} added to wishlist!`);
  };

  return (
    <div className="product-catalog">
      <header className="catalog-header">
        <h1>Product Catalog</h1>
        <p>Discover amazing products at great prices</p>
      </header>

      <div className="catalog-controls">
        <div className="search-section">
          <input 
            type="text" 
            placeholder="Search products..." 
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="search-input"
          />
        </div>

        <div className="filter-section">
          <select 
            value={selectedCategory} 
            onChange={(e) => setSelectedCategory(e.target.value)}
            className="category-filter"
          >
            {categories.map(category => (
              <option key={category.id} value={category.id}>
                {category.name}
              </option>
            ))}
          </select>

          <select 
            value={sortBy} 
            onChange={(e) => setSortBy(e.target.value)}
            className="sort-filter"
          >
            <option value="name">Sort by Name</option>
            <option value="price-low">Price: Low to High</option>
            <option value="price-high">Price: High to Low</option>
            <option value="rating">Highest Rated</option>
          </select>

          <div className="view-toggle">
            <button 
              className={`view-btn ${viewMode === 'grid' ? 'active' : ''}`}
              onClick={() => setViewMode('grid')}
            >
              Grid
            </button>
            <button 
              className={`view-btn ${viewMode === 'list' ? 'active' : ''}`}
              onClick={() => setViewMode('list')}
            >
              List
            </button>
          </div>
        </div>
      </div>

      <div className="results-info">
        <p>Showing {sortedProducts.length} products</p>
      </div>

      <div className={`products-container ${viewMode}`}>
        {sortedProducts.map(product => (
          <div key={product.id} className="product-card">
            <div className="product-image-container">
              <img 
                src={`/images/${product.image}`}
                className="product-image"
              />
              {!product.inStock && (
                <div className="out-of-stock-badge">Out of Stock</div>
              )}
              <button 
                className="wishlist-btn" 
                onClick={() => toggleWishlist(product)}
                title="Add to Wishlist"
              >
                ♥
              </button>
            </div>

            <div className="product-info">
              <h3 className="product-name">{product.name}</h3>
              
              <div className="product-rating">
                <div className="stars">
                  {Array(5).fill(0).map((_, i) => (
                    <span 
                      key={i} 
                      className={`star ${i < Math.floor(product.rating) ? 'filled' : ''}`}
                    >
                      ★
                    </span>
                  ))}
                </div>
                <span className="rating-text">{product.rating} ({product.reviews} reviews)</span>
              </div>

              <div className="product-price">
                <span className="current-price">${product.price}</span>
                {product.price > 50 && (
                  <span className="original-price">${(product.price * 1.2).toFixed(2)}</span>
                )}
              </div>

              <div className="product-actions">
                <button 
                  className="add-to-cart-btn" 
                  onClick={() => addToCart(product)}
                  disabled={!product.inStock}
                >
                  {product.inStock ? 'Add to Cart' : 'Out of Stock'}
                </button>
                <button className="quick-view-btn">Quick View</button>
              </div>
            </div>
          </div>
        ))}
      </div>

      {sortedProducts.length === 0 && (
        <div className="no-results">
          <h3>No products found</h3>
          <p>Try adjusting your search or filter criteria</p>
        </div>
      )}

      <style jsx>{`
        .product-catalog {
          max-width: 1200px;
          margin: 50px auto;
          padding: 20px;
          font-family: Arial, sans-serif;
        }

        .catalog-header {
          text-align: center;
          margin-bottom: 30px;
        }

        .catalog-header h1 {
          margin: 0 0 10px 0;
          font-size: 32px;
          color: #333;
        }

        .catalog-header p {
          margin: 0;
          color: #666;
          font-size: 16px;
        }

        .catalog-controls {
          background: #f8f9fa;
          padding: 20px;
          border-radius: 8px;
          margin-bottom: 20px;
          display: flex;
          flex-direction: column;
          gap: 15px;
        }

        .search-section {
          display: flex;
          justify-content: center;
        }

        .search-input {
          width: 100%;
          max-width: 400px;
          padding: 12px 16px;
          border: 1px solid #ddd;
          border-radius: 6px;
          font-size: 16px;
        }

        .filter-section {
          display: flex;
          gap: 15px;
          align-items: center;
          flex-wrap: wrap;
          justify-content: center;
        }

        .category-filter,
        .sort-filter {
          padding: 8px 12px;
          border: 1px solid #ddd;
          border-radius: 4px;
          background: white;
        }

        .view-toggle {
          display: flex;
          border: 1px solid #ddd;
          border-radius: 4px;
          overflow: hidden;
        }

        .view-btn {
          padding: 8px 16px;
          border: none;
          background: white;
          cursor: pointer;
          transition: background-color 0.2s ease;
        }

        .view-btn.active {
          background: #007bff;
          color: white;
        }

        .results-info {
          margin-bottom: 20px;
          color: #666;
        }

        .products-container.grid {
          display: grid;
          grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
          gap: 20px;
        }

        .products-container.list {
          display: flex;
          flex-direction: column;
          gap: 15px;
        }

        .products-container.list .product-card {
          display: flex;
          flex-direction: row;
          align-items: center;
        }

        .products-container.list .product-image-container {
          width: 120px;
          height: 120px;
          flex-shrink: 0;
        }

        .products-container.list .product-image {
          width: 100%;
          height: 100%;
          object-fit: cover;
        }

        .product-card {
          background: white;
          border-radius: 8px;
          box-shadow: 0 2px 8px rgba(0,0,0,0.1);
          overflow: hidden;
          transition: transform 0.2s ease, box-shadow 0.2s ease;
        }

        .product-card:hover {
          transform: translateY(-2px);
          box-shadow: 0 4px 16px rgba(0,0,0,0.15);
        }

        .product-image-container {
          position: relative;
          height: 200px;
          overflow: hidden;
        }

        .product-image {
          width: 100%;
          height: 100%;
          object-fit: cover;
        }

        .out-of-stock-badge {
          position: absolute;
          top: 10px;
          right: 10px;
          background: #dc3545;
          color: white;
          padding: 4px 8px;
          border-radius: 4px;
          font-size: 12px;
          font-weight: bold;
        }

        .wishlist-btn {
          position: absolute;
          top: 10px;
          left: 10px;
          background: rgba(255,255,255,0.9);
          border: none;
          border-radius: 50%;
          width: 32px;
          height: 32px;
          cursor: pointer;
          font-size: 16px;
          display: flex;
          align-items: center;
          justify-content: center;
        }

        .product-info {
          padding: 15px;
        }

        .product-name {
          margin: 0 0 10px 0;
          font-size: 16px;
          color: #333;
          line-height: 1.4;
        }

        .product-rating {
          display: flex;
          align-items: center;
          gap: 8px;
          margin-bottom: 10px;
        }

        .stars {
          display: flex;
          gap: 2px;
        }

        .star {
          color: #ddd;
          font-size: 14px;
        }

        .star.filled {
          color: #ffc107;
        }

        .rating-text {
          font-size: 12px;
          color: #666;
        }

        .product-price {
          margin-bottom: 15px;
        }

        .current-price {
          font-size: 18px;
          font-weight: bold;
          color: #007bff;
        }

        .original-price {
          font-size: 14px;
          color: #999;
          text-decoration: line-through;
          margin-left: 8px;
        }

        .product-actions {
          display: flex;
          gap: 8px;
        }

        .add-to-cart-btn {
          flex: 1;
          background: #007bff;
          color: white;
          border: none;
          padding: 10px;
          border-radius: 4px;
          cursor: pointer;
          font-weight: bold;
        }

        .add-to-cart-btn:disabled {
          background: #6c757d;
          cursor: not-allowed;
        }

        .quick-view-btn {
          background: #6c757d;
          color: white;
          border: none;
          padding: 10px 15px;
          border-radius: 4px;
          cursor: pointer;
        }

        .no-results {
          text-align: center;
          padding: 40px;
          color: #666;
        }

        .no-results h3 {
          margin: 0 0 10px 0;
          font-size: 24px;
        }
      `}</style>
    </div>
  );
}
