// scenarios/basic/web/svelte/MissingSkipLink.svelte
<script>
  let currentSection = 'hero';
  let isMenuOpen = false;
  let searchTerm = '';
  let selectedCategory = 'all';

  const categories = [
    { id: 'all', name: 'All Products' },
    { id: 'electronics', name: 'Electronics' },
    { id: 'clothing', name: 'Clothing' },
    { id: 'home', name: 'Home & Garden' },
    { id: 'sports', name: 'Sports' }
  ];

  const products = [
    {
      id: 1,
      name: 'Wireless Headphones',
      price: 99.99,
      category: 'electronics',
      image: 'headphones.jpg',
      rating: 4.5,
      inStock: true
    },
    {
      id: 2,
      name: 'Cotton T-Shirt',
      price: 24.99,
      category: 'clothing',
      image: 'tshirt.jpg',
      rating: 4.2,
      inStock: true
    },
    {
      id: 3,
      name: 'Coffee Maker',
      price: 149.99,
      category: 'home',
      image: 'coffeemaker.jpg',
      rating: 4.7,
      inStock: false
    },
    {
      id: 4,
      name: 'Running Shoes',
      price: 129.99,
      category: 'sports',
      image: 'shoes.jpg',
      rating: 4.4,
      inStock: true
    }
  ];

  $: filteredProducts = products.filter(product => {
    const matchesCategory = selectedCategory === 'all' || product.category === selectedCategory;
    const matchesSearch = product.name.toLowerCase().includes(searchTerm.toLowerCase());
    return matchesCategory && matchesSearch;
  });

  function scrollToSection(sectionId) {
    currentSection = sectionId;
    const element = document.getElementById(sectionId);
    if (element) {
      element.scrollIntoView({ behavior: 'smooth' });
    }
  }

  function toggleMenu() {
    isMenuOpen = !isMenuOpen;
  }

  function handleAction(action, product) {
    alert(`${action} action performed on "${product.name}"`);
  }

  function handleSearch() {
    scrollToSection('products');
  }
</script>

<div class="ecommerce-site">
  <header class="site-header">
    <div class="header-top">
      <div class="container">
        <div class="header-info">
          <span class="phone">📞 +1 (555) 123-4567</span>
          <span class="email">✉️ support@example.com</span>
          <span class="hours">🕒 Mon-Fri 9AM-6PM</span>
        </div>
        <div class="header-actions">
          <button class="header-btn">Account</button>
          <button class="header-btn">Wishlist</button>
          <button class="header-btn">Cart (0)</button>
        </div>
      </div>
    </div>

    <div class="header-main">
      <div class="container">
        <div class="logo-section">
          <h1 class="site-logo">ShopHub</h1>
          <p class="site-tagline">Your One-Stop Shopping Destination</p>
        </div>

        <div class="search-section">
          <div class="search-bar">
            <input 
              type="text" 
              placeholder="Search for products..." 
              bind:value={searchTerm}
              class="search-input"
            />
            <button class="search-btn" on:click={handleSearch}>Search</button>
          </div>
        </div>

        <div class="header-cta">
          <button class="cta-btn primary">Sign Up</button>
          <button class="cta-btn secondary">Login</button>
        </div>
      </div>
    </div>

    <nav class="main-navigation">
      <div class="container">
        <button class="mobile-menu-btn" on:click={toggleMenu}>
          ☰ Menu
        </button>
        
        <ul class="nav-list {isMenuOpen ? 'open' : ''}">
          <li class="nav-item">
            <button class="nav-link" on:click={() => scrollToSection('hero')}>
              Home
            </button>
          </li>
          <li class="nav-item">
            <button class="nav-link" on:click={() => scrollToSection('products')}>
              Products
            </button>
          </li>
          <li class="nav-item">
            <button class="nav-link" on:click={() => scrollToSection('features')}>
              Features
            </button>
          </li>
          <li class="nav-item">
            <button class="nav-link" on:click={() => scrollToSection('about')}>
              About
            </button>
          </li>
          <li class="nav-item">
            <button class="nav-link" on:click={() => scrollToSection('contact')}>
              Contact
            </button>
          </li>
        </ul>
      </div>
    </nav>
  </header>

  <main class="site-main">
    <section id="hero" class="hero-section">
      <div class="hero-content">
        <h2 class="hero-title">Welcome to ShopHub</h2>
        <p class="hero-description">
          Discover amazing products at unbeatable prices. 
          Shop with confidence and enjoy fast, reliable delivery.
        </p>
        <div class="hero-actions">
          <button class="hero-btn primary" on:click={() => scrollToSection('products')}>
            Shop Now
          </button>
          <button class="hero-btn secondary" on:click={() => scrollToSection('features')}>
            Learn More
          </button>
        </div>
      </div>
      <div class="hero-image">
        <div class="image-placeholder">
          <h3>Featured Products</h3>
          <p>Discover our best-selling items</p>
        </div>
      </div>
    </section>

    <section id="products" class="products-section">
      <div class="container">
        <h2 class="section-title">Our Products</h2>
        <p class="section-description">Browse our carefully curated selection of quality products</p>

        <div class="product-filters">
          <select bind:value={selectedCategory} class="category-filter">
            {#each categories as category}
              <option value={category.id}>{category.name}</option>
            {/each}
          </select>
        </div>

        <div class="products-grid">
          {#each filteredProducts as product}
            <div class="product-card">
              <div class="product-image">
                <img src="/images/{product.image}" alt="{product.name}" />
                {#if !product.inStock}
                  <div class="out-of-stock-badge">Out of Stock</div>
                {/if}
              </div>
              
              <div class="product-info">
                <h3 class="product-name">{product.name}</h3>
                <div class="product-rating">
                  {#each Array(5) as _, i}
                    <span class="star {i < Math.floor(product.rating) ? 'filled' : ''}">★</span>
                  {/each}
                  <span class="rating-text">{product.rating}</span>
                </div>
                <div class="product-price">${product.price}</div>
                
                <div class="product-actions">
                  <button 
                    class="action-btn primary" 
                    on:click={() => handleAction('Add to Cart', product)}
                    disabled={!product.inStock}
                  >
                    {product.inStock ? 'Add to Cart' : 'Out of Stock'}
                  </button>
                  <button 
                    class="action-btn secondary" 
                    on:click={() => handleAction('View Details', product)}
                  >
                    View Details
                  </button>
                </div>
              </div>
            </div>
          {/each}
        </div>
      </div>
    </section>

    <section id="features" class="features-section">
      <div class="container">
        <h2 class="section-title">Why Choose ShopHub?</h2>
        <p class="section-description">We're committed to providing the best shopping experience</p>

        <div class="features-grid">
          <div class="feature-card">
            <div class="feature-icon">🚚</div>
            <h3 class="feature-title">Free Shipping</h3>
            <p class="feature-description">Free delivery on orders over $50</p>
          </div>
          
          <div class="feature-card">
            <div class="feature-icon">🔒</div>
            <h3 class="feature-title">Secure Payment</h3>
            <p class="feature-description">Your payment information is always safe</p>
          </div>
          
          <div class="feature-card">
            <div class="feature-icon">↩️</div>
            <h3 class="feature-title">Easy Returns</h3>
            <p class="feature-description">30-day return policy for all items</p>
          </div>
          
          <div class="feature-card">
            <div class="feature-icon">💬</div>
            <h3 class="feature-title">24/7 Support</h3>
            <p class="feature-description">Our team is here to help you anytime</p>
          </div>
        </div>
      </div>
    </section>

    <section id="about" class="about-section">
      <div class="container">
        <div class="about-content">
          <h2 class="section-title">About ShopHub</h2>
          <p class="about-description">
            Founded in 2020, ShopHub has been revolutionizing the online shopping experience. 
            We believe that everyone deserves access to quality products at affordable prices.
          </p>
          <div class="about-stats">
            <div class="stat-item">
              <div class="stat-number">50K+</div>
              <div class="stat-label">Happy Customers</div>
            </div>
            <div class="stat-item">
              <div class="stat-number">10K+</div>
              <div class="stat-label">Products</div>
            </div>
            <div class="stat-item">
              <div class="stat-number">99%</div>
              <div class="stat-label">Satisfaction Rate</div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section id="contact" class="contact-section">
      <div class="container">
        <h2 class="section-title">Get in Touch</h2>
        <p class="section-description">Have questions? We'd love to hear from you</p>

        <div class="contact-content">
          <div class="contact-info">
            <div class="contact-item">
              <div class="contact-icon">📍</div>
              <div class="contact-details">
                <h4>Address</h4>
                <p>123 Commerce Street<br>New York, NY 10001</p>
              </div>
            </div>
            
            <div class="contact-item">
              <div class="contact-icon">📞</div>
              <div class="contact-details">
                <h4>Phone</h4>
                <p>+1 (555) 123-4567</p>
              </div>
            </div>
            
            <div class="contact-item">
              <div class="contact-icon">✉️</div>
              <div class="contact-details">
                <h4>Email</h4>
                <p>support@shophub.com</p>
              </div>
            </div>
          </div>

          <div class="contact-form">
            <form>
              <div class="form-group">
                <input type="text" placeholder="Your Name" class="form-input" />
              </div>
              <div class="form-group">
                <input type="email" placeholder="Your Email" class="form-input" />
              </div>
              <div class="form-group">
                <textarea placeholder="Your Message" class="form-textarea" rows="5"></textarea>
              </div>
              <button type="submit" class="submit-btn">Send Message</button>
            </form>
          </div>
        </div>
      </div>
    </section>
  </main>

  <footer class="site-footer">
    <div class="container">
      <div class="footer-content">
        <div class="footer-section">
          <h4>ShopHub</h4>
          <p>Your trusted online shopping partner</p>
          <div class="social-links">
            <button class="social-btn">📘</button>
            <button class="social-btn">🐦</button>
            <button class="social-btn">📷</button>
            <button class="social-btn">💼</button>
          </div>
        </div>
        
        <div class="footer-section">
          <h4>Quick Links</h4>
          <ul>
            <li><button class="footer-link" on:click={() => scrollToSection('products')}>Products</button></li>
            <li><button class="footer-link" on:click={() => scrollToSection('about')}>About Us</button></li>
            <li><button class="footer-link" on:click={() => scrollToSection('contact')}>Contact</button></li>
            <li><button class="footer-link">FAQ</button></li>
          </ul>
        </div>
        
        <div class="footer-section">
          <h4>Customer Service</h4>
          <ul>
            <li><button class="footer-link">Shipping Info</button></li>
            <li><button class="footer-link">Returns</button></li>
            <li><button class="footer-link">Size Guide</button></li>
            <li><button class="footer-link">Track Order</button></li>
          </ul>
        </div>
        
        <div class="footer-section">
          <h4>Newsletter</h4>
          <p>Subscribe for updates and special offers</p>
          <div class="newsletter-form">
            <input type="email" placeholder="Enter your email" class="newsletter-input" />
            <button class="newsletter-btn">Subscribe</button>
          </div>
        </div>
      </div>
      
      <div class="footer-bottom">
        <p>&copy; 2024 ShopHub. All rights reserved.</p>
        <div class="footer-links">
          <button class="footer-link">Privacy Policy</button>
          <button class="footer-link">Terms of Service</button>
          <button class="footer-link">Cookie Policy</button>
        </div>
      </div>
    </div>
  </footer>
</div>

<style>
  .ecommerce-site {
    font-family: Arial, sans-serif;
    line-height: 1.6;
  }

  .container {
    max-width: 1200px;
    margin: 0 auto;
    padding: 0 20px;
  }

  .site-header {
    background: white;
    box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    position: sticky;
    top: 0;
    z-index: 1000;
  }

  .header-top {
    background: #f8f9fa;
    padding: 8px 0;
    font-size: 14px;
  }

  .header-info {
    display: flex;
    gap: 20px;
    color: #666;
  }

  .header-actions {
    display: flex;
    gap: 15px;
  }

  .header-btn {
    background: none;
    border: none;
    color: #666;
    cursor: pointer;
    font-size: 14px;
  }

  .header-btn:hover {
    color: #007bff;
  }

  .header-main {
    padding: 20px 0;
  }

  .header-main .container {
    display: flex;
    justify-content: space-between;
    align-items: center;
    gap: 30px;
  }

  .logo-section h1 {
    margin: 0;
    font-size: 32px;
    color: #007bff;
    font-weight: bold;
  }

  .site-tagline {
    margin: 0;
    color: #666;
    font-size: 14px;
  }

  .search-section {
    flex: 1;
    max-width: 500px;
  }

  .search-bar {
    display: flex;
    border: 2px solid #ddd;
    border-radius: 25px;
    overflow: hidden;
  }

  .search-input {
    flex: 1;
    padding: 12px 20px;
    border: none;
    font-size: 16px;
  }

  .search-input:focus {
    outline: none;
  }

  .search-btn {
    background: #007bff;
    color: white;
    border: none;
    padding: 12px 24px;
    cursor: pointer;
    font-weight: bold;
  }

  .search-btn:hover {
    background: #0056b3;
  }

  .header-cta {
    display: flex;
    gap: 10px;
  }

  .cta-btn {
    padding: 10px 20px;
    border: none;
    border-radius: 6px;
    cursor: pointer;
    font-weight: bold;
  }

  .cta-btn.primary {
    background: #007bff;
    color: white;
  }

  .cta-btn.secondary {
    background: #6c757d;
    color: white;
  }

  .main-navigation {
    background: #333;
  }

  .mobile-menu-btn {
    display: none;
    background: none;
    border: none;
    color: white;
    padding: 15px;
    cursor: pointer;
    font-size: 16px;
  }

  .nav-list {
    display: flex;
    list-style: none;
    margin: 0;
    padding: 0;
  }

  .nav-item {
    margin: 0;
  }

  .nav-link {
    display: block;
    padding: 15px 25px;
    background: none;
    border: none;
    color: white;
    cursor: pointer;
    font-size: 16px;
    transition: background-color 0.2s ease;
  }

  .nav-link:hover {
    background: #555;
  }

  .site-main {
    min-height: 100vh;
  }

  .hero-section {
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    color: white;
    padding: 80px 0;
    display: flex;
    align-items: center;
    min-height: 500px;
  }

  .hero-content {
    flex: 1;
    max-width: 600px;
    margin-right: 40px;
  }

  .hero-title {
    margin: 0 0 20px 0;
    font-size: 48px;
    font-weight: bold;
  }

  .hero-description {
    margin: 0 0 30px 0;
    font-size: 20px;
    line-height: 1.5;
  }

  .hero-actions {
    display: flex;
    gap: 20px;
  }

  .hero-btn {
    padding: 15px 30px;
    border: none;
    border-radius: 8px;
    cursor: pointer;
    font-size: 18px;
    font-weight: bold;
    transition: all 0.2s ease;
  }

  .hero-btn.primary {
    background: white;
    color: #667eea;
  }

  .hero-btn.primary:hover {
    background: #f8f9fa;
  }

  .hero-btn.secondary {
    background: rgba(255,255,255,0.2);
    color: white;
    border: 2px solid white;
  }

  .hero-btn.secondary:hover {
    background: white;
    color: #667eea;
  }

  .hero-image {
    flex: 1;
    display: flex;
    justify-content: center;
    align-items: center;
  }

  .image-placeholder {
    width: 100%;
    height: 300px;
    background: rgba(255,255,255,0.1);
    border-radius: 12px;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    text-align: center;
  }

  .image-placeholder h3 {
    margin: 0 0 10px 0;
    font-size: 24px;
  }

  .image-placeholder p {
    margin: 0;
    font-size: 16px;
    opacity: 0.8;
  }

  .products-section,
  .features-section,
  .about-section,
  .contact-section {
    padding: 80px 0;
  }

  .products-section {
    background: #f8f9fa;
  }

  .section-title {
    text-align: center;
    margin: 0 0 20px 0;
    font-size: 36px;
    color: #333;
  }

  .section-description {
    text-align: center;
    margin: 0 0 40px 0;
    font-size: 18px;
    color: #666;
  }

  .product-filters {
    display: flex;
    justify-content: center;
    margin-bottom: 40px;
  }

  .category-filter {
    padding: 10px 20px;
    border: 2px solid #ddd;
    border-radius: 6px;
    background: white;
    font-size: 16px;
  }

  .products-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
    gap: 30px;
  }

  .product-card {
    background: white;
    border-radius: 12px;
    box-shadow: 0 4px 12px rgba(0,0,0,0.1);
    overflow: hidden;
    transition: transform 0.2s ease;
  }

  .product-card:hover {
    transform: translateY(-5px);
  }

  .product-image {
    position: relative;
    height: 200px;
    overflow: hidden;
  }

  .product-image img {
    width: 100%;
    height: 100%;
    object-fit: cover;
  }

  .out-of-stock-badge {
    position: absolute;
    top: 10px;
    right: 10px;
    background: #dc3545;
    color: white;
    padding: 4px 8px;
    border-radius: 4px;
    font-size: 12px;
    font-weight: bold;
  }

  .product-info {
    padding: 20px;
  }

  .product-name {
    margin: 0 0 10px 0;
    font-size: 18px;
    color: #333;
  }

  .product-rating {
    display: flex;
    align-items: center;
    gap: 5px;
    margin-bottom: 10px;
  }

  .star {
    color: #ddd;
    font-size: 16px;
  }

  .star.filled {
    color: #ffc107;
  }

  .rating-text {
    font-size: 14px;
    color: #666;
    margin-left: 5px;
  }

  .product-price {
    font-size: 24px;
    font-weight: bold;
    color: #007bff;
    margin-bottom: 15px;
  }

  .product-actions {
    display: flex;
    gap: 10px;
  }

  .action-btn {
    flex: 1;
    padding: 10px;
    border: none;
    border-radius: 6px;
    cursor: pointer;
    font-weight: bold;
    transition: all 0.2s ease;
  }

  .action-btn.primary {
    background: #007bff;
    color: white;
  }

  .action-btn.primary:hover:not(:disabled) {
    background: #0056b3;
  }

  .action-btn.primary:disabled {
    background: #6c757d;
    cursor: not-allowed;
  }

  .action-btn.secondary {
    background: #f8f9fa;
    color: #666;
    border: 1px solid #ddd;
  }

  .action-btn.secondary:hover {
    background: #e9ecef;
    color: #333;
  }

  .features-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
    gap: 30px;
  }

  .feature-card {
    text-align: center;
    padding: 30px;
    background: white;
    border-radius: 12px;
    box-shadow: 0 4px 12px rgba(0,0,0,0.1);
  }

  .feature-icon {
    font-size: 48px;
    margin-bottom: 20px;
  }

  .feature-title {
    margin: 0 0 15px 0;
    font-size: 20px;
    color: #333;
  }

  .feature-description {
    margin: 0;
    color: #666;
    line-height: 1.5;
  }

  .about-content {
    text-align: center;
    max-width: 800px;
    margin: 0 auto;
  }

  .about-description {
    margin: 0 0 40px 0;
    font-size: 18px;
    color: #666;
    line-height: 1.6;
  }

  .about-stats {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
    gap: 30px;
  }

  .stat-item {
    text-align: center;
  }

  .stat-number {
    font-size: 36px;
    font-weight: bold;
    color: #007bff;
    margin-bottom: 10px;
  }

  .stat-label {
    font-size: 16px;
    color: #666;
  }

  .contact-content {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 40px;
    align-items: start;
  }

  .contact-item {
    display: flex;
    gap: 20px;
    margin-bottom: 30px;
  }

  .contact-icon {
    font-size: 24px;
    color: #007bff;
  }

  .contact-details h4 {
    margin: 0 0 5px 0;
    font-size: 18px;
    color: #333;
  }

  .contact-details p {
    margin: 0;
    color: #666;
  }

  .form-group {
    margin-bottom: 20px;
  }

  .form-input,
  .form-textarea {
    width: 100%;
    padding: 12px 16px;
    border: 2px solid #ddd;
    border-radius: 6px;
    font-size: 16px;
  }

  .form-input:focus,
  .form-textarea:focus {
    outline: none;
    border-color: #007bff;
  }

  .submit-btn {
    background: #007bff;
    color: white;
    border: none;
    padding: 12px 30px;
    border-radius: 6px;
    cursor: pointer;
    font-size: 16px;
    font-weight: bold;
  }

  .submit-btn:hover {
    background: #0056b3;
  }

  .site-footer {
    background: #333;
    color: white;
    padding: 40px 0 20px 0;
  }

  .footer-content {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
    gap: 30px;
    margin-bottom: 30px;
  }

  .footer-section h4 {
    margin: 0 0 15px 0;
    font-size: 18px;
  }

  .footer-section p {
    margin: 0 0 15px 0;
    color: #ccc;
  }

  .footer-section ul {
    list-style: none;
    margin: 0;
    padding: 0;
  }

  .footer-section li {
    margin-bottom: 8px;
  }

  .footer-link {
    background: none;
    border: none;
    color: #ccc;
    cursor: pointer;
    text-decoration: none;
  }

  .footer-link:hover {
    color: white;
  }

  .social-links {
    display: flex;
    gap: 10px;
  }

  .social-btn {
    background: #555;
    border: none;
    border-radius: 4px;
    padding: 8px;
    cursor: pointer;
    font-size: 16px;
  }

  .social-btn:hover {
    background: #666;
  }

  .newsletter-form {
    display: flex;
    gap: 10px;
  }

  .newsletter-input {
    flex: 1;
    padding: 8px 12px;
    border: 1px solid #555;
    border-radius: 4px;
    background: #444;
    color: white;
  }

  .newsletter-btn {
    background: #007bff;
    color: white;
    border: none;
    padding: 8px 16px;
    border-radius: 4px;
    cursor: pointer;
  }

  .newsletter-btn:hover {
    background: #0056b3;
  }

  .footer-bottom {
    border-top: 1px solid #555;
    padding-top: 20px;
    display: flex;
    justify-content: space-between;
    align-items: center;
    flex-wrap: wrap;
    gap: 20px;
  }

  .footer-bottom p {
    margin: 0;
    color: #ccc;
  }

  .footer-links {
    display: flex;
    gap: 20px;
  }

  @media (max-width: 768px) {
    .mobile-menu-btn {
      display: block;
    }

    .nav-list {
      display: none;
      position: absolute;
      top: 100%;
      left: 0;
      right: 0;
      background: #333;
      flex-direction: column;
    }

    .nav-list.open {
      display: flex;
    }

    .header-main .container {
      flex-direction: column;
      gap: 20px;
    }

    .hero-section {
      flex-direction: column;
      text-align: center;
    }

    .hero-content {
      margin-right: 0;
      margin-bottom: 30px;
    }

    .contact-content {
      grid-template-columns: 1fr;
    }

    .footer-bottom {
      flex-direction: column;
      text-align: center;
    }
  }
</style>

// scenarios/basic/web/nextjs/MissingSkipLink.jsx
import { useState, useEffect } from 'react';

export default function MissingSkipLink() {
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [isSearchOpen, setIsSearchOpen] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedCategory, setSelectedCategory] = useState('all');
  const [currentPage, setCurrentPage] = useState(1);
  const [isScrolled, setIsScrolled] = useState(false);

  const categories = [
    { id: 'all', name: 'All Products' },
    { id: 'electronics', name: 'Electronics' },
    { id: 'clothing', name: 'Clothing' },
    { id: 'home', name: 'Home & Garden' },
    { id: 'sports', name: 'Sports' },
    { id: 'books', name: 'Books' }
  ];

  const products = [
    {
      id: 1,
      name: 'Wireless Headphones',
      category: 'electronics',
      price: 199.99,
      rating: 4.5,
      image: '/api/placeholder/300/300',
      description: 'High-quality wireless headphones with noise cancellation',
      inStock: true,
      discount: 20
    },
    {
      id: 2,
      name: 'Cotton T-Shirt',
      category: 'clothing',
      price: 29.99,
      rating: 4.2,
      image: '/api/placeholder/300/300',
      description: 'Comfortable cotton t-shirt in various colors',
      inStock: true,
      discount: 0
    },
    {
      id: 3,
      name: 'Smart Home Hub',
      category: 'electronics',
      price: 149.99,
      rating: 4.7,
      image: '/api/placeholder/300/300',
      description: 'Control all your smart devices from one place',
      inStock: false,
      discount: 15
    },
    {
      id: 4,
      name: 'Garden Tools Set',
      category: 'home',
      price: 79.99,
      rating: 4.3,
      image: '/api/placeholder/300/300',
      description: 'Complete set of professional garden tools',
      inStock: true,
      discount: 0
    },
    {
      id: 5,
      name: 'Running Shoes',
      category: 'sports',
      price: 129.99,
      rating: 4.6,
      image: '/api/placeholder/300/300',
      description: 'Lightweight running shoes for all terrains',
      inStock: true,
      discount: 25
    },
    {
      id: 6,
      name: 'Programming Book',
      category: 'books',
      price: 49.99,
      rating: 4.8,
      image: '/api/placeholder/300/300',
      description: 'Learn modern programming techniques',
      inStock: true,
      discount: 10
    }
  ];

  const navigationItems = [
    { name: 'Home', href: '/home' },
    { name: 'Products', href: '/products' },
    { name: 'Categories', href: '/categories' },
    { name: 'Deals', href: '/deals' },
    { name: 'About', href: '/about' },
    { name: 'Contact', href: '/contact' }
  ];

  const filteredProducts = products.filter(product => {
    const matchesCategory = selectedCategory === 'all' || product.category === selectedCategory;
    const matchesSearch = product.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         product.description.toLowerCase().includes(searchTerm.toLowerCase());
    return matchesCategory && matchesSearch;
  });

  const itemsPerPage = 6;
  const totalPages = Math.ceil(filteredProducts.length / itemsPerPage);
  const paginatedProducts = filteredProducts.slice(
    (currentPage - 1) * itemsPerPage,
    currentPage * itemsPerPage
  );

  useEffect(() => {
    const handleScroll = () => {
      setIsScrolled(window.scrollY > 50);
    };

    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const handleSearch = (e) => {
    e.preventDefault();
    setCurrentPage(1);
  };

  const handleCategoryChange = (category) => {
    setSelectedCategory(category);
    setCurrentPage(1);
  };

  const handlePageChange = (page) => {
    setCurrentPage(page);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const handleAddToCart = (product) => {
    alert(`Added "${product.name}" to cart`);
  };

  const handleQuickView = (product) => {
    alert(`Quick view for "${product.name}"`);
  };

  const formatPrice = (price) => {
    return `$${price.toFixed(2)}`;
  };

  const renderStars = (rating) => {
    const stars = [];
    const fullStars = Math.floor(rating);
    const hasHalfStar = rating % 1 !== 0;

    for (let i = 0; i < fullStars; i++) {
      stars.push('★');
    }
    if (hasHalfStar) {
      stars.push('☆');
    }
    while (stars.length < 5) {
      stars.push('☆');
    }
    return stars.join('');
  };

  return (
    <div className="ecommerce-store">
      <header className={`main-header ${isScrolled ? 'scrolled' : ''}`}>
        <div className="header-container">
          <div className="logo">
            <h1>ShopMax</h1>
          </div>

          <nav className={`main-nav ${isMenuOpen ? 'open' : ''}`}>
            <ul className="nav-list">
              {navigationItems.map((item, index) => (
                <li key={index} className="nav-item">
                  <a href={item.href} className="nav-link">
                    {item.name}
                  </a>
                </li>
              ))}
            </ul>
          </nav>

          <div className="header-actions">
            <div className={`search-container ${isSearchOpen ? 'open' : ''}`}>
              <form onSubmit={handleSearch} className="search-form">
                <input
                  type="text"
                  placeholder="Search products..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="search-input"
                />
                <button type="submit" className="search-btn">
                  🔍
                </button>
              </form>
            </div>

            <button className="cart-btn">
              🛒 Cart (0)
            </button>

            <button 
              className="menu-toggle"
              onClick={() => setIsMenuOpen(!isMenuOpen)}
            >
              ☰
            </button>
          </div>
        </div>
      </header>

      <main className="main-content">
        <section className="hero-section">
          <div className="hero-content">
            <h2>Discover Amazing Products</h2>
            <p>Find everything you need at unbeatable prices</p>
            <div className="hero-actions">
              <button className="cta-button primary">Shop Now</button>
              <button className="cta-button secondary">View Deals</button>
            </div>
          </div>
        </section>

        <section className="categories-section">
          <div className="categories-container">
            <h3>Shop by Category</h3>
            <div className="categories-grid">
              {categories.map((category) => (
                <button
                  key={category.id}
                  className={`category-card ${selectedCategory === category.id ? 'active' : ''}`}
                  onClick={() => handleCategoryChange(category.id)}
                >
                  <div className="category-icon">
                    {category.id === 'electronics' && '📱'}
                    {category.id === 'clothing' && '👕'}
                    {category.id === 'home' && '🏠'}
                    {category.id === 'sports' && '⚽'}
                    {category.id === 'books' && '📚'}
                    {category.id === 'all' && '🛍️'}
                  </div>
                  <span className="category-name">{category.name}</span>
                </button>
              ))}
            </div>
          </div>
        </section>

        <section className="products-section">
          <div className="products-container">
            <div className="products-header">
              <h3>Products ({filteredProducts.length})</h3>
              <div className="sort-options">
                <select className="sort-select">
                  <option value="name">Sort by Name</option>
                  <option value="price-low">Price: Low to High</option>
                  <option value="price-high">Price: High to Low</option>
                  <option value="rating">Rating</option>
                </select>
              </div>
            </div>

            <div className="products-grid">
              {paginatedProducts.map((product) => (
                <div key={product.id} className="product-card">
                  <div className="product-image-container">
                    <img 
                      src={product.image} 
                      alt={product.name}
                      className="product-image"
                    />
                    {product.discount > 0 && (
                      <div className="discount-badge">
                        -{product.discount}%
                      </div>
                    )}
                    {!product.inStock && (
                      <div className="out-of-stock-badge">
                        Out of Stock
                      </div>
                    )}
                    <div className="product-actions">
                      <button 
                        className="action-btn quick-view"
                        onClick={() => handleQuickView(product)}
                      >
                        👁️
                      </button>
                      <button className="action-btn wishlist">
                        ❤️
                      </button>
                    </div>
                  </div>

                  <div className="product-content">
                    <h4 className="product-name">{product.name}</h4>
                    <p className="product-description">{product.description}</p>
                    
                    <div className="product-rating">
                      <span className="stars">{renderStars(product.rating)}</span>
                      <span className="rating-text">({product.rating})</span>
                    </div>

                    <div className="product-price">
                      {product.discount > 0 ? (
                        <div className="price-container">
                          <span className="original-price">
                            {formatPrice(product.price)}
                          </span>
                          <span className="sale-price">
                            {formatPrice(product.price * (1 - product.discount / 100))}
                          </span>
                        </div>
                      ) : (
                        <span className="price">{formatPrice(product.price)}</span>
                      )}
                    </div>

                    <button 
                      className={`add-to-cart-btn ${!product.inStock ? 'disabled' : ''}`}
                      onClick={() => handleAddToCart(product)}
                      disabled={!product.inStock}
                    >
                      {product.inStock ? 'Add to Cart' : 'Out of Stock'}
                    </button>
                  </div>
                </div>
              ))}
            </div>

            {totalPages > 1 && (
              <div className="pagination">
                <button 
                  className="page-btn"
                  onClick={() => handlePageChange(currentPage - 1)}
                  disabled={currentPage === 1}
                >
                  Previous
                </button>
                
                {Array(totalPages).fill(0).map((_, i) => (
                  <button
                    key={i}
                    className={`page-btn ${currentPage === i + 1 ? 'active' : ''}`}
                    onClick={() => handlePageChange(i + 1)}
                  >
                    {i + 1}
                  </button>
                ))}
                
                <button 
                  className="page-btn"
                  onClick={() => handlePageChange(currentPage + 1)}
                  disabled={currentPage === totalPages}
                >
                  Next
                </button>
              </div>
            )}
          </div>
        </section>

        <section className="features-section">
          <div className="features-container">
            <h3>Why Choose ShopMax</h3>
            <div className="features-grid">
              <div className="feature-card">
                <div className="feature-icon">🚚</div>
                <h4>Free Shipping</h4>
                <p>Free shipping on orders over $50</p>
              </div>
              <div className="feature-card">
                <div className="feature-icon">↩️</div>
                <h4>Easy Returns</h4>
                <p>30-day return policy</p>
              </div>
              <div className="feature-card">
                <div className="feature-icon">🔒</div>
                <h4>Secure Payment</h4>
                <p>Your payment information is safe</p>
              </div>
              <div className="feature-card">
                <div className="feature-icon">📞</div>
                <h4>24/7 Support</h4>
                <p>Customer support whenever you need it</p>
              </div>
            </div>
          </div>
        </section>
      </main>

      <footer className="main-footer">
        <div className="footer-container">
          <div className="footer-content">
            <div className="footer-section">
              <h4>Shop</h4>
              <ul>
                <li><a href="/products">All Products</a></li>
                <li><a href="/categories">Categories</a></li>
                <li><a href="/deals">Deals</a></li>
                <li><a href="/new">New Arrivals</a></li>
              </ul>
            </div>
            <div className="footer-section">
              <h4>Customer Service</h4>
              <ul>
                <li><a href="/help">Help Center</a></li>
                <li><a href="/shipping">Shipping Info</a></li>
                <li><a href="/returns">Returns</a></li>
                <li><a href="/contact">Contact Us</a></li>
              </ul>
            </div>
            <div className="footer-section">
              <h4>Company</h4>
              <ul>
                <li><a href="/about">About Us</a></li>
                <li><a href="/careers">Careers</a></li>
                <li><a href="/press">Press</a></li>
                <li><a href="/blog">Blog</a></li>
              </ul>
            </div>
            <div className="footer-section">
              <h4>Connect</h4>
              <ul>
                <li><a href="/newsletter">Newsletter</a></li>
                <li><a href="/social">Social Media</a></li>
                <li><a href="/reviews">Reviews</a></li>
                <li><a href="/feedback">Feedback</a></li>
              </ul>
            </div>
          </div>
          <div className="footer-bottom">
            <p>&copy; 2024 ShopMax. All rights reserved.</p>
          </div>
        </div>
      </footer>

      <style jsx>{`
        .ecommerce-store {
          font-family: Arial, sans-serif;
          line-height: 1.6;
        }

        .main-header {
          position: fixed;
          top: 0;
          left: 0;
          right: 0;
          z-index: 1000;
          background: rgba(255, 255, 255, 0.95);
          backdrop-filter: blur(10px);
          transition: all 0.3s ease;
        }

        .main-header.scrolled {
          background: rgba(255, 255, 255, 0.98);
          box-shadow: 0 2px 20px rgba(0,0,0,0.1);
        }

        .header-container {
          max-width: 1200px;
          margin: 0 auto;
          padding: 0 20px;
          display: flex;
          align-items: center;
          justify-content: space-between;
          height: 70px;
        }

        .logo h1 {
          margin: 0;
          font-size: 24px;
          font-weight: bold;
          color: #333;
        }

        .main-nav {
          display: flex;
          align-items: center;
        }

        .nav-list {
          display: flex;
          list-style: none;
          margin: 0;
          padding: 0;
          gap: 30px;
        }

        .nav-link {
          text-decoration: none;
          color: #333;
          font-weight: 500;
          transition: color 0.2s ease;
        }

        .nav-link:hover {
          color: #007bff;
        }

        .header-actions {
          display: flex;
          align-items: center;
          gap: 20px;
        }

        .search-container {
          position: relative;
        }

        .search-form {
          display: flex;
          align-items: center;
        }

        .search-input {
          padding: 8px 12px;
          border: 1px solid #ddd;
          border-radius: 20px;
          width: 200px;
          transition: width 0.3s ease;
        }

        .search-container.open .search-input {
          width: 300px;
        }

        .search-btn {
          background: none;
          border: none;
          cursor: pointer;
          font-size: 16px;
          margin-left: 5px;
        }

        .cart-btn {
          background: #007bff;
          color: white;
          border: none;
          padding: 8px 16px;
          border-radius: 20px;
          cursor: pointer;
          font-weight: bold;
        }

        .menu-toggle {
          display: none;
          background: none;
          border: none;
          font-size: 20px;
          cursor: pointer;
        }

        .main-content {
          margin-top: 70px;
        }

        .hero-section {
          background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
          color: white;
          padding: 80px 20px;
          text-align: center;
        }

        .hero-content h2 {
          font-size: 48px;
          margin: 0 0 20px 0;
        }

        .hero-content p {
          font-size: 20px;
          margin: 0 0 40px 0;
          opacity: 0.9;
        }

        .hero-actions {
          display: flex;
          gap: 20px;
          justify-content: center;
          flex-wrap: wrap;
        }

        .cta-button {
          padding: 15px 30px;
          border-radius: 30px;
          text-decoration: none;
          font-weight: bold;
          font-size: 16px;
          transition: all 0.3s ease;
          border: none;
          cursor: pointer;
        }

        .cta-button.primary {
          background: white;
          color: #667eea;
        }

        .cta-button.primary:hover {
          background: #f8f9fa;
          transform: translateY(-2px);
        }

        .cta-button.secondary {
          background: transparent;
          color: white;
          border: 2px solid white;
        }

        .cta-button.secondary:hover {
          background: white;
          color: #667eea;
        }

        .categories-section {
          padding: 60px 20px;
          background: #f8f9fa;
        }

        .categories-container {
          max-width: 1200px;
          margin: 0 auto;
        }

        .categories-container h3 {
          text-align: center;
          font-size: 32px;
          margin-bottom: 40px;
          color: #333;
        }

        .categories-grid {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
          gap: 20px;
        }

        .category-card {
          background: white;
          border: 2px solid #e9ecef;
          border-radius: 8px;
          padding: 20px;
          text-align: center;
          cursor: pointer;
          transition: all 0.3s ease;
        }

        .category-card:hover,
        .category-card.active {
          border-color: #007bff;
          transform: translateY(-2px);
          box-shadow: 0 4px 12px rgba(0,123,255,0.2);
        }

        .category-icon {
          font-size: 32px;
          margin-bottom: 10px;
        }

        .category-name {
          font-weight: bold;
          color: #333;
        }

        .products-section {
          padding: 60px 20px;
        }

        .products-container {
          max-width: 1200px;
          margin: 0 auto;
        }

        .products-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 40px;
        }

        .products-header h3 {
          font-size: 28px;
          color: #333;
          margin: 0;
        }

        .sort-select {
          padding: 8px 12px;
          border: 1px solid #ddd;
          border-radius: 4px;
          background: white;
        }

        .products-grid {
          display: grid;
          grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
          gap: 30px;
          margin-bottom: 40px;
        }

        .product-card {
          background: white;
          border-radius: 8px;
          box-shadow: 0 2px 8px rgba(0,0,0,0.1);
          overflow: hidden;
          transition: transform 0.3s ease;
        }

        .product-card:hover {
          transform: translateY(-4px);
        }

        .product-image-container {
          position: relative;
          height: 200px;
          overflow: hidden;
        }

        .product-image {
          width: 100%;
          height: 100%;
          object-fit: cover;
        }

        .discount-badge {
          position: absolute;
          top: 10px;
          right: 10px;
          background: #dc3545;
          color: white;
          padding: 4px 8px;
          border-radius: 4px;
          font-size: 12px;
          font-weight: bold;
        }

        .out-of-stock-badge {
          position: absolute;
          top: 10px;
          left: 10px;
          background: #6c757d;
          color: white;
          padding: 4px 8px;
          border-radius: 4px;
          font-size: 12px;
          font-weight: bold;
        }

        .product-actions {
          position: absolute;
          top: 10px;
          right: 10px;
          display: flex;
          flex-direction: column;
          gap: 5px;
          opacity: 0;
          transition: opacity 0.3s ease;
        }

        .product-card:hover .product-actions {
          opacity: 1;
        }

        .action-btn {
          background: rgba(255, 255, 255, 0.9);
          border: none;
          border-radius: 50%;
          width: 35px;
          height: 35px;
          cursor: pointer;
          font-size: 14px;
          display: flex;
          align-items: center;
          justify-content: center;
        }

        .product-content {
          padding: 20px;
        }

        .product-name {
          font-size: 18px;
          font-weight: bold;
          margin: 0 0 10px 0;
          color: #333;
        }

        .product-description {
          color: #666;
          font-size: 14px;
          margin: 0 0 15px 0;
          line-height: 1.4;
        }

        .product-rating {
          display: flex;
          align-items: center;
          gap: 5px;
          margin-bottom: 15px;
        }

        .stars {
          color: #ffc107;
          font-size: 14px;
        }

        .rating-text {
          color: #666;
          font-size: 12px;
        }

        .product-price {
          margin-bottom: 15px;
        }

        .price-container {
          display: flex;
          align-items: center;
          gap: 10px;
        }

        .original-price {
          text-decoration: line-through;
          color: #999;
          font-size: 14px;
        }

        .sale-price {
          font-size: 18px;
          font-weight: bold;
          color: #dc3545;
        }

        .price {
          font-size: 18px;
          font-weight: bold;
          color: #333;
        }

        .add-to-cart-btn {
          width: 100%;
          background: #007bff;
          color: white;
          border: none;
          padding: 12px;
          border-radius: 4px;
          cursor: pointer;
          font-weight: bold;
          transition: background-color 0.3s ease;
        }

        .add-to-cart-btn:hover:not(.disabled) {
          background: #0056b3;
        }

        .add-to-cart-btn.disabled {
          background: #6c757d;
          cursor: not-allowed;
        }

        .pagination {
          display: flex;
          justify-content: center;
          gap: 5px;
        }

        .page-btn {
          padding: 8px 12px;
          border: 1px solid #ddd;
          background: white;
          cursor: pointer;
          border-radius: 4px;
          transition: all 0.2s ease;
        }

        .page-btn:hover:not(:disabled) {
          border-color: #007bff;
          color: #007bff;
        }

        .page-btn.active {
          background: #007bff;
          color: white;
          border-color: #007bff;
        }

        .page-btn:disabled {
          opacity: 0.5;
          cursor: not-allowed;
        }

        .features-section {
          padding: 60px 20px;
          background: #f8f9fa;
        }

        .features-container {
          max-width: 1200px;
          margin: 0 auto;
        }

        .features-container h3 {
          text-align: center;
          font-size: 32px;
          margin-bottom: 40px;
          color: #333;
        }

        .features-grid {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
          gap: 30px;
        }

        .feature-card {
          text-align: center;
          padding: 30px;
          background: white;
          border-radius: 8px;
          box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        }

        .feature-icon {
          font-size: 32px;
          margin-bottom: 15px;
        }

        .feature-card h4 {
          font-size: 18px;
          margin-bottom: 10px;
          color: #333;
        }

        .feature-card p {
          color: #666;
          margin: 0;
        }

        .main-footer {
          background: #333;
          color: white;
          padding: 60px 20px 20px;
        }

        .footer-container {
          max-width: 1200px;
          margin: 0 auto;
        }

        .footer-content {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
          gap: 40px;
          margin-bottom: 40px;
        }

        .footer-section h4 {
          margin-bottom: 20px;
          color: white;
        }

        .footer-section ul {
          list-style: none;
          padding: 0;
          margin: 0;
        }

        .footer-section li {
          margin-bottom: 10px;
        }

        .footer-section a {
          color: #ccc;
          text-decoration: none;
          transition: color 0.2s ease;
        }

        .footer-section a:hover {
          color: white;
        }

        .footer-bottom {
          text-align: center;
          padding-top: 20px;
          border-top: 1px solid #555;
          color: #ccc;
        }

        @media (max-width: 768px) {
          .main-nav {
            display: none;
          }

          .menu-toggle {
            display: block;
          }

          .hero-content h2 {
            font-size: 36px;
          }

          .hero-actions {
            flex-direction: column;
            align-items: center;
          }

          .cta-button {
            width: 100%;
            max-width: 300px;
          }

          .products-header {
            flex-direction: column;
            gap: 20px;
            align-items: flex-start;
          }
        }
      `}</style>
    </div>
  );
}
