// scenarios/basic/web/svelte/n16.svelte
<script>
  let isLoading = false;
  let loadingProgress = 0;
  let loadingMessage = '';
  let currentStep = 0;
  let isComplete = false;

  const loadingSteps = [
    { message: 'Initializing application...', duration: 1000 },
    { message: 'Loading user data...', duration: 1500 },
    { message: 'Fetching content...', duration: 2000 },
    { message: 'Processing information...', duration: 1000 },
    { message: 'Finalizing setup...', duration: 500 }
  ];

  function startLoading() {
    isLoading = true;
    isComplete = false;
    loadingProgress = 0;
    currentStep = 0;
    loadingMessage = loadingSteps[0].message;
    
    processLoadingSteps();
  }

  function processLoadingSteps() {
    if (currentStep >= loadingSteps.length) {
      completeLoading();
      return;
    }

    const step = loadingSteps[currentStep];
    loadingMessage = step.message;
    
    const stepDuration = step.duration;
    const progressIncrement = 100 / loadingSteps.length;
    const targetProgress = (currentStep + 1) * progressIncrement;
    
    const interval = setInterval(() => {
      loadingProgress += (progressIncrement / (stepDuration / 50));
      
      if (loadingProgress >= targetProgress) {
        loadingProgress = targetProgress;
        clearInterval(interval);
        currentStep++;
        setTimeout(processLoadingSteps, 100);
      }
    }, 50);
  }

  function completeLoading() {
    loadingProgress = 100;
    loadingMessage = 'Loading complete!';
    isComplete = true;
    
    setTimeout(() => {
      isLoading = false;
      isComplete = false;
      loadingProgress = 0;
    }, 2000);
  }

  function handleAction(action) {
    alert(`${action} action performed`);
  }
</script>

<div class="loading-demo">
  <header class="demo-header">
    <h1>Loading State Demo</h1>
    <p>Experience different loading states and progress indicators</p>
  </header>

  <div class="demo-controls">
    <button 
      class="demo-btn primary" 
      on:click={startLoading}
      disabled={isLoading}
    >
      {isLoading ? 'Loading...' : 'Start Loading Demo'}
    </button>
    
    <button 
      class="demo-btn secondary" 
      on:click={() => handleAction('Reset')}
      disabled={isLoading}
    >
      Reset
    </button>
  </div>

  {#if isLoading}
    <div class="loading-container">
      <div class="loading-content">
        <div class="loading-spinner">
          <div class="spinner"></div>
        </div>
        
        <div class="loading-info">
          <div class="loading-message">{loadingMessage}</div>
          <div class="loading-progress">
            <div class="progress-bar">
              <div class="progress-fill" style="width: {loadingProgress}%"></div>
            </div>
            <div class="progress-text">{Math.round(loadingProgress)}%</div>
          </div>
        </div>
      </div>
    </div>
  {/if}

  {#if isComplete}
    <div class="completion-message">
      <div class="success-icon">✅</div>
      <h3>Loading Complete!</h3>
      <p>All data has been successfully loaded and processed.</p>
    </div>
  {/if}

  <div class="demo-content">
    <h2>Loading State Features</h2>
    <div class="features-grid">
      <div class="feature-card">
        <div class="feature-icon">⏳</div>
        <h3>Progress Tracking</h3>
        <p>Visual progress bar shows loading completion percentage</p>
      </div>
      
      <div class="feature-card">
        <div class="feature-icon">💬</div>
        <h3>Status Messages</h3>
        <p>Clear messages inform users about current loading step</p>
      </div>
      
      <div class="feature-card">
        <div class="feature-icon">🎯</div>
        <h3>Step-by-Step</h3>
        <p>Loading process broken down into manageable steps</p>
      </div>
      
      <div class="feature-card">
        <div class="feature-icon">✨</div>
        <h3>Smooth Animation</h3>
        <p>Fluid animations provide visual feedback during loading</p>
      </div>
    </div>

    <div class="loading-examples">
      <h3>Different Loading States</h3>
      <div class="examples-grid">
        <div class="example-card">
          <h4>Spinner Loading</h4>
          <div class="example-spinner">
            <div class="spinner small"></div>
          </div>
          <p>Simple rotating spinner for quick operations</p>
        </div>
        
        <div class="example-card">
          <h4>Progress Bar</h4>
          <div class="example-progress">
            <div class="progress-bar">
              <div class="progress-fill" style="width: 65%"></div>
            </div>
            <span class="progress-text">65%</span>
          </div>
          <p>Progress bar with percentage for longer operations</p>
        </div>
        
        <div class="example-card">
          <h4>Dots Animation</h4>
          <div class="example-dots">
            <div class="dots">
              <span></span>
              <span></span>
              <span></span>
            </div>
          </div>
          <p>Animated dots for indeterminate loading states</p>
        </div>
      </div>
    </div>

        </div>
        
        <div class="info-item">
          <span class="info-icon">⏱️</span>
          <div class="info-text">
            <h4>Time Estimates</h4>
            <p>Provide estimated time remaining when possible</p>
          </div>
        </div>
        
        <div class="info-item">
          <span class="info-icon">🎯</span>
          <div class="info-text">
            <h4>Clear Messaging</h4>
            <p>Use descriptive text to explain what's happening</p>
          </div>
        </div>
        
        <div class="info-item">
          <span class="info-icon">⌨️</span>
          <div class="info-text">
            <h4>Keyboard Access</h4>
            <p>Ensure loading states don't trap keyboard focus</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<style>
  .loading-demo {
    max-width: 1200px;
    margin: 50px auto;
    padding: 20px;
    font-family: Arial, sans-serif;
  }

  .demo-header {
    text-align: center;
    margin-bottom: 40px;
  }

  .demo-header h1 {
    margin: 0 0 10px 0;
    font-size: 32px;
    color: #333;
  }

  .demo-header p {
    margin: 0;
    color: #666;
    font-size: 16px;
  }

  .demo-controls {
    display: flex;
    justify-content: center;
    gap: 15px;
    margin-bottom: 40px;
  }

  .demo-btn {
    padding: 12px 24px;
    border: none;
    border-radius: 6px;
    cursor: pointer;
    font-size: 16px;
    font-weight: bold;
    transition: all 0.2s ease;
  }

  .demo-btn.primary {
    background: #007bff;
    color: white;
  }

  .demo-btn.primary:hover:not(:disabled) {
    background: #0056b3;
  }

  .demo-btn.secondary {
    background: #6c757d;
    color: white;
  }

  .demo-btn.secondary:hover:not(:disabled) {
    background: #545b62;
  }

  .demo-btn:disabled {
    opacity: 0.6;
    cursor: not-allowed;
  }

  .loading-container {
    background: white;
    border-radius: 12px;
    box-shadow: 0 4px 16px rgba(0,0,0,0.1);
    padding: 40px;
    margin-bottom: 40px;
    text-align: center;
  }

  .loading-content {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 30px;
  }

  .loading-spinner {
    position: relative;
  }

  .spinner {
    width: 60px;
    height: 60px;
    border: 4px solid #f3f3f3;
    border-top: 4px solid #007bff;
    border-radius: 50%;
    animation: spin 1s linear infinite;
  }

  .spinner.small {
    width: 30px;
    height: 30px;
    border-width: 3px;
  }

  @keyframes spin {
    0% { transform: rotate(0deg); }
    100% { transform: rotate(360deg); }
  }

  .loading-info {
    width: 100%;
    max-width: 400px;
  }

  .loading-message {
    font-size: 18px;
    color: #333;
    margin-bottom: 20px;
    font-weight: bold;
  }

  .loading-progress {
    display: flex;
    align-items: center;
    gap: 15px;
  }

  .progress-bar {
    flex: 1;
    height: 8px;
    background: #f0f0f0;
    border-radius: 4px;
    overflow: hidden;
  }

  .progress-fill {
    height: 100%;
    background: linear-gradient(90deg, #007bff, #0056b3);
    border-radius: 4px;
    transition: width 0.3s ease;
  }

  .progress-text {
    font-size: 14px;
    font-weight: bold;
    color: #007bff;
    min-width: 40px;
  }

  .completion-message {
    background: #d4edda;
    border: 1px solid #c3e6cb;
    border-radius: 8px;
    padding: 30px;
    text-align: center;
    margin-bottom: 40px;
  }

  .success-icon {
    font-size: 48px;
    margin-bottom: 15px;
  }

  .completion-message h3 {
    margin: 0 0 10px 0;
    color: #155724;
    font-size: 24px;
  }

  .completion-message p {
    margin: 0;
    color: #155724;
    font-size: 16px;
  }

  .demo-content h2 {
    margin: 0 0 30px 0;
    font-size: 28px;
    color: #333;
  }

  .features-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
    gap: 20px;
    margin-bottom: 40px;
  }

  .feature-card {
    background: white;
    padding: 25px;
    border-radius: 8px;
    box-shadow: 0 2px 8px rgba(0,0,0,0.1);
    text-align: center;
  }

  .feature-icon {
    font-size: 32px;
    margin-bottom: 15px;
  }

  .feature-card h3 {
    margin: 0 0 10px 0;
    font-size: 18px;
    color: #333;
  }

  .feature-card p {
    margin: 0;
    color: #666;
    font-size: 14px;
    line-height: 1.4;
  }

  .loading-examples {
    background: #f8f9fa;
    padding: 30px;
    border-radius: 8px;
    margin-bottom: 40px;
  }

  .loading-examples h3 {
    margin: 0 0 25px 0;
    font-size: 24px;
    color: #333;
  }

  .examples-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 20px;
  }

  .example-card {
    background: white;
    padding: 20px;
    border-radius: 6px;
    text-align: center;
  }

  .example-card h4 {
    margin: 0 0 15px 0;
    font-size: 16px;
    color: #333;
  }

  .example-spinner,
  .example-progress,
  .example-dots {
    margin-bottom: 15px;
    display: flex;
    justify-content: center;
    align-items: center;
  }

  .example-progress {
    flex-direction: column;
    gap: 10px;
  }

  .example-dots {
    height: 30px;
  }

  .dots {
    display: flex;
    gap: 4px;
  }

  .dots span {
    width: 8px;
    height: 8px;
    background: #007bff;
    border-radius: 50%;
    animation: bounce 1.4s ease-in-out infinite both;
  }

  .dots span:nth-child(1) { animation-delay: -0.32s; }
  .dots span:nth-child(2) { animation-delay: -0.16s; }

  @keyframes bounce {
    0%, 80%, 100% {
      transform: scale(0);
    }
    40% {
      transform: scale(1);
    }
  }

  .example-card p {
    margin: 0;
    color: #666;
    font-size: 12px;
    line-height: 1.4;
  }

  .info-panel {
    background: white;
    padding: 30px;
    border-radius: 8px;
    box-shadow: 0 2px 8px rgba(0,0,0,0.1);
  }

  .info-panel h3 {
    margin: 0 0 25px 0;
    font-size: 24px;
    color: #333;
  }

  .info-content {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
    gap: 20px;
  }

  .info-item {
    display: flex;
    gap: 15px;
    align-items: flex-start;
  }

  .info-icon {
    font-size: 24px;
    flex-shrink: 0;
  }

  .info-text h4 {
    margin: 0 0 5px 0;
    font-size: 16px;
    color: #333;
  }

  .info-text p {
    margin: 0;
    color: #666;
    font-size: 14px;
    line-height: 1.4;
  }

  @media (max-width: 768px) {
    .demo-controls {
      flex-direction: column;
      align-items: center;
    }

    .demo-btn {
      width: 200px;
    }

    .loading-content {
      gap: 20px;
    }

    .loading-progress {
      flex-direction: column;
      gap: 10px;
    }

    .progress-text {
      min-width: auto;
    }
  }
</style>

// scenarios/basic/web/nextjs/n16.jsx
import { useState, useEffect } from 'react';

export default function SilentLoadingState() {
  const [isLoading, setIsLoading] = useState(false);
  const [data, setData] = useState([]);
  const [error, setError] = useState(null);
  const [currentPage, setCurrentPage] = useState(1);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedCategory, setSelectedCategory] = useState('all');
  const [sortBy, setSortBy] = useState('name');

  const categories = [
    { id: 'all', name: 'All Items' },
    { id: 'electronics', name: 'Electronics' },
    { id: 'clothing', name: 'Clothing' },
    { id: 'books', name: 'Books' },
    { id: 'home', name: 'Home & Garden' }
  ];

  const sampleData = [
    { id: 1, name: 'Wireless Headphones', category: 'electronics', price: 199.99, rating: 4.5, inStock: true },
    { id: 2, name: 'Cotton T-Shirt', category: 'clothing', price: 29.99, rating: 4.2, inStock: true },
    { id: 3, name: 'Programming Book', category: 'books', price: 49.99, rating: 4.8, inStock: false },
    { id: 4, name: 'Smart Home Hub', category: 'electronics', price: 149.99, rating: 4.7, inStock: true },
    { id: 5, name: 'Garden Tools Set', category: 'home', price: 79.99, rating: 4.3, inStock: true },
    { id: 6, name: 'Running Shoes', category: 'clothing', price: 129.99, rating: 4.6, inStock: true },
    { id: 7, name: 'Cookbook Collection', category: 'books', price: 39.99, rating: 4.4, inStock: true },
    { id: 8, name: 'LED Desk Lamp', category: 'electronics', price: 89.99, rating: 4.1, inStock: false }
  ];

  const loadData = async () => {
    setIsLoading(true);
    setError(null);
    
    try {
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      let filteredData = sampleData;
      
      if (selectedCategory !== 'all') {
        filteredData = filteredData.filter(item => item.category === selectedCategory);
      }
      
      if (searchQuery) {
        filteredData = filteredData.filter(item => 
          item.name.toLowerCase().includes(searchQuery.toLowerCase())
        );
      }
      
      filteredData.sort((a, b) => {
        switch(sortBy) {
          case 'name':
            return a.name.localeCompare(b.name);
          case 'price':
            return a.price - b.price;
          case 'rating':
            return b.rating - a.rating;
          default:
            return 0;
        }
      });
      
      setData(filteredData);
    } catch (err) {
      setError('Failed to load data. Please try again.');
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    loadData();
  }, [selectedCategory, searchQuery, sortBy]);

  const handleSearch = (e) => {
    e.preventDefault();
    setCurrentPage(1);
  };

  const handleCategoryChange = (category) => {
    setSelectedCategory(category);
    setCurrentPage(1);
  };

  const handleSortChange = (sort) => {
    setSortBy(sort);
    setCurrentPage(1);
  };

  const handleRefresh = () => {
    loadData();
  };

  const handleRetry = () => {
    loadData();
  };

  const formatPrice = (price) => {
    return `$${price.toFixed(2)}`;
  };

  const renderStars = (rating) => {
    const stars = [];
    const fullStars = Math.floor(rating);
    const hasHalfStar = rating % 1 !== 0;

    for (let i = 0; i < fullStars; i++) {
      stars.push('★');
    }
    if (hasHalfStar) {
      stars.push('☆');
    }
    while (stars.length < 5) {
      stars.push('☆');
    }
    return stars.join('');
  };

  return (
    <div className="product-catalog">
      <header className="catalog-header">
        <h1>Product Catalog</h1>
        <p>Browse and discover amazing products</p>
      </header>

      <div className="catalog-controls">
        <div className="search-section">
          <form onSubmit={handleSearch} className="search-form">
            <input
              type="text"
              placeholder="Search products..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="search-input"
            />
            <button type="submit" className="search-btn">Search</button>
          </form>
        </div>

        <div className="filter-section">
          <div className="filter-group">
            <label>Category:</label>
            <select 
              value={selectedCategory} 
              onChange={(e) => handleCategoryChange(e.target.value)}
              className="filter-select"
            >
              {categories.map(category => (
                <option key={category.id} value={category.id}>
                  {category.name}
                </option>
              ))}
            </select>
          </div>

          <div className="filter-group">
            <label>Sort by:</label>
            <select 
              value={sortBy} 
              onChange={(e) => handleSortChange(e.target.value)}
              className="filter-select"
            >
              <option value="name">Name</option>
              <option value="price">Price</option>
              <option value="rating">Rating</option>
            </select>
          </div>

          <button 
            className="refresh-btn"
            onClick={handleRefresh}
            disabled={isLoading}
          >
            {isLoading ? 'Refreshing...' : 'Refresh'}
          </button>
        </div>
      </div>

      <div className="catalog-content">
        {isLoading && (
          <div className="loading-overlay">
            <div className="loading-spinner"></div>
            <p>Loading products...</p>
          </div>
        )}

        {error && (
          <div className="error-message">
            <div className="error-icon">⚠️</div>
            <div className="error-content">
              <h3>Something went wrong</h3>
              <p>{error}</p>
              <button className="retry-btn" onClick={handleRetry}>
                Try Again
              </button>
            </div>
          </div>
        )}

        {!isLoading && !error && data.length === 0 && (
          <div className="empty-state">
            <div className="empty-icon">📦</div>
            <h3>No products found</h3>
            <p>Try adjusting your search or filter criteria</p>
            <button className="clear-filters-btn" onClick={() => {
              setSearchQuery('');
              setSelectedCategory('all');
            }}>
              Clear Filters
            </button>
          </div>
        )}

        {!isLoading && !error && data.length > 0 && (
          <div className="products-grid">
            {data.map(item => (
              <div key={item.id} className="product-card">
                <div className="product-image">
                  <div className="image-placeholder">
                    {item.category === 'electronics' && '📱'}
                    {item.category === 'clothing' && '👕'}
                    {item.category === 'books' && '📚'}
                    {item.category === 'home' && '🏠'}
                  </div>
                  {!item.inStock && (
                    <div className="out-of-stock-badge">Out of Stock</div>
                  )}
                </div>

                <div className="product-info">
                  <h3 className="product-name">{item.name}</h3>
                  
                  <div className="product-rating">
                    <span className="stars">{renderStars(item.rating)}</span>
                    <span className="rating-text">({item.rating})</span>
                  </div>

                  <div className="product-price">
                    {formatPrice(item.price)}
                  </div>

                  <div className="product-actions">
                    <button 
                      className="action-btn primary"
                      disabled={!item.inStock}
                    >
                      {item.inStock ? 'Add to Cart' : 'Out of Stock'}
                    </button>
                    <button className="action-btn secondary">
                      View Details
                    </button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      <div className="catalog-footer">
        <div className="results-info">
          <span>
            {isLoading ? 'Loading...' : `${data.length} products found`}
          </span>
        </div>

        <div className="pagination">
          <button 
            className="page-btn"
            disabled={currentPage === 1}
            onClick={() => setCurrentPage(currentPage - 1)}
          >
            Previous
          </button>
          
          <span className="page-info">
            Page {currentPage} of 3
          </span>
          
          <button 
            className="page-btn"
            disabled={currentPage === 3}
            onClick={() => setCurrentPage(currentPage + 1)}
          >
            Next
          </button>
        </div>
      </div>

      <style jsx>{`
        .product-catalog {
          max-width: 1200px;
          margin: 0 auto;
          padding: 20px;
          font-family: Arial, sans-serif;
        }

        .catalog-header {
          text-align: center;
          margin-bottom: 30px;
        }

        .catalog-header h1 {
          margin: 0 0 10px 0;
          font-size: 32px;
          color: #333;
        }

        .catalog-header p {
          margin: 0;
          color: #666;
          font-size: 16px;
        }

        .catalog-controls {
          display: flex;
          flex-wrap: wrap;
          gap: 20px;
          align-items: center;
          justify-content: space-between;
          margin-bottom: 30px;
          padding: 20px;
          background: #f8f9fa;
          border-radius: 8px;
        }

        .search-section {
          flex: 1;
          min-width: 300px;
        }

        .search-form {
          display: flex;
          gap: 10px;
        }

        .search-input {
          flex: 1;
          padding: 10px 15px;
          border: 1px solid #ddd;
          border-radius: 4px;
          font-size: 14px;
        }

        .search-btn {
          padding: 10px 20px;
          background: #007bff;
          color: white;
          border: none;
          border-radius: 4px;
          cursor: pointer;
          font-weight: bold;
        }

        .search-btn:hover {
          background: #0056b3;
        }

        .filter-section {
          display: flex;
          gap: 20px;
          align-items: center;
          flex-wrap: wrap;
        }

        .filter-group {
          display: flex;
          flex-direction: column;
          gap: 5px;
        }

        .filter-group label {
          font-size: 12px;
          font-weight: bold;
          color: #666;
        }

        .filter-select {
          padding: 8px 12px;
          border: 1px solid #ddd;
          border-radius: 4px;
          background: white;
          cursor: pointer;
        }

        .refresh-btn {
          padding: 8px 16px;
          background: #6c757d;
          color: white;
          border: none;
          border-radius: 4px;
          cursor: pointer;
          font-weight: bold;
        }

        .refresh-btn:hover:not(:disabled) {
          background: #545b62;
        }

        .refresh-btn:disabled {
          opacity: 0.5;
          cursor: not-allowed;
        }

        .catalog-content {
          position: relative;
          min-height: 400px;
        }

        .loading-overlay {
          position: absolute;
          top: 0;
          left: 0;
          right: 0;
          bottom: 0;
          background: rgba(255, 255, 255, 0.9);
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          z-index: 10;
        }

        .loading-spinner {
          width: 40px;
          height: 40px;
          border: 4px solid #f3f3f3;
          border-top: 4px solid #007bff;
          border-radius: 50%;
          animation: spin 1s linear infinite;
          margin-bottom: 20px;
        }

        @keyframes spin {
          0% { transform: rotate(0deg); }
          100% { transform: rotate(360deg); }
        }

        .error-message {
          display: flex;
          align-items: center;
          gap: 20px;
          padding: 30px;
          background: #f8d7da;
          border: 1px solid #f5c6cb;
          border-radius: 8px;
          color: #721c24;
        }

        .error-icon {
          font-size: 48px;
        }

        .error-content h3 {
          margin: 0 0 10px 0;
          font-size: 18px;
        }

        .error-content p {
          margin: 0 0 15px 0;
        }

        .retry-btn {
          padding: 8px 16px;
          background: #dc3545;
          color: white;
          border: none;
          border-radius: 4px;
          cursor: pointer;
          font-weight: bold;
        }

        .retry-btn:hover {
          background: #c82333;
        }

        .empty-state {
          text-align: center;
          padding: 60px 20px;
          color: #666;
        }

        .empty-icon {
          font-size: 64px;
          margin-bottom: 20px;
        }

        .empty-state h3 {
          margin: 0 0 10px 0;
          font-size: 24px;
          color: #333;
        }

        .empty-state p {
          margin: 0 0 20px 0;
          font-size: 16px;
        }

        .clear-filters-btn {
          padding: 10px 20px;
          background: #007bff;
          color: white;
          border: none;
          border-radius: 4px;
          cursor: pointer;
          font-weight: bold;
        }

        .clear-filters-btn:hover {
          background: #0056b3;
        }

        .products-grid {
          display: grid;
          grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
          gap: 20px;
        }

        .product-card {
          background: white;
          border: 1px solid #ddd;
          border-radius: 8px;
          overflow: hidden;
          transition: transform 0.2s ease, box-shadow 0.2s ease;
        }

        .product-card:hover {
          transform: translateY(-2px);
          box-shadow: 0 4px 12px rgba(0,0,0,0.1);
        }

        .product-image {
          position: relative;
          height: 200px;
          background: #f8f9fa;
          display: flex;
          align-items: center;
          justify-content: center;
        }

        .image-placeholder {
          font-size: 48px;
        }

        .out-of-stock-badge {
          position: absolute;
          top: 10px;
          right: 10px;
          background: #dc3545;
          color: white;
          padding: 4px 8px;
          border-radius: 4px;
          font-size: 12px;
          font-weight: bold;
        }

        .product-info {
          padding: 20px;
        }

        .product-name {
          margin: 0 0 10px 0;
          font-size: 16px;
          font-weight: bold;
          color: #333;
        }

        .product-rating {
          display: flex;
          align-items: center;
          gap: 5px;
          margin-bottom: 10px;
        }

        .stars {
          color: #ffc107;
          font-size: 14px;
        }

        .rating-text {
          font-size: 12px;
          color: #666;
        }

        .product-price {
          font-size: 18px;
          font-weight: bold;
          color: #333;
          margin-bottom: 15px;
        }

        .product-actions {
          display: flex;
          gap: 10px;
        }

        .action-btn {
          flex: 1;
          padding: 10px;
          border: none;
          border-radius: 4px;
          cursor: pointer;
          font-weight: bold;
          transition: all 0.2s ease;
        }

        .action-btn.primary {
          background: #007bff;
          color: white;
        }

        .action-btn.primary:hover:not(:disabled) {
          background: #0056b3;
        }

        .action-btn.primary:disabled {
          background: #6c757d;
          cursor: not-allowed;
        }

        .action-btn.secondary {
          background: #6c757d;
          color: white;
        }

        .action-btn.secondary:hover {
          background: #545b62;
        }

        .catalog-footer {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-top: 30px;
          padding: 20px;
          background: #f8f9fa;
          border-radius: 8px;
        }

        .results-info {
          font-size: 14px;
          color: #666;
        }

        .pagination {
          display: flex;
          align-items: center;
          gap: 15px;
        }

        .page-btn {
          padding: 8px 16px;
          border: 1px solid #ddd;
          background: white;
          cursor: pointer;
          border-radius: 4px;
          font-weight: bold;
          transition: all 0.2s ease;
        }

        .page-btn:hover:not(:disabled) {
          border-color: #007bff;
          color: #007bff;
        }

        .page-btn:disabled {
          opacity: 0.5;
          cursor: not-allowed;
        }

        .page-info {
          font-size: 14px;
          color: #666;
        }

        @media (max-width: 768px) {
          .catalog-controls {
            flex-direction: column;
            align-items: stretch;
          }

          .search-section {
            min-width: auto;
          }

          .filter-section {
            justify-content: center;
          }

          .products-grid {
            grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
            gap: 15px;
          }

          .catalog-footer {
            flex-direction: column;
            gap: 15px;
            text-align: center;
          }
        }
      `}</style>
    </div>
  );
}
