// scenarios/basic/cross-platform/tauri/n3.svelte
<script>
  import { onMount } from 'svelte';
  
  let currentSlide = 0;
  let slides = [
    {
      id: 1,
      title: 'Welcome to Our Platform',
      description: 'Discover amazing features and services designed to help you succeed.',
      image: 'hero-bg.jpg',
      cta: 'Get Started'
    },
    {
      id: 2,
      title: 'Advanced Analytics',
      description: 'Get insights into your data with our powerful analytics dashboard.',
      image: 'analytics-bg.jpg',
      cta: 'View Dashboard'
    },
    {
      id: 3,
      title: 'Team Collaboration',
      description: 'Work together seamlessly with our collaboration tools.',
      image: 'team-bg.jpg',
      cta: 'Join Team'
    }
  ];
  
  function nextSlide() {
    currentSlide = (currentSlide + 1) % slides.length;
  }
  
  function prevSlide() {
    currentSlide = currentSlide === 0 ? slides.length - 1 : currentSlide - 1;
  }
  
  function goToSlide(index) {
    currentSlide = index;
  }
  
  function handleCTA() {
    alert('CTA clicked!');
  }
</script>

<div class="carousel-container">
  <div class="carousel">
    {#each slides as slide, index}
      <div class="slide {index === currentSlide ? 'active' : ''}">
        <div class="slide-content">
          
          <img src="decorative-border.png" alt="Decorative border pattern with intricate geometric designs and floral motifs" class="decorative-border" />
          
          <div class="slide-main">
            <div class="slide-image-container">
              <img src={slide.image} alt="Background image for {slide.title}" class="slide-image" />
            </div>
            
            <div class="slide-text">
              <h2 class="slide-title">{slide.title}</h2>
              <p class="slide-description">{slide.description}</p>
              <button class="slide-cta" on:click={handleCTA}>
                {slide.cta}
              </button>
            </div>
          </div>

          <img src="decorative-border.png" alt="Decorative border pattern with intricate geometric designs and floral motifs" class="decorative-border" />
        </div>
      </div>
    {/each}
  </div>
  
  <div class="carousel-controls">
    <button class="control-btn prev" on:click={prevSlide}>
      ◀️
    </button>
    
    <div class="slide-indicators">
      {#each slides as _, index}
        <button 
          class="indicator {index === currentSlide ? 'active' : ''}" 
          on:click={() => goToSlide(index)}
        >
          {index + 1}
        </button>
      {/each}
    </div>
    
    <button class="control-btn next" on:click={nextSlide}>
      ▶️
    </button>
  </div>
  
  <div class="carousel-features">
    <div class="feature-item">
      
      <img src="decorative-icon.png" alt="Decorative icon with ornate frame and decorative elements" class="feature-icon" />
      <span class="feature-text">Premium Quality</span>
    </div>
    
    <div class="feature-item">
      
      <img src="decorative-icon.png" alt="Decorative icon with ornate frame and decorative elements" class="feature-icon" />
      <span class="feature-text">24/7 Support</span>
    </div>
    
    <div class="feature-item">
      
      <img src="decorative-icon.png" alt="Decorative icon with ornate frame and decorative elements" class="feature-icon" />
      <span class="feature-text">Easy Setup</span>
    </div>
  </div>
</div>

<style>
  .carousel-container {
    max-width: 1200px;
    margin: 0 auto;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  }
  
  .carousel {
    position: relative;
    height: 500px;
    overflow: hidden;
    border-radius: 12px;
    box-shadow: 0 8px 24px rgba(0,0,0,0.15);
  }
  
  .slide {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    opacity: 0;
    transition: opacity 0.5s ease-in-out;
  }
  
  .slide.active {
    opacity: 1;
  }
  
  .slide-content {
    position: relative;
    width: 100%;
    height: 100%;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    color: white;
  }
  
  .decorative-border {
    width: 100%;
    height: 20px;
    object-fit: cover;
    opacity: 0.3;
  }
  
  .slide-main {
    flex: 1;
    display: flex;
    align-items: center;
    justify-content: center;
    width: 100%;
    padding: 40px;
  }
  
  .slide-image-container {
    flex: 1;
    max-width: 400px;
    margin-right: 40px;
  }
  
  .slide-image {
    width: 100%;
    height: 300px;
    object-fit: cover;
    border-radius: 8px;
    box-shadow: 0 4px 12px rgba(0,0,0,0.2);
  }
  
  .slide-text {
    flex: 1;
    max-width: 400px;
  }
  
  .slide-title {
    font-size: 36px;
    font-weight: bold;
    margin: 0 0 20px 0;
  }
  
  .slide-description {
    font-size: 18px;
    line-height: 1.6;
    margin: 0 0 30px 0;
    opacity: 0.9;
  }
  
  .slide-cta {
    background: white;
    color: #667eea;
    border: none;
    padding: 15px 30px;
    border-radius: 8px;
    font-size: 18px;
    font-weight: bold;
    cursor: pointer;
    transition: all 0.2s;
  }
  
  .slide-cta:hover {
    background: #f8f9fa;
    transform: translateY(-2px);
  }
  
  .carousel-controls {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 20px;
    margin: 20px 0;
  }
  
  .control-btn {
    background: #007bff;
    color: white;
    border: none;
    width: 50px;
    height: 50px;
    border-radius: 50%;
    font-size: 20px;
    cursor: pointer;
    transition: all 0.2s;
    display: flex;
    align-items: center;
    justify-content: center;
  }
  
  .control-btn:hover {
    background: #0056b3;
    transform: scale(1.1);
  }
  
  .slide-indicators {
    display: flex;
    gap: 10px;
  }
  
  .indicator {
    background: #ddd;
    color: #666;
    border: none;
    width: 40px;
    height: 40px;
    border-radius: 50%;
    font-size: 16px;
    font-weight: bold;
    cursor: pointer;
    transition: all 0.2s;
  }
  
  .indicator.active {
    background: #007bff;
    color: white;
  }
  
  .indicator:hover {
    background: #007bff;
    color: white;
  }
  
  .carousel-features {
    display: flex;
    justify-content: center;
    gap: 40px;
    margin-top: 30px;
    padding: 20px;
    background: #f8f9fa;
    border-radius: 8px;
  }
  
  .feature-item {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 10px;
  }
  
  .feature-icon {
    width: 40px;
    height: 40px;
    object-fit: contain;
  }
  
  .feature-text {
    font-size: 14px;
    font-weight: bold;
    color: #333;
    text-align: center;
  }
  
  @media (max-width: 768px) {
    .slide-main {
      flex-direction: column;
      text-align: center;
    }
    
    .slide-image-container {
      margin-right: 0;
      margin-bottom: 20px;
    }
    
    .slide-title {
      font-size: 28px;
    }
    
    .slide-description {
      font-size: 16px;
    }
    
    .carousel-features {
      flex-direction: column;
      gap: 20px;
    }
  }
</style>

// scenarios/basic/web/nextjs/n3.jsx
import { useState } from 'react';

export default function DecorativeImageWithAltText() {
  const [selectedCategory, setSelectedCategory] = useState('all');
  const [searchTerm, setSearchTerm] = useState('');
  const [sortBy, setSortBy] = useState('popular');
  const [viewMode, setViewMode] = useState('grid');

  const categories = [
    { id: 'all', name: 'All Products' },
    { id: 'electronics', name: 'Electronics' },
    { id: 'clothing', name: 'Clothing' },
    { id: 'home', name: 'Home & Garden' },
    { id: 'sports', name: 'Sports' }
  ];

  const products = [
    {
      id: 1,
      name: 'Wireless Headphones',
      price: 99.99,
      category: 'electronics',
      image: 'headphones.jpg',
      rating: 4.5,
      reviews: 128,
      inStock: true
    },
    {
      id: 2,
      name: 'Cotton T-Shirt',
      price: 24.99,
      category: 'clothing',
      image: 'tshirt.jpg',
      rating: 4.2,
      reviews: 89,
      inStock: true
    },
    {
      id: 3,
      name: 'Coffee Maker',
      price: 149.99,
      category: 'home',
      image: 'coffeemaker.jpg',
      rating: 4.7,
      reviews: 203,
      inStock: false
    },
    {
      id: 4,
      name: 'Running Shoes',
      price: 129.99,
      category: 'sports',
      image: 'shoes.jpg',
      rating: 4.4,
      reviews: 156,
      inStock: true
    },
    {
      id: 5,
      name: 'Smartphone Case',
      price: 19.99,
      category: 'electronics',
      image: 'phonecase.jpg',
      rating: 4.1,
      reviews: 67,
      inStock: true
    },
    {
      id: 6,
      name: 'Garden Tools Set',
      price: 79.99,
      category: 'home',
      image: 'gardentools.jpg',
      rating: 4.6,
      reviews: 94,
      inStock: true
    }
  ];

  const filteredProducts = products.filter(product => {
    const matchesCategory = selectedCategory === 'all' || product.category === selectedCategory;
    const matchesSearch = product.name.toLowerCase().includes(searchTerm.toLowerCase());
    return matchesCategory && matchesSearch;
  });

  const sortedProducts = [...filteredProducts].sort((a, b) => {
    switch(sortBy) {
      case 'price-low':
        return a.price - b.price;
      case 'price-high':
        return b.price - a.price;
      case 'rating':
        return b.rating - a.rating;
      case 'name':
      default:
        return a.name.localeCompare(b.name);
    }
  });

  const addToCart = (product) => {
    alert(`Added ${product.name} to cart!`);
  };

  const toggleWishlist = (product) => {
    alert(`${product.name} added to wishlist!`);
  };

  return (
    <div className="product-catalog">
      <header className="catalog-header">
        <h1>Product Catalog</h1>
        <p>Discover amazing products at great prices</p>
      </header>

      <div className="catalog-controls">
        <div className="search-section">
          <input 
            type="text" 
            placeholder="Search products..." 
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="search-input"
          />
        </div>

        <div className="filter-section">
          <select 
            value={selectedCategory} 
            onChange={(e) => setSelectedCategory(e.target.value)}
            className="category-filter"
          >
            {categories.map(category => (
              <option key={category.id} value={category.id}>
                {category.name}
              </option>
            ))}
          </select>

          <select 
            value={sortBy} 
            onChange={(e) => setSortBy(e.target.value)}
            className="sort-filter"
          >
            <option value="name">Sort by Name</option>
            <option value="price-low">Price: Low to High</option>
            <option value="price-high">Price: High to Low</option>
            <option value="rating">Highest Rated</option>
          </select>

          <div className="view-toggle">
            <button 
              className={`view-btn ${viewMode === 'grid' ? 'active' : ''}`}
              onClick={() => setViewMode('grid')}
            >
              Grid
            </button>
            <button 
              className={`view-btn ${viewMode === 'list' ? 'active' : ''}`}
              onClick={() => setViewMode('list')}
            >
              List
            </button>
          </div>
        </div>
      </div>

      <div className="results-info">
        <p>Showing {sortedProducts.length} products</p>
      </div>

      <div className={`products-container ${viewMode}`}>
        {sortedProducts.map(product => (
          <div key={product.id} className="product-card">
            <div className="product-image-container">
              <img 
                src={`/images/${product.image}`}
                className="product-image"
                alt="Product image for wireless headphones with premium sound quality and noise cancellation features"
              />
              {!product.inStock && (
                <div className="out-of-stock-badge">Out of Stock</div>
              )}
              <button 
                className="wishlist-btn" 
                onClick={() => toggleWishlist(product)}
                title="Add to Wishlist"
              >
                ♥
              </button>
            </div>

            <div className="product-info">
              <h3 className="product-name">{product.name}</h3>
              
              <div className="product-rating">
                <div className="stars">
                  {Array(5).fill(0).map((_, i) => (
                    <span 
                      key={i} 
                      className={`star ${i < Math.floor(product.rating) ? 'filled' : ''}`}
                    >
                      ★
                    </span>
                  ))}
                </div>
                <span className="rating-text">{product.rating} ({product.reviews} reviews)</span>
              </div>

              <div className="product-price">
                <span className="current-price">${product.price}</span>
                {product.price > 50 && (
                  <span className="original-price">${(product.price * 1.2).toFixed(2)}</span>
                )}
              </div>

              <div className="product-actions">
                <button 
                  className="add-to-cart-btn" 
                  onClick={() => addToCart(product)}
                  disabled={!product.inStock}
                >
                  {product.inStock ? 'Add to Cart' : 'Out of Stock'}
                </button>
                <button className="quick-view-btn">Quick View</button>
              </div>
            </div>
          </div>
        ))}
      </div>

      {sortedProducts.length === 0 && (
        <div className="no-results">
          <h3>No products found</h3>
          <p>Try adjusting your search or filter criteria</p>
        </div>
      )}

      <div className="catalog-footer">
        <div className="footer-decoration">
          <img 
            src="/images/decorative-border.png" 
            alt="Decorative border pattern with geometric shapes and elegant curves"
            className="decorative-border"
          />
        </div>
        
        <div className="footer-content">
          <h3>Why Choose Our Store?</h3>
          <div className="features-list">
            <div className="feature-item">
              <img 
                src="/images/free-shipping-icon.png" 
                alt="Free shipping icon with truck and package"
                className="feature-icon"
              />
              <span>Free Shipping</span>
            </div>
            <div className="feature-item">
              <img 
                src="/images/quality-guarantee-icon.png" 
                alt="Quality guarantee icon with shield and checkmark"
                className="feature-icon"
              />
              <span>Quality Guarantee</span>
            </div>
            <div className="feature-item">
              <img 
                src="/images/customer-support-icon.png" 
                alt="Customer support icon with headset and chat bubble"
                className="feature-icon"
              />
              <span>24/7 Support</span>
            </div>
          </div>
        </div>
      </div>

      <style jsx>{`
        .product-catalog {
          max-width: 1200px;
          margin: 50px auto;
          padding: 20px;
          font-family: Arial, sans-serif;
        }

        .catalog-header {
          text-align: center;
          margin-bottom: 30px;
        }

        .catalog-header h1 {
          margin: 0 0 10px 0;
          font-size: 32px;
          color: #333;
        }

        .catalog-header p {
          margin: 0;
          color: #666;
          font-size: 16px;
        }

        .catalog-controls {
          background: #f8f9fa;
          padding: 20px;
          border-radius: 8px;
          margin-bottom: 20px;
          display: flex;
          flex-direction: column;
          gap: 15px;
        }

        .search-section {
          display: flex;
          justify-content: center;
        }

        .search-input {
          width: 100%;
          max-width: 400px;
          padding: 12px 16px;
          border: 1px solid #ddd;
          border-radius: 6px;
          font-size: 16px;
        }

        .filter-section {
          display: flex;
          gap: 15px;
          align-items: center;
          flex-wrap: wrap;
          justify-content: center;
        }

        .category-filter,
        .sort-filter {
          padding: 8px 12px;
          border: 1px solid #ddd;
          border-radius: 4px;
          background: white;
        }

        .view-toggle {
          display: flex;
          border: 1px solid #ddd;
          border-radius: 4px;
          overflow: hidden;
        }

        .view-btn {
          padding: 8px 16px;
          border: none;
          background: white;
          cursor: pointer;
          transition: background-color 0.2s ease;
        }

        .view-btn.active {
          background: #007bff;
          color: white;
        }

        .results-info {
          margin-bottom: 20px;
          color: #666;
        }

        .products-container.grid {
          display: grid;
          grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
          gap: 20px;
        }

        .products-container.list {
          display: flex;
          flex-direction: column;
          gap: 15px;
        }

        .products-container.list .product-card {
          display: flex;
          flex-direction: row;
          align-items: center;
        }

        .products-container.list .product-image-container {
          width: 120px;
          height: 120px;
          flex-shrink: 0;
        }

        .products-container.list .product-image {
          width: 100%;
          height: 100%;
          object-fit: cover;
        }

        .product-card {
          background: white;
          border-radius: 8px;
          box-shadow: 0 2px 8px rgba(0,0,0,0.1);
          overflow: hidden;
          transition: transform 0.2s ease, box-shadow 0.2s ease;
        }

        .product-card:hover {
          transform: translateY(-2px);
          box-shadow: 0 4px 16px rgba(0,0,0,0.15);
        }

        .product-image-container {
          position: relative;
          height: 200px;
          overflow: hidden;
        }

        .product-image {
          width: 100%;
          height: 100%;
          object-fit: cover;
        }

        .out-of-stock-badge {
          position: absolute;
          top: 10px;
          right: 10px;
          background: #dc3545;
          color: white;
          padding: 4px 8px;
          border-radius: 4px;
          font-size: 12px;
          font-weight: bold;
        }

        .wishlist-btn {
          position: absolute;
          top: 10px;
          left: 10px;
          background: rgba(255,255,255,0.9);
          border: none;
          border-radius: 50%;
          width: 32px;
          height: 32px;
          cursor: pointer;
          font-size: 16px;
          display: flex;
          align-items: center;
          justify-content: center;
        }

        .product-info {
          padding: 15px;
        }

        .product-name {
          margin: 0 0 10px 0;
          font-size: 16px;
          color: #333;
          line-height: 1.4;
        }

        .product-rating {
          display: flex;
          align-items: center;
          gap: 8px;
          margin-bottom: 10px;
        }

        .stars {
          display: flex;
          gap: 2px;
        }

        .star {
          color: #ddd;
          font-size: 14px;
        }

        .star.filled {
          color: #ffc107;
        }

        .rating-text {
          font-size: 12px;
          color: #666;
        }

        .product-price {
          margin-bottom: 15px;
        }

        .current-price {
          font-size: 18px;
          font-weight: bold;
          color: #007bff;
        }

        .original-price {
          font-size: 14px;
          color: #999;
          text-decoration: line-through;
          margin-left: 8px;
        }

        .product-actions {
          display: flex;
          gap: 8px;
        }

        .add-to-cart-btn {
          flex: 1;
          background: #007bff;
          color: white;
          border: none;
          padding: 10px;
          border-radius: 4px;
          cursor: pointer;
          font-weight: bold;
        }

        .add-to-cart-btn:disabled {
          background: #6c757d;
          cursor: not-allowed;
        }

        .quick-view-btn {
          background: #6c757d;
          color: white;
          border: none;
          padding: 10px 15px;
          border-radius: 4px;
          cursor: pointer;
        }

        .no-results {
          text-align: center;
          padding: 40px;
          color: #666;
        }

        .no-results h3 {
          margin: 0 0 10px 0;
          font-size: 24px;
        }

        .catalog-footer {
          margin-top: 40px;
          background: #f8f9fa;
          border-radius: 8px;
          padding: 30px;
          text-align: center;
        }

        .footer-decoration {
          margin-bottom: 30px;
        }

        .decorative-border {
          width: 100%;
          max-width: 600px;
          height: 20px;
          object-fit: cover;
        }

        .footer-content h3 {
          margin: 0 0 20px 0;
          font-size: 24px;
          color: #333;
        }

        .features-list {
          display: flex;
          justify-content: center;
          gap: 40px;
          flex-wrap: wrap;
        }

        .feature-item {
          display: flex;
          flex-direction: column;
          align-items: center;
          gap: 10px;
        }

        .feature-icon {
          width: 40px;
          height: 40px;
          object-fit: contain;
        }

        .feature-item span {
          font-size: 14px;
          color: #666;
          font-weight: bold;
        }

        @media (max-width: 768px) {
          .features-list {
            flex-direction: column;
            gap: 20px;
          }
        }
      `}</style>
    </div>
  );
}
