// scenarios/basic/web/svelte/RightClickOnlyMenu.svelte
<script>
  let contextMenu = { visible: false, x: 0, y: 0, itemId: null };
  let selectedItem = null;
  let searchTerm = '';
  let selectedCategory = 'all';
  let currentPage = 1;
  const itemsPerPage = 8;

  const categories = [
    { id: 'all', name: 'All Files' },
    { id: 'documents', name: 'Documents' },
    { id: 'images', name: 'Images' },
    { id: 'videos', name: 'Videos' },
    { id: 'audio', name: 'Audio' },
    { id: 'archives', name: 'Archives' }
  ];

  const files = [
    {
      id: 1,
      name: 'Project Proposal.docx',
      type: 'document',
      category: 'documents',
      size: '2.3 MB',
      modified: '2024-01-15',
      author: 'John Smith',
      icon: '📄'
    },
    {
      id: 2,
      name: 'Team Photo.jpg',
      type: 'image',
      category: 'images',
      size: '4.1 MB',
      modified: '2024-01-14',
      author: 'Sarah Johnson',
      icon: '🖼️'
    },
    {
      id: 3,
      name: 'Product Demo.mp4',
      type: 'video',
      category: 'videos',
      size: '125.7 MB',
      modified: '2024-01-13',
      author: 'Mike Chen',
      icon: '🎥'
    },
    {
      id: 4,
      name: 'Meeting Notes.pdf',
      type: 'document',
      category: 'documents',
      size: '856 KB',
      modified: '2024-01-12',
      author: 'Lisa Rodriguez',
      icon: '📄'
    },
    {
      id: 5,
      name: 'Background Music.mp3',
      type: 'audio',
      category: 'audio',
      size: '8.2 MB',
      modified: '2024-01-11',
      author: 'David Wilson',
      icon: '🎵'
    },
    {
      id: 6,
      name: 'Data Backup.zip',
      type: 'archive',
      category: 'archives',
      size: '45.6 MB',
      modified: '2024-01-10',
      author: 'Emma Davis',
      icon: '📦'
    },
    {
      id: 7,
      name: 'Logo Design.png',
      type: 'image',
      category: 'images',
      size: '1.8 MB',
      modified: '2024-01-09',
      author: 'Tom Anderson',
      icon: '🖼️'
    },
    {
      id: 8,
      name: 'User Manual.pdf',
      type: 'document',
      category: 'documents',
      size: '3.4 MB',
      modified: '2024-01-08',
      author: 'Anna Garcia',
      icon: '📄'
    }
  ];

  $: filteredFiles = files.filter(file => {
    const matchesCategory = selectedCategory === 'all' || file.category === selectedCategory;
    const matchesSearch = file.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         file.author.toLowerCase().includes(searchTerm.toLowerCase());
    return matchesCategory && matchesSearch;
  });

  $: totalPages = Math.ceil(filteredFiles.length / itemsPerPage);
  $: paginatedFiles = filteredFiles.slice(
    (currentPage - 1) * itemsPerPage, 
    currentPage * itemsPerPage
  );

  function handleContextMenu(event, fileId) {
    event.preventDefault();
    contextMenu = {
      visible: true,
      x: event.clientX,
      y: event.clientY,
      itemId: fileId
    };
    selectedItem = fileId;
  }

  function handleClick() {
    contextMenu = { visible: false, x: 0, y: 0, itemId: null };
    selectedItem = null;
  }

  function handleContextAction(action) {
    const file = files.find(f => f.id === contextMenu.itemId);
    alert(`${action} action performed on "${file?.name}"`);
    contextMenu = { visible: false, x: 0, y: 0, itemId: null };
    selectedItem = null;
  }

  function handleFileAction(action, file) {
    alert(`${action} action performed on "${file.name}"`);
  }

  function formatDate(dateString) {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric'
    });
  }

  function goToPage(page) {
    currentPage = page;
  }

  function nextPage() {
    if (currentPage < totalPages) {
      currentPage++;
    }
  }

  function prevPage() {
    if (currentPage > 1) {
      currentPage--;
    }
  }
</script>

<div class="file-manager" on:click={handleClick}>
  <header class="manager-header">
    <h1>File Manager</h1>
    <p>Right-click on files to access additional options</p>
  </header>

  <div class="manager-controls">
    <div class="search-section">
      <input 
        type="text" 
        placeholder="Search files..." 
        bind:value={searchTerm}
        class="search-input"
      />
    </div>

    <div class="filter-section">
      <select bind:value={selectedCategory} class="category-filter">
        {#each categories as category}
          <option value={category.id}>{category.name}</option>
        {/each}
      </select>
    </div>
  </div>

  <div class="files-container">
    <div class="files-header">
      <h2>Files ({filteredFiles.length})</h2>
      <div class="view-options">
        <button class="view-btn active">Grid View</button>
        <button class="view-btn">List View</button>
      </div>
    </div>

    <div class="files-grid">
      {#each paginatedFiles as file}
        <div 
          class="file-item {selectedItem === file.id ? 'selected' : ''}"
          on:contextmenu={(e) => handleContextMenu(e, file.id)}
        >
          <div class="file-icon">{file.icon}</div>
          
          <div class="file-info">
            <h3 class="file-name">{file.name}</h3>
            <div class="file-details">
              <span class="file-size">{file.size}</span>
              <span class="file-modified">{formatDate(file.modified)}</span>
              <span class="file-author">By {file.author}</span>
            </div>
          </div>

          <div class="file-actions">
            <button 
              class="action-btn primary" 
              on:click={() => handleFileAction('Open', file)}
            >
              Open
            </button>
            <button 
              class="action-btn secondary" 
              on:click={() => handleFileAction('Download', file)}
            >
              Download
            </button>
          </div>
        </div>
      {/each}
    </div>

    {#if totalPages > 1}
      <div class="pagination">
        <button 
          class="page-btn" 
          on:click={prevPage} 
          disabled={currentPage === 1}
        >
          Previous
        </button>
        
        {#each Array(totalPages) as _, i}
          <button 
            class="page-btn {currentPage === i + 1 ? 'active' : ''}" 
            on:click={() => goToPage(i + 1)}
          >
            {i + 1}
          </button>
        {/each}
        
        <button 
          class="page-btn" 
          on:click={nextPage} 
          disabled={currentPage === totalPages}
        >
          Next
        </button>
      </div>
    {/if}
  </div>

  {#if contextMenu.visible}
    <div 
      class="context-menu" 
      style="left: {contextMenu.x}px; top: {contextMenu.y}px;"
      on:click|stopPropagation
    >
      <div class="context-header">
        <span class="context-title">File Actions</span>
      </div>
      
      <div class="context-items">
        <div 
          class="context-item" 
          on:click={() => handleContextAction('Open')}
        >
          <span class="context-icon">👁️</span>
          <span class="context-text">Open</span>
        </div>
        
        <div 
          class="context-item" 
          on:click={() => handleContextAction('Download')}
        >
          <span class="context-icon">⬇️</span>
          <span class="context-text">Download</span>
        </div>
        
        <div 
          class="context-item" 
          on:click={() => handleContextAction('Rename')}
        >
          <span class="context-icon">✏️</span>
          <span class="context-text">Rename</span>
        </div>
        
        <div 
          class="context-item" 
          on:click={() => handleContextAction('Copy')}
        >
          <span class="context-icon">📋</span>
          <span class="context-text">Copy</span>
        </div>
        
        <div 
          class="context-item" 
          on:click={() => handleContextAction('Move')}
        >
          <span class="context-icon">📁</span>
          <span class="context-text">Move</span>
        </div>
        
        <div class="context-divider"></div>
        
        <div 
          class="context-item danger" 
          on:click={() => handleContextAction('Delete')}
        >
          <span class="context-icon">🗑️</span>
          <span class="context-text">Delete</span>
        </div>
      </div>
    </div>
  {/if}

  <div class="manager-info">
    <h3>File Manager Instructions</h3>
    <div class="info-content">
      <div class="info-item">
        <span class="info-icon">🖱️</span>
        <div class="info-text">
          <h4>Right-Click Menu</h4>
          <p>Right-click on any file to access additional options like rename, copy, move, or delete</p>
        </div>
      </div>
      
      <div class="info-item">
        <span class="info-icon">⌨️</span>
        <div class="info-text">
          <h4>Keyboard Access</h4>
          <p>Essential actions like delete are only available through right-click context menu</p>
        </div>
      </div>
      
      <div class="info-item">
        <span class="info-icon">⚠️</span>
        <div class="info-text">
          <h4>Accessibility Issue</h4>
          <p>This demonstrates an accessibility problem where critical functions are only available via right-click</p>
        </div>
      </div>
    </div>
  </div>
</div>

<style>
  .file-manager {
    max-width: 1200px;
    margin: 50px auto;
    padding: 20px;
    font-family: Arial, sans-serif;
  }

  .manager-header {
    text-align: center;
    margin-bottom: 30px;
  }

  .manager-header h1 {
    margin: 0 0 10px 0;
    font-size: 32px;
    color: #333;
  }

  .manager-header p {
    margin: 0;
    color: #666;
    font-size: 16px;
  }

  .manager-controls {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 30px;
    padding: 20px;
    background: #f8f9fa;
    border-radius: 8px;
  }

  .search-section {
    flex: 1;
    max-width: 400px;
  }

  .search-input {
    width: 100%;
    padding: 10px 16px;
    border: 2px solid #ddd;
    border-radius: 6px;
    font-size: 16px;
  }

  .search-input:focus {
    outline: none;
    border-color: #007bff;
  }

  .filter-section {
    margin-left: 20px;
  }

  .category-filter {
    padding: 10px 16px;
    border: 2px solid #ddd;
    border-radius: 6px;
    background: white;
    font-size: 16px;
  }

  .files-container {
    background: white;
    border-radius: 8px;
    box-shadow: 0 2px 8px rgba(0,0,0,0.1);
    padding: 30px;
    margin-bottom: 30px;
  }

  .files-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 25px;
  }

  .files-header h2 {
    margin: 0;
    font-size: 24px;
    color: #333;
  }

  .view-options {
    display: flex;
    border: 1px solid #ddd;
    border-radius: 4px;
    overflow: hidden;
  }

  .view-btn {
    padding: 8px 16px;
    border: none;
    background: white;
    cursor: pointer;
    transition: background-color 0.2s ease;
  }

  .view-btn.active {
    background: #007bff;
    color: white;
  }

  .files-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
    gap: 20px;
    margin-bottom: 30px;
  }

  .file-item {
    border: 2px solid #eee;
    border-radius: 8px;
    padding: 20px;
    cursor: pointer;
    transition: all 0.2s ease;
    position: relative;
  }

  .file-item:hover {
    border-color: #007bff;
    box-shadow: 0 4px 12px rgba(0,123,255,0.1);
  }

  .file-item.selected {
    border-color: #007bff;
    background: #e3f2fd;
  }

  .file-icon {
    font-size: 48px;
    text-align: center;
    margin-bottom: 15px;
  }

  .file-info {
    text-align: center;
    margin-bottom: 15px;
  }

  .file-name {
    margin: 0 0 10px 0;
    font-size: 16px;
    color: #333;
    word-break: break-word;
  }

  .file-details {
    display: flex;
    flex-direction: column;
    gap: 4px;
    font-size: 12px;
    color: #666;
  }

  .file-actions {
    display: flex;
    gap: 8px;
  }

  .action-btn {
    flex: 1;
    padding: 8px 12px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    font-size: 12px;
    font-weight: bold;
    transition: all 0.2s ease;
  }

  .action-btn.primary {
    background: #007bff;
    color: white;
  }

  .action-btn.primary:hover {
    background: #0056b3;
  }

  .action-btn.secondary {
    background: #6c757d;
    color: white;
  }

  .action-btn.secondary:hover {
    background: #545b62;
  }

  .pagination {
    display: flex;
    justify-content: center;
    gap: 8px;
  }

  .page-btn {
    padding: 8px 12px;
    border: 1px solid #ddd;
    background: white;
    cursor: pointer;
    border-radius: 4px;
    font-weight: bold;
    transition: all 0.2s ease;
  }

  .page-btn:hover:not(:disabled) {
    border-color: #007bff;
    color: #007bff;
  }

  .page-btn.active {
    background: #007bff;
    color: white;
    border-color: #007bff;
  }

  .page-btn:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  .context-menu {
    position: fixed;
    background: white;
    border: 1px solid #ddd;
    border-radius: 6px;
    box-shadow: 0 4px 12px rgba(0,0,0,0.15);
    z-index: 1000;
    min-width: 200px;
    overflow: hidden;
  }

  .context-header {
    background: #f8f9fa;
    padding: 10px 15px;
    border-bottom: 1px solid #eee;
  }

  .context-title {
    font-weight: bold;
    color: #333;
    font-size: 14px;
  }

  .context-items {
    padding: 5px 0;
  }

  .context-item {
    display: flex;
    align-items: center;
    gap: 10px;
    padding: 10px 15px;
    cursor: pointer;
    transition: background-color 0.2s ease;
  }

  .context-item:hover {
    background: #f8f9fa;
  }

  .context-item.danger:hover {
    background: #f8d7da;
  }

  .context-icon {
    font-size: 16px;
    width: 20px;
    text-align: center;
  }

  .context-text {
    font-size: 14px;
    color: #333;
  }

  .context-item.danger .context-text {
    color: #dc3545;
  }

  .context-divider {
    height: 1px;
    background: #eee;
    margin: 5px 0;
  }

  .manager-info {
    background: #f8f9fa;
    padding: 30px;
    border-radius: 8px;
  }

  .manager-info h3 {
    margin: 0 0 20px 0;
    font-size: 24px;
    color: #333;
  }

  .info-content {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
    gap: 20px;
  }

  .info-item {
    display: flex;
    gap: 15px;
    align-items: flex-start;
  }

  .info-icon {
    font-size: 24px;
    flex-shrink: 0;
  }

  .info-text h4 {
    margin: 0 0 5px 0;
    font-size: 16px;
    color: #333;
  }

  .info-text p {
    margin: 0;
    color: #666;
    font-size: 14px;
    line-height: 1.4;
  }

  @media (max-width: 768px) {
    .manager-controls {
      flex-direction: column;
      gap: 15px;
    }

    .filter-section {
      margin-left: 0;
    }

    .files-grid {
      grid-template-columns: 1fr;
    }

    .context-menu {
      position: relative;
      left: 0 !important;
      top: 0 !important;
      margin-top: 10px;
    }
  }
</style>

// scenarios/basic/web/nextjs/RightClickOnlyMenu.jsx
import { useState, useEffect, useRef } from 'react';

export default function RightClickOnlyMenu() {
  const [selectedItems, setSelectedItems] = useState([]);
  const [contextMenu, setContextMenu] = useState({ visible: false, x: 0, y: 0, itemId: null });
  const [isEditing, setIsEditing] = useState(false);
  const [editingItem, setEditingItem] = useState(null);
  const [editValue, setEditValue] = useState('');
  const [sortBy, setSortBy] = useState('name');
  const [filterBy, setFilterBy] = useState('all');

  const fileListRef = useRef(null);
  const editInputRef = useRef(null);

  const fileItems = [
    { id: 1, name: 'Project Proposal.docx', type: 'document', size: '2.4 MB', modified: '2024-01-15', status: 'active' },
    { id: 2, name: 'Budget Spreadsheet.xlsx', type: 'spreadsheet', size: '1.8 MB', modified: '2024-01-14', status: 'active' },
    { id: 3, name: 'Team Photo.jpg', type: 'image', size: '3.2 MB', modified: '2024-01-13', status: 'archived' },
    { id: 4, name: 'Meeting Notes.pdf', type: 'document', size: '856 KB', modified: '2024-01-12', status: 'active' },
    { id: 5, name: 'Presentation.pptx', type: 'presentation', size: '4.1 MB', modified: '2024-01-11', status: 'draft' },
    { id: 6, name: 'Database Backup.sql', type: 'database', size: '15.2 MB', modified: '2024-01-10', status: 'active' },
    { id: 7, name: 'Logo Design.psd', type: 'image', size: '8.7 MB', modified: '2024-01-09', status: 'draft' },
    { id: 8, name: 'User Manual.pdf', type: 'document', size: '5.3 MB', modified: '2024-01-08', status: 'active' }
  ];

  const filteredItems = fileItems.filter(item => {
    if (filterBy === 'all') return true;
    return item.status === filterBy;
  });

  const sortedItems = [...filteredItems].sort((a, b) => {
    switch(sortBy) {
      case 'name':
        return a.name.localeCompare(b.name);
      case 'size':
        return parseFloat(b.size) - parseFloat(a.size);
      case 'modified':
        return new Date(b.modified) - new Date(a.modified);
      case 'type':
        return a.type.localeCompare(b.type);
      default:
        return 0;
    }
  });

  const handleContextMenu = (e, itemId) => {
    e.preventDefault();
    setContextMenu({
      visible: true,
      x: e.clientX,
      y: e.clientY,
      itemId: itemId
    });
  };

  const handleContextMenuAction = (action, itemId) => {
    const item = fileItems.find(f => f.id === itemId);
    
    switch(action) {
      case 'rename':
        setIsEditing(true);
        setEditingItem(itemId);
        setEditValue(item.name);
        break;
      case 'copy':
        alert(`Copying "${item.name}"`);
        break;
      case 'cut':
        alert(`Cutting "${item.name}"`);
        break;
      case 'delete':
        if (confirm(`Are you sure you want to delete "${item.name}"?`)) {
          alert(`Deleted "${item.name}"`);
        }
        break;
      case 'properties':
        alert(`Properties for "${item.name}"`);
        break;
      case 'download':
        alert(`Downloading "${item.name}"`);
        break;
      case 'share':
        alert(`Sharing "${item.name}"`);
        break;
      case 'archive':
        alert(`Archiving "${item.name}"`);
        break;
      default:
        break;
    }
    
    setContextMenu({ visible: false, x: 0, y: 0, itemId: null });
  };

  const handleItemClick = (itemId) => {
    if (isEditing && editingItem === itemId) return;
    
    setSelectedItems(prev => 
      prev.includes(itemId) 
        ? prev.filter(id => id !== itemId)
        : [...prev, itemId]
    );
  };

  const handleItemDoubleClick = (itemId) => {
    const item = fileItems.find(f => f.id === itemId);
    alert(`Opening "${item.name}"`);
  };

  const handleEditSubmit = () => {
    if (editValue.trim()) {
      alert(`Renamed to "${editValue}"`);
      setIsEditing(false);
      setEditingItem(null);
      setEditValue('');
    }
  };

  const handleEditCancel = () => {
    setIsEditing(false);
    setEditingItem(null);
    setEditValue('');
  };

  const handleEditKeyDown = (e) => {
    if (e.key === 'Enter') {
      handleEditSubmit();
    } else if (e.key === 'Escape') {
      handleEditCancel();
    }
  };

  const handleBulkAction = (action) => {
    if (selectedItems.length === 0) {
      alert('Please select items first');
      return;
    }
    
    const itemNames = selectedItems.map(id => 
      fileItems.find(f => f.id === id).name
    ).join(', ');
    
    alert(`${action} action performed on: ${itemNames}`);
  };

  const getFileIcon = (type) => {
    const icons = {
      document: '📄',
      spreadsheet: '📊',
      image: '🖼️',
      presentation: '📽️',
      database: '🗄️'
    };
    return icons[type] || '📁';
  };

  const getStatusColor = (status) => {
    const colors = {
      active: '#28a745',
      draft: '#ffc107',
      archived: '#6c757d'
    };
    return colors[status] || '#6c757d';
  };

  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleDateString();
  };

  useEffect(() => {
    const handleClickOutside = (e) => {
      if (contextMenu.visible && !e.target.closest('.context-menu')) {
        setContextMenu({ visible: false, x: 0, y: 0, itemId: null });
      }
    };

    const handleKeyDown = (e) => {
      if (e.key === 'Escape') {
        setContextMenu({ visible: false, x: 0, y: 0, itemId: null });
        if (isEditing) {
          handleEditCancel();
        }
      }
    };

    document.addEventListener('click', handleClickOutside);
    document.addEventListener('keydown', handleKeyDown);

    return () => {
      document.removeEventListener('click', handleClickOutside);
      document.removeEventListener('keydown', handleKeyDown);
    };
  }, [contextMenu.visible, isEditing]);

  useEffect(() => {
    if (isEditing && editInputRef.current) {
      editInputRef.current.focus();
      editInputRef.current.select();
    }
  }, [isEditing]);

  return (
    <div className="file-manager">
      <header className="manager-header">
        <h1>File Manager</h1>
        <p>Manage your files and documents</p>
      </header>

      <div className="manager-controls">
        <div className="view-controls">
          <button className="view-btn active">List View</button>
          <button className="view-btn">Grid View</button>
        </div>

        <div className="filter-controls">
          <select 
            value={filterBy} 
            onChange={(e) => setFilterBy(e.target.value)}
            className="filter-select"
          >
            <option value="all">All Files</option>
            <option value="active">Active</option>
            <option value="draft">Draft</option>
            <option value="archived">Archived</option>
          </select>

          <select 
            value={sortBy} 
            onChange={(e) => setSortBy(e.target.value)}
            className="sort-select"
          >
            <option value="name">Sort by Name</option>
            <option value="size">Sort by Size</option>
            <option value="modified">Sort by Modified</option>
            <option value="type">Sort by Type</option>
          </select>
        </div>

        <div className="bulk-actions">
          <button 
            className="action-btn"
            onClick={() => handleBulkAction('Download')}
            disabled={selectedItems.length === 0}
          >
            Download Selected
          </button>
          <button 
            className="action-btn"
            onClick={() => handleBulkAction('Archive')}
            disabled={selectedItems.length === 0}
          >
            Archive Selected
          </button>
          <button 
            className="action-btn danger"
            onClick={() => handleBulkAction('Delete')}
            disabled={selectedItems.length === 0}
          >
            Delete Selected
          </button>
        </div>
      </div>

      <div className="file-list" ref={fileListRef}>
        <div className="list-header">
          <div className="list-checkbox">
            <input
              type="checkbox"
              checked={selectedItems.length === sortedItems.length && sortedItems.length > 0}
              onChange={(e) => {
                if (e.target.checked) {
                  setSelectedItems(sortedItems.map(item => item.id));
                } else {
                  setSelectedItems([]);
                }
              }}
            />
          </div>
          <div className="list-name">Name</div>
          <div className="list-type">Type</div>
          <div className="list-size">Size</div>
          <div className="list-modified">Modified</div>
          <div className="list-status">Status</div>
        </div>

        {sortedItems.map(item => (
          <div 
            key={item.id} 
            className={`list-item ${selectedItems.includes(item.id) ? 'selected' : ''}`}
            onClick={() => handleItemClick(item.id)}
            onDoubleClick={() => handleItemDoubleClick(item.id)}
            onContextMenu={(e) => handleContextMenu(e, item.id)}
          >
            <div className="list-checkbox">
              <input
                type="checkbox"
                checked={selectedItems.includes(item.id)}
                onChange={() => handleItemClick(item.id)}
                onClick={(e) => e.stopPropagation()}
              />
            </div>
            <div className="list-name">
              {isEditing && editingItem === item.id ? (
                <input
                  ref={editInputRef}
                  type="text"
                  value={editValue}
                  onChange={(e) => setEditValue(e.target.value)}
                  onBlur={handleEditSubmit}
                  onKeyDown={handleEditKeyDown}
                  className="edit-input"
                />
              ) : (
                <div className="file-name">
                  <span className="file-icon">{getFileIcon(item.type)}</span>
                  <span className="file-text">{item.name}</span>
                </div>
              )}
            </div>
            <div className="list-type">{item.type}</div>
            <div className="list-size">{item.size}</div>
            <div className="list-modified">{formatDate(item.modified)}</div>
            <div className="list-status">
              <span 
                className="status-badge"
                style={{ backgroundColor: getStatusColor(item.status) }}
              >
                {item.status}
              </span>
            </div>
          </div>
        ))}
      </div>

      {contextMenu.visible && (
        <div 
          className="context-menu"
          style={{
            position: 'fixed',
            left: contextMenu.x,
            top: contextMenu.y,
            zIndex: 1000
          }}
        >
          <div className="context-menu-item" onClick={() => handleContextMenuAction('rename', contextMenu.itemId)}>
            <span className="context-icon">✏️</span>
            Rename
          </div>
          <div className="context-menu-item" onClick={() => handleContextMenuAction('copy', contextMenu.itemId)}>
            <span className="context-icon">📋</span>
            Copy
          </div>
          <div className="context-menu-item" onClick={() => handleContextMenuAction('cut', contextMenu.itemId)}>
            <span className="context-icon">✂️</span>
            Cut
          </div>
          <div className="context-menu-divider"></div>
          <div className="context-menu-item" onClick={() => handleContextMenuAction('download', contextMenu.itemId)}>
            <span className="context-icon">⬇️</span>
            Download
          </div>
          <div className="context-menu-item" onClick={() => handleContextMenuAction('share', contextMenu.itemId)}>
            <span className="context-icon">🔗</span>
            Share
          </div>
          <div className="context-menu-item" onClick={() => handleContextMenuAction('archive', contextMenu.itemId)}>
            <span className="context-icon">📦</span>
            Archive
          </div>
          <div className="context-menu-divider"></div>
          <div className="context-menu-item" onClick={() => handleContextMenuAction('properties', contextMenu.itemId)}>
            <span className="context-icon">ℹ️</span>
            Properties
          </div>
          <div className="context-menu-item danger" onClick={() => handleContextMenuAction('delete', contextMenu.itemId)}>
            <span className="context-icon">🗑️</span>
            Delete
          </div>
        </div>
      )}

      <div className="help-section">
        <h3>How to Use</h3>
        <div className="help-items">
          <div className="help-item">
            <span className="help-icon">🖱️</span>
            <span className="help-text">Right-click on any file to access context menu</span>
          </div>
          <div className="help-item">
            <span className="help-icon">⌨️</span>
            <span className="help-text">Use keyboard shortcuts for quick actions</span>
          </div>
          <div className="help-item">
            <span className="help-icon">📁</span>
            <span className="help-text">Double-click to open files</span>
          </div>
        </div>
      </div>

      <style jsx>{`
        .file-manager {
          max-width: 1200px;
          margin: 0 auto;
          padding: 20px;
          font-family: Arial, sans-serif;
        }

        .manager-header {
          text-align: center;
          margin-bottom: 30px;
        }

        .manager-header h1 {
          margin: 0 0 10px 0;
          font-size: 32px;
          color: #333;
        }

        .manager-header p {
          margin: 0;
          color: #666;
          font-size: 16px;
        }

        .manager-controls {
          display: flex;
          flex-wrap: wrap;
          gap: 20px;
          align-items: center;
          justify-content: space-between;
          margin-bottom: 20px;
          padding: 20px;
          background: #f8f9fa;
          border-radius: 8px;
        }

        .view-controls {
          display: flex;
          gap: 5px;
        }

        .view-btn {
          padding: 8px 16px;
          border: 1px solid #ddd;
          background: white;
          cursor: pointer;
          border-radius: 4px;
          font-weight: bold;
          transition: all 0.2s ease;
        }

        .view-btn.active {
          background: #007bff;
          color: white;
          border-color: #007bff;
        }

        .view-btn:hover:not(.active) {
          border-color: #007bff;
          color: #007bff;
        }

        .filter-controls {
          display: flex;
          gap: 10px;
        }

        .filter-select,
        .sort-select {
          padding: 8px 12px;
          border: 1px solid #ddd;
          border-radius: 4px;
          background: white;
          cursor: pointer;
        }

        .bulk-actions {
          display: flex;
          gap: 10px;
        }

        .action-btn {
          padding: 8px 16px;
          border: 1px solid #ddd;
          background: white;
          cursor: pointer;
          border-radius: 4px;
          font-weight: bold;
          transition: all 0.2s ease;
        }

        .action-btn:hover:not(:disabled) {
          background: #f8f9fa;
          border-color: #007bff;
          color: #007bff;
        }

        .action-btn:disabled {
          opacity: 0.5;
          cursor: not-allowed;
        }

        .action-btn.danger {
          background: #dc3545;
          color: white;
          border-color: #dc3545;
        }

        .action-btn.danger:hover:not(:disabled) {
          background: #c82333;
        }

        .file-list {
          background: white;
          border: 1px solid #ddd;
          border-radius: 8px;
          overflow: hidden;
        }

        .list-header {
          display: grid;
          grid-template-columns: 40px 1fr 100px 100px 120px 100px;
          gap: 15px;
          padding: 15px 20px;
          background: #f8f9fa;
          font-weight: bold;
          font-size: 14px;
          color: #333;
          border-bottom: 2px solid #dee2e6;
        }

        .list-item {
          display: grid;
          grid-template-columns: 40px 1fr 100px 100px 120px 100px;
          gap: 15px;
          padding: 15px 20px;
          border-bottom: 1px solid #eee;
          align-items: center;
          cursor: pointer;
          transition: background-color 0.2s ease;
        }

        .list-item:hover {
          background: #f8f9fa;
        }

        .list-item.selected {
          background: #e3f2fd;
        }

        .list-item:last-child {
          border-bottom: none;
        }

        .list-checkbox input {
          width: 16px;
          height: 16px;
        }

        .file-name {
          display: flex;
          align-items: center;
          gap: 10px;
        }

        .file-icon {
          font-size: 16px;
        }

        .file-text {
          font-weight: bold;
          color: #333;
        }

        .edit-input {
          width: 100%;
          padding: 4px 8px;
          border: 2px solid #007bff;
          border-radius: 4px;
          font-size: 14px;
          font-weight: bold;
        }

        .status-badge {
          padding: 4px 8px;
          border-radius: 12px;
          color: white;
          font-size: 11px;
          font-weight: bold;
          text-transform: uppercase;
        }

        .context-menu {
          background: white;
          border: 1px solid #ddd;
          border-radius: 6px;
          box-shadow: 0 4px 12px rgba(0,0,0,0.15);
          padding: 5px 0;
          min-width: 180px;
        }

        .context-menu-item {
          display: flex;
          align-items: center;
          gap: 10px;
          padding: 8px 15px;
          cursor: pointer;
          font-size: 14px;
          transition: background-color 0.2s ease;
        }

        .context-menu-item:hover {
          background: #f8f9fa;
        }

        .context-menu-item.danger {
          color: #dc3545;
        }

        .context-menu-item.danger:hover {
          background: #f8d7da;
        }

        .context-icon {
          font-size: 14px;
          width: 16px;
          text-align: center;
        }

        .context-menu-divider {
          height: 1px;
          background: #eee;
          margin: 5px 0;
        }

        .help-section {
          margin-top: 30px;
          padding: 20px;
          background: #f8f9fa;
          border-radius: 8px;
          border-left: 4px solid #007bff;
        }

        .help-section h3 {
          margin: 0 0 15px 0;
          font-size: 18px;
          color: #333;
        }

        .help-items {
          display: flex;
          flex-direction: column;
          gap: 10px;
        }

        .help-item {
          display: flex;
          align-items: center;
          gap: 10px;
        }

        .help-icon {
          font-size: 16px;
        }

        .help-text {
          font-size: 14px;
          color: #666;
        }

        @media (max-width: 768px) {
          .manager-controls {
            flex-direction: column;
            align-items: stretch;
          }

          .bulk-actions {
            flex-wrap: wrap;
            justify-content: center;
          }

          .list-header,
          .list-item {
            grid-template-columns: 30px 1fr 80px 80px 100px 80px;
            gap: 10px;
            padding: 10px 15px;
          }

          .context-menu {
            min-width: 160px;
          }
        }
      `}</style>
    </div>
  );
}
